### ISSUE TITLE
Ability to override onTap for UrlAttachment Widget

### ISSUE THREAD

**Issue by bhayatus** [GetStream/stream-chat-flutter#1003]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Sample use of StreamChannel as an example:

```dart
StreamChannel(
  channel: widget.channel,
  child: Builder(
    builder: (context) => Column(
      children: [
        Expanded(
          child: MessageListView(
            loadingBuilder: (context) => const Center(
              child: DesignLoader(),
            ),
            messageBuilder: (
              context,
              details,
              messages,
              defaultMessageWidget,
            ) =>
                defaultMessageWidget.copyWith(
              showUsername: false,
              onAttachmentTap: _onAttachmentTap,
              onLinkTap: (url) {
                // Open the link in my own custom in-app web view
              },
            ),
            showFloatingDateDivider: false,
          ),
        ),
      ],
    ),
  ),
)
```

When typing a url, it generates a url attachment like seen below:
![Untitled](https://user-images.githubusercontent.com/35541711/157753343-740b5fe6-148d-4262-942b-5d3678924398.png)

Tapping the top portion of the attachment works fine, onLinkTap gets called. The issue is tapping anywhere below that always opens in an external browser. I took a look at the source code, and in url_attachment.dart, the following lines can be found:

```dart
  @override
  Widget build(BuildContext context) {
    final chatThemeData = StreamChatTheme.of(context);
    return GestureDetector(
      onTap: () {
        final titleLink = urlAttachment.titleLink;
        if (titleLink != null) launchURL(context, titleLink);
      },
      child: Column(

```

It appears to me that there is no way to override this functionality at the moment.

### Describe the solution that you'd like

![Untitled](https://user-images.githubusercontent.com/35541711/157753724-9aad8392-8587-4cc4-a6ce-d3efde992d09.png)

When clicking anywhere on the url attachment, I want to be able to supply my own onTap function.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ptrbrynt** [comment]
@bhayatus This seems to have regressed in version 5.3.0.
