### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Abdulrehman53** [GetStream/stream-chat-flutter#1007]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^3.4.0

### What happened?

I/flutter ( 7110): │ Null check operator used on a null value

I/flutter ( 7110): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄

I/flutter ( 7110): │ #0   RenderViewportBase.getOffsetToReveal
package:flutter/…/rendering/viewport.dart:764

I/flutter ( 7110): │ #1   _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure>
package:stream_chat_flutter/…/src/positioned_list.dart:339

I/flutter ( 7110): │ #2   SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143

I/flutter ( 7110): │ #3   SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088

I/flutter ( 7110): │ #4   _rootRun (dart:async/zone.dart:1428:13)

I/flutter ( 7110): │ #5   _CustomZone.run (dart:async/zone.dart:1328:19)

I/flutter ( 7110): │ #6   _CustomZone.runGuarded (dart:async/zone.dart:1236:7)

I/flutter ( 7110): │ #6   _CustomZone.runGuarded (dart:async/zone.dart:1236:7)

### Steps to reproduce

```bash
1. Open chat list
2. Send new message
3. Issue on scrolling
```

### Relevant log output

```shell
Null check operator used on a null value
I/flutter (18177): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (18177): │ #0   RenderViewportBase.getOffsetToReveal
package:flutter/…/rendering/viewport.dart:764
I/flutter (18177): │ #1   _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure>
package:stream_chat_flutter/…/src/positioned_list.dart:339
I/flutter (18177): │ #2   SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
I/flutter (18177): │ #3   SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088
I/flutter (18177): │ #4   SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
I/flutter (18177): │ #5   _rootRun (dart:async/zone.dart:1428:13)
I/flutter (18177): │ #6   _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (18177): │ #7   _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
I/flutter (18177): │ #8   _invoke (dart:ui/hooks.dart:166:10)
I/flutter (18177): │ #9   PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.5.3 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/Documents/Softwares/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi can you be more specific on how to reproduce the issue?
I should send a message and just scroll? I don't that happens all the time, does it?

**Comment by Abdulrehman53** [comment]
> Hi can you be more specific on how to reproduce the issue? I should send a message and just scroll? I don't that happens all the time, does it?

Don't have issue if there're fewer messages which are not scrollable
<img width="972" alt="Screen Shot 2022-03-15 at 3 59 42 PM" src="https://user-images.githubusercontent.com/13569710/158363767-4b07842c-2f3f-49bb-bef1-1db4c85f33b5.png">

Issue produces when there are more messages which are scrollable and then send a new message. This is both on IOS and Android. 
Steps to reproduce

- Send enough messages which becomes scrollable
- Go Back
- Again open chat screen
- Send a new message raise that exception

**Comment by ManasviPatidar** [comment]
Faced the same issue. Possibly the same as #856, the error message varies with flutter versions.

**Comment by imtoori** [comment]
I agree, I think it's related to this one https://github.com/GetStream/stream-chat-flutter/issues/856
I don't think there's much we can do at the moment https://github.com/GetStream/stream-chat-flutter/issues/856#issuecomment-1040318219

**Comment by Abacaxi-Nelson** [comment]
Hi all,
Im having this issue as well 

```dart
while (child.parent != this) {
      final RenderObject parent = child.parent! as RenderObject;
      assert(parent != null, '$target must be a descendant of $this');
      if (child is RenderBox) {
        pivot = child;
      }
      if (parent is RenderSliver) {
        leadingScrollOffset += parent.childScrollOffset(child)!; // HERE
      } else {
        onlySlivers = false;
        leadingScrollOffset = 0.0;
      }
      child = parent;
    }

════════ Exception caught by scheduler library ═════════════════════════════════
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      RenderViewportBase.getOffsetToReveal
package:flutter/…/rendering/viewport.dart:764
#1      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure>
package:stream_chat_flutter/…/src/positioned_list.dart:339
#2      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#3      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1089
#4      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:995
#8      _invoke (dart:ui[/hooks.dart:151:10]())
#9      PlatformDispatcher._drawFrame (dart:ui[/platform_dispatcher.dart:308:5]())
#10     _drawFrame (dart:ui[/hooks.dart:115:31]())
(elided 3 frames from dart:async)
```

I cant reproduce exactly, but happen.

Worst, it happen to my users :

<img width="1261" alt="Capture d’écran 2022-04-06 à 22 30 34" src="https://user-images.githubusercontent.com/556990/162065575-a02e9f62-ae8c-49b1-b2cc-030bc0d82f91.png">

<img width="1222" alt="Capture d’écran 2022-04-06 à 22 31 21" src="https://user-images.githubusercontent.com/556990/162065616-a481fded-3a68-4976-a335-71d355268e71.png">
