### ISSUE TITLE
Open channel in unread position

### ISSUE THREAD

**Issue by imtoori** [GetStream/stream-chat-flutter#1012]
this could be a `bool` property that you pass in `StreamChannel`

**Comment by bhanu-under25** [comment]
I have worked on this and it does scroll to unread message but pagination stops working sometimes when using initialMessageId.

I used wrapWith to find the message which is the last message and wrapping that with the message saying unread messages with the unread count.


I have a opened a issue for the initialMessageId pagination [issue](https://github.com/GetStream/stream-chat-flutter/issues/1085)
