### ISSUE TITLE
[WEB] Persistance - exceeded the quota

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1017]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

Web

### What version are you using?

Latest 
- `3.5.1` of `stream_chat_flutter`
- `3.1.0` of `stream_chat_persistance`

### What happened?

After a while of using the app on web we're seeing errors in the console
```
Failed to execute 'setItem' on 'Storage': Setting the value of 'moor_db_str_db_xxx' exceeded the quota.
```
and also 
```
Error: no such table: messages at 
Error: no such table: messages
```

### Steps to reproduce

Use chat on web with the persistance, switch users, read a lot of channels and you'll see `exceeded the quota` in the console

### Supporting info

We believe it's the local storage issue as it has a small size limit (10 MB?), so it'd nice to introduce some db truncation (like clearing the most unused channels data or users who haven't logged in for a while.

We're also trying indexed db option: https://github.com/GetStream/stream-chat-flutter/pull/1016 but would be best to support db truncation anyway so persistence works fine on web by default.

We were also talking to the support (had a call last week) about this issue so we're looking forward to hearing from you what can be done here and how quickly :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @geweald, Thanks for pointing this out. This does makes sense and we will look into this soon 👍🏼

**Comment by geweald** [comment]
Hey @xsahil03x any progress on this issue? Using experimental indexedDB we're getting errors on safari `Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 1.)`, maybe something similar to [this stackoverflow issue](https://stackoverflow.com/questions/68386273/error-loading-blob-to-img-in-safari-webkitblobresource-error-1)

**Comment by xsahil03x** [comment]
Hey @geweald, We have this in our backlog but there are some other tasks/issues that need to be addressed first.
