### ISSUE TITLE
Add custom separator support for ChannelListView

### ISSUE THREAD

**Issue by troy379** [GetStream/stream-chat-flutter#102]
**Is your feature request related to a problem? Please describe.**
I'm using the `ChannelListView.channelPreviewBuilder` method to create my own UI for channel previews, but I can't use my own separator style.

**Describe the solution you'd like**
Could you add the `ChannelListView.channelPreviewBuilder` so I can do this?

**Describe alternatives you've considered**
At least, it would be ok to have the ability to disable separators at all, so a user can put the separator as a part of the channel preview widget.

gz#6640

**Comment by imtoori** [comment]
In the latest release you can find a `ChannelListView.separatorBuilder` parameter!
Thanks for the feature request :)

**Comment by troy379** [comment]
Supersonic speed! 💪
