### ISSUE TITLE
Hard delete from dashboard does not delete message from client

### ISSUE THREAD

**Issue by TramPamPam** [GetStream/stream-chat-flutter#1033]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter_core: ^3.5.0
  stream_chat_flutter: ^3.5.0
  stream_chat_persistence: ^3.1.0

### What happened?

Hard delete from dashboard does not delete message from client

### Steps to reproduce

```bash
1. Go to dashboard
2. Click on Explorer
3. Find any channel
4. Hard delete message
5. Message still appear in the chat. But disappear from dashboard.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
@TramPamPam thanks for reporting the issue
we'll test this and see what we can do
