### ISSUE TITLE
Keyboard misbehaving on Channel Screen

### ISSUE THREAD

**Issue by Siqlain-Hanif** [GetStream/stream-chat-flutter#1034]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

^3.4.0

### What happened?

Keyboards just closes when i focus on textfield. This is highly reproducible in IOS but on android it's not that often
Currently i have no logs for that.

https://user-images.githubusercontent.com/53166182/159305303-b1db2b3b-cfe3-4a0c-9326-86df9a05118a.MOV

### Steps to reproduce

```bash
Just tries to open the MessageInput textfield
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Siqlain-Hanif** [comment]
First keyboard dismiss was due to the onDrag keyboardDismiss behaviour after that it dismiss automatically

**Comment by imtoori** [comment]
Hi @Siqlain-Hanif is this related to a specific ios version? I'm trying to reproduce it with no luck

**Comment by Siqlain-Hanif** [comment]
HI @imtoori i am experiencing this on IOS 15.2 not sure if it's specific to 15.2

**Comment by imtoori** [comment]
@Siqlain-Hanif did you add any specific customization? to the MessageListView or the MessageInput?

**Comment by Siqlain-Hanif** [comment]
@imtoori for the MessageInput we did not do any customizations. And also for MessageListView no customization either except and providing MessageListView with customMessageBuilders

**Comment by Siqlain-Hanif** [comment]
@imtoori ok let me check.

**Comment by Siqlain-Hanif** [comment]
@imtoori currently not able to reproduce this on the code provided i am trying to reproduce this on that code once it gets reproduced i will get back to you ..

**Comment by Siqlain-Hanif** [comment]
@imtoori we couldn't reproduce this on the code provided, with the release of 2.10.4 seems like this is fixed. So closing this, will keep an eye on this is need be will open on future.
