### ISSUE TITLE
'streamChatTheme != null' while opening message detail screen

### ISSUE THREAD

**Issue by bhavy5145** [GetStream/stream-chat-flutter#1036]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

3.5.1

### What happened?

from the channel listing page i am going inside the message detail screen and this error comes

### Steps to reproduce

```bash
1. Go to channel listing page
2. Click on any channel that will lead you to the message detail screen
```

### Relevant log output

```shell
You must have a StreamChatTheme widget at the top of your widget tree
'stream_chat_theme.dart':
Failed assertion: line 29 pos 7: 'streamChatTheme != null'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
@bhavy5145 this is probably an implementation error

Let me try to help you
Where do you place the `StreamChat` widget?
