### ISSUE TITLE
own_capabilities extraData missing after update

### ISSUE THREAD

**Issue by xsahil03x** [GetStream/stream-chat-flutter#1047]
### Discussed in https://github.com/GetStream/stream-chat-flutter/discussions/1045

<div type='discussions-op-text'>

<sup>Originally posted by **Brazol** March 30, 2022</sup>
I'm watching `channel.extraDataStream` and printing its content and it looks like after calling `channel.updateName` I get a new value in the stream (as expected) but without `own-capabilities`. Is this expected behaviour? 

And that is the state in which the channel is then cached and from now on when checking permissions there are none.</div>

**Comment by xsahil03x** [comment]
@Brazol can you share a small snippet using which we can reproduce this? Thanks

**Comment by Brazol** [comment]
I'm using hooks so it will be easiest for me to share it that way, but basicaly I just listen to extraData:
` final extraData = useStream(channel.extraDataStream, initialData: channel.extraData);`

and when I get new data I print it:
`useEffect(() { print(extraData.data); }, [extraData.data]);`

and initially I get correct json with own_capabilities array of permissions but after calling
`channel.updateName`
there is no own_capabilities (extraData only contains new name)

**Comment by Brazol** [comment]
I added a comment in the discussion so I'll also add it here

#discussioncomment-2469801
