### ISSUE TITLE
membersStream returns incomplete list of members

### ISSUE THREAD

**Issue by Brazol** [GetStream/stream-chat-flutter#1052]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

4.0.0-beta.1

### What happened?

When I listen to `membersStream` I get an incomplete list of members after each update to the channel:

- after calling `channel.updateName`, `membersStream` pushes empty list as data
- after calling `channel.addMembers`, `membersStream` pushes empty list OR list with only newly added members
- after calling `channel.removeMembers`, `membersStream` pushes the correct list with members (without removed members) BUT then right after the empty list of members is pushed as data

I don't think this is correct behaviour especially that looks like the last value pushed is also cached in the channel state so most of a time after channel update members are cleared in the channel cache.

### Steps to reproduce

```bash
1. Listen to channel. membersStream and print every new data
2. Perform various updates to the channel (updateName, addMembers, removeMembers)
3. Check printed results
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Taking a look 👀

**Comment by tanjunior** [comment]
`channel.addMembers` not doing anything for me as well. causing...
```
I/flutter (18541): 2022-05-07 02:13:22.788790 🚨 🕸️ ╔ DioErrorType.response
I/flutter (18541): 2022-05-07 02:13:22.790302 🚨 🕸️ ║    {
I/flutter (18541): 2022-05-07 02:13:22.794234 🚨 🕸️ ║         code: 17,
I/flutter (18541): 2022-05-07 02:13:22.796183 🚨 🕸️ ║         "GetOrCreateChannel failed with error: "User 'ay7Gs2o0TrURxBTlGj2pANEduz83' with role 'user' is not allowed to p
I/flutter (18541): 2022-05-07 02:13:22.797139 🚨 🕸️ ║         erform action ReadChannel in scope 'messaging'""
I/flutter (18541): 2022-05-07 02:13:22.799609 🚨 🕸️ ║         StatusCode: 403,
I/flutter (18541): 2022-05-07 02:13:22.805408 🚨 🕸️ ║         duration: "0.00ms",
I/flutter (18541): 2022-05-07 02:13:22.805813 🚨 🕸️ ║         more_info: "https://getstream.io/chat/docs/api_errors_response"
I/flutter (18541): 2022-05-07 02:13:22.805938 🚨 🕸️ ║    }
I/flutter (18541): 2022-05-07 02:13:22.806093 🚨 🕸️ ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```
Chat Explorer in the dash board also does not reflect the new member.

**Comment by imtoori** [comment]
@Brazol can you check if still experience the same problem with the latest v4 release? Thanks a lot

**Comment by imtoori** [comment]
@tanjunior yours looks like a permission issue
I'd suggest to check how you set those in the dashboard
Maybe contact support about this since it's not strictly flutter related
