### ISSUE TITLE
Increase the 5KB limit for channel Extra Data.

### ISSUE THREAD

**Issue by bhanu-under25** [GetStream/stream-chat-flutter#1061]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter, stream_chat_flutter_core

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Channel which have more then 100 members causes problem of sending essential data like mute status through send notification webhook in extra data of the channel.

Only the first 100 members have those information.

### Describe the solution that you'd like

If there is a way to increase the limit of data ( right now 5KB ) which has to be sent. It would be a game changer.

Let me know if there is a way we can get those information through client sdk or something.

### Describe alternatives that you have considered

We tried the GetStream legacy push notification but the problem we faced was only the first 100 members used to get notification and not the others 400 members present in the group.

So we tried using webhook to handle the notification but the problem we faced was that to get mute status it was throwing error of Limit of 5KB.

### Additional context

We have multiple groups which have approx 500 members for community building and networking but it gets spammy when the mute status can't be handled from our side because we don't have the data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi @bhanu-under25 
there's nothing we can do here since this is not a flutter sdk limitation.
I know you're in contact with support, I'm sure they can help you achieve what you need.
Regards,
Salvatore
