### ISSUE TITLE
GUIDE: in-channel search message feature

### ISSUE THREAD

**Issue by imtoori** [GetStream/stream-chat-flutter#1063]
Let's try to build this, if it's doable let's post a guide

**Comment by bhavy5145** [comment]
```
filter: Filter.and([
            Filter.in_('members', [StreamChat.of(context).currentUser!.id]),
            // trying to search from here...
            if (searchText.isNotEmpty) Filter.autoComplete('member.user.name', "${searchText}"),
          ]),
```
you can try filtering with this this works for me.

**Comment by Srj-Love** [comment]
Any updates on this @imtoori

**Comment by Srj-Love** [comment]
Hello Team,
I'm still waiting for the update on this features.
My use case is releated to the above. 
Goto CHannel Page -> Click Search button -> Search any messages in same channel -> Navigate to th respected Message + Highlight.

**Comment by Srj-Love** [comment]
Hey @imtoori waiting for your reply. We're stuck here.
