### ISSUE TITLE
Scroll To A certain message on press

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1070]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

No

### Describe the solution that you'd like

It would be nice to allow people to click on a message in search for example and go to that message in the chat and not have to scroll back up to that message.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi @rlee1990 
That should be possible
You can take a look at how we do it in the sample app https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1
There's a search functionality in there and we do exactly what you said

**Comment by imtoori** [comment]
maybe take a look at this https://github.com/GetStream/flutter-samples/blob/main/packages/stream_chat_v1/lib/routes/app_routes.dart#L52
basically, you need to pass the `initialMessageId` to the `StreamChannel` widget, that should already be enough

**Comment by rlee1990** [comment]
okay cool will give that a try.
