### ISSUE TITLE
Save File in full_screen_media freezes up the app, shows random progress and throws range error

### ISSUE THREAD

**Issue by bhanu-under25** [GetStream/stream-chat-flutter#1071]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^3.5.1

### What happened?

Full Screen media shows range error and shows random progress indicator.

Below are the steps to reproduce and it affects not only on the sample app but all other full screen media implementation.

I hope following video gives enough steps to reproduce in sample app code.

 - This a gif showing the range error.
 
![range error](https://user-images.githubusercontent.com/92363650/162725847-35aa3884-37dc-4222-93d8-6026c1c99be1.gif)

- This shows the random progress in dialog box, it freezes the app and dialog box is never dismissed.

![random](https://user-images.githubusercontent.com/92363650/162725963-2decb3e0-419b-4e67-8965-4478806bbc25.gif)

Let me know if you need any more information to reproduce this.

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayush221b** [comment]
Hey @bhanu-under25 thank you for bringing this to our attention, I am able to reproduce the RangeError, working on a fix. I will update here once done.

**Comment by bhanu-under25** [comment]
@ayush221b

You can reproduce the save file error too in flutter sample app.
- It shows download random progress.
- Doesn't get dismissed automatically.
- And because the showDialog used is non dismissable we can't navigate back.

Let me know if you need any more information regarding this.

Thank You.

**Comment by bhanu-under25** [comment]
Thanks for solving.
