### ISSUE TITLE
AttachmentFileUploader Providing More Information

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1074]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter, stream_chat_flutter_core

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

As it stands currently we don't have an option when using the attachmentFileUploader to get the information on the person sending the file.

### Describe the solution that you'd like

To include the user object with the send functions and the delete functions?
I am using Appwrite as the backend and have the files set with user-level rules and not hard-coded rules.

### Describe alternatives that you have considered

Tried to do this manually. Will not work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rlee1990** [comment]
@ayush221b any chance someone could take a look at this? If not I can submit a pull request for it.

**Comment by rlee1990** [comment]
@GroovinChip can someone take a look at this?

**Comment by ayush221b** [comment]
Hey @rlee1990 we apologise for the delay in getting back to you. Thank you for the PR, we will have a look at it and discuss your use case today.

**Comment by ayush221b** [comment]
Hey @rlee1990 as I understand from your issue, you want to access the data linked to the user who is uploading the attachment(s) right? I am guessing that would always be the currently connected user, and you can access all the data attached to the connected user simply by doing:

```
StreamChat.of(context).currentUser
```

if you the `StreamChat` widget at the top of your widget tree.

You could also access the same using:

```
streamChatClient.state.currentUser
```

where `streamChatClient` is an instance of `StreamChatClient`.

Please let me know if this helps, or if I have completely misunderstood your problem. I'd be happy to get to it again.

**Comment by rlee1990** [comment]
@ayush221b I need access to more then just the user also you can't access context from the function when your trying to make your own uploader for attachments

**Comment by xsahil03x** [comment]
Hey @rlee1990, can you please explain your full use case as we are not able to understand it correctly? It will help us to better answer this particular issue.

**Comment by rlee1990** [comment]
@xsahil03x so for me to use my own storage system with the attachmentFileUploader I need to be able to pass other items in that are required for appwrite. The pull request I submitted would allow us to have access to this all.

**Comment by rlee1990** [comment]
@xsahil03x I need to be able to pass the userID the bucketID the read and write access depending on the chat it is.

**Comment by rlee1990** [comment]
@xsahil03x  so with the PR the extraData is set as an optional item of Map so that anyone can use it to pass what they need access to inside the AttachmentFileUploader overrides. Such as the bucket and user ids. If they do not need to use it no harm no foul.

**Comment by rlee1990** [comment]
@ayush221b @xsahil03x Does that help

**Comment by xsahil03x** [comment]
@rlee1990 can you share a short snippet of how the user can pass the additional `extraData` ? I am still not sure about that.

**Comment by rlee1990** [comment]
@xsahil03x i don't get what's not sure about being able to pass a map of dynamic data into the function. As of now your trying our hands and not making the ask flexible. All someone has to do is create a map of whatever they need and pass it when the function is called

**Comment by xsahil03x** [comment]
@rlee1990 the thing is we do not allow calling those functions outside the library. We only call it internally in our SDK.
https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/client/channel.dart#L772-L785

**Comment by rlee1990** [comment]
As told in other comments @xsahil03x if we want to use our own backends to upload files via chat we need to use these functions. I'm failing to see how this would cause any harm

**Comment by imtoori** [comment]
@rlee1990 what Sahil is trying to say is that in your PR you added the extraData param in some methods, but the thing is that the attachment uploader is called from our code 

for example https://github.com/rlee1990/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/client/client.dart#L735

that's why he's arguing that your pr is not enough to solve the issue 
do you agree?

**Comment by rlee1990** [comment]
@imtoori I disagree one the only thing I did was make the package more flexible with what was told from your docs [here](https://getstream.io/chat/docs/flutter-dart/file_uploads/?language=dart), Also the only time I am calling this is from within the chat sdk usage. Without that it makes using the sdk useless. We as developers should have the ability to access other data that is critical to file uploads. You say we can use our own backends/cdn to upload files but are not making it flexible to use with them all.

**Comment by imtoori** [comment]
if you look here https://github.com/rlee1990/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/client/client.dart#L735 you don't pass any extraData property, how would this solve your problem?

did you try using the code in your pr and it solved your issue?

**Comment by rlee1990** [comment]
@imtoori The link was to state that we are being told we can use our own backends but that as the SDK is set right now it does not fit to support all use cases.
Using the Pr works for me because I can pass in the different items I need to have in order to upload files dynamically

**Comment by xsahil03x** [comment]
@rlee1990 Will something like this will be enough for your use-case?

```dart
class MyCustomUploader extends AttachmentFileUploader {
  const MyCustomUploader({
    required this.client,
    required this.appWriteUploader,
  });

  final StreamChatClient client;

  final AppWriteUploader appWriteUploader;

  @override
  Future<SendImageResponse> sendImage(
    AttachmentFile image,
    String channelId,
    String channelType, {
    ProgressCallback? onSendProgress,
    CancelToken? cancelToken,
  }) {
    final currentUser = client.state.currentUser;
    return appWriteUploader.uploadFile(
      image,
      channelId,
      channelType,
      onSendProgress: onSendProgress,
      cancelToken: cancelToken,
      currentUser: currentUser,
    );
  }
}
```
Passing it down to client
```dart
  final client = StreamChatClient(
    'b67pax5b2wdq',
    logLevel: Level.INFO,
    attachmentFileUploaderProvider: (client) {
      return MyCustomUploader(
        client: client,
        appWriteUploader: AppWriteUploader(),
      );
    },
  );
```

**Comment by rlee1990** [comment]
@xsahil03x that won't help. When I am using my backend I need access to other items and not just the current user.

**Comment by xsahil03x** [comment]
@rlee1990 can you mention all the needed items?

**Comment by xsahil03x** [comment]
@rlee1990 does the updated PR look good to you?
https://github.com/GetStream/stream-chat-flutter/pull/1110

**Comment by rlee1990** [comment]
@xsahil03x yes that looks great. Thank you all.

**Comment by xsahil03x** [comment]
@rlee1990 the PR is merged and will be released soon. Thanks 👍🏼
