### ISSUE TITLE
[Analytics] List interactions we want to let users track

### ISSUE THREAD

**Issue by imtoori** [GetStream/stream-chat-flutter#1077]

**Comment by ayush221b** [comment]
Context:

One very important aspect of building apps is tracking user journeys and understanding what works for the end users and what doesn't. Most modern apps have a very robust analytics system that spans across multiple providers. The app tracks all the user interactions and sends events, which can then be used to craft out journeys, conversion funnels, identify which steps have the maximum drop off and further optimise the app, to eventually improve user experience.

To make it easier for developers using Stream, we are introducing a Stream of interaction events that the developers can subscribe to and use for firing their own analytics events/perform other background callback operations.

**Comment by ayush221b** [comment]
We have identified a list of standard interactions that the developers might want to track, along with the data attached to them, but please feel free to submit requests for new events to be added to this list.

Identified Interactions:

1. CHANNEL_LIST_VIEW

channelCount (int): The number of channels loaded initially
isSearch (bool): Is this the search view?

2. CHANNEL_LIST_TILE_CLICK

channelId (string): The ID of the channel
unreadMessageCount (int): The number of unread messages for this channel
isSearch (bool): Is this the search view?

3. CHANNEL_LIST_TILE_AVATAR_CLICK

channelId (string): The ID of the channel
unreadMessageCount (int): The number of unread messages for this channel
isSearch (bool): Is this the search view?

4. MESSAGE_INPUT_FOCUS

5. MESSAGE_INPUT_TYPING_STARTED

6. MESSAGE_INPUT_SEND_BTN_CLICK

hasText (bool): Does the message have text?
hasAttachments (bool): Does the message have attachments?
hasMentions (bool): Does the message have mentions?

7. MESSAGE_INPUT_ATTACHMENT_BTN_CLICK

8. MESSAGE_INPUT_COMMAND_BTN_CLICK

9. MESSAGE_INPUT_ATTACHMENT_ACTION_CLICK

targetAction (enum): GALLERY/FILE_PICKER/CAPTURE_PHOTO/CAPTURE_VIDEO

10. CHANNEL_HEADER_BACK_BTN_CLICK

unreadMessageCount (int): The number of unread messages visible on the back button
channelId (String): Id of the channel

11. CHANNEL_HEADER_AVATAR_CLICK

channelId (String): Id of the channel

12. MESSAGE_LIST_VIEW

channelId (String): id of the channel
messageCount: The number of messages loaded initially

13. MESSAGE_MENTION_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
mentionedUserId (String): The id of the mentioned user who was tapped

14. MESSAGE_URL_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message

15. MESSAGE_ACTIONS_TRIGGER - When someone long presses on the message on mobile/opens the context menu on web/desktop

channelId (String): The id of the channel
messageId (String): The id of the message

16. MESSAGE_REACTION_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
reactionType (String): The type of reaction

17. MESSAGE_ACTION_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
actionType (enum): REPLY/THREAD_REPLY/FLAG/PIN/UNPIN/DELETE

18. MESSAGE_ATTACHMENT_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
attachmentType (String): image/video/giphy/any custom attachment type
attachmentId (String): the id of the attachment

19. ATTACHMENT_FULL_SCREEN_VIEW

channelId (String): The id of the channel
messageId (String): The id of the message
attachmentType (String): image/video/giphy/any custom attachment type
attachmentId (String): the id of the attachment

20. ATTACHMENT_FULL_SCREEN_SHARE_BTN_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
attachmentType (String): image/video/giphy/any custom attachment type
attachmentId (String): the id of the attachment

21. ATTACHMENT_FULL_SCREEN_GRID_BTN_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
attachmentType (String): image/video/giphy/any custom attachment type
attachmentId (String): the id of the attachment

22. ATTACHMENT_FULL_SCREEN_CLOSE_BTN_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
attachmentType (String): image/video/giphy/any custom attachment type
attachmentId (String): the id of the attachment

23. ATTACHMENT_FULL_SCREEN_ACTIONS_MENU_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
attachmentType (String): image/video/giphy/any custom attachment type
attachmentId (String): the id of the attachment

24. ATTACHMENT_FULL_SCREEN_ACTION_ITEM_CLICK

channelId (String): The id of the channel
messageId (String): The id of the message
attachmentType (String): image/video/giphy/any custom attachment type
attachmentId (String): the id of the attachment
actionType (enum): REPLY/SHOW_IN_CHAT/SAVE

25. MESSAGES_LIST_SCROLL_TO_BOTTOM_CLICK

channelId (String): The id of the channel
