### ISSUE TITLE
When app is in background for a long time, and go foreground.. we are unable to reconnect 

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#1086]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

3.5.1

### What happened?

1. Display a ```ChannelListView```
2. Go in background
3. Wait a lot
4. Put back the app in foreground
5. 'errorBuilder' is called, and button calling ```_channelListController.loadData!()``` does nothing

Error im logging :
```StreamChatError(message: You cannot use queryChannels without an active connection. Please call `connectUser` to connect the client.)``` // i was logged
 

### Steps to reproduce

```dart
ChannelListView(
  channelListController: listController,
  errorBuilder: (context, error) {
    ErrorsService().recordChannelError(error, null, 'errorBuilder 1');
    return SizedBox(
      width: MediaQuery.of(context).size.width,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Text(
            'Internet issue! Please reload your app',
            textAlign: TextAlign.center,
            style: TextStyle(
                fontFamily: PicnicTheme.fontFamily,
                fontWeight: FontWeight.bold,
                fontSize: 17,
                color: PicnicTheme.primaryFill),
          ),
          const SizedBox(height: 20),
          SizedBox(
            width: 130,
            height: 38,
            child: PicnicGradientButton(
              callback: () {
                listController.loadData!();
              },
              text: 'reload',
              fontSize: 18,
              gradient: PicnicTheme.picnicGradient,
            ),
          ),
          const SizedBox(height: 25),
        ],
      ),
    );
  },
  onChannelLongPress: (c) {
    onChannelLongPress(c, context);
  },
  swipeToAction: false,
  separatorBuilder: (_, __) => const SizedBox(height: 16),
  filter: Filter.and([
    Filter.in_('members', [user!.id]),
    Filter.equal('type', widget.type)
  ]),
  presence: true,
  limit: 20,
  channelWidget: ChannelPage(
    changeToFeedPage: widget.changeToFeedPage,
    getstreamClient: widget.getstreamClient,
  ),
  channelPreviewBuilder: (context, channel) {
  },
  onViewInfoTap: (channel) {},
)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abacaxi-Nelson** [comment]
seems to be okay for version 4 :)

**Comment by Abacaxi-Nelson** [comment]
Grrr in fact still not working

**Comment by imtoori** [comment]
hi @Abacaxi-Nelson this is a very tricky issue
We've tried reproducing this behaviour for weeks, but it's really unpredictable
Can you try using 3.6.1?

**Comment by Abacaxi-Nelson** [comment]
Hey @imtoori 
To be honest,  cant as well. But we are seeing this on many users.
Yes im on the 3.6.1

![Capture d’écran 2022-04-22 à 09 50 00](https://user-images.githubusercontent.com/556990/164642865-b8bb0e71-d90d-44fe-8d32-7fa79357bf1b.png)

**Comment by g-apparence** [comment]
Having same problem. 
This randomly happens and make app crash... 

Why does stream chat widgets not running in a separate zone ? 
If not working showing a retry or just prevent crash ?

**Comment by imtoori** [comment]
hey @g-apparence we're constantly trying to reproduce this bug and solve it, do you have more information on how to reproduce it?

**Comment by g-apparence** [comment]
I don't have many reproducing cases as it randomly happens. 
Anyway, I have some sentry logs that happen many times a day. 
![Capture d’écran 2022-05-30 à 15 10 08](https://user-images.githubusercontent.com/48241546/170999172-a34de47e-4903-40a2-9d85-2e30b01e1328.png)
Happens on both Android and iOS. 
Our client is starting to get nervous about the chat...

**Comment by imtoori** [comment]
@g-apparence I think your issue is different, can you show me how you connect the user?

**Comment by imtoori** [comment]
#1237 might fix this issue
Can you try and let me know?
