### ISSUE TITLE
Limited Access to Camera

### ISSUE THREAD

**Issue by MateusHBR** [GetStream/stream-chat-flutter#1087]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS

### Is your feature request related to a problem?

When we have Limited Access to library in iOS, there is no easy way to open the library and select more photos.

### Describe alternatives that you have considered

The alternative that i found is recreate the Attachment.

### Additional context

Happens in Chat Screen, in the MessageInput widget.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
solved by #1092
