### ISSUE TITLE
Add functionality to MessageWidget onAttachmentTap without overriding default functionality

### ISSUE THREAD

**Issue by arquadrado** [GetStream/stream-chat-flutter#1096]
I am not sure if this a bug or just the way the library works for some reason but I've encountered a problem for my particular use case.
I am using the library to implement a chat experience and I need to run some code parallel to some events for logging purposes.

Normally when a message with an image is sent, I can click on it and it opens the image preview. I want this behavior to remain the same but if I pass the `onAttachmentTap` to the `MessageWidget` I totally override the behavior instead of adding to it.

I was expecting something similar to what happens with the `MessageInput` component and the `onMessageSend` hook where I can pass a function that runs parallel to the default functionality of sending the message.

Am I missing something here?

Thank you

**EDIT**

I found this issue https://githubmemory.com/repo/GetStream/stream-chat-flutter/issues/828 and was able to reproduce the default behavior by adding the following, as mentioned in the issue: 

```
                   Navigator.push(context, MaterialPageRoute(builder: (_) {
                    return StreamChannel(
                      channel: StreamChannel.of(context).channel,
                      child: FullScreenMedia(
                        mediaAttachments: [attachment],
                        message: message,
                      ),
                    );
                  }));
```

Is this still the way to achieve the behavior I mentioned initially?

**EDIT2**

This solution does not work for pdfs. It just display a blank page.

**Comment by imtoori** [comment]
hi @arquadrado that's a good solution, adding a check on `attachment.type` should solve your other problem

**Comment by imtoori** [comment]
btw, we're starting to work on a way to easily add analytics functionalities. You'll see more in the next months
