### ISSUE TITLE
StreamInputMessage PlatformException

### ISSUE THREAD

**Issue by S-ecki** [GetStream/stream-chat-flutter#1113]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

4.0.0

### What happened?

A `PlatformException` is thrown when opening a screen with `StreamMessageInput`. 
The code is "_STORAGE_NOT_LEGACY_" and the message "_Use `requestLegacyExternalStorage` when your project is targeting above Android Q._"

### Steps to reproduce

```bash
1. Go to any screen containing the StreamMessageInput
2. The error should show up automatically
3. The error is thrown on any interaction with StreamMessageInput again
```

### Supporting info to reproduce

Android Pixel 4 with API 29 is used for testing

### Flutter analyze output

```shell
No issues found! (ran in 50.2s)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
ok I think I found the problem
https://pub.dev/packages/photo_manager#android-10-q-29
Can you see if this works for you? I'll add in the right section in the readme if that works

**Comment by S-ecki** [comment]
I can confirm that this works, thanks!
However, there is another issue which was not present in previous releases:
When opening the keyboard, my bottom navigation bar resizes with it (previously it was places "under the keyboard" and only the input field was resized

![image](https://user-images.githubusercontent.com/75510543/166485280-c3e489ad-2efb-4c70-992c-a866c5760c37.png)

![image](https://user-images.githubusercontent.com/75510543/166485312-d8dfd82f-56ee-4248-ac71-6bce1ce48bd1.png)

**Comment by imtoori** [comment]
@S-ecki I think this is specific to your implementation :/ we have a nav bar in the [sample app](https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1) and everything still works fine

**Comment by S-ecki** [comment]
I added the comment as the behaviour changed between v3 und v4, but thanks for the clarification

**Comment by trile127** [comment]
I get this same error when I upgraded to flutter 3.0
