### ISSUE TITLE
ValueListenable not accepting userListController 

### ISSUE THREAD

**Issue by mal33k-eden** [GetStream/stream-chat-flutter#1129]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, MacOS

### What version are you using?

4.1

### What happened?

The argument type 'StreamUserListController' can't be assigned to the parameter type 'ValueListenable<PagedValue<int, Channel>>'

### Steps to reproduce

```bash
1. Follow the tutorials for the link https://getstream.io/chat/docs/sdk/flutter/stream_chat_flutter_core/stream_user_list_controller/#background

using V4.1.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
yeah sorry that's an error
you should use a  PagedValueListenableBuilder<int, User>
I'll update the docs accordingly

**Comment by mal33k-eden** [comment]
the documentation already uses PagedValueListenableBuilder. your proposal doesn't change anything. kindly throw more light on the work around. 
> body: PagedValueListenableBuilder<int, User>(
>         valueListenable: userListController,
>         builder: (context, value, child) {

[check here ](https://getstream.io/chat/docs/sdk/flutter/stream_chat_flutter_core/stream_user_list_controller/)
