### ISSUE TITLE
Can is support web and desktop?

### ISSUE THREAD

**Issue by ValentinVignal** [GetStream/stream-chat-flutter#1139]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

If I go to https://pub.dev/packages/stream_chat_flutter it is written it is only supported on iOS and android.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/32538273/167988892-cb4e7f36-b846-43d0-990f-ba8eea396012.png">
The initial request was to support web and desktop platforms (macOS, linux and windows).

But from the question _"Which platforms would this feature impact?"_, I'm a bit confused, is it already supported ?

### Describe the solution that you'd like

I would like the package to be supported on web and desktop platforms.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayush221b** [comment]
Hey @ValentinVignal the work to support Desktop and Web is actively underway. You can track the progress here: https://github.com/GetStream/stream-chat-flutter/pull/913

**Comment by ValentinVignal** [comment]
Thank you @ayush221b , do you have a rough estimation on when it will be deployed?

**Comment by ayush221b** [comment]
Hey @ValentinVignal I can't give you a date right now, but we are working on it actively to get it out as soon as possible. We will keep updating the PR and the linked issues, please stay tuned for more updates.
