### ISSUE TITLE
Update photo_view package

### ISSUE THREAD

**Issue by ayush221b** [GetStream/stream-chat-flutter#1140]
Need to update the photo_view package when they publish a new pub release with this fix: https://github.com/bluefireteam/photo_view/pull/499

**Comment by bhayatus** [comment]
Looks like there is a new release of the package on pub.dev: https://pub.dev/packages/photo_view/versions/0.14.0

**Comment by ayush221b** [comment]
Hey, thanks for pointing it out, I will see if this solves the issue, and if we can upgrade. Moving this issue out of blocked.
