### ISSUE TITLE
Incompatibility with flutter_stripe on flutter version 3 because of freezed_annotation dependancy

### ISSUE THREAD

**Issue by seena98** [GetStream/stream-chat-flutter#1146]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

4.1.0

### What happened?

Because no versions of stream_chat_flutter match >4.1.0 <5.0.0 and stream_chat_flutter 4.1.0 depends on stream_chat_flutter_core ^4.1.0, stream_chat_flutter ^4.1.0 requires stream_chat_flutter_core ^4.1.0.
And because no versions of stream_chat_flutter_core match >4.1.0 <5.0.0 and stream_chat_flutter_core 4.1.0 depends on freezed_annotation ^1.0.0, stream_chat_flutter ^4.1.0 requires freezed_annotation ^1.0.0.
And because flutter_stripe >=3.0.0 depends on stripe_platform_interface ^3.0.0 which depends on freezed_annotation ^2.0.3, stream_chat_flutter ^4.1.0 is incompatible with flutter_stripe >=3.0.0.

### Steps to reproduce

```bash
When i try to update flutter_stripe package to version three to make it work with new version of flutter, I get this error that stream chat is using freezed_annotiation 1.0.0 and is not compatible
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
we're upgrading the freezed dependency, you'll find it in the next version
