### ISSUE TITLE
Calling channel.show() triggers around 10-12 API calls simultaneously to https://chat.stream-io-api.com/channels/messaging

### ISSUE THREAD

**Issue by Ayush-gupta-josh** [GetStream/stream-chat-flutter#1150]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

4.1.0

### What happened?

I called `channel.show()` which called the show API along with 10-12 query calls for the same channel id to `https://chat.stream-io-api.com/channels/messaging` while `channel.hide()` works as expected.

![image](https://user-images.githubusercontent.com/67139749/168610953-6b1c3e06-962c-484f-a0b0-ad6c326da415.png)

### Steps to reproduce

```bash
1. Call `channel.show()`.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi @Ayush-gupta-josh this is not happening for me
Do you have any additional information on this?

**Comment by Ayush-gupta-josh** [comment]
@imtoori Checked it on the latest 4.3 version whenever channel.show() is called it triggers multiple channel queries as you can see in above screenshots

**Comment by imtoori** [comment]
could you provide a snippet or a sample app to reproduce the issue?

**Comment by Ayush-gupta-josh** [comment]
Difficult for me to replicate the exact scenario since we have a lot of custom functionality. But I also tried recreating this sample app working fine there. I will look into this a bit more and will write here if I find something on my end.

**Comment by imtoori** [comment]
sounds good, if you tried creating a new app and it works fine it's probably something on your side
let me know

**Comment by Ayush-gupta-josh** [comment]
@imtoori Issue is reproducible when we use `PagedValueListenableBuilder` to build channel list please check out the demo https://github.com/Ayush-gupta-josh/stream-chat-flutter/tree/demo-multiapi-call

**Comment by xsahil03x** [comment]
Hey @Ayush-gupta-josh 

Working fine for me. Can you test again with the dart devtools? Or maybe also share a video with the same.
https://user-images.githubusercontent.com/25670178/184877018-3ff6ca5d-716a-4d27-9c89-596a3df51edd.mov

**Comment by Ayush-gupta-josh** [comment]
@xsahil03x After looking it further based on your response, it seems like extra calls are only pre-flight calls that happens on browser only not on native devices. Based on that we can close this issue I guess.
