### ISSUE TITLE
Emoji-only message gets cut at the top

### ISSUE THREAD

**Issue by mkobuolys** [GetStream/stream-chat-flutter#1168]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: 4.1.0

### What happened?

Emoji-only messages get cut at the top:
<img width="586" alt="Screenshot 2022-05-19 at 16 39 13" src="https://user-images.githubusercontent.com/17415795/169307203-9578572a-bc16-4b13-9c68-f98f9d8702d2.png">

### Steps to reproduce

```bash
1. Send an emoji-only message.
```

### Flutter analyze output

```shell
Analyzing project...                                                    
No issues found! (ran in 23.9s)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-LT)
    • Flutter version 2.10.5 at /Users/mkazlauskas/dev/flutter
    • Upstream repository https://gith ub.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mkazlauskas/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mkazlauskas/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 4370853B-AFFC-4C7A-BDFD-B6BDA8B6ACD3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GroovinChip** [comment]
Hi @mkobuolys, thanks for letting us know about this. I just attempted to reproduce your issue and was unable to do so - single-emoji messages are not cut off for me. 

Here are some screenshots:
![image](https://user-images.githubusercontent.com/4250470/169308458-2e6820b7-db3a-4fd8-8599-df46a5c86bc1.png)
![image](https://user-images.githubusercontent.com/4250470/169308711-a3f94b29-e335-4205-967d-58c5fb85d798.png)

Would you mind providing some more context on this? Are you using a custom message widget?

Thanks,

Reuben (GroovinChip)

**Comment by mkobuolys** [comment]
Ok, it seems that the problem is with `TextTheme` when setting a custom font height:

```
StreamChatThemeData(
  textTheme: StreamTextTheme.light(
    body: TextStyle(height: 1.0),
  ),
)
```

Not really an issue, then? I mean, it can be improved by having an `emojiTheme`, just not sure whether this use case would be common.

Please consider but I am ok if you close this for now. Sorry for the noise 🙏

**Comment by GroovinChip** [comment]
Glad to hear the problem has been resolved! Please feel free to let us know if you need any more assistance and we'll be happy to help you out.

Cheers!
