### ISSUE TITLE
v2 push notification IOS sound (no sound)

### ISSUE THREAD

**Issue by sdegenaar** [GetStream/stream-chat-flutter#1173]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

4.0.1

### What happened?

In V1 we could edit the template and you could add "sound":"default" so that when the user gets a chat notification if the app is closed it plays the default sound. In v2 pf push notifications you cannot edit the template anymore and looking at the docs the template that is is using does not have sound attribute. Is this by default planned and if so how can I add sound back in (safely) as my users are complaining about this. Thanks!

### Steps to reproduce

```bash
1. Send a chat message to a IOS user with the app closed
2. Notification is received but it is silent.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi @sdegenaar it's still possible to update the template, but at the moment you should use the cli
https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications_v2/#ios
read here to get more info
