### ISSUE TITLE
Channel List is not updated if a message is received in a newly created channel

### ISSUE THREAD

**Issue by Ayush-gupta-josh** [GetStream/stream-chat-flutter#1174]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

4.1.0

### What happened?

When a message is received in a newly created channel, the channel list is not updated immediately, I have to manually refresh the page for the new channel to reflect in the channel list. I'm using `PagedValueListenableBuilder` along with `StreamChannelListController`

### Steps to reproduce

```bash
1. Open the chat application using multiple users in different browsers such that they have never sent any message to each other
2. Try sending the message from User A to User B by creating a new channel
3. The channel list at User B's end won't get updated immediately.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @Ayush-gupta-josh could you show me how do you create the channel?

**Comment by adityathakur8929** [comment]
@imtoori 

This is how channel is being created at the backend, where stream_chat_client is initialized using 
stream-chat package for python and its version is 4.3.0
```
channel = stream_chat_client.channel(
        "messaging",
        str(member.id),
        data=dict(members=channel_members),
    )
    channel.create(user_id=STREAM_BOT_USER_ID)
    return channel
 ```

**Comment by adityathakur8929** [comment]
Hi here is the link for the video made on stream chat demo app. We just changed the streamAPIkey and created a new channel from our backend:
https://drive.google.com/file/d/1t7ZZmPHU72FAtAUk_DBUcULeqR-nKihm/view?usp=sharing
Steps to reproduce:
1. Open the chat application
2. Creating a new channel from backend sdk
3. The channel list of the connected user gets updated after refreshing.

**Comment by adityathakur8929** [comment]
Hi, I am adding the video for the issue that has been reproduced on stream flutter demo app:
https://drive.google.com/file/d/1t7ZZmPHU72FAtAUk_DBUcULeqR-nKihm/view?usp=sharing

Steps to reproduce:
1. Open the stream chat application for an admin stream user and navigate to channel list
2. Create a new user from the backend sdk
3. Refresh the channel list on UI

**Comment by xsahil03x** [comment]
Thanks @adityathakur8929, I will take a look today

**Comment by adityathakur8929** [comment]
Also the stream demo app repo link on which the issue is persists is:
https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1

**Comment by xsahil03x** [comment]
@adityathakur8929 I tried reproducing it but failed again.

https://user-images.githubusercontent.com/25670178/183409311-d0598e5f-02c9-4905-9681-1ff75f81488c.mov

**Comment by adityathakur8929** [comment]
Okay, I have gone through the video the channel list gets updated in real time if a new channel is added and user is a member of that channel. But if a new channel is added and the user is not a member of that channel but user's role is admin on stream then user has to refresh the list once.

**Comment by xsahil03x** [comment]
@adityathakur8929 can you also share the filters that you are using on your controller?

**Comment by xsahil03x** [comment]
@adityathakur8929
Unfortunately, our backend do not send `channel.created` events to WebSockets due to which this isn't possible at the moment.
