### ISSUE TITLE
Create classes/enums to use instead of `String` / `Map`

### ISSUE THREAD

**Issue by ValentinVignal** [GetStream/stream-chat-flutter#1175]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter, stream_chat_flutter_core

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

I'm trying to install stream chat and understand how it works, and what it can do.

Because it uses a lot `String` and `Map`, it becomes quite hard to understand what are the available options.

For example, from the [documentation](https://getstream.io/chat/docs/flutter-dart/?language=dart)

```dart
final filter = {
  "type": "messaging",
  "members": {
    "\$in": ["john"]
  }
};

final sort = [SortOption("last_message_at", direction: SortOption.DESC)];

final channels = await client.queryChannels(
  filter: filter,
  sort: sort,
);
```

`filter` is here a map where it could be a class with nullable fields `type` and `members`. And `members` could also have its own type. instead of a `String` (`"last_message_at"`) `SortOption` could take an enum.

This will allows dev to know what they can do, because when a method/class asks for a `String` or `Map`, it doesn't give information on the possible options.

### Describe the solution that you'd like

When possible, instead of using `String`s , it could use `Enum`s. And instead of using `Map`s, it could use a custom class.

### Describe alternatives that you have considered

I'm also considering Sendbird or implementing the chat feature by myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@valentinVignal can you share some code snippets on how you want these to be?

**Comment by ValentinVignal** [comment]
For example, the type filter could be 

```dart
class Filter {
  const Filter({
    this.type,
    this.members
  });
  
  final String? type;
  final MembersFilter members;
}

class MembersFilter {
  const MembersFilter({this.isIn});
  final List<String>? isIn
}
```

For the SortOption, it could take an enum instead of a `String`:

```dart
enum SortOptionValue {
  lastMessageAt,
  // ...
} 
```

**Comment by imtoori** [comment]
Hey @ValentinVignal we already have a [Filter class](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/core/models/filter.dart)
You can read more [here](https://getstream.io/chat/docs/sdk/flutter/guides/understanding_filters/)

About the `SortOption`, having a `String` is more flexible since you can use a broad variety of fields, even custom ones
