### ISSUE TITLE
Filtering nested objects with other filters.

### ISSUE THREAD

**Issue by dbrezack** [GetStream/stream-chat-flutter#1184]
### Please select which package this feature is related to

stream_chat_flutter_core

### Is your feature request related to a problem?

Currently this is possible 
```
{
   ...
   someObj: {
      id: 123,
      name: 'Test name'
   }
}
```
`Filter.equal('someObj', {'id': 1234})`
This solution ONLY works with equal. Not autocomplete 

### Describe the solution that you'd like

Some form of nesting operator would be very helpful
For example
`Filter.equal('someObj.name', 'Test Name')`
Alternatively a list could be used 
`Filter.equal(['someObj', 'name'], 'Test Name')`
Maybe even renamed for this case. 
`Filter.deepEqual(['someObj', 'name'], 'Test Name')`

### Describe alternatives that you have considered

Alternatively you could split the objects having 
```
someObjId: 123,
someObjName: 'TestName'
```
This leads to a bloating issue though

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @dbrezack I'm sorry but the backend doesn't support nested filtering of custom objects at the moment

**Comment by imtoori** [comment]
yeah I shared the feature request, but this is the flutter SDK repo, that's why I closed the issue
