### ISSUE TITLE
[security]: integrate Signal-Protocol

### ISSUE THREAD

**Issue by Ahmadre** [GetStream/stream-chat-flutter#1191]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

No.

### Describe the solution that you'd like

Is it possible to integrate the Signal Protocol into the message exchange?

A possible solution for dart-only is here: https://pub.dev/packages/libsignal_protocol_dart

### Describe alternatives that you have considered

https://pub.dev/packages/libsignal_protocol_dart

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayush221b** [comment]
Hey @Ahmadre thank you so much for your suggestion. Stream already has end-to-end encryption for chat, you can read more about it here: https://getstream.io/blog/end-to-end-encrypted-chat-in-flutter/
