### ISSUE TITLE
PhotoManager.requestPermissionExtend() called too soon

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1194]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS

### What version are you using?

  stream_chat_flutter: ^4.2.0
  stream_chat_localizations: ^3.1.0
  stream_chat_persistence: ^4.1.0

### What happened?

The native iOS permissions dialog for photo access opens as soon as the `_PickerWidget` state is created. This is too soon, as permissions should only be requested once the user wants to send a photo/file.

### Steps to reproduce

```bash
1. Use the StreamMessageInput widget in a detail page
2. Navigate from overview to detail page
3. Native iOS dialog for photo/gallery permissions appears, instead of only appearing once the user clicks the attachment button
```

### Supporting info to reproduce

cause of the bug: 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/6661557/172631193-96ee760d-70d0-45f8-ba33-eaab3ecc77a5.png">

this shoud occur when the attachments icon is clicked the first time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matthewfx** [comment]
@imtoori Hey, I've just updated to 4.3.0 but unfortunately, the permission alert view is still being displayed as soon as the StreamChannel widget is being displayed. It shouldn't happen until the user wants to add an attachment.

**Comment by imtoori** [comment]
@matthewfx I think you're still using the deprecated `MessageInput` widget, can you try using the `StreamMessageInput`? 
You can read here how to migrate https://getstream.io/chat/docs/sdk/flutter/guides/migration_guide_4_0/#messageinput-to-streammessageinput

**Comment by matthewfx** [comment]
@imtoori uh oh... That's possible I haven't noticed it is deprecated. Will give it a go. Thank you :)

**Comment by matthewfx** [comment]
@imtoori Just wanted to confirm that after replacing deprecated `MessageInput` with its successor everything works fine. Thank you!
