### ISSUE TITLE
User.name missing within message.user object

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1197]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS

### What version are you using?

  stream_chat_flutter: ^4.2.0
  stream_chat_localizations: ^3.1.0
  stream_chat_persistence: ^4.1.0

### What happened?

Message.user does not match the actual user object. `name` is missing
This is how we set the users name on sign in, making sure that all messages are shown with the correct first name (e.g. "Max"):
```
    final streamChatUser = User(id: streamUsername, name: ownUserObject.displayName);
    final tokens = await _authenticationRepository.tokens();
    final streamChatToken = tokens.streamChatToken;
    return await client.connectUser(streamChatUser, streamChatToken);

```
This is how this looks in the streamchat dashboard: 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/6661557/172662446-0418fe8d-b777-4a5e-a95a-e71e2f1b295a.png">

When sending a message this is what the user object in the message looks like: 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/6661557/172662522-4817888d-9d6e-4ee5-953c-7f3d7989b2e2.png">

As far as i recall, this only happened after i reacted to one message. After adding the reaction the Name displayed below the message was immediately exchanged with the `user.id` and now all new messages do not have the `user.name` property set.

Logout, Restart, Login, triggering the `client.connectUser` logic again, does sadly not resolve the issue for the effected user. 

### Steps to reproduce

```bash
Note: I was unable to reproduce it with these steps, but this is how I initially did it:
1. Register two streamchat users with the name property set
2. Send some messages between the two messages. The set name property shows below the message
3. As one user react to the message from the other user
4. The set name property is removed and the user.id is shown instead
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
I can't manage to reproduce this issue, do you have more info on this?
