### ISSUE TITLE
MessageInput grows indefinitely

### ISSUE THREAD

**Issue by nosmirck** [GetStream/stream-chat-flutter#12]
Message Input grows with message content but doesn't stop, reaching an overflow.

Image attached for reference:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 11 47 25](https://user-images.githubusercontent.com/6027290/78578802-05bea480-77fe-11ea-8916-43817ee58d62.png)

If there's no one working on this one, I can PR a fix today.

**Comment by imtoori** [comment]
We'll fix it as soon as possible, however feel free to contribute

**Comment by nosmirck** [comment]
@imtoori  PR is up! :)
