### ISSUE TITLE
Add Custom Emoji Support

### ISSUE THREAD

**Issue by ayush221b** [GetStream/stream-chat-flutter#1208]
Customers might have a set of custom emojis that they would like to use. 

1. Figure out the best way to support custom emojis
    Should we support an emoji picker that can pick a data source which is default or custom or both?
2. What is the simplest way to use custom emojis? Can it fit in a guide, or a blog post? Does it need a fully functional example?

**Comment by imtoori** [comment]
Using #989 it's very easy to achieve this. Let's write a guide on it.

**Comment by imtoori** [comment]
closing this in favor of #1275
