### ISSUE TITLE
Show in chat and Reply not working

### ISSUE THREAD

**Issue by tarunkhatri** [GetStream/stream-chat-flutter#1211]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

4.2.0

### What happened?

Show in chat is not working and Reply is just closing detail screen. Please add some parameters so that we can show/hide these buttons or just add some functionality for them thanks.
![untitled](https://user-images.githubusercontent.com/57035940/174073177-3b29e3bb-321b-4ccf-88ba-9a59ead5723a.gif)

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arteminthesky** [comment]
Hi! You can hide the Reply button with showReplyMessage parameter of the StreamMessageWidget.
You can provide this parameter by setting it in the messageBuilder of the StreamMessageListView.

`
StreamMessageListView(
        ....
        messageBuilder: BuildContext context, BaseProfile artist, StreamMessageInputController? inputController) {
               return widget.copyWith(showReplyMessage: false);
        },
      ),
`

**Comment by imtoori** [comment]
Hi
We're improving this in v5, but you can still use it at the moment
```dart
StreamMessageListView(
                messageBuilder:
                    (context, details, messages, defaultMessageWidget) {
                  return defaultMessageWidget.copyWith(onReplyTap: _reply);
                },
              )
```
Basically, you need to pass the `onReplyTap` callback to the message widget
