### ISSUE TITLE
Reply button does not responses.

### ISSUE THREAD

**Issue by Hwan-seok** [GetStream/stream-chat-flutter#1229]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

4.3.0

### What happened?

When tapping the reply button, it responds nothing.
It only closes the gallery page.

### Steps to reproduce

```bash
1. Send the image to other.
2. Tap the image
3. Tap action button(more_dots)
4. Tap reply button
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
To make the reply button in the gallery work you should use the `StreamMessageListView.onMessageSwiped` function.
I get that it's not clear and that we shouldn't show the button if you don't pass the callback, that's what we're doing on v5. (at the moment it's in beta)
