### ISSUE TITLE
Show in chat button is not working

### ISSUE THREAD

**Issue by Hwan-seok** [GetStream/stream-chat-flutter#1230]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

4.3.0

### What happened?

When tapping the `Show in Chat` button, it responses nothing.

### Steps to reproduce

```bash
1. Send image to other
2. Tap image
3. Tap action button
4. Tap `Show in Chat` button
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
To make the `Show in Chat` button work you should the `MessageWidget.onShowMessage` property using the `StreamMessageListView.messageBuilder`
More info on this page https://getstream.io/chat/docs/sdk/flutter/guides/customize_message_widget/
Let me know if you have any questions
