### ISSUE TITLE
Multiple Issues related to attachments on web

### ISSUE THREAD

**Issue by Ayush-gupta-josh** [GetStream/stream-chat-flutter#1231]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

5.0.0-beta.1

### What happened?

- [ ] Video Thumbnail Not loading at all, shows red warning size instead
- [ ] Clicking on a video while the upload is in progress opens Red Error Screen
- [ ] Save Video / Save Image not working from the attachment preview modal
- [ ] The Reply button doesn't work in the Attachment preview modal, it just closes the modal
- [ ] Uploading SVG Images doesn't work
- [ ] The reaction icons are not visible due to transparent border (Using the `accentPrimary` as blue)
- [ ] The reply action for the video shows the blob URL of the video, we can improve this behavior. Along side the whole video tile is not clickable, only the `!` icon is clickable
![image](https://user-images.githubusercontent.com/67139749/176861900-a2eb769d-99f4-4723-a9d4-3574ad9bc591.png)
- [ ] Although no text is added, there is a blank space at the bottom when the video is upload
![image](https://user-images.githubusercontent.com/67139749/176861218-8d5dafc6-c513-4f5c-a8fe-694f7d2110f2.png)

Reference Video:

https://user-images.githubusercontent.com/67139749/176863857-3c2d8d0d-9051-4979-ab7f-59a99fce30da.mp4

### Steps to reproduce

```bash
Refer to the attached video.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ayush-gupta-josh** [comment]
@imtoori Any timeline for the resolution of above issues

**Comment by imtoori** [comment]
I think a couple of weeks is reasonable, we're gonna include those in the next v5 releases

**Comment by Ayush-gupta-josh** [comment]
@imtoori Any updates on upcoming release?

**Comment by imtoori** [comment]
Hi @Ayush-gupta-josh I think I solved all this issues 
You can checkout the v5 branch and see if everything works fine or you can wait for the next release, probably tomorrow

**Comment by esarbanis** [comment]
This is almost a year old, I am going to close it in order to clean up the backlog. If you think this is still relevant then feel free to re-open it.
