### ISSUE TITLE
Custom divider builder not showing

### ISSUE THREAD

**Issue by EtcGonza** [GetStream/stream-chat-flutter#1232]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: ^4.3.0

### What happened?

Hi! I have in my app a StreamMessageListView with a custom date divider and showFloatingDateDivider in false because my app doesn't need floating dividers.

This is my code

```
StreamMessageListView(
                showFloatingDateDivider: false,
                messageFilter: (message) => _canShowMessage(message),
                dateDividerBuilder: (date) => CustomDateDivider(date),
                messageBuilder: (context, details, messageList, defaultImpl) =>
                    CustomMessage(message: details.message),
                onMessageSwiped: (messageSwiped) =>
                    _replyMessage(messageSwiped),
              ),
```

With this configuration my app doesn't show the date dividers even if I remove my custom divider still. Only shows my custom divider if a switch showFloatingDateDivider to true. This behavier is correct? I downgrade the version of my stream_chat_flutter to 3.x.x and the custom dividers shows.

### Steps to reproduce

```bash
1. Implement a StreamMessageListView.
2. Set the showFloatingDateDivider to false.
3. Set (or not) a custom widget for the dateDividerBuilder.
4. check if the custom date divider shows
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @EtcGonza, I tried reproducing your issue but it's working fine for me. Can you share a sample code snippet where I can replicate this?

Thanks.

**Comment by EtcGonza** [comment]
Hi! @xsahil03x . Today I tryed to use custom date dividers in the samples [https://github.com/GetStream/flutter-samples](url).

I run the stream_chat_v1 sample and modified the StreamMessageListView in the channel_page.dart. And the date divider doesn't appearce. This is my modiffied code of the sample.

```
                StreamMessageListView(
                 /// My code
                  showFloatingDateDivider: false, /// Only if you set this in true the divider shows.
                  dateDividerBuilder: (date) => Container(
                    color: Colors.purple,
                    child: Text(date.toString()),
                  ),
                 /// ------------------
                  initialScrollIndex: widget.initialScrollIndex,
                  initialAlignment: widget.initialAlignment,
                  highlightInitialMessage: widget.highlightInitialMessage,
                  onMessageSwiped: _reply,
                  messageFilter: defaultFilter,
                  messageBuilder: (context, details, messages, defaultMessage) {
                    return defaultMessage.copyWith(
                      onReplyTap: _reply,
                      onShowMessage: (m, c) async {
                        final client = StreamChat.of(context).client;
                        final message = m;
                        final channel = client.channel(
                          c.type,
                          id: c.id,
                        );
                        if (channel.state == null) {
                          await channel.watch();
                        }
                        Navigator.pushReplacementNamed(
                          context,
                          Routes.CHANNEL_PAGE,
                          arguments: ChannelPageArgs(
                            channel: channel,
                            initialMessage: message,
                          ),
                        );
                      },
                      deletedBottomRowBuilder: (context, message) {
                        return const StreamVisibleFootnote();
                      },
                    );
                  },
                  threadBuilder: (_, parentMessage) {
                    return ThreadPage(parent: parentMessage!);
                  },
                ),
```

The only changes I did is the *showFloatingDateDivider* to false and set *dateDividerBuilder*. The rest of the code have no changes.

This is how it looks with the *showFloatingDateDivider* in true
![image](https://user-images.githubusercontent.com/44512291/177853293-62d8f2b1-3d0a-436f-befc-a237574da486.png)

And this is if you set the *showFloatingDateDivider* to false. The divider doesn't appearce even if I don't use the custom divider builder.
![image](https://user-images.githubusercontent.com/44512291/177853418-131b03de-9ea0-4550-bdcf-f9ac022a055e.png)

The sample used stream_chat_flutter: ^4.2.0.
