### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by dokumanx** [GetStream/stream-chat-flutter#1234]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter_core: ^4.3.0
stream_chat_flutter: ^4.3.0

### What happened?

I used `StreamChannelListView` to display available channels. But in `StreamChannelListTile`, `StreamSendingIndicator` throws an exception. `channelState.currentUserRead!.lastRead` causes the error. Because `currentUserRead` returns `null`.

No matter which user sends a message to a channel, `currentUserRead` will return always `null`.

### Steps to reproduce

```bash
1- Navigate to StreamChannelListView.
2- It will throw the error
```

### Supporting info to reproduce

I have no clue 

### Relevant log output

```shell
When the exception was thrown, this was the stack: 
#0      StreamChannelListTile.build.<anonymous closure>.<anonymous closure> (package:stream_chat_flutter/src/v4/scroll_view/channel_scroll_view/stream_channel_list_tile.dart:211:51)
#1      _BetterStreamBuilderState.build (package:stream_chat_flutter_core/src/better_stream_builder.dart:62:26)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4968:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (15 frames)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#28     SlottedRenderObjectElement._updateChild (package:flutter/src/widgets/slotted_render_object_widget.dart:242:31)
#29     SlottedRenderObjectElement._updateChildren (package:flutter/src/widgets/slotted_render_object_widget.dart:235:7)
#30     SlottedRenderObjectElement.mount (package:flutter/src/widgets/slotted_render_object_widget.dart:214:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @dokumanx, Can you confirm if you are also connecting the user first before opening the channel list?

**Comment by dokumanx** [comment]
Hey @xsahil03x, thank you for your response. Yes, I can confirm.

**Comment by mingzew** [comment]
Hi this issue is still happening in the latest 5.2.0 release. I see the approved merge request, but the changes are not reflected in the code for the said release

**Comment by Aaron2464** [comment]
I faced the same issue in 5.3.0 release.

**Comment by Velkamhell97** [comment]
Same with 5.3.0 🙁

**Comment by Aaron2464** [comment]
@mingzew @Velkamhell97  
I faced same issue few days before.
And I found out if you are using gaming/livestream type, you have to go to Dashboard -> Channel Types to switch on "Read Event" / "Typing Event".
Hope this can help you out.

**Comment by Velkamhell97** [comment]
> @mingzew @Velkamhell97 I faced same issue few days before. And I found out if you are using gaming/livestream type, you have to go to Dashboard -> Channel Types to switch on "Read Event" / "Typing Event". Hope this can help you out.

Hi @Aaron2464  i am using "mesaging" type and that options are enabled by default, so i dont know if it is a bug or i i'm missing something, anyway thanks for your advice 😁. i'm going to do more tests and wait for updates.
