### ISSUE TITLE
Data Payload issue

### ISSUE THREAD

**Issue by ankitTiwar** [GetStream/stream-chat-flutter#1252]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter_core: ^4.2.0

### What happened?

We are not getting the click_action key in the data payload for redirection on the particular screen

<img width="794" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/102948392/177697865-2477fd73-5f69-44ea-add1-6be87ebef9c8.png">

### Steps to reproduce

```bash
Just send the notification and check the data payload, we are using Ruby and Rails as Backend SDK.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @ankitTiwar 
we don't add the `click_action` by default
Did you use the template on your dashboard to add this field? https://dashboard.getstream.io/app/<YOUR-APP-ID>/chat/push/single/firebase/

**Comment by bhavy5145** [comment]
Can you Let us know how to add it?
When I tried to add it is adding in notification payload and not in data payload,
we need the key to be added to the data payload.
