### ISSUE TITLE
Mute method mutes the logged user

### ISSUE THREAD

**Issue by EtcGonza** [GetStream/stream-chat-flutter#1266]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: ^4.4.0

### What happened?

Hi! I created a issue a few months ago about the mute/unmute feature #1053 . The most of the issues I reported are solved, but one still.

When I mute a user adds the id of the user logged. If my user have id 1 and I want to mute the user with Id 7, in the list of mutes adds an entry with the user id 1. I tryied few times more and the list of mutes always add a new entry of the logged user.

I triple checked my implementacion because maybe... was my mistake. So i checked if the id of the user I was passing to the mute method. It was correct.

So I guess that the mute method is doing something wrong.

### Steps to reproduce

```bash
1. Log in with some user.
2. Use the method mute that provides the StreamChatClient class.
3. Check the array of mutes of the logged user (OwnUser).
4. You should see an instance of the logged user.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kanat** [comment]
Hey @EtcGonza,

I've tried to replicate the issue with no luck.

There is a debug screen available in the [example app](https://github.com/GetStream/stream-chat-flutter/tree/fix/1266-mute/packages/stream_chat_flutter/example) now. 
Feel free to play around and see if you're still able to reproduce this issue: https://github.com/GetStream/stream-chat-flutter/pull/1601
