### ISSUE TITLE
StreamMessageSearchListView always show loading indicator

### ISSUE THREAD

**Issue by NiyazFazlyev** [GetStream/stream-chat-flutter#1271]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

4.3.0

### What happened?

When I am using StreamMessageSearchListView widget I always see loading indicator after data is completely loaded.
This issue repeats https://github.com/GetStream/stream-chat-flutter/issues/1181

### Steps to reproduce

```bash
- Implement StreamMessageSearchListView.(Used code from https://getstream.io/chat/docs/sdk/flutter/stream_chat_flutter/stream_message_search_list_view/ ).

- Loading Indicator spins infinitely.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mark-heyylife** [comment]
Hi Imtoori,
I have the same problem with StreamChannelListView 
GetStream version: 4.4.0
Reproduce steps:
1. Implement StreamChannelListView as example
2. Click one item in StreamChannelListView to open StreamChannel
3. Send and receive message in opened channel.
4. Go back to StreamChannelListView
==> Loading more indicator is shown and can't be dismissed

**Comment by imtoori** [comment]
This is a backend issue and the team is working on it, I'll update you when I have more information

**Comment by imtoori** [comment]
Hi the backend has been fixed, I'm closing this issue.
If you're still experiencing it, please contact support
