### ISSUE TITLE
Stream user's online flag does not get updated in real time. There is some delay in updation of user's online flag.

### ISSUE THREAD

**Issue by adityathakur8929** [GetStream/stream-chat-flutter#1272]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

4.1.0

### What happened?

When a user has minimized or closed the app the stream user's online flag take some delay in updating its value on stream.

### Steps to reproduce

```bash
1. Open chat application and send messages to other users registered on stream
2. Close or minimize the app 
3. Check online flag on stream dashboard for the user logged in
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hi @adityathakur8929 this is expected
we have a ~5 mins resolution to update the online status
