### ISSUE TITLE
Ability to scroll left and right in media attachment fullscreen

### ISSUE THREAD

**Issue by bhanuU25** [GetStream/stream-chat-flutter#1281]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Ability to scroll the media attachment in chat when you open attachment in full screen.

The Problem: You can only view the current image in the chat, but if I try to scroll left or right it doesn't show the previous media attachment which was sent earlier.

### Describe the solution that you'd like

If we can implement something like what you have in ChannelInfo page inside Photos and Videos.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
This is something that can be achieved as shown in our [example app](https://github.com/GetStream/flutter-samples/blob/016d7ae4eff22e61cbad97c957d62b7164db2048/packages/stream_chat_v1/lib/pages/channel_media_display_screen.dart#L9).

I am closing this issue as stale.
