### ISSUE TITLE
Slack-like reactions

### ISSUE THREAD

**Issue by BrunoJurkovic** [GetStream/stream-chat-flutter#1284]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

One of my projects require a "Slack" like emoji reactions. I was surprised that this is supported in React Native, but not in Flutter? 

### Describe the solution that you'd like

Basically the exact same functionality for the emoji reactions as from the React Native SDK.

https://getstream.io/blog/slack-clone-with-stream-chat-part-1/

### Describe alternatives that you have considered

Building our own custom message widget. Would be very time-expensive and is the last possible solution we are considering.

### Additional context

https://getstream.io/blog/slack-clone-with-stream-chat-part-1/
[Example](https://cdn.vox-cdn.com/thumbor/i_boDRFGzp-KabfDX4UMxZPpoBA=/0x0:500x139/1200x0/filters:focal(0x0:500x139):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/3856280/tumblr_inline_nr6itnVinW1tqy3dn_500.0.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey 
this shouldn't be hard to achieve
we're doing something similar in v5, but only for desktop
I think it will be easy to make it available and configurable for all platforms
we'll keep this is mind, thanks

**Comment by BrunoJurkovic** [comment]
@imtoori Thanks for the response, when is v5 planned?

**Comment by imtoori** [comment]
it's already out as beta
we're working on a stable release to be pushed in the upcoming weeks

**Comment by BrunoJurkovic** [comment]
> it's already out as beta we're working on a stable release to be pushed in the upcoming weeks

Wow, sounds perfect. Thanks for the good work & the quick response Salvatore!

**Comment by imtoori** [comment]
Thank you :)
I'll leave this open so that we can use this issue to make sure we provide this correctly

**Comment by BrunoJurkovic** [comment]
Hey, looking at your W.I.P. migration guide, I noticed that the bubble reactions are going to be only for web and desktop. Is there any way to enable them for mobile?

Also, what would be the best route for replacing the standard reactions with all emojis?

**Comment by BrunoJurkovic** [comment]
Hey @imtoori, can you check this out please?

**Comment by imtoori** [comment]
hey @BrunoJurkovic I think there's no easy way of doing that on mobile yet
It shouldn't be hard to support it. I'm gonna look into it

**Comment by imtoori** [comment]
@BrunoJurkovic this is gonna take a while because we want to do that as configurable as possible

Anyways It shouldn't be hard to do that on your own. Let me know if you need help but I think customizing the bottom row should be enough

**Comment by xsahil03x** [comment]
Closing as not planned, You can always customize the bottom row to achieve this.
