### ISSUE TITLE
Weird Backgound overlay over attachments

### ISSUE THREAD

**Issue by bhanu-under25** [GetStream/stream-chat-flutter#1302]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

  stream_chat_flutter: ^4.4.0

### What happened?

Please refer to below screenshot and video:

![ss](https://user-images.githubusercontent.com/92363650/184311128-52a7a514-1078-4633-9600-57c4816f0532.jpeg)

https://user-images.githubusercontent.com/92363650/184311113-ba91e70e-2670-4ad5-95d6-8afafa5c6451.mp4

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi this is weird indeed 
Is it still happening for you? I'm trying to reproduce this, but I'm struggling
Can you post a snippet of your code, or something that might help me, please?

**Comment by bhanu-under25** [comment]
This is from stream sample app.

It mostly occurs in android!

**Comment by imtoori** [comment]
I just tried and it's not glitching like that for me.
Did you change anything? Also does it happen in any specific situation or with any specific gif?
