### ISSUE TITLE
video_thumbnail package update

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1303]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

4.4.1

### What happened?

The video_thumbnail package has an issue that they fixed with version 0.5.2. Please update to the latest package.

### Steps to reproduce

```bash
Run the application.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rlee1990** [comment]
I created #1304 to fix this issue.

**Comment by rlee1990** [comment]
It appears that this issue still hasn't been completely fixed yet.

**Comment by imtoori** [comment]
Hi @rlee1990 
we're using version ^0.5.0, so it should use 0.5.2 if you run flutter pub upgrade
Can you confirm?

**Comment by rlee1990** [comment]
@imtoori Yes there is still an issue the issue is the video thumbnail package. There is a pull request to fix the issue but everyone is waiting for the package owner to merge it.

**Comment by arthurpiccoli** [comment]
@rlee1990 if you lock the version in the pubspec of your project as so:` video_thumbnail: 0.5.1` you're good to go. @imtoori a catch block was removed from 0.5.1 to 0.5.2 and that's what is broking the build

**Comment by rlee1990** [comment]
> was removed from 0.5.1 to 0.5.2 and that's what is broking the build

How can I do that if I am not directly using that package but I am using Stream chat.
