### ISSUE TITLE
Validation Issue when TextInputType.text is passed to StreamMessageInput widget

### ISSUE THREAD

**Issue by mayankeshmishra** [GetStream/stream-chat-flutter#1306]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android, Web

### What version are you using?

version-4.3.0

### What happened?

The default behavious of the StreamMessageInput field is that on pressing the enter key a new line is inserted.
This behaviour is overriden when we pass keyboardType: TextInputType.text and now instead of adding a new line the field gets submitted.
Due to this behaviour, the validations passed to the StreamMessageWidgets don't work and the user is able to send empty message without any text

### Steps to reproduce

```bash
1. Pass keyboardType: TextInputType.text
2. Go to Messages page
3. Click inside message field and press enter without typing anything
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hey @mayankeshmishra this has been fixed in v5
At the moment it's a beta release, but it will soon be out as stable
