### ISSUE TITLE
Channel data null when opening chat screen from notification from terminated state

### ISSUE THREAD

**Issue by BrunoJurkovic** [GetStream/stream-chat-flutter#1307]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter - 4.1.0

### What happened?

We have a very interesting and weird issue. We are handling Stream notifications from the background, foreground, and terminated state. Handling the former two were easy, but we're having an issue handling the notification from the terminated state.

When the app is in the terminated state, upon clicking the notification, the app is opened with the chat screen, but the chat is loading infinitely. Upon closer inspection, we realized that the `client.channel(...)` method is returning a channel, but only with the id, and no other data. 

We practically use the same logic for all of the three scenarios but for this one it just simply doesn't work.

### Steps to reproduce

```bash
1. Send either a test notification or have a colleague send me a message
2. Ensure that the app is terminated
3. Tap on the notification
4. Issue occurs
```

### Supporting info to reproduce

Stream has not initialized yet, but we are handling the terminated state way deep inside ep inside of our app loading process, so this should not be the issue.

Minimum code sample.

```dart
FirebaseMessaging.instance.getInitialMessage().then((message) async {
      if (!didHandleInitialMessage) {
        didHandleInitialMessage = true;
        if (message != null) {
          final notification = message.notification;
          if (notification != null) {
            if (message.data['sender'] == 'stream.chat') {
                final channel = sl<StreamChatClient>().channel(
                  'messaging',
                  id: message.data['channel_id'] as String,
                ScaffoldMessenger.of(context).showSnackBar(
                  MoonSnackBar.snackBar(
                    color: MoonTheme.softBlue,
                    text: '${channel.name} ${channel.id}, ${channel.name}',
                  ),
                );
                await context.router.push(MoonChatRoute(channel: channel));
            }
          }
        }
      }
    });
    ```

- [X] I agree to follow this project's Code of Conduct

**Comment by ManasviPatidar** [comment]
You can add this before navigation to query for the channel state.
`if (channel.state == null) {
      await channel.watch();
    }`

**Comment by BrunoJurkovic** [comment]
> You can add this before navigation to query for the channel state. `if (channel.state == null) { await channel.watch(); }`

Thanks for the quick response, interestingly, the workaround I discovered for this is just delaying the `.channel` and navigation by 1500ms. This is of course far from the ideal answer.

How come the `.channel` method is not async? Seems like it would make sense for this to be awaitable?

**Comment by imtoori** [comment]
Hi @BrunoJurkovic 
`StreamChatClient.channel` returns a channel object, then it's on you to call `channel.watch()/query()` or whatever method you need
It doesn't make much sense for the method to be async since it doesn't perform any async operations
