### ISSUE TITLE
Duplicate notification when app is either in the background or terminated state

### ISSUE THREAD

**Issue by arizonal2014** [GetStream/stream-chat-flutter#1310]
Hello there!
I am using Push Notifications (V2)everything seems working fine except that I am receiving duplicate notifications when the app is either in the background or terminated state.

As per this [](https://stackoverflow.com/questions/67820474/double-notifications-in-flutter-firebase-messaging) answered, I am receiving both notification and data.

I also tried to use a template to no avail.

**Comment by BrunoJurkovic** [comment]
Are you maybe using a local notifications plugin? 

Check [this thread](https://stackoverflow.com/questions/69024672/duplicate-notifications-with-different-sounds-push-notification-remote) out, should resolve your issue.

**Comment by arizonal2014** [comment]
Yes. I am using a local notification plugin as stated in the doc https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications_v2/

any directive on how to send a data message instead of a notification message with your backend javascript SDK?
?

**Comment by arizonal2014** [comment]
I have fixed it.
