### ISSUE TITLE
Image library shows up blurry 

### ISSUE THREAD

**Issue by BrunoJurkovic** [GetStream/stream-chat-flutter#1311]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: ^4.1.0
stream_chat_persistence: ^4.1.0

### What happened?

We've noticed that in the image library, sometimes the images are really blurry, and sometimes they are just noticeably blurry. 

Is there anything we can do about this? Thanks.

![image](https://i.imgur.com/osxJggI.png)

### Steps to reproduce

```bash
1. Click on the attachment button
2. Images are blurry

This seems really hard to reproduce, but the images are always at least a little blurry.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @BrunoJurkovic, this has been fixed in the latest release, thanks
https://pub.dev/packages/stream_chat_flutter/changelog#450
