### ISSUE TITLE
Weird indicator on pinned messages

### ISSUE THREAD

**Issue by BrunoJurkovic** [GetStream/stream-chat-flutter#1312]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: ^4.1.0
  stream_chat_persistence: ^4.1.0

### What happened?

When we pin a message, on the top left or right side there seems to be some weird bubble indicator that resembles the reaction indicator (but with no reaction).

(just pinning)
<img width="145" alt="Screenshot 2022-08-23 at 14 30 15" src="https://user-images.githubusercontent.com/28235257/186158352-bd58cdba-edf2-495b-9021-e1fd7a051f90.png">
 
 When we react to a message, there is an additional indicator that seems to stack.
 
 (pinning & reacting)
<img width="156" alt="image" src="https://user-images.githubusercontent.com/28235257/186158682-87e9c804-24c8-49d6-a2bc-3aceafc36949.png">

### Steps to reproduce

```bash
1. Open chat
2. Pin a message
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi
Are you customizing the widget in any way?
I just tested this and it's not happening for me

**Comment by BrunoJurkovic** [comment]
> Hi Are you customizing the widget in any way? I just tested this and it's not happening for me

Not in any way that should affect this. We are just implementing a bunch of custom messages. I'll go to the dev tools to see which widget is causing this

**Comment by imtoori** [comment]
That's the message widget, but I'm not seeing that :/ 
Very weird..

**Comment by BrunoJurkovic** [comment]
I can't find it in the Widget Inspector. This is very very weird, any ideas on how I might isolate it? Any additional data I can provide so that we can solve this? It's obviously not a glaring nor critical issue, but would still be nice to not have it.

**Comment by imtoori** [comment]
Can you send me a snippet of how you customize the MessageWidget? Do you use the `StreamMessageListView.messageBuilder` param?

**Comment by BrunoJurkovic** [comment]
```dart
 return defaultMessageWidget.copyWith(
    showThreadReplyIndicator:
        (details.message.threadParticipants?.length ?? 0) > 0,
    showThreadReplyMessage: true,
    showTimestamp: true,
    showReplyMessage: true,
    showReactionPickerIndicator: true,
  );
  ```
  
  I've omitted the custom message types

**Comment by imtoori** [comment]
ok I think I got it
`showReactionPickerIndicator` is the property that toggles that ui
We need that in order to show the proper ui when there are reactions on the message. the UI is really tricky, so this was our only option.
I'd delete that line, it should work fine
