### ISSUE TITLE
Message shows as unread even when user is on chat screen

### ISSUE THREAD

**Issue by bhayatus** [GetStream/stream-chat-flutter#1314]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter - 4.5.0
stream_chat_flutter_core - 4.5.0

### What happened?

I am on the chat screen, and after sending a message, the other side sends a message back. Shows an unread message banner, even though I am still viewing the chat. Expected behaviour is that the unread message banner is not shown if I am on the page.

### Steps to reproduce

```bash
1. I am on the chat screen (using the StreamMessageListView), and send a message first. 
2. The other side then sends a message, while I am still viewing the chat screen. 
3. Shows "1 unread message". 
4. If the other side sends another message, it then changes to "2 unread messages".
5. If I send a message, the unread message banner goes away.
```

### Supporting info to reproduce

![image](https://user-images.githubusercontent.com/35541711/186183473-1d147c6b-e2e6-479a-a296-537d57c4cecc.png)
![image](https://user-images.githubusercontent.com/35541711/186183508-cef95ba9-01d2-45f4-8dd6-f6e3e92800f6.png)
![image](https://user-images.githubusercontent.com/35541711/186183534-0c4a4b26-721f-46e6-9366-8e6dc337ec5a.png)

### Flutter analyze output

```shell
$ flutter analyze
Analyzing src...                                                        
No issues found! (ran in 7.9s)
```

### Flutter doctor output

```shell
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 20.04.4 LTS 5.14.0-1048-oem,
    locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @bhayatus this has been fixed on v5
it's a beta at the moment, but will soon reach a stable release
stay tuned :)
