### ISSUE TITLE
showEditMessage has no effect

### ISSUE THREAD

**Issue by BrunoJurkovic** [GetStream/stream-chat-flutter#1317]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter - 4.1.0

### What happened?

It seems like the `showEditMessage` property is not working as intended. Whatever the value is set as, the action will always show. With a quick 'CTRL + F', it seems like it is not linked to anything.

### Steps to reproduce

```bash
1. Set the property to true
2. Inspect
3. Set the property to false
4. Inspect
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BrunoJurkovic** [comment]
@imtoori Could you please take a look?

**Comment by imtoori** [comment]
Hey @BrunoJurkovic this has been fixed in the later versions of the SDK
we're now at 4.5.0
Can you update?
