### ISSUE TITLE
invite link generation to send the link on group to join members when they click on that link.

### ISSUE THREAD

**Issue by sanketp1** [GetStream/stream-chat-flutter#1318]
### Please select which package this feature is related to

stream_chat

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Actually, I am working on the project where my team want to generate the invitation link for joining the channel or group. I was read many articles but didn't find the relevant one.
Could anyone please help me with this?

### Describe the solution that you'd like

when create the invitation link and send to any group there will be custom widget like join this group like whatsapp.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanketp1** [comment]
anyone please help me with this.

**Comment by imtoori** [comment]
Hello
I'm sorry, but I talked with the backend team and there's nothing we can do about this. 
You should implement this on your side.

**Comment by imtoori** [comment]
I think the solution by @bhanu-under25 might work fine
