### ISSUE TITLE
Grouped channels

### ISSUE THREAD

**Issue by csandovalgt** [GetStream/stream-chat-flutter#1320]
Hi team,
I'm implementing a chat with grouped channels. I'm using own criteria for channels grouping and my question is if is there any way to get the total_unread_count for a group of channels or by channels type.

I see in the documentation that there are total_unread_count and unread_channels but I don't see anything to filter by own criteria or by channel type. Obviously I would like to have those values in real time.

Any help would be appreciated.

**Comment by imtoori** [comment]
This is not possible at the moment, it's a backend limitation.

**Comment by Srj-Love** [comment]
Hey This is also my requirement, 
can I get the update on this?

**Comment by csandovalgt** [comment]
hi @Srj-Love , I ended implementing this on my own backend.

**Comment by Srj-Love** [comment]
Great!, can you help me out with your implementation.

Thanks
