### ISSUE TITLE
[Android] App don't show enablePhotoAndVideoAccessMessage after denying permissions

### ISSUE THREAD

**Issue by arteminthesky** [GetStream/stream-chat-flutter#1322]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

4.5.0

### What happened?

The problem is there are two places where the package requests photo permissions simultaneously
[First place](https://github.com/GetStream/stream-chat-flutter/blob/4532a0dd69c2c86c762760f3fde2a152c30c9065/packages/stream_chat_flutter/lib/src/v4/message_input/stream_attachment_picker.dart#L325)
[Second place](https://github.com/GetStream/stream-chat-flutter/blob/4532a0dd69c2c86c762760f3fde2a152c30c9065/packages/stream_chat_flutter/lib/src/v4/message_input/stream_attachment_picker.dart#L543)

And in second place throws error which is not handled in the package

Error:
PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done.)

### Steps to reproduce

```bash
1. Go to Chat contains StreamMessageInput
2. Tap Attachment button
3. Deny permission
4. See empty placeholder (Offstage)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
This has been solved in v5, it's a beta release, but it will be promoted to stable soon
