### ISSUE TITLE
StreamMessageListView not displaying messages

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1323]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS

### What version are you using?

  stream_chat_flutter: 4.5.0
  stream_chat_localizations: 3.3.0
  stream_chat_persistence: 4.4.0

### What happened?

we use the `StreamMessageListView` and this is the behaviour starting to happen when upgrading to flutter 3.3

![File](https://user-images.githubusercontent.com/6661557/187886562-8eb9451c-6a8d-4b86-98b5-4fe59e5ebea0.jpg)

### Steps to reproduce

```bash
1. Upgrade to flutter 3.3
2. Use StreamMessageListView
3. observe broken message widgets
```

### Supporting info to reproduce

This does not occur on flutter 3.0.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
you're right, this is happening and I can reproduce it
it seems like flutter 3.3 broke something
let me take a look at it

**Comment by CalHoll** [comment]
Any chance for an ETA on bugfix?

**Comment by imtoori** [comment]
@CalHoll you're right, removing that seems to solve the issue
Let me see if this causes any other problem

**Comment by johnsonejezie** [comment]
When will this be published?

**Comment by imtoori** [comment]
@johnsonejezie yes, in the following days

**Comment by CalHoll** [comment]
See it made it into 4.6.0, can we get this on the [5.0.0-beta.2](https://pub.dev/packages/stream_chat_flutter/versions/5.0.0-beta.2) 
 channel too? Thanks!

**Comment by Froelund** [comment]
It seems there's still some issues with 4.6.0 and flutter 3.3.2.https://user-images.githubusercontent.com/2089088/192001064-e41bfb46-1c6e-470a-bb32-5e234a6368f5.MOV

**Comment by imtoori** [comment]
@Froelund it's working fine for me :/

**Comment by Froelund** [comment]
Well that is sort of good to hear :P Are you using `stream_chat_flutter: 4.6.0`? Anyone else still has the issue? Maybe @flodaniel ?

**Comment by imtoori** [comment]
yes I'm using 4.6.0 and the latest flutter version

**Comment by Froelund** [comment]
For future users with this issue: Our problem was that the theme for our `MaterialApp` had this configuration:
```
cardTheme: CardTheme(
  shadowColor: Theme.of(context).shadowColor.withOpacity(0.5),
  clipBehavior: Clip.hardEdge, // We removed this, and the issue was solved.
  elevation: 2,
),
```
