### ISSUE TITLE
In version 5.0.0-beta.2 - hitting "enter" on the android keyboard sends the message instead of going to a new line

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#1326]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter

### Which platforms would this feature impact?

Android

### Is your feature request related to a problem?

In version 5.0.0-beta.2 - hitting "enter" on the android keyboard sends the message instead of going to a new line.

Please add a parameter to StreamMessageInput so that "enter" goes to a new line for multi-lined messages.

### Describe the solution that you'd like

Please add a parameter to StreamMessageInput so that "enter" goes to a new line for multi-lined messages.

### Describe alternatives that you have considered

Disable the enter button? or change default keyboard type.

### Additional context

This is not expected behavior, there's a button for "send" already, so the enter button (on mobile), should go to a new line.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @CalHoll, 

fixed in [`d3fff37` (#1222)](https://github.com/GetStream/stream-chat-flutter/pull/1222/commits/d3fff37fcdd7adcc1defb63eeeb1d48e422fedbb) and will be released soon.

Thanks,
Sahil
