### ISSUE TITLE
Make it obvious which thread contains unread messages

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#1337]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

Users are frustrated when they have an unread message but can't find it because it's in a thread.

### Describe the solution that you'd like

When a thread contains unread messages an icon and bolded/colored text or some other identifier should be used to easily find which thread contains the unread message.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalHoll** [comment]
Looks good! That would help for sure :-)

**Comment by leandroBorgesFerreira** [comment]
Hello @CalHoll. To solve this issue we need the information from the backend about the date of the last message inside a thread. 

The threads are going to receive a work in the next quarter of this year.

**Comment by CalHoll** [comment]
I guess that implementation makes sense, so you need a new table joined against the thread message table and the corresponding API endpoint?

I appreciate the update!

**Comment by celineestrada** [comment]
My team is also looking to achieve something very similar to this but for stream-chat-react-native. Would be great if we could get infrastructure for tracking unread thread replies!

**Comment by AndreHaueisen** [comment]
Any updates on this issue?

**Comment by crxm** [comment]
From the stream-ci-bot, it look like unread counts for threads was merged into the stream-chat-react branch yesterday: https://github.com/GetStream/stream-chat-react/issues/2022

Is this planned for the Flutter version as well?
