### ISSUE TITLE
sharing emails with custom domains shouldn't trigger url preview

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#1338]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

The latest Beta

### What happened?

when sharing my custom email in the chat it triggered a url preview - hello@cheerly.app

### Steps to reproduce

```bash
share a custom domain url in chat (i.e. hello@cheerly.app)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HayesGordon** [comment]
Hi @CalHoll, thanks for reporting this! We will look into resolving this as soon as possible

**Comment by xsahil03x** [comment]
Hey @CalHoll, added the possibility to filter some url's in [#1516](https://github.com/GetStream/stream-chat-flutter/pull/1516).

eg:
  ```dart
  StreamMessageInput(
    ogPreviewFilter: (matchedUri, messageText) {
      final url = matchedUri.toString();
      if (url.contains('hello@cheerly.app')) {
        // Return false to prevent the OG preview from being built.
        return false;
      }
      // Return true to build the OG preview.
      return true;
  ),
  ```
