### ISSUE TITLE
Improvement FloatingDateDivider behavior in  StreamMessageListView.

### ISSUE THREAD

**Issue by NiyazFazlyev** [GetStream/stream-chat-flutter#1339]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

When scrolling MessagesList and date divider reach floating date divider, they overlap each other. It doesn't look cool.

### Describe the solution that you'd like

I would suggest looking at the implementations in Whatsapp or Telegram. 

### Additional context

![Simulator Screen Shot - iPhone 13 Pro - 2022-10-03 at 13 26 35](https://user-images.githubusercontent.com/51171687/193536478-559ae0e9-d4bd-453a-a4f2-9c6729f71f5c.png)
![Simulator Screen Shot - iPhone 13 Pro - 2022-10-03 at 13 42 37](https://user-images.githubusercontent.com/51171687/193536494-4052e08c-e67e-4da7-acf7-1e9bbd97df7e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Closing as not in our pipeline, You can always modify the dividers using the `dateDividerBuilder` available in the `StreamMessageListView`.

**Comment by NiyazFazlyev** [comment]
How can I track that dateDivider overlaps the floatingDateDivider ? I want to save both of them, but I don't want them to be on top of each other. May be you can help me to implement the effect that I showed in a video. 

https://github.com/GetStream/stream-chat-flutter/assets/51171687/f67c8a9a-7bd5-4871-abe9-6d3c0bae1912

**Comment by xsahil03x** [comment]
@NiyazFazlyev, I'm sorry but the UX you are looking for is not possible with the current `StreamMessageListView` implementation. You might need to create your own custom list view in order to achieve this behaviour.
