### ISSUE TITLE
Missing documentation for v5

### ISSUE THREAD

**Issue by BrunoJurkovic** [GetStream/stream-chat-flutter#1340]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

Version v5.0.0 stable

### What happened?

The v5 release lacks documentation on deprecated methods, the `customOverlays` method has disappeared from StreamMessageInput, with no mention of it in the changelog, also, it seems like imports to parts of your package have been disabled, I can no longer import properties such as `package:stream_chat_flutter/src/extension.dart`. Please issue some documentation so we can see what is new and changed in this new version! 

Thanks

### Steps to reproduce

```bash
1. Updating the dependency in pubspec.yaml
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @BrunoJurkovic we're currently working on a migration guide and on updating documentation and tutorial
I'll post an update once it's all sorted out

**Comment by BrunoJurkovic** [comment]
@imtoori thanks for the quick response Salvatore, as always ;) Looking forward to it :)

**Comment by BrunoJurkovic** [comment]
@imtoori Do you have an ETA on this possibly?

**Comment by HayesGordon** [comment]
Hey @BrunoJurkovic we plan on announcing today. You can look at this branch for the v5 guide in the meantime.

https://github.com/GetStream/stream-chat-flutter/blob/docs/v5/docusaurus/docs/Flutter/guides/migration_guide_5_0.mdx

Please let us know if you spot any issues or if there is something we can expand on.

**Comment by imtoori** [comment]
pr got merged, you'll find the doc on website
let us know if you think there's anything missing
