### ISSUE TITLE
Upgrading file_picker to ^5.0.0

### ISSUE THREAD

**Issue by mkobuolys** [GetStream/stream-chat-flutter#1344]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

The currently used `file_picker` package version is quite outdated (^4.1.3). Are there any issues why it cannot be upgraded to  ^5.0.0? In our project, we are using the `file_picker` package as well (version ^5.0.1), thus we cannot upgrade the `stream_chat_flutter` to v5.0.0.

### Describe the solution that you'd like

Upgrade the `file_picker` package version to the most recent one.

### Describe alternatives that you have considered

There is an option to downgrade the `file_picker` package version in our project. Just, if there are no blockers upgrading it in `stream_chat_flutter`, it would be better to upgrade it there. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
yes, we're upgrading it. I'll release a 5.0.1 soon

**Comment by mkobuolys** [comment]
Wow, this is amazing, team! Thanks 🙌 Closing the issue, then.

**Comment by imtoori** [comment]
Apparently that's not possible at the moment 😓 sorry for giving you false hope

```
Because file_picker >=5.0.0 depends on ffi ^2.0.1 and every version of dart_vlc_ffi depends on ffi ^1.0.0, file_picker >=5.0.0 is incompatible with dart_vlc_ffi.
And because dart_vlc 0.3.0 depends on dart_vlc_ffi ^0.1.7 and no versions of dart_vlc match >0.3.0 <0.4.0, file_picker >=5.0.0 is incompatible with dart_vlc ^0.3.0.
So, because stream_chat_flutter depends on both dart_vlc ^0.3.0 and file_picker ^5.2.0+1, version solving failed.
```
let me see what the guys at dart_vlc are planning to do

**Comment by mkobuolys** [comment]
Oh, ok 😞 Keep us updated!

**Comment by luvishq** [comment]
Any updates on this ?

**Comment by imtoori** [comment]
@luvishq not yet, I'm waiting for the dart_vlc guys 
if it takes too long we'll eventually contribute to the package of consider an alternative

**Comment by MichaelMarner** [comment]
So we are looking at this because the older file_picker is causing permissions problems on Android 13.

Looking at FFI - there are no breaking changes between 1 and 2, and so the update to `dart_vlc` should be simple.

In the meantime, we are evaluating just overriding the dependencies in our app:

```
  ffi: 2.0.1
  file_picker: ^5.2.2
```
