### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by 3ph** [GetStream/stream-chat-flutter#1354]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

5.0.1

### What happened?

I'm trying to elevate the user role in the channel but there doesn't seem to be a way how to do this. The relevant part of the documentation (https://getstream.io/chat/docs/flutter-dart/user_permissions/?language=dart) appears to be just copied from other frameworks' documentation with no dart code. The methods described don't exist in the Flutter SDK.

Could you please point me to the correct documentation?

### Steps to reproduce

```bash
Cannot reproduce.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HayesGordon** [comment]
HI @3ph, updating user roles/permissions is normally a sensitive operation that is limited to be performed on a server client and not a front-end client. The languages that you see examples for are the libraries that Stream provides backend clients for. Some of the functionality listed in the documentation you linked can be called from the Flutter frontend client (such as addMember), while the others are considered sensitive and require a server SDK which is initialized with a secret key. See our available [backend clients](https://getstream.io/chat/sdk/#backend-clients)
