### ISSUE TITLE
Easily Configured Attachment Actions

### ISSUE THREAD

**Issue by Dillan-Jasper** [GetStream/stream-chat-flutter#1358]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web

### Is your feature request related to a problem?

We need to manage PHI within our systems/chat conversations. We have yet to find a way to prevent people from downloading attachments in a chat channel. This presents a possible avenue for PHI exposure. 

### Describe the solution that you'd like

Similar to `showReplyMessage` and `showThreadReplyMessage` for the `StreamMessageWidget` we'd like for the `AttachmentActionsModal` to be easily configured. If this is already possible let me know. 

### Describe alternatives that you have considered

The `AttachmentActionsModal` could also implicitly inherit from the `StreamMessageWidget`. This would make for less configuration but also less flexibility. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey I think this could be possible already
take a look at the `StreamMessageWidget.customActions` and `StreamMessageWidget.onMessageActions` parameters
