### ISSUE TITLE
Increase share_plus version to 6.0.1

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1360]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

latest

### What happened?

Update share_plus dependency from ^4.5.0 to ^6.0.0 

### Steps to reproduce

```bash
Update packages and run flutter pub get
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalHoll** [comment]
6.2.0 now please!

**Comment by Purus** [comment]
yes please. i have enforce older version because of this issue.

**Comment by Purus** [comment]
it's in 6.3.0 now

**Comment by deven98** [comment]
Hi,

We're keen to update this but the dart_vlc package is currently a blocker in order for us to do this.
At the moment, we're looking into our options to make this possible.

**Comment by HayesGordon** [comment]
Additional information:

This is currently blocked by https://github.com/alexmercerind/dart_vlc/issues/334

In the meantime, you can add the following override:
```yaml
dependency_overrides:
  ffi: 2.0.1
```

There does not seem to be any breaking changes in ffi, so the above should be fine, but please evaluate.

We are investigating what to do long-term if this continues to be a blocker.

**Comment by CalHoll** [comment]
> Additional information:
> 
> This is currently blocked by [alexmercerind/dart_vlc#334](https://github.com/alexmercerind/dart_vlc/issues/334)
> 
> In the meantime, you can add the following override:
> 
> ```yaml
> dependency_overrides:
>   ffi: 2.0.1
> ```
> 
> There does not seem to be any breaking changes in ffi, so the above should be fine, but please evaluate.
> 
> We are investigating what to do long-term if this continues to be a blocker.

Looks like dependency was updated at [alexmercerind/dart_vlc#334](https://github.com/alexmercerind/dart_vlc/issues/334)

Let's roll!

**Comment by HayesGordon** [comment]
👀😄 @CalHoll, we know! Stream is now a proud sponsor of the dart_vlc package and looking forward to future enhancement to the video ecosystem for Flutter.

Will update you soon with a release.

**Comment by flodaniel** [comment]
Hi @HayesGordon, 

just a friendly reminder that i think this can be updated now? :) 
Thanks!
