### ISSUE TITLE
Is it possible to compress attachments before downloading them?

### ISSUE THREAD

**Issue by dokumanx** [GetStream/stream-chat-flutter#1364]
### Please select which package this feature is related to

stream_chat_flutter

### Is your feature request related to a problem?

I need to download the attachment (let's say an image) and then save it locally. And add the image via its path to the notification. Afterward, delete the saved image. Big image size slows notifications down. Also, I need to download a big-size image and delete it every time. big-size

### Describe the solution that you'd like

Compress the image by suffix `/400x400` at the end of the URL to get 400 widths and 400 heights image for example. Or, maybe there is a way to compress assets with `stream_core`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @dokumanx I think this is what you're looking for https://getstream.io/chat/docs/flutter-dart/file_uploads/?language=dart&q=cdn#image-resizing

**Comment by dokumanx** [comment]
Thank you for your response @imtoori! Can you give me an example usage of resizing? I couldn't find how to use it.

**Comment by imtoori** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/20601437/199466318-9ea92c91-5f64-49b7-910f-fe99d5c2b4b9.png">

these are all parameters to be used as queryparams in the url of the image 

for example 

https://us-east.stream-io-cdn.com/63735/images/66bfcea3-e922-4d7c-bc62-7fcc6b929b15.1664289875399.gif?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy1lYXN0LnN0cmVhbS1pby1jZG4uY29tLzYzNzM1L2ltYWdlcy82NmJmY2VhMy1lOTIyLTRkN2MtYmM2Mi03ZmNjNmI5MjliMTUuMTY2NDI4OTg3NTM5OS5naWY~Km9oPTI3Mipvdz01MDAqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY4NTIwMDQ4fX19XX0_&Signature=nCnVGF6FZ96QBMs2XmqVAWa0rUtq9pSIiSf1ZuIHD8qt0tUlLvX4Ry38CWsJWm-mwl~cuJNTBvvx7Mnwm40sF3l~HfleQSFoNDqswDu6KhJHJNDnAwdlDgk71cJcv7RtKiQX-9CRP9AZkVZ1S~~qkFSP8EraruRXHTVuYtqqCYgbzgUz46iFB-QWSY4Ill~nvv4dHqqnKNRfiwjOrT7WqWXUGOHVewT4xoqkDFwaLvRTPWjYR~F0EHRR-kBBkVZml7Oo45OY5Hbkui4149MP82BzLXsVfFVr4Y30yNLldWirrR7MVTaMFG7rFPZmLQ173hNJOYJh1YzzpfWdGnRwqQ__&oh=272&ow=500&h=400&w=400&crop=center&resize=clip

**Comment by dokumanx** [comment]
Oh I see. Thank you so much @imtoori !
