### ISSUE TITLE
StreamWidget widthFactor

### ISSUE THREAD

**Issue by senkia24** [GetStream/stream-chat-flutter#1365]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

I want to change stream message widget width factor  0.78 to 1

### Additional context
StreamWidgetMessage

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @senkia24, 

0.78 is the default value. You can modify this.

To modify this, you can use the `messageBuilder` property of the `StreamMessageListView`:

```
StreamMessageListView(
    // ...
    messageBuilder: (context, details, list, def) {
        return def.copyWith(widthFactor: 1);
    },
}
```

Let me know if this helps or if you need something else. 

Thanks!
