### ISSUE TITLE
Is there a function which is exactly for re-connecting?

### ISSUE THREAD

**Issue by alper-efe-sahin** [GetStream/stream-chat-flutter#1373]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

^5.1.0

### What happened?

I saw that there is a connectUser and disconnectUser methods. Are there any methods for re-connecting?

### Steps to reproduce

```bash
'streamChatClient.connectUser(User(id: signedInUser.id), devToken);'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi @alper-efe-sahin you can use `streamChatClient.openConnection` to open a ws connection.
Using `streamChatClient.closeConnection` would disconnect the websocket
