### ISSUE TITLE
fetch user channels in the realtime (like watch) 

### ISSUE THREAD

**Issue by alperefesahin** [GetStream/stream-chat-flutter#1378]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter_core: ^5.1.0

### What happened?

I want to fetch user channels via `Stream`. So, it provides us stream actually, but If I add the current user to another group, I can not see this group in real-time. Think as someone adds you to a group in WhatsApp, then you can see this group directly, without doing anything (refreshing page, etc). If and only If I can see the group after refreshing the application. 

### Steps to reproduce

```bash
in the Supporting info to reproduce section, I wrote the functions with an order. So, I listen the getUserAllChats getter in the bloc, but UI does not update itself. I also tried to print some texts in the debug console, like "random text", but it also does not print anything. So, it behaves like a Future.
```

### Supporting info to reproduce

Here I get user chats (channels actually):

```dart
  @override
  Stream<List<Channel>> get getUserAllChats async* {
    final filter =
        Filter.in_('members', [streamChatClient.state.currentUser!.id]);

    final List<SortOption<ChannelState>> sort = [
      const SortOption("last_message_at", direction: SortOption.DESC)
    ];

    final channels =
        streamChatClient.queryChannels(filter: filter, channelStateSort: sort);

    yield* channels;
  }
```

Then, In the bloc/cubit file, I watch it via StreamSubscription.

```dart
late StreamSubscription<List<Channel>>?
      _getstreamCurrentUserChannelsSubscription;

  late final IChatService _chatService;

  ChatSetup() : super(ChatSetupState.empty()) {
    _chatService = getIt<IChatService>();

    _getstreamWebSocketConnectionSubscription = _chatService
        .getstreamWebSocketConnectionChanges
        .listen(_listenChatUserAuthStateChangesStream);

    _getstreamCurrentUserChannelsSubscription =
        _chatService.getUserAllChats.listen(_getUserAllChats); //here
  }

```

and finally, _getUserAllChats method is here (to update the ui):

```dart
  Future<void> _getUserAllChats(List<Channel> listOfChannels) async {
    final Set<Channel> channels = {...state.listOfChannels};

    channels.addAll(listOfChannels.map((e) => e));

    emit(state.copyWith(listOfChannels: channels.toList()));
  }

```

Also, I need to give some information for you. I use `[...state.listOfChannels]`, since I use freezed package. If we want to update the list, then we need to update our state via our old state.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisElliotUK** [comment]
Any update on this?

**Comment by ChrisElliotUK** [comment]
I have implemented it to this spec but when we assign a user a new channel it does not update the stream. I can check the admin console and the user is assigned but not when I call the api from the app.

**Comment by ChrisElliotUK** [comment]
The .queryChannels api simply doesn't when used like this: 

````
Future<Stream<List<Channel>>> getChatChannels({required String streamChatuserId}) async {
    final filter = Filter.in_('members', [streamChatuserId]);
    final channel = _chatClient.queryChannels(filter: filter, channelStateSort: const [SortOption('last_message_at')]);

    return channel;
  }
````

**Comment by ChrisElliotUK** [comment]
Ok I have found the issue for me. The docs are super unclear that the pagination limit is set to 10 by default. If you up the PaginiationParams.limit to whatever you need then it should work.

````
final channel = _chatClient.queryChannels(
        paginationParams: PaginationParams(limit: 30),
        filter: filter,
        channelStateSort: const [SortOption('last_message_at')]);
````
