### ISSUE TITLE
Issues with photo attachments on web 

### ISSUE THREAD

**Issue by tanphuccgl** [GetStream/stream-chat-flutter#1379]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

5.0.1

### What happened?

Actual result: Show warning icon immediately then upload successfully
Expected result: should not show warning icon, if need time to load then maybe show loading icon instead

https://user-images.githubusercontent.com/80146701/201003728-6fc99604-eeb6-4ae2-a6cb-344eef2080b5.mov

### Steps to reproduce

```bash
Refer to the attached video.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HayesGordon** [comment]
Hi @tanphuccgl thank you for reporting this. I can reproduce this, and it's an easy fix that we will push soon. It's also an opportunity to expand this widget with some extra customization options for the error condition.

**Comment by tanphuccgl** [comment]
Yes thanks for it. By the way, can you look into this problem: https://github.com/GetStream/stream-chat-flutter/issues/1346 . @HayesGordon

**Comment by HayesGordon** [comment]
@tanphuccgl I will take a look at this as soon as possible as well 👍

**Comment by tanphuccgl** [comment]
ok, thank you @HayesGordon
