### ISSUE TITLE
Null check operator used on a null value in Channel.extraDataStream at line 363

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1384]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: 5.1.0
  stream_chat_localizations: 4.0.0
  stream_chat_persistence: 5.1.0

### What happened?

We get multiple crash reports in production (collected via sentry). 
![image](https://user-images.githubusercontent.com/6661557/202649633-70af9392-3825-4342-a5d2-dd2570e7ea66.png)

This should not be possible to happen as your package checks the initialized status before access state, which is the only object being asserted: 

```
  /// Channel extra data as a stream.
  Stream<Map<String, Object?>> get extraDataStream {
    _checkInitialized();
    return state!.channelStateStream.map(
      (cs) => cs.channel?.extraData ?? _extraData,
    );
  }
```

### Steps to reproduce

```bash
return StreamBuilder<Map<String, Object?>>(
      stream: sharedChannel.channel.extraDataStream,
      builder: (context, snapshot) {
        // crash happens before we reach the builder function
       return Container();
      },
    );
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HayesGordon** [comment]
Hi @flodaniel, `assert` logic is stripped from a release build, so the check to ensure the channel is initialized is only performed on a debug build. You either have to call `channel.watch` before using it, or you can re-instantiate a channel with `channel.fromState`. It could be that somewhere in your `sharedChannel` state the channel is being recreated or overridden.
