### ISSUE TITLE
desktop_drop upgrade to version 0.4.0 required

### ISSUE THREAD

**Issue by ramy9109** [GetStream/stream-chat-flutter#1386]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

latest

### What happened?

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':desktop_drop' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HayesGordon** [comment]
Related to https://github.com/getstream/stream-chat-flutter/issues/1375 and https://github.com/GetStream/stream-chat-flutter/issues/1372
