### ISSUE TITLE
how to share post like a instagram in stream chat ? please help

### ISSUE THREAD

**Issue by theappideasankit** [GetStream/stream-chat-flutter#1387]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

<img width="342" alt="image" src="https://user-images.githubusercontent.com/97028121/203269717-72cbcb30-999c-4d31-8ccd-1ca1afd2419d.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HayesGordon** [comment]
Hi @theappideasankit could you explain a bit more? From what I understand you want to be able to share something from Instagram to a Stream chat application.

**Comment by theappideasankit** [comment]
> Hi @theappideasankit could you explain a bit more? From what I understand you want to be able to share something from Instagram to a Stream chat application.

i upload post same as instagram in my app and i want to share post in chat using getstream

**Comment by HayesGordon** [comment]
It will depend on your logic within the app. But within Stream chat you can send custom attachments, see here:
- https://getstream.io/chat/docs/sdk/flutter/customization/custom-widgets/adding_custom_attachments/
- https://getstream.io/chat/docs/sdk/flutter/stream_chat_flutter/stream_message_widget/#building-a-custom-attachment

You can set up an attachment to share any kind of data. From the logic in the screenshot you shared above, I would imagine that once you press share, a list of all available chat channels pops up that the current user is in, then they can select a channel and you send a custom attachment as a message to that channel. Maybe you can then also create a deep link in your app to redirect the user from the chat message to the post on click.

**Comment by theappideasankit** [comment]
okay i will try

**Comment by theappideasankit** [comment]
how to send direct message without opening chat
