### ISSUE TITLE
SqliteException when syncing 

### ISSUE THREAD

**Issue by bishalstha** [GetStream/stream-chat-flutter#1392]
### Which packages are you using?

stream_chat_persistance

### On what platforms did you experience the issue?

iOS

### What version are you using?

5.1.0

### What happened?

Seems like sometimes syncing causes exceptions.

### Steps to reproduce

```bash
1. query the channels for the current user
2. Sync the chat persistence using the 'sync' method (Note: It doesn't always occur).
```

### Relevant log output

```shell
SqliteException(5): database is locked, database is locked (code 5)
Causing statement: UPDATE connection_events SET last_sync_at = ? WHERE id = ?;
```

### Flutter doctor output

```shell
Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale ...)
    • Flutter version 3.3.9 on channel stable at ....
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (6 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HayesGordon** [comment]
Hi @bishalstha, thank you for opening an issue. We will look into this. It will be extremely helpful if you can create a small sample that demonstrates the exception and allow us to recreate it.

**Comment by bishalstha** [comment]
> Hi @bishalstha, thank you for opening an issue. We will look into this. It will be extremely helpful if you can create a small sample that demonstrates the exception and allow us to recreate it.

@HayesGordon 
This generally occurs if you have a large number of channels to which you are added, and whenever a channel task is performed with sync, it may occur. For example, I have this issue generally when adding and removing the logged-in user to channels and then syncing the local persistence. I think the issue here is that when one sync is happening next sync should not happen(due to locking), and it can be solved by either making a queue for syncing(within the package itself) or adding a way to check if the sync is in progress. I hope this will help you in fixing this issue.

**Comment by bishalstha** [comment]
Sure, and thanks for the update.

Best regards,
