### ISSUE TITLE
[How to?] Query members by extraData

### ISSUE THREAD

**Issue by vasilich6107** [GetStream/stream-chat-flutter#1394]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS

### Is your feature request related to a problem?

I have some fields in `extraData` that I want to use in autocomplete querying 
`Filter.autoComplete('vessel_id', query),`

### Describe the solution that you'd like

Ability to `queryMembers` by extra data

### Describe alternatives that you have considered

Local filtering `if (members.length < 100) {` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hello @vasilich6107. Sorry for the late reply. We don't recommend querying tables using extra data, for performance reasons. It is much harder to query in our server-side dynamic fields.
