### ISSUE TITLE
Using StreamChatConfigurationData per Channel

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1426]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web, Windows, MacOS, Linux

### What version are you using?

5.2.0

### What happened?

Right now I do not see a way to use StreamChatConfigurationData to make changes per channel. I only see that this can be set Globally if this isn't true can we get an example? If not can this be changed to support this?

### Steps to reproduce

```bash
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rlee1990** [comment]
@Nash0x7E2 is there anyone still looking at these in Github?

**Comment by adasiewiczr** [comment]
hey @rlee1990,
`StreamChatConfigurationData` is a global app configuration that is being applied to all the channels.
Could you give us more information about your use case and which things you would like to configure per channel? 
It'll help us with providing the best possible option.

**Comment by rlee1990** [comment]
Closing in favor of #1419
