### ISSUE TITLE
Unread count value from a channel is always 0

### ISSUE THREAD

**Issue by demolaf** [GetStream/stream-chat-flutter#1430]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

5.2.0

## Issue
We've still been unable to get the unread count per channel `communitySupportChannel?.state?.unreadCount`, this value always returns 0 for each channel in my use case.

### What I've tried
- I've tried calling `markRead();` when the channel screen is opened. 
- Tried accessing the other count values exposed by the channel and client objects but they all return 0.

### Steps to reproduce

```bash
1. Send a message in the channel you're listening for unread count changes
2. Access this channel using another account 
3. Check the unread count value using the other account.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adasiewiczr** [comment]
Hey @demolaf,
could you check if the `Read Events` are enabled for the given channel type? You can do that in the Dashboard

**Comment by demolaf** [comment]
Hi @adasiewiczr, thanks for responding. Yes, we have it enabled.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/48495111/212062166-d86a09a9-3df7-4267-917d-474ddf93484f.png">

**Comment by mingzew** [comment]
I am also encountering the same issue. Using the 5.2.0 release as well

**Comment by mingzew** [comment]
My issue has been fixed. It was indeed the read event that needed to be turned on.
