### ISSUE TITLE
Channel List is not updated if a message send via search user 

### ISSUE THREAD

**Issue by nikhilkhurana1** [GetStream/stream-chat-flutter#1438]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

5.2.0

### What happened?

When a message send to user via search user, currently search user is not present in channel list. After send message search user should be visible in top of the list, but channel list is not updated immediately, I have to manually refresh the page for the new channel to reflect in the channel list. I'm using PagedValueListenableBuilder along with StreamChannelListController.

### Steps to reproduce

```bash
1. Open the chat application. Search a user which is not present in list.
2. Try sending the message.
3. The channel list won't get updated immediately.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hello @nikhilkhurana1. Could you record a video showing the behaviour you get and what is the behaviour expected?
