### ISSUE TITLE
Dio

### ISSUE THREAD

**Issue by bstolinski** [GetStream/stream-chat-flutter#1447]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

Currently [dio](https://github.com/flutterchina/dio) library is very poorly maintained, looking at how fast Dart and Flutter are developing in the near future this could become problematic.

### Describe the solution that you'd like

I wanted to ask if you are considering replacing [dio](https://github.com/flutterchina/dio) with its fork, which is [diox](https://github.com/cfug/diox). More information here https://github.com/cfug/diox/issues/29

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @bstolinski 👋 ,

We share your concern about ensuring all dependencies we use are feature-complete and robust. 
As for `dio`, all code related to it is thoroughly tested and we monitor any potential problems caused.
While we have no immediate plans for switching to `diox`, we will not hesitate to make this change if we see any obvious problems coming up. 

As this is not currently planned, I am closing this issue. However, feel free to re-open this if you feel the change you describe is immediately needed. Thanks for the suggestion and we will keep this in mind :)

**Comment by bstolinski** [comment]
Hello @deven98 ,
I don't think this change is immediately needed, but the fact that they have already fixed many of the [problems](https://github.com/orgs/cfug/projects/1/views/1) that have existed on the dio repository for many months is a change for the better. This is a fork so most of the code will remain the same. 
This is just my suggestion and you will do what you think is right, but I really think it is worth considering.

**Comment by TomBeckett** [comment]
@deven98 to provide a bit of context. 

We've been experiencing a lot of issues in production with dio. As @bstolinski mentioned, these are fixed on the fork.

We can't move to the fork of dio since getstream also uses dio. So we have a choice - we either do nothing and live with the issues in dio, we remove getstream or getstream releases an update.

From the response above it seems like one of those options are off the table.

**Comment by bstolinski** [comment]
Hi @adasiewiczr ,

> However, if you need to use diox in your application, you can override the dio dependency used by our SDK. You can find more information [here](https://github.com/cfug/diox#diox).

I've tried to do it:

```
../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-5.3.0/lib/src/stream_channel.dart:428:48: Error: Member not found: 'response'.
            if (dioError?.type == DioErrorType.response) {
                                               ^^^^^^^^
../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-5.3.0/lib/src/stream_channel.dart:429:35: Error: A value of type 'String?' can't be assigned to a variable of type 'String' because 'String?' is nullable and 'String' isn't.
              message = dioError!.message;
                                  ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/http/stream_http_client.dart:32:58: Error: A value of type 'int' can't be assigned to a variable of type 'Duration?'.
 - 'Duration' is from 'dart:core'.
      ..options.receiveTimeout = _options.receiveTimeout.inMilliseconds
                                                         ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/http/stream_http_client.dart:33:58: Error: A value of type 'int' can't be assigned to a variable of type 'Duration?'.
 - 'Duration' is from 'dart:core'.
      ..options.connectTimeout = _options.connectTimeout.inMilliseconds
                                                         ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/error/stream_chat_error.dart:100:61: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
          errorResponse?.message ?? response?.statusMessage ?? error.message,
                                                            ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/http/interceptor/logging_interceptor.dart:124:36: Error: Member not found: 'response'.
      if (err.type == DioErrorType.response) {
                                   ^^^^^^^^
../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-5.3.0/lib/src/stream_channel.dart:428:48: Error: Member not found: 'response'.
            if (dioError?.type == DioErrorType.response) {
                                               ^^^^^^^^
../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-5.3.0/lib/src/stream_channel.dart:429:35: Error: A value of type 'String?' can't be assigned to a variable of type 'String' because 'String?' is nullable and 'String' isn't.
              message = dioError!.message;
                                  ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/http/stream_http_client.dart:32:58: Error: A value of type 'int' can't be assigned to a variable of type 'Duration?'.
 - 'Duration' is from 'dart:core'.
      ..options.receiveTimeout = _options.receiveTimeout.inMilliseconds
                                                         ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/http/stream_http_client.dart:33:58: Error: A value of type 'int' can't be assigned to a variable of type 'Duration?'.
 - 'Duration' is from 'dart:core'.
      ..options.connectTimeout = _options.connectTimeout.inMilliseconds
                                                         ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/error/stream_chat_error.dart:100:61: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
          errorResponse?.message ?? response?.statusMessage ?? error.message,
                                                            ^
../../.pub-cache/hosted/pub.dev/stream_chat-5.3.0/lib/src/core/http/interceptor/logging_interceptor.dart:124:36: Error: Member not found: 'response'.
      if (err.type == DioErrorType.response) {
                                   ^^^^^^^^
```

**Comment by AlexV525** [comment]
`diox` can be used as a fork of `dio`, but it contains breaking changes during improvements, so the code must be changed if you want to adapt to `diox` no matter the choice.

**Comment by AlexV525** [comment]
`dio` has back online, but the package needs to adapt the breaking changes.

**Comment by Hwan-seok** [comment]
Sorry for spamming but is there a plan to work on this?

**Comment by hieuvt1414** [comment]
please reopen it @deven98
