### ISSUE TITLE
Demo app that uses V5 ?

### ISSUE THREAD

**Issue by ajonno** [GetStream/stream-chat-flutter#1454]
### Please select which package this feature is related to

stream_chat

### Which platforms would this feature impact?

iOS, Android, Web

### Is your feature request related to a problem?

hi, is there a sample app that uses V5 of the SDK and which runs on ios, android and web ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adasiewiczr** [comment]
hey @ajonno,
you can go to [Stream Flutter Samples repo](https://github.com/GetStream/flutter-samples/tree/develop) and switch to the `develop` branch.

**Comment by ajonno** [comment]
Ok great many thanks!
