### ISSUE TITLE
StreamChannelListTile, sendingIndicatorBuilder shows wrong result.

### ISSUE THREAD

**Issue by eli1stark** [GetStream/stream-chat-flutter#1456]
### Which packages are you using?

stream_chat_flutter
stream_chat_localizations
stream_chat_persistence

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: 5.3.0
  stream_chat_localizations: 4.1.0
  stream_chat_persistence: 5.1.0

### What happened?

`StreamChannelListTile` is showing an incorrect sending indicator. The message inside the `StreamMessageListView` shows the right indicator, but for the `StreamChannelListTile`, it's always unread or not present. 

### Steps to reproduce

Use `StreamChannelListTile`. Write a message to user B as user A, and let user B read the message. The message is still unread in the StreamChannelListTile but it's fine in the `bottomRowBuilderWithDefaultWidget` of `StreamMessageListView`.

### Supporting info to reproduce

Even if you look at the code of `StreamChannelListTile`, why do you want to check `currentUserRead`, it doesn't make a lot of sense. What we need to do here is to check for the `lastMesage` and check whether it comes from the current user or not, if it is, check for read/unread status.
```dart
                  return Padding(
                    padding: const EdgeInsets.only(right: 4),
                    child:
                        sendingIndicatorBuilder?.call(context, lastMessage) ??
                            StreamSendingIndicator(
                              message: lastMessage,
                              size: channelPreviewTheme.indicatorIconSize,
                              isMessageRead: channelState
                                  .currentUserRead!.lastRead
                                  .isAfter(lastMessage.createdAt),
                            ),
                  );
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eli1stark** [comment]
If you will replace `sendingIndicatorBuilder` of `StreamChannelListTile` with `sendingIndicatorBuilder` of `StreamMessageListView` it works as expected.


```dart
sendingIndicatorBuilder: (context, message) {
        final streamChat = context.stream;
        final memberCount = channel.memberCount ?? 0;

        return BetterStreamBuilder<List<Read>>(
          stream: channel.state?.readStream,
          initialData: channel.state?.read,
          builder: (context, data) {
            final readList = data.where(
              (it) =>
                  it.user.id != streamChat.currentUser?.id &&
                  (it.lastRead.isAfter(message.createdAt) ||
                      it.lastRead.isAtSameMomentAs(message.createdAt)),
            );
            final isMessageRead =
                readList.length >= (channel.memberCount ?? 0) - 1;
            Widget child = StreamSendingIndicator(
              message: message,
              isMessageRead: isMessageRead,
              size: 16,
            );
            if (isMessageRead) {
              child = Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  if (memberCount > 2)
                    Text(
                      readList.length.toString(),
                      style: const TextStyle(
                        color: Colors.red,
                      ),
                    ),
                  const SizedBox(width: 2),
                  child,
                ],
              );
            }
            return child;
          },
        );
      },
```

**Comment by eli1stark** [comment]
@xsahil03x

**Comment by eli1stark** [comment]
Also can be related to this https://github.com/GetStream/stream-chat-flutter/issues/1396

**Comment by leandroBorgesFerreira** [comment]
Hello @eli1stark. Thanks for posting this issue. I'll take a look and I'll update you in a while.

**Comment by leandroBorgesFerreira** [comment]
I could reproduce the reproduce the problem. When sending a message in a group channel the "sending indicator" appears as a grey check mark showing that the message was read. But it never becomes blue with a double check when someone in the groups reads it. Neither inside the channel or in the channel list.
