### ISSUE TITLE
StreamTypingIndicator overlaps for StreamChannelListTile

### ISSUE THREAD

**Issue by eli1stark** [GetStream/stream-chat-flutter#1459]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: 5.3.0
  stream_chat_localizations: 4.1.0
  stream_chat_persistence: 5.1.0

### What happened?

When 2 or more users are typing, they overlap.
<img width="560" alt="Screenshot 2023-02-08 at 10 25 35 AM" src="https://user-images.githubusercontent.com/57593530/217619543-414f9439-4d95-460b-a026-6a44694a9001.png">

### Steps to reproduce

Use StreamChannelListTile, 2 distinct users should start typing, 3rd user should observe the StreamChannelListTile.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hello @eli1stark Thanks for posting this. I'll take a look at update you in a while.

**Comment by leandroBorgesFerreira** [comment]
Hello @eli1stark. This doesn't reproduce on my side. What I get is simply this:
![Screenshot_20230210-134513](https://user-images.githubusercontent.com/10619102/218095851-c23d25f9-b80c-41fe-bb4f-d9183cda815a.png)

**Comment by leandroBorgesFerreira** [comment]
Are you using this component in a customized way? Could you share your code?

**Comment by eli1stark** [comment]
```dart
class ChannelTile extends StatelessWidget {
  const ChannelTile({
    super.key,
    required this.channel,
    required this.defaultTile,
  });

  final Channel channel;
  final StreamChannelListTile defaultTile;

  @override
  Widget build(BuildContext context) {
    return StreamChannelListTile(
      channel: channel,
      tileColor: Colors.black,
      leading: defaultTile.leading,
      title: StreamChannelName(
        channel: channel,
        textStyle: const TextStyle(
          fontSize: 16,
          color: Colors.white,
          fontWeight: FontWeight.bold,
        ),
      ),
      // here ->
      subtitle: ChannelListTileSubtitle(
        channel: channel,
        textStyle: const TextStyle(
          fontSize: 14,
          color: Colors.red,
        ),
      ),
      trailing: ChannelLastMessageDate(
        channel: channel,
        textStyle: const TextStyle(
          color: Colors.purple,
        ),
      ),
      onTap: defaultTile.onTap,
      sendingIndicatorBuilder: defaultTile.sendingIndicatorBuilder,
      unreadIndicatorBuilder: defaultTile.unreadIndicatorBuilder,
    );
  }
}
```

**Comment by leandroBorgesFerreira** [comment]
Looks like you're inserting a `StreamChannelListTile` inside another `StreamChannelListTile`, which is probably what is causing your issue. We use the method `copyWith` to provide the behaviour that you would like to have: 

```
StreamChannelListTile example(StreamChannelListTile defaultTile, Channel channel) {
    return defaultTile.copyWith(
      tileColor: Colors.black,
      title: StreamChannelName(
        channel: channel,
        textStyle: const TextStyle(
          fontSize: 16,
          color: Colors.white,
          fontWeight: FontWeight.bold,
        ),
      ),
      subtitle: ChannelListTileSubtitle(
        channel: channel,
        textStyle: const TextStyle(
          fontSize: 14,
          color: Colors.red,
        ),
      ),
      // [Complete the code with your intended logic.]
    );
}
```
