### ISSUE TITLE
StreamFullScreenMediaBuilder. Share button doesn't work on iPad.

### ISSUE THREAD

**Issue by eli1stark** [GetStream/stream-chat-flutter#1462]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance

### On what platforms did you experience the issue?

iOS

### What version are you using?

  stream_chat_flutter: 5.3.0
  stream_chat_localizations: 4.1.0
  stream_chat_persistence: 5.1.0

### What happened?

When I press the share button in the StreamFullScreenMediaBuilder I expect the share dialog to be opened, the same way it happens on iPhone, but as the result, I receive the following error:

```bash
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, sharePositionOrigin: argument must be set, {{0, 1294}, {0, 0}} must be non-zero and within coordinate space of source view: {{0, 0}, {1024, 1366}}, null, null)
#0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:653
#1      MethodChannel._invokeMethod
platform_channel.dart:315
<asynchronous suspension>
#2      MethodChannelShare.shareFilesWithResult
method_channel_share.dart:134
<asynchronous suspension>
#3      _StreamGalleryFooterState.build.<anonymous closure>
gallery_footer.dart:113
<asynchronous suspension>

```

<img width="138" alt="Screenshot 2023-02-09 at 8 58 56 AM" src="https://user-images.githubusercontent.com/57593530/217884492-bfb6d80b-38b4-41a9-bf06-5878081d1791.png">

### Steps to reproduce

```bash
1. Use StreamFullScreenMediaBuilder.
2. Tap on the share button in the bottom left corner of the iPad, the simulator will work fine.
3. You got the PlatformException.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
@eli1stark. Let me check this...
