### ISSUE TITLE
Channel name blinks after renaming

### ISSUE THREAD

**Issue by eli1stark** [GetStream/stream-chat-flutter#1464]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: 5.3.0
  stream_chat_localizations: 4.1.0
  stream_chat_persistence: 5.1.0

### What happened?

I created this issue several days ago with Stream support. Adding issue for tracking. When you rename the channel it blinks. It goes to a new name, then to the old, and then back to the new name.

```dart
class ChannelScreen extends StatelessWidget {
  const ChannelScreen({
    super.key,
    required this.channel,
  });

  final Channel channel;

  @override
  Widget build(BuildContext context) {
    return StreamChannel(
      channel: channel,
      child: Scaffold(
        body: Column(
          children: [
            const SizedBox(
              height: 100,
            ),
            StreamChannelName(
              channel: channel,
              textStyle: const TextStyle(
                color: Colors.red,
                fontSize: 16.0,
              ),
            ),
            TextButton(
              onPressed: () {
                // just update with DateTime, then change to empty string
                // and update again
                channel.updateName('${DateTime.now()}');
              },
              child: const Text('Update name'),
            )
          ],
        ),
      ),
    );
  }
}
```

### Steps to reproduce

Use the code I provided above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hello @eli1stark. We already have the Widget to create a header for a channel [StreamChannelHeader](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/lib/src/channel/channel_header.dart). Which is our recommended way. It is a customisable Widget, could you try to use it to get the app bar that you're trying to draw?

**Comment by leandroBorgesFerreira** [comment]
I have made some small changes in our [tutorial_part1.dart](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/example/lib/tutorial_part_1.dart). Like this:
```
class MyApp extends StatelessWidget {
  const MyApp({
    super.key,
    required this.client,
    required this.channel,
  });

  final StreamChatClient client;

  final Channel channel;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: (context, widget) {
        return StreamChat(
          client: client,
          child: widget,
        );
      },
      home: StreamChannel(
        channel: channel,
        child: ChannelPage(channel: channel),
      ),
    );
  }
}

class ChannelPage extends StatelessWidget {
  const ChannelPage({
    super.key,
    required this.channel,
  });

  final Channel channel;

  @override
  // ignore: prefer_expression_function_bodies
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: StreamChannelHeader(
        actions: [
          ElevatedButton(
            onPressed: () {
              channel.updateName('${DateTime.now()}');
            },
            child: const Text('Action'),
          ),
        ],
      ),
      body: Column(
        children: const <Widget>[
          Expanded(
            child: StreamMessageListView(),
          ),
          StreamMessageInput(),
        ],
      ),
    );
  }
}
```

And it works without blinking.

**Comment by eli1stark** [comment]
But you confirm it works with blinking in my case? Unfortunately I need to construct custom app bar and I need to use StreamChannelName separately.

**Comment by leandroBorgesFerreira** [comment]
Hello @eli1stark, sorry for the late reply. The `StreamChannelHeader` is a customizable widget, if you show a picture that presents more or less what are you trying to achieve I can help you evaluate if there are other ways to create your layout. 

By anyway, I'll check it your code in the tutorial makes it blink.

**Comment by leandroBorgesFerreira** [comment]
Your layout either breaks of draws in a very odd way. The easiest way would be to tell us what you would like to achieve then we can elaborate a little guide. 

If the layout is propretary, no problem, we can continue via zendesk.
