### ISSUE TITLE
Chat Image save not working

### ISSUE THREAD

**Issue by ChiragGajjar** [GetStream/stream-chat-flutter#1465]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^4.6.0

### What happened?

I have already used Stream chat on top widget, but still getting this issue. only for while click on "**Save Image"**

### Steps to reproduce

```bash
1 - Chat list
2 - Click on the Image
3 - Click on the top three dots and open the menu
4 - Click on the Save Image button
```

### Relevant log output

```shell
You must have a StreamChatTheme widget at the top of your widget tree
'package:stream_chat_flutter/src/stream_chat_theme.dart':
Failed assertion: line 25 pos 7: 'streamChatTheme != null'

The relevant error-causing widget was: 
  AppSizes AppSizes:file:///Volumes/Data/Trucking%20Digital/project/truckindigital-driver-flutter/lib/main.dart:559:11
When the exception was thrown, this was the stack: 
#2      StreamChatTheme.of (package:stream_chat_flutter/src/stream_chat_theme.dart:25:7)
#3      AttachmentActionsModal._buildDownloadProgressDialog (package:stream_chat_flutter/src/attachment_actions_modal.dart:306:35)
#4      AttachmentActionsModal._buildPage.<anonymous closure>.<anonymous closure> (package:stream_chat_flutter/src/attachment_actions_modal.dart:197:49)
#5      Builder.build (package:flutter/src/widgets/basic.dart:7326:48)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4932:49)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4861:15)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4587:5)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:4939:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adasiewiczr** [comment]
hey @ChiragGajjar,
could you provide us an MVP project in which we can reproduce this problem?
Alternatively, could you check if you can reproduce the issue in our [sample app](https://github.com/GetStream/stream-chat-flutter/tree/develop/packages/stream_chat_flutter/example)?

**Comment by ChiragGajjar** [comment]
I need to hide this functionality, can you help me how to hide this save image option? 
![screenshot-1676396108517](https://user-images.githubusercontent.com/20324254/218944303-910c9710-5d2b-4ff3-9f77-4ff0ef739e7f.png)

**Comment by ChiragGajjar** [comment]
> hey @ChiragGajjar, we added a possibility to hide the option in the PR mentioned above. Let us know if you have any further questions.

Thanks for the update, When it will be available in pub.dev? stream_chat_flutter: ^5.3.0
