### ISSUE TITLE
Update flutter_svg to >2.0

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1466]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

5.3.

### What happened?

Because stream_chat_flutter 5.3.0 depends on flutter_svg ^1.0.1 and pave_app depends on flutter_svg 2.0.1, stream_chat_flutter 5.3.0 is forbidden.

### Steps to reproduce

```bash
1. update flutter_svg to 2.0.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adasiewiczr** [comment]
Hey @flodaniel,
thank you for reporting the issue. Unfortunately, we cannot immediately update the dependency as it would be a breaking change for anyone still using flutter_svg 1.X.X.
However, I marked the issue with the v6 release label, which will be covered in the next major release.

**Comment by CalHoll** [comment]
v6 timeline?

**Comment by CalHoll** [comment]
Is this package still being maintained by your team, it's been over 2 months since any updates to the pub.dev packages and there are a lot of reported issues that are weeks old.

Please let us know if your teams priorities have changed so we can make informed decisions on our own projects.

**Comment by xsahil03x** [comment]
All the packages have been updated to the latest resolvable version in the new v6 release.
[pub.dev/packages/stream_chat_flutter](https://pub.dev/packages/stream_chat_flutter)
