### ISSUE TITLE
Unread channels count based on filter

### ISSUE THREAD

**Issue by krishnakumarcn** [GetStream/stream-chat-flutter#1468]
### Please select which package this feature is related to

stream_chat_flutter

### Is your feature request related to a problem?

In our setup, we have N number of channels per user, but they are grouped on an outer scope in the app. Only some of those N channels were visible at a time. We are fetching the channels using `filter` while querying.

```

final filter = Filter.in_("id", chennelIdsForThisScope);

final Stream<List<Channel>> channelsStream = await streamChatClient.queryChannels(filter: filter, watch: true);

```

A major use case for the app is to show an `Unread count badge` on the bottom navigation bar for number of unread channels, stream chat only support `client.state.unreadChannelsStream` which simply provides the number of unread channels for the user.  But In this case, this is not exactly relevant since the user is interested in the unread count only for the filtered channels. 

Not sure if such a feature is there without watching the channel and keeping everything in memory.

Currently one workaround is to query the channels and watch them seperately and then listen to individual unread message count stream.  But this looks like too much performance intensive as we are keeping all the channels in memory even though they are not required at that point. 

It would have been nicer if this `client.state.unreadChannelsStream` also support on a filter, or not sure if there any other proper way of handling this case right now?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samuel2629** [comment]
I'm also facing this issue. Any update ?

**Comment by Srj-Love** [comment]
me too

**Comment by gc0rtes** [comment]
Hello @krishnakumarcn 

Thank you for reaching out to us regarding the unread count feature. 
Unfortunately, the total unread count cannot be changed per your suggestion. This count returns the total number of unread messages in all channels a user is a member of.

However, we do have a workaround that might help you. When you retrieve the channels from the API using query channels, you can rely on the response to get the read state for the current user. The unread count for each channel is included under the path `channel.state.unreadCount`.

If you need further assistance with this, please don't hesitate to reach out to our support team through this link: https://getstream.io/contact/support/. We are always ready to help.

Thank you for using our service.

Best regards,
Guilherme Cortes
Support Engineer

**Comment by rgtstha** [comment]
I am working on a similar project that needs a similar situation where unread count should be based on `filter`. Unfortunately, I didn't find any better workaround solutions.
