### ISSUE TITLE
StreamChatClient.on() receives last event every time when subscribed

### ISSUE THREAD

**Issue by Hwan-seok** [GetStream/stream-chat-flutter#1471]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

iOS, Android, Web, Windows, MacOS, Linux

### What version are you using?

stream_chat: 5.3.0

### What happened?

Since `StreamChatClient._eventController` is `BehaviorSubject` not `StreamController`, 
we receive an event that is already given every time we listen on the `eventStream`. 

### Steps to reproduce

```bash
1. Create ChatClient
2. Subscribe to the eventStream via `on`.
3. Trigger some events.
4. Receives events.
5. Cancel the subscription and subscribe to the event again.
6. Receives last received event again.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adasiewiczr** [comment]
hey @Hwan-seok,
`_eventController ` is a `BehaviorSubject` by design. If you are not interested in the initial value you can either skip the first event or convert the stream to `PublishSubject`.
