### ISSUE TITLE
channel.query

### ISSUE THREAD

**Issue by vladnicut12345** [GetStream/stream-chat-flutter#1474]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

stream_chat_flutter: ^5.3.0

### What happened?

calling just channel.query({watch: true, presence: true, state: true}) will not initialize the ChannelClientState? which will result in a null value. This will further block the StreamChannel() widget and you will end up in a loading screen.

if you call channel.watch() from what I have seen this call function also calls channel.query() but if the state returned by query() is null it uses _initState() to actually initialize it.

I have tried to recreate the functionality of the _initState() after calling channel.query() it works, but now I can't send messages. 

I need to use the .query() function because I can not use the presence: true in the watch method because that was broken.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @vladnicut12345, 

You can now use `channel.watch(presence: true)` to achieve the same behaviour in the latest `v6` release.

Thanks,
Sahil
