### ISSUE TITLE
typo in vlc_manager.dart breaks compile

### ISSUE THREAD

**Issue by mcku** [GetStream/stream-chat-flutter#1475]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android, Web

### What version are you using?

5.3.0

### What happened?

Compilation fails.

### Steps to reproduce

```bash
1. compile an example project and it fails
```

### Supporting info to reproduce

It looks like there is a typo here

https://github.com/GetStream/stream-chat-flutter/blame/develop/packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager.dart#L3

### Relevant log output

```shell
Unsupported operation: dar.library.html not supported for config specific imports. Only the dart.library.<name> constants are supported.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hello @mcku. You're right, looks like there's a typo there. I'm gonna fix this. 
But we compile our SDK on a daily basis, how are you compiling the example? 
Thanks!

**Comment by mcku** [comment]
Hi @leandroBorgesFerreira . 
I am using build_runner for code generation. The example of course may not use those tools. Please find a reproducible one here:
https://github.com/mcku/stream-chat-flutter/tree/develop/packages/stream_chat_flutter/example
I've added a test folder that triggers compilation, along `build_web_compilers`, it gets compiled for the web. 

Running `flutter pub run build_runner build`  before `flutter build web` fails:

```log
[INFO] Generating build script...
[INFO] Generating build script completed, took 503ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 856ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.4s

[INFO] Running build...
[SEVERE] build_web_compilers:entrypoint on test/example_test.dart.browser_test.dart:
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:stream_chat_flutter/stream_chat_flutter.dart';` from stream_chat_flutter_example|test/example_test.dart at 2:1

[INFO] Running build completed, took 736ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 706ms

[SEVERE] build_web_compilers:ddc_modules on package:stream_chat_flutter/$lib$ (cached):

Unsupported operation: dar.library.html not supported for config specific imports. Only the dart.library.<name> constants are supported.
[SEVERE] build_web_compilers:ddc_modules on package:stream_chat_flutter/stream_chat_flutter.dart (cached):

Null check operator used on a null value
[SEVERE] Failed after 1.5s
pub finished with exit code 1
```
