### ISSUE TITLE
Push notification does not disappear after reading the message

### ISSUE THREAD

**Issue by Rai220** [GetStream/stream-chat-flutter#1477]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: 5.3.0

### What happened?

1. I receive a push notification about a new message
2. I open my application, go to the chat and read this message
3. Tray push notification keeps showing

### Steps to reproduce

```bash
It is enough to assemble and run - the problem looks like a common one for everyone.
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-RU)
    • Flutter version 3.3.10 on channel stable at /Users/konstantinkrestnikov/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/konstantinkrestnikov/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hello @Rai220 I'll have to check if this is a bug or if this is a feature that we need to implement in our Flutter SDK.

**Comment by kanat** [comment]
Hey @Rai220,

In order to achieve this functionality you can switch to `data-only` push notifications:
- Go to your Stream's App Dashboard
- Open section `Push Notifications`
- Open `Firebase Configuration`
- Delete content in `Notification Template` - affects Android
- In `APN Template` paste the the following template (affects iOS)
```json
{
  "aps": {
    "content-available": 1
  }
}
```
- Then in your app you need to listen [FirebaseMessaging.onBackgroundMessage](https://firebase.flutter.dev/docs/messaging/usage#background-messages)
- From that function you should be able to show [local notifications](https://pub.dev/packages/flutter_local_notifications), which you can cancel whenever you want
