### ISSUE TITLE
There might be no indicator for unread messages for channels with 100+ members

### ISSUE THREAD

**Issue by lavinov-mercury** [GetStream/stream-chat-flutter#1482]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

5.3.0

### What happened?

There is a check, either the user is a member of a channel or not, and if not - unread messages indicator won't be displayed. However, there are only 100 members available for this check, even if the actual count is higher.

| 1 | 2 |
|---|---|
| <img width="679" alt="image" src="https://user-images.githubusercontent.com/86644843/224714275-cd2da3e9-3586-419f-9009-df2d35b8c918.png"> | <img width="856" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/86644843/224714585-6b1f9a56-3696-4aa7-bce2-5eefd2b3f2d7.png"> |

If the user is not in the list of 100, he won't see the indicator.

### Steps to reproduce

```bash
Preconditions:
There is a channel with 100+ members. Your user is not within the first hundred (most likely it depends on the order of joining)

Steps to Reproduce:

1. Open `StreamChannelListView`
2. Observe indicator for the channel which matches precondition
```

### Supporting info to reproduce

Here is the check from the screenshots:

https://github.com/GetStream/stream-chat-flutter/blob/dfcef5252ea22c967ad6bd8780217291a3edb3cb/packages/stream_chat_flutter/lib/src/scroll_view/channel_scroll_view/stream_channel_list_tile.dart#L197

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @lavinov-mercury, what should be the ideal behaviour?
