### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by mkobuolys** [GetStream/stream-chat-flutter#1485]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^5.2.0

### What happened?

Getting "Null check operator used on a null value" when the user opens the chat page with `StreamMessageListView`.

### Steps to reproduce

```bash
I am not able to reproduce the issue locally but I notice multiple errors in our crashlytics (~50 errors per day).
```

### Relevant log output

```shell
Null check operator used on a null value
#0      RenderViewportBase.getOffsetToReveal (package:flutter/src/rendering/viewport.dart:816)
#1      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:stream_chat_flutter/scrollable_positioned_list/src/positioned_list.dart:337)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076)
#5      _invoke (dart:ui/hooks.dart:145)
#6      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338)
#7      _drawFrame (dart:ui/hooks.dart:112)
```

### Flutter analyze output

```shell
Analyzing project...                                                    
No issues found! (ran in 8.8s)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-LT)
    • Flutter version 3.7.7 on channel stable at <...>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (7 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at <...>/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = <...>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thanhnd2812** [comment]
Hello, any updates yet?

We also got the same issue while testing group chat. It made an app crash while getting new incoming messages. Thanks.

**Comment by deven98** [comment]
Hey @mkobuolys and @thanhnd2812,

We will try to replicate this on our end. Is there any specific trigger for this issue that you've noticed?
Any other details will also be helpful.

Let me get back to you after a bit of testing.

Thanks.

**Comment by mkobuolys** [comment]
@deven98 Hey, sorry, not much context from our end. I noticed that most of the time when this error occurred, the chat was scrollable (all the messages did not fit in the view). Also, I see some errors went together with an "Invalid image data" error when the image could not be rendered in the chat view. Other than that, nothing useful, I suppose.

**Comment by thanhnd2812** [comment]
hi @deven98 

Crashes often occur when we are in the chat window and there are messages coming in, messages from people on the same channel or on different channels are likely to happen.

**Comment by senkia24** [comment]
Any update here. I got same issue

**Comment by xsahil03x** [comment]
Hey, we just update `ScrollablePositionedList` with the latest changes from `pub` int this [pr](https://github.com/GetStream/stream-chat-flutter/pull/1519) and the issue should be fixed now.

Additionally, we also added support for `shrinkWrap` in `MessageListView` in this [pr].(https://github.com/GetStream/stream-chat-flutter/pull/1520)

Closing it for now, Feel free to re-open if it persists.

Thanks.
