### ISSUE TITLE
Reply message popup not closing

### ISSUE THREAD

**Issue by ChiragGajjar** [GetStream/stream-chat-flutter#1489]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^5.3.0

### What happened?

When i reply to someone's message then it will show on the reply text on a text field with a bottom sheet with the close button, but when i try to close this or remove this message i can't able to do it, because nothing happens when we click on cross close button. 

[
![image](https://user-images.githubusercontent.com/20324254/226911138-222a15c3-4b19-4249-9038-3c54a332280e.png)
](url)

### Steps to reproduce

```bash
1 - Chat screen 
2 - Click on message - show popup - Press reply option.
3 - Show text field with reply message
4 - Try to close this reply actionsheet.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by po-hb** [comment]
@ChiragGajjar I had the same problem. You can try adding the following code to your StreamMessageInput 
`StreamMessageInput(
...
                    messageInputController: _messageInputController,
                    onQuotedMessageCleared: ()=>{
                        _messageInputController.clearQuotedMessage()
                    },
...
)
`

**Comment by ChiragGajjar** [comment]
@po-hb  Thanks it working
