### ISSUE TITLE
editMessageInputBuilder property not used in message edit widget 

### ISSUE THREAD

**Issue by po-hb** [GetStream/stream-chat-flutter#1490]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: 5.3.0
  stream_chat_persistence: 5.1.0

### What happened?

StreamMessageWidget and EditMessageSheet have editMessageInputBuilder property in their constructors, but it is not passed from StreamMessageWidget to EditMessageSheet
StreamMessageWidget code:
`
              builder: (_) => EditMessageSheet(
                message: widget.message,
                channel: StreamChannel.of(context).channel,
              ),

`
 for class MessageActionsModal, we have similar situation 

### Steps to reproduce

```bash
1. implement your own editMessageInputBuilder 
2. pass editMessageInputBuilder into StreamMessageListView messageBuilder
3. open conversation and try to edit some message
4. make sure that your editMessageInputBuilder is not used
```

### Supporting info to reproduce

```
             StreamMessageListView(
                  messageBuilder: (context, details, messages, defaultMessage) {
                    return defaultMessage.copyWith(
                      editMessageInputBuilder:(c, message) => Container(height: 50, color: Colors.red,),
                    );
                  },
                ),
```
when I tried to check it on sample app with versions of getstream (  stream_chat_flutter: ^4.2.0
  stream_chat_persistence: ^4.1.0), editMessageInputBuilder worked well

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NiyazFazlyev** [comment]
I have the same problem too

**Comment by PeterOmbodi** [comment]
Hi @xsahil03x for ver.6.0.1 still not fixed,
see https://github.com/GetStream/stream-chat-flutter/blob/895bce157e8955dbc30e29bcd4b855e4992f9f8a/packages/stream_chat_flutter/lib/src/message_actions_modal/message_actions_modal.dart#LL402C36-L402C36
`      builder: (context) => EditMessageSheet(
        message: widget.message,
        channel: channel,
      ),
`
editMessageInputBuilder not passed into EditMessageSheet

**Comment by xsahil03x** [comment]
Hey @PeterOmbodi, thanks I missed this for `MessageActionsModal`. Creating a PR rn.
