### ISSUE TITLE
Twitter links are not scrapped properly

### ISSUE THREAD

**Issue by 3ph** [GetStream/stream-chat-flutter#1494]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

5.3.0

### What happened?

I understand this is (likely) not an issue with the Flutter Stream SDK but I'm unsure where to post this issue (there are over 300 Stream repositories). The issue is that when you send a Twitter link as part of the message the enriched attachment coming back does not contain the tweet name and descriptions as it used to. Now it only has `Tweet / Twitter` (sometimes it contains some Arabic characters as well).

### Steps to reproduce

```bash
1. Go to any channel
2. Send any tweet link
3. When the enriched attachment is received, it only contains `Tweet / Twitter`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @3ph,

Tried replicating this with a tweet of mine, came back with all content:

<img width="286" alt="Screenshot 2023-04-03 at 2 37 28 PM" src="https://user-images.githubusercontent.com/26357843/229464333-2b598d32-4630-46c1-b46e-589538f47f15.png">

Can you give me an example tweet that's not working for you and preferably a screenshot too?

Thanks.

**Comment by 3ph** [comment]
Hi @deven98. Indeed it seems to be fixed now. This is how it looked before:

![Image 4-04-23 at 9 19 AM](https://user-images.githubusercontent.com/6635044/229630261-61f89930-fbf1-4814-be74-4d5ca8e9fe78.jpg)

Thanks!
