### ISSUE TITLE
Updating package versions

### ISSUE THREAD

**Issue by Advait1306** [GetStream/stream-chat-flutter#1496]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

^5.3.0

### What happened?

I can't update my dio dependency to the latest version because stream_chat_flutter depends on the 4.6.0 version of dio library.

### Steps to reproduce

```bash
No steps
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @Advait1306,

There were some issues preventing us from updating Dio previously. Now that those are resolved, we are working on updating it. 

Will close this PR once that change is merged and you can find it on the next version release. 

Thanks!

**Comment by Advait1306** [comment]
Thank you @deven98

**Comment by Ayush-gupta-josh** [comment]
@deven98 Any updates on this?

**Comment by deven98** [comment]
@Ayush-gupta-josh @Advait1306 Dio is updated, we are reviewing one last PR before releasing the next version of chat. Drift is updated but let me see if we can bump it up to make it compatible with amplify as well.

**Comment by deven98** [comment]
@Advait1306 are there any other packages that are acting as blockers for you?

**Comment by Mounix99** [comment]
@deven98 also actual for
video_player: ^2.6.1
flutter_svg: ^2.0.5
share_plus: ^6.3.2

**Comment by xsahil03x** [comment]
All the packages have been updated to the latest resolvable version in the new `v6` release.
https://pub.dev/packages/stream_chat_flutter

**Comment by Advait1306** [comment]
Somehow missed the notifications from this thread, thank you so much @deven98 & team for updating these promptly.
