### ISSUE TITLE
Mentions - clicking user on WEB on the latest flutter is broken

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1498]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

Latest

### What happened?

When you see a list of users to mention and you click on a user then the overlay closes but the user is not being mentioned nor added to the message. This happens on the latest flutter version (last working version that I have checked is 3.3.10, newer are broken)

### Steps to reproduce

```bash
1. Start mentioning overlay
2. Tap on a user
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@geweald It's also broken on MacOS, I took a look couple of weeks back and it's something related to the textEditing focus getting lost. I will try to give more time to this in the upcoming weeks.

Thanks.
