### ISSUE TITLE
Support for push notifications?

### ISSUE THREAD

**Issue by isaiahtaylorhh** [GetStream/stream-chat-flutter#15]
Hello, I can't find any documentation regarding using push notifications with this SDK. Is that documented somewhere?

**Comment by imtoori** [comment]
Hi, right now we are working on offline storage and push notifications
You'll see some progress soon

**Comment by isaiahtaylor** [comment]
Thanks for the quick response. Is there any way to register with the stream chat API for push notifications in the meantime? This is a blocker for us. Do you have a timeline estimate?

**Comment by imtoori** [comment]
I hope to finish this/next week.
By the way you can try to use https://pub.dev/packages/flutter_apns to have both android and ios notifications. A simple configuration is not difficult
