### ISSUE TITLE
Message bubble disappears

### ISSUE THREAD

**Issue by APPXOTICA** [GetStream/stream-chat-flutter#1505]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^5.3.0

### What happened?

Message bubble disappears randomly as seen on the bottom right screenshot.
Seems like the message bubble Container() widget is gone and the child text lost size constraints.
This happens frequently like half of our user's open channels on iOS and AOS both.
Below screenshots are taken from the same app on the same device.

![issue](https://user-images.githubusercontent.com/62071176/233331937-9c597618-c72c-4976-8e80-b049965da30b.png)

### Steps to reproduce

```bash
It's not possible to reproduce this issue becuase it happens at random.
```

### Flutter doctor output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.1 22C65 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@APPXOTICA, looks like our regex is identifying it as an emoji. Can you please paster these characters, so that we can test it locally?

```dart
  /// Returns whether the string contains only emoji's or not.
  ///
  ///  Emojis guidelines
  ///  1 to 3 emojis: big size with no text bubble.
  ///  4+ emojis or emojis+text: standard size with text bubble.
  bool get isOnlyEmoji {
    final trimmedString = trim();
    if (trimmedString.isEmpty) return false;
    if (trimmedString.characters.length > 3) return false;
    final emojiRegex = RegExp(
      r'^(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff])+$',
      multiLine: true,
      caseSensitive: false,
    );
    return emojiRegex.hasMatch(trimmedString);
  }
```

**Comment by APPXOTICA** [comment]
ㅎㅎㅎㅎ
ㅎㅎㅎ
But as you see on the screenshots, the same characters(ㅎㅎㅎ) have no issue on the left screenshot but have issue on the right screenshot.
