### ISSUE TITLE
Customizable attachment thumbnails

### ISSUE THREAD

**Issue by AustralianSpy** [GetStream/stream-chat-flutter#1511]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

We have been in the process of setting up custom attachment types that we are rendering ourselves, making use of the `attachmentThumbnailBuilders` on the `StreamMessageInput` and the `customAttachmentBuilders` on `StreamMessageListView`. The blocker we ran into is that we have very little control over what the attachment thumbnail actually looks like. In the source code, all non-standard attachment types are handled the same way, and are ultimately constrained into a box:

```
        if (remainingAttachments.isNotEmpty)
          Padding(
            padding: const EdgeInsets.fromLTRB(8, 8, 8, 0),
            child: LimitedBox(
              maxHeight: 104,
              child: ListView(
                scrollDirection: Axis.horizontal,
                children: remainingAttachments
                    .map<Widget>(
                      (attachment) => ClipRRect(
                        borderRadius: BorderRadius.circular(10),
                        child: Stack(
                          children: <Widget>[
                            AspectRatio(
                              aspectRatio: 1,
                              child: SizedBox(
                                height: 104,
                                width: 104,
                                child: _buildAttachment(attachment),
                              ),
                            ),
                            Positioned(
                              top: 8,
                              right: 8,
                              child: _buildRemoveButton(attachment),
                            ),
                          ],
                        ),
                      ),
                    )
                    .insertBetween(const SizedBox(width: 8)),
              ),
            ),
          ),
```
This results in a thumbnail like this:
![Simulator Screenshot - iPhone 14 - 2023-04-21 at 13 18 52](https://user-images.githubusercontent.com/69498225/234917283-5560081b-da9b-48dc-bb65-88581f41a43e.png)

### Describe the solution that you'd like

It would be nice to have more control over the thumbnails of custom attachments so that they better reflect the resulting attachment, such as the mockup below. 

<img width="569" alt="Screenshot 2023-04-27 at 10 53 15 AM" src="https://user-images.githubusercontent.com/69498225/234917789-8c260a40-97a1-4302-81fd-8591d8728aca.png">

Ideally, the carousel housing the thumbnails would not constrain width and would instead accept the widget as-is. It would be understandable if the height was still programmatically compressed so as not to oversize the input itself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @AustralianSpy,

Thanks for mentioning this, it sure looks like an enhancement.
