### ISSUE TITLE
Stream MessageWidget actions dialog backdrop filter is cut off by safe area

### ISSUE THREAD

**Issue by dan-wearearch** [GetStream/stream-chat-flutter#1532]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

6.0.0 

### What happened?

When long pressing on a message the backdrop filter for the dialog does not stretch the full screen. It is using position.fill for the backdrop but it is being cut off by the `SafeArea` inside flutter's `showDialog`. Suggest using the `useSafeArea` on `showDialog` to prevent this.

### Steps to reproduce

```bash
1. Go to message
2. Long press
3. View the Backdrop
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@dan-wearearch can you also share a screen shot for help?
