### ISSUE TITLE
Long messages should have `read more` button

### ISSUE THREAD

**Issue by OutdatedGuy** [GetStream/stream-chat-flutter#1541]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

It's very common for people to send long... I mean very very long messages. It's annoying that we always have to scroll more to get to top or bottom of messages when this types of messages are present.

In the `StreamMessageListView` widget, the messages built have all the text from the message without any _read more_ button or ellipsis. So it's very annoying trying to avoid these long messages.

https://github.com/GetStream/stream-chat-flutter/assets/74326345/b006e690-7b68-4239-835e-e6435d3c8ed3

### Describe the solution that you'd like

I want that the messages built by the `StreamMessageListView` widget to have a **1st** _read more_ button after a certain number of lines and a **2nd** _read more_ button after many many lines.

So it'll be very easy to pass these types of long messages when scrolling up or down to avoid them.

### Additional context

Flutter packages [readmore](https://pub.dev/packages/readmore) or [parsed_readmore](https://pub.dev/packages/parsed_readmore) might be helpful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @OutdatedGuy, you can always override the default widget using the builders we provide. In case of messages, you can use the `textBuilder` property of the `StreamMessageWidget`.

```dart
messageBuilder: (context, details, messages, defaultMessage) {
  return defaultMessage.copyWith(
    textBuilder: (context, message){
      // Return your custom text widget.
      return MyCustomText(message: message);
    },
  );
},
```

You can also look at the default implementation of the [StreamMessageText](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/lib/src/message_widget/message_text.dart) widget for inspiration.

**Comment by OutdatedGuy** [comment]
@xsahil03x, but shouldn't the Message widget by default have a read more feature?

**Comment by xsahil03x** [comment]
@OutdatedGuy It depends on the app preference, so it's better to not do it at the SDK level right now as it will be breaking for other users.
