### ISSUE TITLE
'package:flutter/src/widgets/layout_builder.dart': Failed assertion: line 157 pos 12: 'slot == null': is not true.

### ISSUE THREAD

**Issue by bratlove123** [GetStream/stream-chat-flutter#155]
**Describe the bug**
Got error when I started chatting. The UI is hang:

'package:flutter/src/widgets/layout_builder.dart': Failed assertion: line 157 pos 12: 'slot == null': is not true.

Flutter doctor:
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)

**To Reproduce**
1. Go to Channel List
2. Click on one channel
3. Do the chat

**Screenshots**

**Logs **
flutter: [2020-11-27 11:29:53.050514 | ConsoleHandler | INFO] ---------- ERROR ----------
flutter: [2020-11-27 11:29:53.050977 | ConsoleHandler | INFO] 'package:flutter/src/widgets/layout_builder.dart': Failed assertion: line 157 pos 12: 'slot == null': is not true.
flutter: [2020-11-27 11:29:53.051631 | ConsoleHandler | INFO]
flutter: [2020-11-27 11:29:53.052126 | ConsoleHandler | INFO] ------- STACK TRACE -------
flutter: [2020-11-27 11:29:53.054744 | ConsoleHandler | INFO] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
flutter: [2020-11-27 11:29:53.054942 | ConsoleHandler | INFO] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
flutter: [2020-11-27 11:29:53.055571 | ConsoleHandler | INFO] #2      _LayoutBuilderElement.insertRenderObjectChild
package:flutter/…/widgets/layout_builder.dart:157
flutter: [2020-11-27 11:29:53.055843 | ConsoleHandler | INFO] #3      RenderObjectElement.attachRenderObject
package:flutter/…/widgets/framework.dart:5851
flutter: [2020-11-27 11:29:53.055993 | ConsoleHandler | INFO] #4      RenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5547
flutter: [2020-11-27 11:29:53.056162 | ConsoleHandler | INFO] #5      _LayoutBuilderElement.mount
package:flutter/…/widgets/layout_builder.dart:83
flutter: [2020-11-27 11:29:53.056343 | ConsoleHandler | INFO] #6      Element.inflateWidget
package:flutter/…/widgets/framework.dart:3615

gz#7619

**Comment by imtoori** [comment]
Hi @bratlove123 
what version of the package are you using

**Comment by bratlove123** [comment]
Hi @imtoori . I'm using the latest version
stream_chat_flutter: ^0.2.1

**Comment by imtoori** [comment]
@bratlove123 the latest version is 0.2.14
I think you copied from the README, I'll update it removing the specific version
Can you try using version ^0.2.14?

**Comment by bratlove123** [comment]
Actually I'm using 0.2.3, that is the latest version.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/16585807/100587560-4cc84f80-3323-11eb-8254-2974a143d2bb.png">

**Comment by imtoori** [comment]
you can check on [pub.dev](https://pub.dev/packages/stream_chat_flutter)
the latest version is 0.2.14

**Comment by bratlove123** [comment]
Thanks for your sp. The new version work good.
