### ISSUE TITLE
StreamChatPersistenceClient doesn't take api key into consideration

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1556]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

Latest versions

### What happened?

StreamChatPersistenceClient doesn't consider apiKey and can be returning offline results for another app (if the query has the same parameters).

### Steps to reproduce

```bash
1. Query channels online with persistence with apiKey 1
2. Create a new client with persistence but apiKey 2
3. Go offline and use the same query for channels, you'll get channels from the 1. Instead of an empty list. It also happens for a moment if you're online (first query is to offline and then to online)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @geweald, Is this a valid usecase, Can you explain it a bit more?

Note: You can always `flush` the database while disconnecting the user.

**Comment by xsahil03x** [comment]
Yes, it's not directly provided. we call it from the `client.disconnectUser` method.
