### ISSUE TITLE
Searching channels doesn't return pagination data and does not sort properly

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1563]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

Latest

### What happened?

When trying to search messages the returned data doesn't contain pagination data (and seems not to be sorted properly). 

In the search query docs, I see that search only searches max 500 channels, I have thousands of channels so maybe that's a partial reason. But using `StreamMessageSearchListController` when I see network requests there are no pagination data in the response of my search query. I see a full page of results within the max limit, but even when I search for the same text and I set a limit of 1 then the response has just the single item, without any info to paginate.

Also, I'm trying to sort by `created_at` or `updated_at` but changing the sorting direction doesn't change the results, it stays the same (looks like it's still sorted by relevance).

Either way, because of thousands of channels, I cannot query correctly eg. for the latest mentions (which are actually part of a sample app), because the search can only consider 500 channels and WE CANNOT CHOOSE the sorting of channels my latest messages are not even returned, but some old ones (like it was checking the 500 oldest channels). 

What can be done here?

### Steps to reproduce

```bash
1. Having many channels (eg 1k), search for messages with `StreamMessageSearchListController` and use `StreamMessageSearchListView` to see results (can be in mentions in sample stream flutter app). Use sorting by `created_at`.
2. You will see results from old channels, not properly sorted and without pagination to load all resutls
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @geweald, the new page based pagination needs to be enabled from your project if its and old one. Feel free to contact the Stream [Support](https://getstream.io/contact/support/) for enabling it.

Feel free to re-open if this does not fixes your problem.

Thanks.
