### ISSUE TITLE
StreamChannelListController was used after being disposed

### ISSUE THREAD

**Issue by mal33k-eden** [GetStream/stream-chat-flutter#1574]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter - 6.0.0

### What happened?

In my chat screen,  i have my setup like so 
<img width="860" alt="Screenshot 2023-05-27 at 13 11 02" src="https://github.com/GetStream/stream-chat-flutter/assets/21183898/bccea231-6f1c-44f1-95d5-8dfadb844409">

Just like the documentation states,  i have disposed the controller. 

Everything works well until i navigate from the chat tab to another tab and back to the chat tab quickly then i get the error below.

<img width="1449" alt="Screenshot 2023-05-27 at 13 14 08" src="https://github.com/GetStream/stream-chat-flutter/assets/21183898/a294d8ea-e10d-45b2-bc01-13e4e5cee61b">

### Steps to reproduce

```bash
- from chat tab
- navigate to any other tab and back
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @mal33k-eden, I am not able to reproduce it. Can you share a small sample which i can try?

**Comment by xsahil03x** [comment]
@mal33k-eden Switching tabs by default resets the state of the widget. You should try adding the `KeepAlive` mixin to your tabs.

Read more here: https://stackoverflow.com/a/51225879/7668129

Feel free to re-open if this doesn't solve your issue.
