### ISSUE TITLE
Push notifications coming on an active channel

### ISSUE THREAD

**Issue by kalptech2021** [GetStream/stream-chat-flutter#1575]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: ^6.1.0

### What happened?

After successful implementation Notifications are working, However when I am in a channel (Active) I am still getting notifications. How can I stop that, I dont want to see a notification as I am already in the channel. 

### Steps to reproduce

```bash
1. Join a channel
2. Get the notifications when you are watching a channel
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kanat** [comment]
Hi @kalptech2021,

I was unable to replicate this issue.
Based on Firebase [doc](https://firebase.flutter.dev/docs/messaging/notifications/#displaying-notifications) notifications are supposed to be displayed only when the app is in the background or terminated:
```
The default behavior on all platforms is to display a notification 
only when the app is in the background or terminated. 

If required, you can override this behavior by following 
the Foreground Notifications documentation.
```

Could you please ensure that you're not showing local notifications for the [foreground](https://firebase.flutter.dev/docs/messaging/notifications/#foreground-notifications) push messages?

Could you also share templates (both iOS & Android) you use within your app?

**Comment by kalptech2021** [comment]
@kanat yes I am using FirebaseMessaging.onMessage.listen method to listen to foreground notifications, As the user might be using the app and is on a different channel, I still want to show them the notifications for other channels.

**Comment by kanat** [comment]
Hey @kalptech2021,

Could you please share the templates (both iOS & Android) you use within your app?
