### ISSUE TITLE
After updating dio to 5.2.0, stream_chat is throwing error. 

### ISSUE THREAD

**Issue by ps6067966** [GetStream/stream-chat-flutter#1588]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance

### On what platforms did you experience the issue?

Android

### What version are you using?

Latest version:  6.2.0

### What happened?

![image](https://github.com/GetStream/stream-chat-flutter/assets/26248740/24139453-3ff8-49c5-a5f6-dae3ec97bdbf)

### Steps to reproduce

```bash
Update dio to 5.2.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@ps6067966 are you overriding the dio dependency in your app?

**Comment by ps6067966** [comment]
> @ps6067966 are you overriding the dio dependency in your app?

No I'm not overriding any dependency.

**Comment by xsahil03x** [comment]
Related PR: https://github.com/cfug/dio/pull/1855

**Comment by xsahil03x** [comment]
Hey @ps6067966, The linked PR will fix the issue, Until then you can try to override the dio dependency to `5.1.2`.

```pubspec
dependency_overrides
	dio: 5.1.2
```

**Comment by tushkaty** [comment]
@xsahil03x overriding doesn't work for me. Can you guys make a release soon?

**Comment by xsahil03x** [comment]
@tushkaty can you share how are you doing it?

**Comment by tushkaty** [comment]
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  stream_chat_flutter: 6.0.0
dependency_overrides:
  dio: 5.1.2

**Comment by xsahil03x** [comment]
You should try removing your `pubspec.lock` file and call pub get again.
