### ISSUE TITLE
Member Mutes

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1594]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

It would be nice if there was an easy way to reload the list of people someone muted or unmuted after the event.
Currently the only way I see of getting the list is by using connectUser function which does work again after its been called unless the app is reloaded.

### Describe the solution that you'd like

The muted list should update and be watched in the same way a channel is or provide a different location for muted users.

### Describe alternatives that you have considered

Tried to reload the connectUser on each mute or unmute but an error is throw that the connection is already there.

### Additional context

Would like to mute a user when someone blocked that user in chat or in another area of the application. Once the person is blocked I filter out their messages based on the mute list.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@rlee1990 I think we can solve this by updating the currentUser object after a succesfull mute/unmute. What do you think?
Also, you can meanwhile try `openConnection/closeConnection` instead to get the updated user and then setting the currentUser with the updated data.

**Comment by xsahil03x** [comment]
Also there's a event you might be interested in.
https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/event_type.dart#L110-L111

**Comment by rlee1990** [comment]
@xsahil03x I tried that option after submitting this but It doesn't update the user still until an app restart. I think the approach you are providing will work.

**Comment by rlee1990** [comment]
@xsahil03x thanks I will check.
I also should mention I do use riverpod when I call connectUser for the first time.

**Comment by rlee1990** [comment]
@xsahil03x Thank you for this I got it working now.
