### ISSUE TITLE
Hard Delete Flag In UI

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1604]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

It would be nice to have a flag to hard delete a message when using Stream Chat Flutter UI.

### Describe the solution that you'd like

As of now it will only soft delete a message and we would have to use an event to then hard delete a message.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@rlee1990 where would you prefer to have this property?

**Comment by rlee1990** [comment]
I think this should be at the channel level @xsahil03x

**Comment by xsahil03x** [comment]
@rlee1990 but a channel can support both hard and soft delete at the same time. Similar to whatsApp (Delete for me, Delete for Everyone)

**Comment by rlee1990** [comment]
@xsahil03x So the channels support it but there doesn't seem to be an option for it on the ui section when we select delete. It would be nice either to have a flag to use just hard delete for that channel, a pop up that says to hard delete or soft delete when you select delete, or an onDelete callback function.
