### ISSUE TITLE
Add support for TextField's contentInsertionConfiguration property in StreamMessageInput

### ISSUE THREAD

**Issue by fryeap** [GetStream/stream-chat-flutter#1613]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

Android

### Is your feature request related to a problem?

Android's Gboard supports adding gifs and images directly from the keyboard. However, the TextField widget only supports plain text by default. Unless the contentInsertionConfiguration callback is provided, a toast message is displayed informing the user that the text field does not support inserting media content.

### Describe the solution that you'd like

The StreamMessageInput already accepts TextField attributes as part of its constructor parameters that are passed through to the text field. It would be a great help if a parameter that accepted the contentInsertionConfiguration callback were added as an additional optional parameter.

### Describe alternatives that you have considered

We have built our own message input widget that includes this parameter.

### Additional context

https://api.flutter.dev/flutter/material/TextField/contentInsertionConfiguration.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @fryeap, we reverted the commit due to incompatibility with flutter 3.10 as mentioned above. I advise to please also revert your changes back to what you were using before. We will try to add the support later in a major version. 🙏🏼 

Thanks.

**Comment by leossmith** [comment]
Is there a guide on how to use this to either past a photo from keyboard or select a gif (android)?
