### ISSUE TITLE
Control Background Colors Of Attachments or No boarder Option

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1621]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

Right now all attachments share the same background colors

### Describe the solution that you'd like

To add an attachment background color option to the StreamChatThemeData for ownMessageTheme and otherMessageTheme.

### Describe alternatives that you have considered

I tried overriding the messageWidget for when it is an attachment but that kicks errors for font sizes and leaves the attachments blank if a don't want a background.

### Additional context

![IMG_0026](https://github.com/GetStream/stream-chat-flutter/assets/21372502/7f4717c2-6ec7-4baa-a7e2-cc1c43ff733b)

The image above shows how a custom attachment looks with a background and that is not the look we are going for

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rlee1990** [comment]
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale
    en-US)
    • Flutter version 3.10.3 on channel stable at
      /Users/rickeylee/Desktop/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (2 weeks ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/rickeylee/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/rickeylee/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (5 available)
    • SM F926U (mobile)            • RFCR802EMHY                              • android-arm64
      • Android 13 (API 33)
    • SM N950U (mobile)            • ce061716d1923703017e                     • android-arm64
      • Android 9 (API 28)
    • rickey lee’s iPhone (mobile) • d0545eb2ff26e1c087d1b29c26f8e15da19284bb • ios
      • iOS 16.5 20F66
    • macOS (desktop)              • macos                                    • darwin-arm64
      • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                 • chrome                                   • web-javascript
      • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by xsahil03x** [comment]
@rlee1990 can you share how are you overriding the builder?

**Comment by rlee1990** [comment]
This is what I do for the attachments:
```
if (messageDetails
                            .message.attachments.isNotEmpty) {
                          return messageWidget.copyWith(
                            messageTheme: StreamMessageThemeData(
                              messageBackgroundColor: Colors.transparent,
                            )
                          );
                        }
```
This returns blank messages.

**Comment by xsahil03x** [comment]
Hey @rlee1990, I added a small fix around the font size errors you were getting. Also you should try to merge the theme rather than passing a totally new instance.

```dart
if (details.message.attachments.isNotEmpty) {
  final messageTheme = details.isMyMessage
      ? StreamChatTheme.of(context).ownMessageTheme
      : StreamChatTheme.of(context).otherMessageTheme;
  return defaultWidget.copyWith(
    messageTheme: messageTheme.merge(
      const StreamMessageThemeData(
        messageBackgroundColor: Colors.transparent,
      ),
    ),
  );
}
```

Also, in order to remove the border, you can pass `borderSide: BorderSide.none` in the messageWidget.

```dart
defaultWidget.copyWith(
  borderSide: BorderSide.none,
);
```

This should be enough for you use-case i guess.

**Comment by rlee1990** [comment]
@xsahil03x sorry for the delay but this did not work. See the image that I added. The last message is a custom attachment. The purple border is coming from the message background when I set the message background to transparent the message is not visible at all. I just want the option on attachments to not show that message background.

**Comment by rlee1990** [comment]
@xsahil03x can this be reopened as it is not resolved?

**Comment by xsahil03x** [comment]
Hey @rlee1990, can you also share the custom attachment implementation and the builder you are using in Message widget?

Also, if you think this can be solved easily with `attachmentBackgroundColor` prop then feel free to test and create a PR.
I am currently working on some other priority issues atm, so this might take some time.

Thanks.

**Comment by rlee1990** [comment]
@xsahil03x 
So I did test that if I set ```messageBackgroundColor: Colors.transparent,``` when overriding the theme for per chat at the top it works as expected but adding it inline like above does not so I will look into a PR over the weekend and get one added.
