### ISSUE TITLE
Move message to the end of the message queue

### ISSUE THREAD

**Issue by atoka93** [GetStream/stream-chat-flutter#1628]
Is there a way to change the message position when updating the message? I would specifically be interested in moving it to the end, basically pretending it has been sent just now.

I searched the documentation but didn't find a/the solution.

Currently I am removing the message and sending a new one; but it's not ideal.

**Comment by xsahil03x** [comment]
You can try sort the message list on the basis of updatedAt

**Comment by xsahil03x** [comment]
@atoka93 this is not the desired behaviour we want to provide in our SDK. You can try to re-implement your own `MessageListView` using the [MessageListCore](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter_core/lib/src/message_list_core.dart) or I just keep using the solution that you are already using.

Thanks.

**Comment by atoka93** [comment]
Sorting the list is not straight forward with pagination.
Also, I need to move only specific messages to the end of the list, not all updated ones.
