### ISSUE TITLE
Check user is muted

### ISSUE THREAD

**Issue by JuI3s** [GetStream/stream-chat-flutter#1636]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

For privacy-related features, I would like to check if a user is muted by another user (e.g. muted user cannot initiate new chat).

### Describe the solution that you'd like

Allows check to see if a user is muted by another user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@JuI3s, you can use the `mutes` field of the `currentUser` in order to check it.

```dart
final mutes = client.state.currentUser!.mutes;
final isMuted = mutes.any((mute) => mute.target.id == 'user-id');
```

**Comment by JuI3s** [comment]
> @JuI3s, you can use the `mutes` field of the `currentUser` in order to check it.
> 
> ```dart
> final mutes = client.state.currentUser!.mutes;
> final isMuted = mutes.any((mute) => mute.target.id == 'user-id');
> ```



> @JuI3s, you can use the `mutes` field of the `currentUser` in order to check it.
> 
> ```dart
> final mutes = client.state.currentUser!.mutes;
> final isMuted = mutes.any((mute) => mute.target.id == 'user-id');
> ```

I was asking the other way around. Suppose user mutes other_user. Is there anyway for other_user to know he is blocked?

**Comment by xsahil03x** [comment]
Hey @JuI3s, I asked the backend team and no, its not available… for privacy concerns :sweat_smile:
