### ISSUE TITLE
emptyBuilder for MessageListView

### ISSUE THREAD

**Issue by brbatwork** [GetStream/stream-chat-flutter#164]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an emptyBuilder function passed into MessageListView so that I can render a custom message when a user selects a channel that has no messages.  This would behave similar to [EmptyStateIndicator](https://github.com/GetStream/stream-chat-react/blob/e173df151959cb6331e314dfccea185739af418a/src/components/MessageList/MessageList.js#L392) in Stream's React SDK

**Describe the solution you'd like**
Provide an emptyBuilder for MessageListView

**Describe alternatives you've considered**
Manually checking the messages list size myself and rendering my own custom message when empty.

gz#7721

**Comment by xsahil03x** [comment]
@brbatwork thanks, that's a valid usecase.

**Comment by imtoori** [comment]
Added in the latest beta
