### ISSUE TITLE
Member not found: 'MediaQuery.sizeOf'.

### ISSUE THREAD

**Issue by nosmirck** [GetStream/stream-chat-flutter#1664]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

stream_chat_flutter: 6.5.0

### What happened?

App won't compile with Flutter 3.7.12 and stream chat flutter package 6.5.0

I understand the maintainers of this package are trying to migrate the package to flutter 3.10+ but in doing so, the package is useless with 3.7.12 since version 6.2.0 (the last usable version is 6.1.0).

For web, the last few versions (6.3.0 and 6.4.0) contain fixes that are needed, however, those versions included implementations for features not available in Flutter 3.7.12, last stable version before last minor update for Flutter (3.10+), which was very big update with many breaking changes, which means most devs won't be willing to update anytime soon due to the amount of braking changes.

So, 6.2.0 and up, including latest 6.5.0 are useless in 3.7.12 and even has issues with 3.10+.

I understand that before going to the next major release (7.0?) you want to leave this package as usable as possible with the previous flutter stable version (3.7.12).

Please, remove any reference to newer flutter 3.10 features for 6.X before you add all the nice features for flutter 3.10+ on stream chat 7.0.

### Steps to reproduce

```bash
App won't compile with Flutter 3.7.12 and stream chat flutter package 6.5.0
```

### Supporting info to reproduce

Add `stream_chat_flutter: 6.5.0` to a brand new app using Flutter 3.7.12 and the example code.

### Relevant log output

```shell
Launching lib\main.dart on Chrome in debug mode...
/C:/Users/nosmi/AppData/Local/Pub/Cache/hosted/pub.dev/stream_chat_flutter-6.5.0/lib/src/message_input/stream_message_input_attachment_list.dart:211:28: Error: Member not found: 'MediaQuery.sizeOf'.
                MediaQuery.sizeOf(context).width * 0.65,
                           ^^^^^^
Failed to compile application.
Exited (sigterm)
```

### Flutter analyze output

```shell
• No issues found!
```

### Flutter doctor output

```shell
> flutter doctor -v
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1848], locale en-CA)
    • Flutter version 3.7.12 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\nosmi\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\nosmi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] VS Code (version 1.80.0-insider)
    • VS Code at C:\Users\nosmi\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.67.20230601

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.37
    ! Device R5CT44HD8TV is not authorized.
      You might need to check your device for an authorization dialog.

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@nosmirck can you add all the references which are not working with `3.7.12`? I will try to revert them and add them as part of `v7`.

**Comment by nosmirck** [comment]
Ok, give me a couple of hours and I'll come back with all the things incompatible with 3.7.12

**Comment by xsahil03x** [comment]
@nosmirck the linked PR should have fixed all the issues.
