### ISSUE TITLE
[Bug] stream_chat_flutter_core >=6.4.0 requires http ^0.13.0

### ISSUE THREAD

**Issue by MayKosiba** [GetStream/stream-chat-flutter#1665]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

Android

### What version are you using?

stream_chat_flutter_core: ^6.4.0

### What happened?

I'm using `http: ^1.1.0` and it is a dependency in my project, however `stream_chat_flutter_core` requires `http ^0.13.0`

```
Because stream_chat_flutter_core >=6.4.0 depends on stream_chat ^6.4.0 which depends on jose ^0.3.3, stream_chat_flutter_core >=6.4.0 requires jose ^0.3.3.
Because jose 0.3.3 depends on http ^0.13.0 and no versions of jose match >0.3.3 <0.4.0, jose ^0.3.3 requires http ^0.13.0.
Thus, stream_chat_flutter_core >=6.4.0 requires http ^0.13.0.
So, because my_app depends on both http ^1.1.0 and stream_chat_flutter_core ^6.4.0, version solving failed.
```

### Steps to reproduce

```bash
1. Have `http: ^1.1.0` as a dependency in `pubspec.yaml`
2. Have `stream_chat_flutter_core >=6.4.0` as a dependency in `pubspec.yaml`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@MayKosiba you can try overriding the http dependency for the time being. We cannot do it atm as we depend on `jose`.

```pubspec
dependency_overrides:
  http: ^1.1.0
```
