### ISSUE TITLE
Channel list sorts after delay when using `StreamChatPersistenceClient`

### ISSUE THREAD

**Issue by ebjorklund01** [GetStream/stream-chat-flutter#1677]
### Please select which package this feature is related to

stream_chat_flutter, stream_chat_persistance

### Which platforms would this feature impact?

iOS, Android, Windows, MacOS, Linux

### Is your feature request related to a problem?

The channel sorting for channels is delayed until channels are retrieved from the network when using `StreamChatPersistenceClient`. 

We apply a sort to our `StreamChannelListController` to sort channels first by `lastMessageAt` and second by `updatedAt`. A sample of our controller looks like...
```dart
_listController = StreamChannelListController(
        client: context.read<StreamService>().client,
        channelStateSort: [_byLastMessageAt],
      );
```
And the sorting function...
```dart
SortOption<ChannelState> get _byLastMessageAt => SortOption<ChannelState>(
        'last_message_at',
        comparator: (a, b) {
          final channelADate = a.channel?.lastMessageAt ?? a.channel?.updatedAt;
          final channelBDate = b.channel?.lastMessageAt ?? b.channel?.updatedAt;

          if (channelADate == null || channelBDate == null) return 0;
          return channelADate.compareTo(channelBDate);
        },
      );
```
This works great with the plain Jane `stream_chat_flutter` package **without** using the `stream_chat_persistence` package. However, when the client is provided a persistence client via
```dart
client.chatPersistenceClient = StreamChatPersistenceClient();
```
The sorting doesn't apply until the channels are retrieved from the network. From a user's perspective, the channels sort after a ~1s delay when connected to a network. However, if a user is offline, the channels don't sort at all. Please see a couple of attached videos below. This could 

### Describe the solution that you'd like

I would like the channels to sort when using `StreamChatPersistenceClient`.

### Describe alternatives that you have considered

I don't know where to start to fix this from my end. The `StreamChannelListController` and `StreamChatPersistenceClient` didn't appear to have any parameters to adjust to address this issue. I could apply a delay to wait to display the channel list if the user is connected to the network, but that is more of a band-aid than a solution.

### Additional context

Channel list when connected to a network:

https://github.com/GetStream/stream-chat-flutter/assets/70149512/ccef9da2-65f6-452b-bac2-b6086d8453d9

Channel list when not connected to a network:

https://github.com/GetStream/stream-chat-flutter/assets/70149512/51895f28-8f0d-4c0a-9ddb-bdc6615cc794

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @ebjorklund01 the sorting is working fine for me. The logic you used should be changed.

```diff
SortOption<ChannelState> get _byLastMessageAt => SortOption<ChannelState>(
        'last_message_at',
        comparator: (a, b) {
          final channelADate = a.channel?.lastMessageAt ?? a.channel?.updatedAt;
          final channelBDate = b.channel?.lastMessageAt ?? b.channel?.updatedAt;

          if (channelADate == null || channelBDate == null) return 0;
-         return channelADate.compareTo(channelBDate);
+         return channelBDate.compareTo(channelADate);
        },
      );
```

If this doesn't work, please share a sample project where, i can reproduce it.

**Comment by ebjorklund01** [comment]
@xsahil03x  Wow thank you for pointing that out 😅. To reduce complexity, I have updated our `StreamChannelListController` initialization to 

```dart
_listController = StreamChannelListController(
        client: context.read<StreamService>().client,
        channelStateSort: const [SortOption('last_message_at')],
        limit: 20,
      );
```

And it does still appear like there is a discrepancy in the sorting of the persisted channels and the channels resolved from the network. Is the `lastMessageAt` timestamp not being persisted for channels? See the video below of what I'm seeing on my end.

https://github.com/GetStream/stream-chat-flutter/assets/70149512/a2d770ee-c940-4dcc-98cd-67307d377f7a

**Comment by ebjorklund01** [comment]
Added the following comparator functions and sorting works as desired both offline and online.

```dart
SortOption<ChannelState> get _byLastMessageAt => SortOption<ChannelState>(
        'last_message_at',
        comparator: (a, b) => b.channel?.lastMessageAt?.compareTo(a.channel?.lastMessageAt ?? DateTime(0)) ?? 0,
      );

  SortOption<ChannelState> get _byUpdatedAt => SortOption<ChannelState>(
        'updated_at',
        comparator: (a, b) => b.channel?.updatedAt.compareTo(a.channel?.updatedAt ?? DateTime(0)) ?? 0,
      );
```

I did not see that the `comparator` function is required for offline sorting.
