### ISSUE TITLE
file_selector and firebase_auth creating conflict in header files in IOS not able to build the app

### ISSUE THREAD

**Issue by RahulFlutter225** [GetStream/stream-chat-flutter#1681]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

^6.4.0

### What happened?

file_selector and firebase_auth creating conflict in header files in IOS not able to build the app
getting error on import of "message.g.h" in ios

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @RahulFlutter225, need some more information. Please paste the output and steps to reproduce.

**Comment by xsahil03x** [comment]
Closing as not related to SDK. read more here: https://github.com/firebase/flutterfire/issues/9511

**Comment by xsahil03x** [comment]
Closing as not related to SDK. read more here: https://github.com/firebase/flutterfire/issues/9511
