### ISSUE TITLE
Sending System Message sends Regular Message instead

### ISSUE THREAD

**Issue by mingjunsiek** [GetStream/stream-chat-flutter#1682]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^6.5.0

### What happened?

Based on the flutter docs in getStream [website](https://getstream.io/chat/docs/flutter-dart/silent_messages/?language=dart), it states the following: 

<img width="816" alt="image" src="https://github.com/GetStream/stream-chat-flutter/assets/13094556/16476137-be51-41fe-b69f-ca3f241fd6b5">

Note the sentence: `The user who sends a system message client-side should have the Create System Message permission.` which meant that we can create system message on the client side.

I have already enabled the `Create System Message` permission on the GetStream dashboard for my project.

But when I used the following code to send the system message via Flutter, the message was somehow converted to a `regular` message instead of `system:
```
final message = Message(
  text: 'systemMessage',
  type: 'system',
);

await channel.sendMessage(message);
```
Screenshot:
<img width="360" alt="image" src="https://github.com/GetStream/stream-chat-flutter/assets/13094556/7efe1744-39a1-401f-9e86-36633c9e1a7d">
- Message stored in GetStream
  - <img width="400" alt="image" src="https://github.com/GetStream/stream-chat-flutter/assets/13094556/0e68e659-e433-4bf5-9f41-c0ae127e257a">

### Steps to reproduce

```bash
1. Create a Message object with type = 'system'

final message = Message(
  text: 'systemMessage',
  type: 'system',
);
2. Send this message to the channel

await channel.sendMessage(message);

3. Message is turned to a regular message instead of a system message.
```

### Supporting info to reproduce

- Printing the Message Object
  - Message(91f2a6ba-5121-4637-b321-93feb1b6ad84, Replying will automatically move you to the next stage in the hiring process., system, [], [], null, null, null, null, null, null, null, 0, null, null, false, false, null, null, null, null, null, null, null, null, false, null, null, null, {}, MessageSendingStatus.sending, null)
  - <img width="360" alt="image" src="https://github.com/GetStream/stream-chat-flutter/assets/13094556/7efe1744-39a1-401f-9e86-36633c9e1a7d">
- Message stored in GetStream
  - <img width="400" alt="image" src="https://github.com/GetStream/stream-chat-flutter/assets/13094556/0e68e659-e433-4bf5-9f41-c0ae127e257a">

### Relevant log output

```shell
-
```

### Flutter analyze output

```shell
-
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4.1 22F770820d darwin-arm64, locale en-SG)
    • Flutter version 3.10.4 on channel stable at /Users/mingjun/fvm/versions/3.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (6 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mingjun/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @mingjunsiek, yes we currently ignore the `type` in the json payload.
https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/core/models/message.dart#L170-L172

I will soon create a PR for this fix.

**Comment by mingjunsiek** [comment]
@xsahil03x Can I know when can we expect this to be released? Because the only other alternative is to send a request to the backend which will use the javascript sdk to send the system message which is not ideal for our use case.

**Comment by xsahil03x** [comment]
I will create a fix probably on Monday.

**Comment by mingjunsiek** [comment]
@xsahil03x Apologies if I sound pushy but when can I expect the fix to be released for stream_chat_flutter?
