### ISSUE TITLE
StreamChannelListController does not apply filter to newly added channels

### ISSUE THREAD

**Issue by jmain20** [GetStream/stream-chat-flutter#1697]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat: 6.7.0
stream_chat_flutter: 6.8.0
stream_chat_flutter_core: 6.7.0
stream_chat_localizations: 5.8.0

### What happened?

Expected behavior:
-StreamChannelListView should only display channels that meet the specified filter criteria.
-If I have a StreamChannelListController with a filter and the current user is added to a channel, the channel should only be added to the controller's list of channels if it meets the filter criteria.

Observed behavior:
-I have a StreamChannelListView with a StreamChannelListController that has a filter.
-The current user is added to a channel that does not meet the filter criteria.
-The channel is added to the controller's channel list and displayed in the list view.
-If I take some action that causes the controller to be rebuilt, that channel is no longer displayed in the list view

### Steps to reproduce

```bash
1. Create a StreamChannelListView with a StreamChannelListController that has a filter.
2. While that StreamChannelListView is being displayed, add the current user to a channel that does not meet the filter criteria provided to the controller.
```

### Supporting info to reproduce

This seems to be happening because the default StreamChannelListEventHandler `onNotificationAddedToChannel` method calls `onChannelVisible`, which adds the event channel to the controller's list of channels without checking for filters.

I was able to work around this issue using a custom channel list event handler with the following override for `onChannelVisible`. However, I would expect this to be the default behavior of StreamChannelListEventHandler/StreamChannelListController.

```
  @override
  void onChannelVisible(final Event event, final StreamChannelListController controller) async {
    if (event.cid == null) return;

    final cidFilter = Filter.equal('cid', event.cid!);
    final filter = controller.filter == null ? cidFilter : Filter.and([controller.filter!, cidFilter]);
    await for (final channels in controller.client.queryChannels(filter: filter)) {
      final channel = channels.firstOrNull;
      if (channel == null) return;

      controller.channels = [
        channel,
        ...controller.currentItems.where((final cc) => cc.cid != channel.cid),
      ];
    }
  }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @jmain20, The current implementation is by design, and it's always customizable, so we don't have any plans to change it atm.

Thanks.
