### ISSUE TITLE
Messages with mentioned users sent from Flutter do not render correctly on React-web

### ISSUE THREAD

**Issue by AustralianSpy** [GetStream/stream-chat-flutter#1702]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

Flutter:
```
  stream_chat:
    version: "6.4.0"
  stream_chat_flutter:
    version: "6.4.0"
```

React (Web):
```
"stream-chat": "^8.10.1",
"stream-chat-react": "^10.8.0",
```

### What happened?

When a user sends a message with mentioned users from a mobile Flutter-based app, the message does not display the name on web. Instead, it displays an @ with the user's id. The message displays correctly on mobile.

When a user sends a message from web in this way, the mention displays the name but is not bolded on mobile, implying it is not rendering as a mention but just as plain text. The message displays correctly on web.

Logging values pre-message sending and post-message sending, on web the text always displays as `@User Name`. On mobile, the text displays `@User Name` pre-message sending, then `@User-ID-String` after it sends.

This was not an issue until recently. I am unsure if this is an issue for Flutter or React, but my gut instinct is that the root of the bug is here. However, there is a possibility that there is a discrepancy between how mentions are sent and/or rendered between these two SDKs.

### Steps to reproduce

Send a message in chat from either React web or Flutter mobile that mentions another user. Check the chat in the opposite app.

### Supporting info to reproduce

Flutter App Screenshot:
<img width="329" alt="Screenshot 2023-08-09 at 2 59 54 PM" src="https://github.com/GetStream/stream-chat-flutter/assets/69498225/47ae2b75-2856-4a28-901a-e74aa8ae5aec">

React Web Screenshot:
<img width="561" alt="Screenshot 2023-08-09 at 3 00 01 PM" src="https://github.com/GetStream/stream-chat-flutter/assets/69498225/c0450d9d-2c6c-4617-bfe2-5518f907786e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @AustralianSpy, We convert the `username` to `id` before sending the message because there can be similar usernames but not IDs.

We do convert them to IDs before sending the message. We use this piece of code to convert them back into usernames.

https://github.com/GetStream/stream-chat-flutter/blob/1b3bf2efbfde06df5ff0170005baaaea232b0886/packages/stream_chat_flutter/lib/src/utils/extensions.dart#L347-L366

You can modify the [Message](https://getstream.io/chat/docs/sdk/react/components/message-components/message/) component on React and take inspiration from this code to convert the IDs back to usernames.

**Comment by AustralianSpy** [comment]
@xsahil03x Thank you. This will work as a bandaid in the interim to hide the IDs, but mentions in a message sent cross-platform are also simply not being recognized _**as**_ a user-mention. They're just being rendered as a plain-text `@UserName` with no functionality to tie to it unless we manually parse every message looking for mentioned users on BOTH platforms. There's an additional underlying issue here where user-mentions are not being treated the same way between Flutter-mobile and React-web. We're making no modifications ourselves to the message text and mentioned users before sending or upon rendering the message.

**Comment by xsahil03x** [comment]
@AustralianSpy yes, I will create a fix for it soon.

**Comment by AustralianSpy** [comment]
@xsahil03x Thank you very much!
