### ISSUE TITLE
When using a custom UserName Builder it doesn't replace all user-name places.

### ISSUE THREAD

**Issue by dankomiocevic** [GetStream/stream-chat-flutter#1708]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS

### What version are you using?

 stream_chat_flutter - 6.6.0

### What happened?

When setting a custom Username by setting the property `bottomRowBuilderWithDefaultWidget` from `StreamMessageListView` and using a custom `usernameBuilder`. Some parts of the UI do not use the widget to set the Username.

For example, the Reactions Card shows a wrong username:

https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter/lib/src/message_widget/reactions/reactions_card.dart#L132

There should be a way to set a custom UserName for all these scenarios.

### Steps to reproduce

```bash
- Create a new StreamMessageListView
- Override the `bottomRowBuilderWithDefaultWidget` property with a custom UserName Builder.
- Open the Reactions Card on any message, the username does not match the one created by the custom builder.
```

### Supporting info to reproduce

- 

### Relevant log output

```shell
-
```

### Flutter analyze output

```shell
-
```

### Flutter doctor output

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @dankomiocevic thanks for opening this issue.

Seems to me like a bug. While we are working on that, if you do not have any spaces in your custom username you can do the following workaround:

```dart
extension UserExtension on User {
    String? get name => // your implementation here
}
```

**Comment by esarbanis** [comment]
Hey @dankomiocevic , although this seemed like a bug at first glance, it is not. The reason is that we have deprecated `usernameBuilder` in favor of `bottomRowBuilderWithDefaultWidget`, and the reason is exactly that: we do not override the username in all places, but rather only in the bottom row, as the name suggests.

The above workaround is sufficient to override the username text in all places.
