### ISSUE TITLE
Push Notification example

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#1717]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

It would be nice to have a proper example of using this package for push notifications.
I have tried and have not been able to get it to work.

### Describe the solution that you'd like

An example of adding a device for both ios and android when using firebase messaging for push notifications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rlee1990** [comment]
@xsahil03x thanks Ill give it a look.

**Comment by rlee1990** [comment]
So I followed the steps and can confirm that I have added a device but I still don't receive notifications when the app is open closed or in the background. I also tried to send a test notification via the dashboard but I get this error ```CheckPush failed with error: "User has no enabled devices associated"``` but that doesn't make sense as I can run getDevices and it returns a device id.

**Comment by rlee1990** [comment]
@xsahil03x any idea why this might be happening using v2 of the push notifications?

**Comment by xsahil03x** [comment]
@rlee1990, I am checking this with the team for more info.

**Comment by xsahil03x** [comment]
@rlee1990 where do you exactly get this error?

**Comment by rlee1990** [comment]
@xsahil03x on the dashboard for getstream when I use the test configurations.
I also don't receive any notifications on Android or iOS when I send a message on any channel.

**Comment by xsahil03x** [comment]
Thanks, I will keep you posted. 👍🏼

**Comment by rlee1990** [comment]
> Thanks, I will keep you posted. 👍🏼

Thank you.

**Comment by monstaro** [comment]
Hi @rlee1990 , I have opened a ticket with your email through our support portal so we can better track this issue

**Comment by rlee1990** [comment]
> Hi @rlee1990 , I have opened a ticket with your email through our support portal so we can better track this issue

Thank you.

**Comment by xsahil03x** [comment]
@rlee1990 I will close this issue then,  We can re-open if not resolved through support 👍🏼
