### ISSUE TITLE
StreamMessageInput allowedAttachmentPickerTypes doesn't hide record video or hide videos on mobile

### ISSUE THREAD

**Issue by kydav** [GetStream/stream-chat-flutter#1721]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

6.9.0

### What happened?

If I set 
`allowedAttachmentPickerTypes: [
    AttachmentPickerType.files,
    AttachmentPickerType.images,
  ],`
  on iOS and Android, videos still appear in the selection and there is a video icon in the bottom sheet to record a video to send.  Is there a way to not allow videos at all in the Stream Chat attachments? 

### Steps to reproduce

```bash
1. Set allowedAttachmentPickerTypes in StreamMessageInput
2. Go to chat
3. Click on paperclip to attach
4. Videos appear in list and take video button is available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey, @kydav, I was able to reproduce this. I will create a fix soon. Thanks.

**Comment by JeisonSanches** [comment]
Hi @xsahil03x, I’m still experiencing the same issue. When I set `allowedAttachmentPickerTypes: [AttachmentPickerType.images]`, it only allows me to take a picture and prevents me from selecting photos from the gallery. Any ideas on how to fix/workaround this?
