### ISSUE TITLE
WebSocketError(message: Connect failed with error: "Token signature is invalid", data: ErrorResponse(code: 5, message: Connect failed with error: "Token signature is invalid", statusCode: 401, moreInfo: https://getstream.io/chat/docs/api_errors_response))

### ISSUE THREAD

**Issue by MdAsifUrRahmanAbir** [GetStream/stream-chat-flutter#1731]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter_core: ^6.7.0
stream_chat_flutter: 6.9.0
![Capture3](https://github.com/GetStream/stream-chat-flutter/assets/50311815/b8de0ee2-713f-4ac7-bea4-f21c8ada573e)

### What happened?

I create a flutter chatting project connecting your sdk,,
my first api key is expired so i created another account and replace the api key, but here have a error,, which is Token signature is invalid.

WebSocketError(message: Connect failed with error: "Token signature is invalid", data: ErrorResponse(code: 5, message: Connect failed with error: "Token signature is invalid", statusCode: 401, moreInfo: https://getstream.io/chat/docs/api_errors_response))

This is the whole error message. why is this error generated ??
![Capture2](https://github.com/GetStream/stream-chat-flutter/assets/50311815/3e98968b-c619-4688-86b4-830cb7ada957)

### Steps to reproduce

```bash
WebSocketError(message: Connect failed with error: "Token signature is invalid", data: ErrorResponse(code: 5, message: Connect failed with error: "Token signature is invalid", statusCode: 401, moreInfo: https://getstream.io/chat/docs/api_errors_response))
```

### Supporting info to reproduce

 WebSocketError(message: Connect failed with error: "Token signature is invalid", data: ErrorResponse(code: 5, message: Connect failed with error: "Token signa
![Capture](https://github.com/GetStream/stream-chat-flutter/assets/50311815/9017a9e4-6b34-4532-9c2f-2cba2d9ae5e0)
ture is invalid", statusCode: 401, moreInfo: https://getstream.io/chat/docs/api_errors_response))
![Capture2](https://github.com/GetStream/stream-chat-flutter/assets/50311815/4b19d207-9c96-4ef5-86da-4c078c2f37bc)

### Relevant log output

```shell
DioExceptionType.badResponse 
I/flutter (25381): 2023-09-09 16:11:45.783327 🚨 🕸️ ║    { 
I/flutter (25381): 2023-09-09 16:11:45.786006 🚨 🕸️ ║         StatusCode: 401, 
I/flutter (25381): 2023-09-09 16:11:45.786245 🚨 🕸️ ║         code: 5, 
I/flutter (25381): 2023-09-09 16:11:45.786730 🚨 🕸️ ║         details: [] 
I/flutter (25381): 2023-09-09 16:11:45.788157 🚨 🕸️ ║         duration: "0", 
I/flutter (25381): 2023-09-09 16:11:45.788830 🚨 🕸️ ║         message: "QueryUsers failed with error: "Token signature is invalid"", 
I/flutter (25381): 2023-09-09 16:11:45.789721 🚨 🕸️ ║         more_info: "https://getstream.io/chat/docs/api_errors_response" 
I/flutter (25381): 2023-09-09 16:11:45.790459 🚨 🕸️ ║    }
```

### Flutter analyze output

```shell
Analyzing android...                                                    
No issues found! (ran in 0.5s)
```

### Flutter doctor output

```shell
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
    • Flutter version 3.13.2 on channel stable at D:\For Flutter Environment\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (2 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 116.0.1938.69

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MdAsifUrRahmanAbir** [comment]
try {
      final client = StreamChatCore.of(context).client;

      User userValue = User(
          id: userData['id'],
          name: userData['name'],
          image: userData['image'],
          extraData: {
            'contacts': userData['contacts'],
            'friendRequest': userData['friendRequest'],
            'token': userData['token'],
            'dob': userData['dob'],
            'gender': userData['gender']
          });

      // create users
      await client.connectUser(
          userValue,
          // userData['id']
          client.devToken(userData['id']).rawValue);

    } catch (e) {
      e.toString().redConsole;
    }

**Comment by xsahil03x** [comment]
@MdAsifUrRahmanAbir you also need to update the user token with the new secret of the project. You can use our manual generator to re-generate the token. Thanks.

https://getstream.io/chat/docs/react/tokens_and_authentication/#manually-generating-tokens

**Comment by Narven** [comment]
I keep getting this error on Flutter, using Firebase Auth with the GetStream authentication extension. I get a proper token, but for some reasone is invalid.
