### ISSUE TITLE
Cannot seem to use this in conjunction with EasyLocalizations

### ISSUE THREAD

**Issue by daveshirman** [GetStream/stream-chat-flutter#1733]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

**Version**: stream_chat_localizations: ^5.10.0

### What happened?

Followed setup instructions, no problems.

However, if I use either of these two lines in main.dart `MaterialApp`:

```
localizationsDelegates: context.localizationDelegates,
localizationsDelegates: GlobalStreamChatLocalizations.delegates,
```

I either get:
- Correct chat interface translations - incl the input textbox
- Correct app translations in general, except chat interface.

But not both.

Is there a conflict here?

Thanks

### Steps to reproduce

```bash
1. Follow setup guide
2. Setup both StreamChat localizations
3. Setup https://pub.dev/packages/easy_localization
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@daveshirman It should be used like below if you are using additional delegates. Thanks.

```dart
        localizationsDelegates: [
          GlobalStreamChatLocalizations.delegate,
          ...context.localizationDelegates,
        ],
```

**Comment by daveshirman** [comment]
Thank you, that works.  Please can the official documentation be updated to at least show this example?
I can't be the only person who didn't get why this wasn't working or who has this type of setup.

Thanks again.

**Comment by xsahil03x** [comment]
Hey @daveshirman, The documentation is correct as per vanilla flutter application. You can read the 7th and 8th points in the official flutter documentation for more info. Thanks.

https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#adding-your-own-localized-messages

**Comment by daveshirman** [comment]
Perfect, thanks for the information.
