### ISSUE TITLE
AllowedAttachmentPickerTypes set to files and images auto opens files only on mobile

### ISSUE THREAD

**Issue by kydav** [GetStream/stream-chat-flutter#1734]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

6.10.0

### What happened?

![Screen Recording 2023-09-11 at 2 15 05 PM](https://github.com/GetStream/stream-chat-flutter/assets/10816342/252bacb3-ad34-415a-a1b1-75b2986a4d87)
I have added `allowedAttachmentPickerTypes: const [ AttachmentPickerType.files, AttachmentPickerType.images ]`, and with the latest version it auto opens the files window instead of letting me choose a photo or a file.  

### Steps to reproduce

```bash
1. Add version 6.10.0
2. Set allowedAttachmentPickerTypes to files and images
3. Touch on the paper clip to attach
4. See that files opens up automatically
(also of note, it appears that the image that is in the attachment drawer is only taking photos not taking photos or attaching photos.)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @kydav, we are working on a fix, and it probably will be part of the next major release. I will keep you posted, Thanks.

**Comment by esarbanis** [comment]
This is fixed AFAIK with [this](https://github.com/GetStream/stream-chat-flutter/commit/dd4815b7c1b36228a39e91dbd2353d24eeb69fa5)
