### ISSUE TITLE
Getting error while sending image on chat - File type application/octet-stream is not supported

### ISSUE THREAD

**Issue by ChiragGajjar** [GetStream/stream-chat-flutter#1736]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^6.10.0

### What happened?

When we send image to chat it will getting upload error 

### Steps to reproduce

```bash
1. Chat message screen
2. select image and send
3. Getting error
```

### Supporting info to reproduce

It will not getting error for all images, this happened only for some images

### Relevant log output

```shell
flutter: 2023-09-13 14:53:11.923221 🚨 🕸️ ╔ DioExceptionType.badResponse
flutter: 2023-09-13 14:53:11.923911 🚨 🕸️ ║    {
flutter: 2023-09-13 14:53:11.924592 🚨 🕸️ ║         code: 4,
flutter: 2023-09-13 14:53:11.925728 🚨 🕸️ ║         message: "UploadImage failed with error: "File type application/octet-stream is not supported"",
flutter: 2023-09-13 14:53:11.925857 🚨 🕸️ ║         StatusCode: 400,
flutter: 2023-09-13 14:53:11.926025 🚨 🕸️ ║         duration: "0.00ms",
flutter: 2023-09-13 14:53:11.926193 🚨 🕸️ ║         more_info: "https://getstream.io/chat/docs/api_errors_response",
flutter: 2023-09-13 14:53:11.926666 🚨 🕸️ ║         details: []
flutter: 2023-09-13 14:53:11.926803 🚨 🕸️ ║    }
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-arm64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Volumes/Personal/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/chiragsondagar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 52EAB4E7-7218-4DBD-AAFD-976DA00D6BA8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@ChiragGajjar can you also share the image which is throwing this error? I can test it on my end. Thanks

**Comment by ChiragGajjar** [comment]
And one another device we getting this issue, - Android 

![MicrosoftTeams-image](https://github.com/GetStream/stream-chat-flutter/assets/20324254/da9425ac-20ce-416b-86da-e8fb0b5414ce)

**Comment by xsahil03x** [comment]
Hey @ChiragGajjar, The file you uploaded is not a valid image file type. It's an ISO media that should be uploaded as a file rather than an image. Thanks.

<img width="706" alt="Screenshot 2023-09-14 at 4 15 50 PM" src="https://github.com/GetStream/stream-chat-flutter/assets/25670178/e099b387-0270-4d74-8e7b-0ea6ee766f9e">

You can also test it here: https://www.checkfiletype.com/

**Comment by xsahil03x** [comment]
> And one another device we getting this issue, - Android
> 
> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/20324254/267721457-da9425ac-20ce-416b-86da-e8fb0b5414ce.png)

Can you verify if the necessary permissions are allowed for the app in settings?

**Comment by ChiragGajjar** [comment]
Yeah, We have given all permissions, it's working another device. but on that device we getting that issue.

**Comment by ChiragGajjar** [comment]
> Hey @ChiragGajjar, The file you uploaded is not a valid image file type. It's an ISO media that should be uploaded as a file rather than an image. Thanks.
> 
> <img alt="Screenshot 2023-09-14 at 4 15 50 PM" width="706" src="https://user-images.githubusercontent.com/25670178/267949919-e099b387-0270-4d74-8e7b-0ea6ee766f9e.png">
> You can also test it here: https://www.checkfiletype.com/

About this I have download some images from safari and 10% images is with this type - application/octet-stream.

**Comment by xsahil03x** [comment]
@ChiragGajjar I asked our backend team for info. I will keep you posted.

**Comment by kanat** [comment]
Hi @ChiragGajjar,

Could you please share your `app_id`?

**Comment by esarbanis** [comment]
I am closing this off as there is no progress or additional info. 

Please don't hesitate to re-open it if the issue persists.

**Comment by esarbanis** [comment]
People still report this issue on Android in the [samples apps](https://github.com/GetStream/flutter-samples/commit/016d7ae4eff22e61cbad97c957d62b7164db2048)

**Comment by ChiragGajjar** [comment]
@esarbanis  Any update on this issue?
![screenshot-1700737465421](https://github.com/GetStream/stream-chat-flutter/assets/20324254/bf979848-aa3d-4ac4-9ef6-10b75b5c75fc)

**Comment by ChiragGajjar** [comment]
Here is the app ID:- 1198644

**Comment by esarbanis** [comment]
@ChiragGajjar I am working on this now, I am trying to reproduce, I may have some more questions to help me out. Please bear with me 🙂 🙏

**Comment by esarbanis** [comment]
@ChiragGajjar I get the error that the mime type is `image/avif` have you tried adding this mime type to your [app's configuration](https://getstream.io/chat/docs/react/app_setting_overview/#image-uploads)?

**Comment by ChiragGajjar** [comment]
I can't find out this methods on flutter. 

client.updateAppSetting

**Comment by esarbanis** [comment]
That can only be called from the server SDKs, alternatively you can go to the dashboard `Chat Messaging` -> `Overview` -> `Upload Configuration` -> `Images` and add an `Allow` behavior.

**Comment by esarbanis** [comment]
I am gong to close this, but will have my eye out if this is reported again to re-open it.

**Comment by mednow-roman** [comment]
I see this issue was recently closed... why? I have been waiting for a resolution October 2023. This is still an issue.

**Comment by esarbanis** [comment]
I am happy to re-open it, but I would like your help to reproduce it @mednow-roman . 

This was closed because no-one answered my [question](https://github.com/GetStream/stream-chat-flutter/issues/1736#issuecomment-1845118012) and lack of activity usually means either a fix or a workaround was found without communicating it.

**Comment by mednow-roman** [comment]
Great, thank you!
Here are screenshots of my correspondence with your team regarding this.
Let me know what else you need from me.

![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/c114171a-28e8-4cbb-9e62-a3e9c7f296ef)
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/94a7a2b2-7f0c-4ad2-8e1a-bda3e29da301)
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/2e884321-b14b-466d-9d19-52a4a9378df1)
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/655f3424-b9d9-4a8a-b2f3-2de5afc949d1)
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/0c4cb1ce-1aa1-49e0-b574-09ce6fe7d529)
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/7bb0bf8c-d2a4-405e-adbd-d8295a7646d5)
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/1a86e940-782a-4865-9faf-3ba4183ea47b)
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/b2156f7b-c507-4766-b201-bd77e2a098d2)

**Comment by mednow-roman** [comment]
Files/Images are NOT blocked as far as I can tell.
![image](https://github.com/GetStream/stream-chat-flutter/assets/160882685/1275d0e8-89bc-4de7-ad89-e8cf5cf066de)

**Comment by mednow-roman** [comment]
@esarbanis 
Any updates on this? You asked for some details... were my screenshots enough?

**Comment by esarbanis** [comment]
@mednow-roman Thank you for your help 🙏 ! To be honest, I didn't find the time to go through them yet.

I expect to tackle this issue within the week. I am now driving [this](https://github.com/GetStream/stream-chat-flutter/pull/1743) to `master`, but I going through conflict hell with it ...

**Comment by mednow-roman** [comment]
Bump.

**Comment by mednow-roman** [comment]
@esarbanis 
Any update on this?

**Comment by mednow-roman** [comment]
We pay $500 USD per month for your services so we would appreciate some progress updates and a timeline of when you expect to have this fixed by... and/or if it has been fixed already in a future version.

We are using the following stream packages:

```
stream_chat_flutter: 6.11.0
stream_chat_flutter_core: 6.10.0
stream_chat_localizations: 5.11.0
```

**Comment by deven98** [comment]
@mednow-roman + @ChiragGajjar there's a lot of noise on this issue, I am creating a new thread with the issue so we can sort out the proper issue.
