### ISSUE TITLE
User mention not working

### ISSUE THREAD

**Issue by Phong-Trinh** [GetStream/stream-chat-flutter#1737]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

6.9.0

### What happened?

![image](https://github.com/GetStream/stream-chat-flutter/assets/89011112/3318f8ae-12e0-468d-9b6a-226637ff67d4)
![image](https://github.com/GetStream/stream-chat-flutter/assets/89011112/ca977bac-2f22-4bf0-9ac3-9314e0ea966b)
![image](https://github.com/GetStream/stream-chat-flutter/assets/89011112/5a026e9d-7b26-4de5-b703-d720b7bc7bfa)

When click on user to mention, it run into the addMentionedUser function but MessageInput still does not update the mentioned users

### Steps to reproduce

```bash
1. Go to 'channel page'
2. Click on chat input and type '@'
2. Click on 'member to mention'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @Phong-Trinh, I am not able to reproduce it. Can you try it on our [example](https://github.com/GetStream/stream-chat-flutter/tree/develop/packages/stream_chat_flutter/example) app? Thanks.

https://github.com/GetStream/stream-chat-flutter/assets/25670178/36d6f7a4-8e90-4dab-aaba-461d87744404
