### ISSUE TITLE
New project using Flutter SDK 3 would generate error when running in iOS simulator

### ISSUE THREAD

**Issue by wenchenglai** [GetStream/stream-chat-flutter#1740]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

  stream_chat_flutter: ^6.10.0

### What happened?

When creating a new Flutter Application with Flutter SDK version 3, using the stream_chat_flutter would generate the following error when running the app in iOS simulator:

Plugin video_player:macos has multiple possible implementations:
  video_player_avfoundation
  video_player_macos
To fix this issue, add one of these dependencies to pubspec.yaml.

Exception: Please resolve the errors

### Steps to reproduce

```bash
1. Create a new Flutter Application project, using SDK version >3. E.g.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.0"

3. Run the new app in iOS simulator, you should be able to see the default counting app.
4. Execute the command in project terminal: "flutter pub add stream_chat_flutter"
5. Run the app again in iOS simulator, you'll see the following error:

Plugin video_player:macos has multiple possible implementations:
  video_player_avfoundation
  video_player_macos
To fix this issue, add one of these dependencies to pubspec.yaml.

Exception: Please resolve the errors
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rlee1990** [comment]
I also get this error on the latest release

**Comment by xsahil03x** [comment]
Hey @wenchenglai , @rlee1990 this is because we are using `video_player_macos` and recently `video_player` also added support for `macos`. So there are two implementation for the same class. Removing the extra dependency will solve this. Creating a fix soon.
