### ISSUE TITLE
Execution failed for task ':image_gallery_saver:compileDebugKotlin

### ISSUE THREAD

**Issue by bensonarafat** [GetStream/stream-chat-flutter#1744]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

versions 6.11.0

### What happened?

I just tried to run my app, i am getting the error.
I am using the latest flutter SDK version, after investigation i found out that one of the dependency called image_gallery_saver is causing the error 

### Steps to reproduce

```bash
Add the dependency and start debugging for my emulator
```

### Relevant log output

```shell
* What went wrong:
Execution failed for task ':image_gallery_saver:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

### Flutter doctor output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version
    10.0.22621.2134], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.      
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of 
      its default components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.83.0)
[√] Connected device (3 available)
[√] Network resources
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @bensonarafat ,

Thank you for opening this up. Can you please confirm that you have tried what is mentioned [here](https://stackoverflow.com/questions/69079963/how-to-set-compilejava-task-11-and-compilekotlin-task-1-8-jvm-target-com) and [here](https://blog.jetbrains.com/kotlin/2021/11/gradle-jvm-toolchain-support-in-the-kotlin-plugin/), with no success?

**Comment by bensonarafat** [comment]
I had to use stream_chat instead.. 
`stream_chat_flutter` depends `image_gallery_saver`
and it is flagging an error because of namespace from `image_gallery_saver`

**Comment by esarbanis** [comment]
@bensonarafat I cannot reproduce it in the latest version, can you confirm that you have setup your environment to the correct java version and it is still happening?

**Comment by hqutrung** [comment]
Hello, has anyone solved this case?

**Comment by furqan23** [comment]
Hi as the error states that image_gallery_saver  is using different compile version. This error mostly happen when u upgrade gradle plugin above 7.6.3 and java/koltin option abouve 18/1.8 respectectively. So you can place 

subprojects {
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
        kotlinOptions.jvmTarget = "1.8"
    }
}

in android/build.gradle so if any project is using these conflicting kotlin and java version they will consume the  right one
Thanks

**Comment by lucasjinreal** [comment]
It doesn't work:

Execution failed for task ':flutter_timezone:compileReleaseKotlin'.
> 'compileReleaseJavaWithJavac' task (current target is 17) and 'compileReleaseKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

**Comment by emonxcode** [comment]
subprojects {
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
kotlinOptions.jvmTarget = "1.8"
}
}

this method is worked, thanks @furqan23

**Comment by RaoSaqib7860** [comment]
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    afterEvaluate {
        // check if android block is available

        if (it.hasProperty('android')) {

            if (it.android.namespace == null) {
                def manifest = new XmlSlurper().parse(file(it.android.sourceSets.main.manifest.srcFile))
                def packageName = manifest.@package.text()
                println("Setting ${packageName} as android namespace")
                android.namespace = packageName
            }

            def javaVersion = JavaVersion.VERSION_17
            android {
                def androidApiVersion = 33
                compileSdkVersion androidApiVersion
                defaultConfig {
                    targetSdkVersion androidApiVersion
                }
                compileOptions {
                    sourceCompatibility javaVersion
                    targetCompatibility javaVersion
                }
                tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
                    kotlinOptions {
                        jvmTarget = javaVersion.toString()
                    }
                }
                println("Setting java version to ${javaVersion.toString()} which is $javaVersion")
                println("Setting compileSdkVersion and targetSdkVersion to $androidApiVersion")
            }
        } 
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}
