### ISSUE TITLE
Can I delete text messages without the message appearing: "Message Deleted"?

### ISSUE THREAD

**Issue by gadzhov** [GetStream/stream-chat-flutter#1747]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web

### Is your feature request related to a problem?

![image](https://github.com/GetStream/stream-chat-flutter/assets/18680832/3250f230-942a-4fdb-8864-f63b20c652f3)

### Describe the solution that you'd like

It will be nice if StreamMessageWidget has a flag for turning it on/off

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
You can use the [`messageBuilder`](https://github.com/GetStream/stream-chat-flutter/blob/1164dbaf18867264e883dc4ab172d114edfd1972/packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart#L135) callback in `MessageListView` component to check if [`defaultMessageWidget.isDeleted`](https://github.com/GetStream/stream-chat-flutter/blob/1164dbaf18867264e883dc4ab172d114edfd1972/packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart#L792) and override the building behavior.

**Comment by gadzhov** [comment]
> You can use the [`messageBuilder`](https://github.com/GetStream/stream-chat-flutter/blob/1164dbaf18867264e883dc4ab172d114edfd1972/packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart#L135) callback in `MessageListView` component to check if [`defaultMessageWidget.isDeleted`](https://github.com/GetStream/stream-chat-flutter/blob/1164dbaf18867264e883dc4ab172d114edfd1972/packages/stream_chat_flutter/lib/src/message_widget/message_widget.dart#L792) and override the building behavior.

Thank you for your response @esarbanis, but with your suggestion, date divider will always appear, even there is no message for that day (all deleted).

![image](https://github.com/GetStream/stream-chat-flutter/assets/18680832/0ceff26a-ddb6-4da3-b18d-f7bf97e25cf8)

Probably you will suggest to override the date divider by using dateDividerBuilder, but it's only providing a date, and things get complicated.
Is there any example for what I want?

p.s. Provided links are not working.

**Comment by esarbanis** [comment]
Hi @gadzhov apologies for the links, you can also try the [`messageFilter`](https://github.com/GetStream/stream-chat-flutter/blob/354ae323b2cef03596d1d126f8188e500f8e8ce5/packages/stream_chat_flutter/lib/src/message_list_view/message_list_view.dart#L258) property of `MessageListView`, this way those messages are eliminated from the list and are not calculated for the dividers.
