### ISSUE TITLE
Unhandled null check operator exception when user is removed from a channel

### ISSUE THREAD

**Issue by jmain20** [GetStream/stream-chat-flutter#1753]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat: 6.9.0
stream_chat_flutter: 6.11.0
stream_chat_flutter_core: 6.10.0
stream_chat_localizations: 5.11.0
stream_chat_persistence: 6.9.0

### What happened?

I got an error from the Stream client when the current user was removed from a channel. If the user was viewing a list of the channel members when they were removed from the channel, the error prevents the list of channel members in the view from updating correctly. 

The user has permission to view channel members without being a member of the channel, so I would expect the view to update and show the correct list of channel members (not including the current user that was just removed).

### Steps to reproduce

```bash
1. Connect to chat from the Flutter client app
2. Open a view that shows the members of a channel
3. Remove that user from the channel
```

### Relevant log output

```shell
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      ClientState._listenChannelLeft.<anonymous closure>
client.dart:1662
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#4      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#5      _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _MultiStreamController.addSync (dart:async/stream_impl.dart:1044:36)
#10     _MultiControllerSink.add
forwarding_stream.dart:130
#11     _StartWithStreamSink.on<…>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @jmain20 !

Thank you for opening this issue! Can you please share the full log?
