### ISSUE TITLE
Filter.notEqual("invite","accepted") throwsQueryChannels failed

### ISSUE THREAD

**Issue by Jan-Stepien** [GetStream/stream-chat-flutter#1755]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat: 6.6.0

### What happened?

Exception preventing from using predefined filer Filter.notEqual() on chatRoom invite

### Steps to reproduce

```bash
1. Run query:
await streamClient.queryChannelsOnline(
            filter: 
                stream.Filter.and(
                  [
                    stream.Filter.in_('members', [memberUid]),
                    stream.Filter.notEqual("invite", "accepted"),
                  ],
                ),
          ),
        );
```

### Supporting info to reproduce

flutter: 2023-10-23 16:43:59.162531 🚨 🕸️  DioException ║ Status: 400 Bad Request
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
flutter: 2023-10-23 16:43:59.162938 🚨 🕸️ ╔ DioExceptionType.badResponse
flutter: 2023-10-23 16:43:59.163363 🚨 🕸️ ║    {
flutter: 2023-10-23 16:43:59.163766 🚨 🕸️ ║         code: 4,
flutter: 2023-10-23 16:43:59.164600 🚨 🕸️ ║         "QueryChannels failed with error: "invalid invite operator, expecting flutter: flutter: 2023-10-23 16:43:59.164600 🚨 🕸️ ║.        {invite:"pending"} or {invite:{$eq:"pendin
flutter: 2023-10-23 16:43:59.165026 🚨 🕸️ ║         g"}}""
flutter: 2023-10-23 16:43:59.165430 🚨 🕸️ ║         StatusCode: 400,
flutter: 2023-10-23 16:43:59.165902 🚨 🕸️ ║         duration: "0.00ms",
flutter: 2023-10-23 16:43:59.166295 🚨 🕸️ ║         more_info: "https://getstream.io/chat/docs/api_errors_response",
flutter: 2023-10-23 16:43:59.166679 🚨 🕸️ ║         details: []
flutter: 2023-10-23 16:43:59.167085 🚨 🕸️ ║    }
flutter: 2023-10-23 16:43:59.167447 🚨 🕸️ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @Jan-Stepien ! Thank you for opening this issue!

It seems to me like a backend issue. I will investigate further and let you know

**Comment by esarbanis** [comment]
Hey @Jan-Stepien unfortunately we do not support `$neq` in strings, so a solution for you would be to switch your filter from `stream.Filter.notEqual("invite", "accepted"),` to `stream.Filter.equal("pending"),`

We also need to update our documentation and even remove this ability from `Filter` class. Thank you for reaching out with this issue!
