### ISSUE TITLE
invite.exists returns more results than invite.pending + invite.accepted + invite.rejected

### ISSUE THREAD

**Issue by Jan-Stepien** [GetStream/stream-chat-flutter#1756]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat: ^6.6.0

### What happened?

when calling `await _chatClient.queryChannelsOnline(`

with
```dart
filter: stream.Filter.exists('invite'),
```
and 
```dart
filter:  stream.Filter.or(
    [
        stream.Filter.equal('invite', 'pending'),
        stream.Filter.equal('invite', 'accepted'),
        stream.Filter.equal('invite', 'rejected'),
    ],
)
```

returns different results - meaning there is more values to query for in terms of `invite` parameter ( not shown by the documentation)

### Steps to reproduce

Call `await _chatClient.queryChannelsOnline(filter: stream.Filter.exists('invite'),)`

and 
```dart
await _chatClient.queryChannelsOnline(
    filter:  stream.Filter.or(
        [
             stream.Filter.equal('invite', 'pending'),
             stream.Filter.equal('invite', 'accepted'),
             stream.Filter.equal('invite', 'rejected'),
        ],
    ),
);
```

2. compare results
```


### Supporting info to reproduce

_No response_

### Relevant log output

_No response_

### Flutter analyze output

_No response_

### Flutter doctor output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @Jan-Stepien ! Thank you for opening this issue with us.

As per our [documentation](https://getstream.io/chat/docs/flutter-dart/query_channels/?language=dart), you can only call `$eq` on `invite` as it is the only operation supported on that field.

Can you please specify what is the difference between the 2 result sets? Does calling `exists` return more results?

**Comment by Jan-Stepien** [comment]
Hello @esarbanis 
Exactly as you mentioned:
`filter: stream.Filter.exists('invite')`
returns more results than 
```
filter:  stream.Filter.or(
    [
        stream.Filter.equal('invite', 'pending'),
        stream.Filter.equal('invite', 'accepted'),
        stream.Filter.equal('invite', 'rejected'),
    ],
)
```
Which leads me into thinking that there are more statuses not exposed.
