### ISSUE TITLE
The Reaction Picker is not being removed when I set showReactionPicker to false.

### ISSUE THREAD

**Issue by MSRPRO** [GetStream/stream-chat-flutter#1759]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

stream_chat_flutter: ^6.11.0

### What happened?

I tried to remove the reaction picker by setting `showReactionPicker = false`, but I still see it when long-press on a message.

One thing that I noticed is when you set `showReactionPicker = false` you got the two bubbles disappear leaving the reaction picker flying alone in the top of the message, and when you set `showReactionPicker = true` you got the two bubbles displayed again, please have a look on the screenshots below.

![Screenshot_1698682982](https://github.com/GetStream/stream-chat-flutter/assets/80641133/117c97af-bf4b-4171-a3e9-019494f22165)
![Screenshot_1698682971](https://github.com/GetStream/stream-chat-flutter/assets/80641133/b841e8c2-e983-4025-883d-ae2506ceca98)

### Steps to reproduce

```bash
1- Set showReactionPicker = false for your StreamMessageWidget
2- Open your Chat UI
3- Long-press on a message
4- You will see the reaction picker pop up
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.4.1 22F82 darwin-arm64, locale
    en-AE)
    • Flutter version 3.13.8 on channel stable at
      /Users/mohammadsrieo/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (12 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/mohammadsrieo/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14
      (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS
      13.4.1 22F82 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
I can confirm this is an issue, and I am working on a fix.

Thanks @MSRPRO

**Comment by mkobuolys** [comment]
@deven98 @esarbanis I think the solution introduced a side effect. Now you can see the picker trail simply in the `StreamMessageListView` even when the picker is not visible. See the screenshot below:

![Simulator Screenshot - iPhone 15 - 2024-01-17 at 16 44 09](https://github.com/GetStream/stream-chat-flutter/assets/17415795/e5fb3783-5edf-45c4-bba9-de69456f4b35)
