### ISSUE TITLE
 File google-services.json is missing. The Google Services Plugin cannot function without it.     Searched Location:       

### ISSUE THREAD

**Issue by jinfagang** [GetStream/stream-chat-flutter#176]
```
 File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location:       
```

Hi, in China, hard to using google services, is this necessary? I really want using this in China.

gz#7997

**Comment by imtoori** [comment]
Hi! It's not
That's just the sample app that has firebase notifications support
Try the tutorial at https://getstream.io/chat/flutter/tutorial
