### ISSUE TITLE
Notification message null when app is killed and notification tapped

### ISSUE THREAD

**Issue by urvashik-7span** [GetStream/stream-chat-flutter#1764]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter_core: ^6.10.0
  stream_chat_flutter: ^6.11.0

### What happened?

For redirecting to particular screen I am using the following but in "message" I got null.

```
 redirectAfterKill() {
    FirebaseMessaging.instance.getInitialMessage().then((message) {
      debugPrint("FirebaseMessaging.getInitialMessage: ${message?.notification}");
      debugPrint("FirebaseMessaging.getInitialMessage: ${message?.data}");

      if (message != null) {
        final appRouter = GetIt.I<AppRouter>();
        appRouter.push(
          WebViewRoute(url: "", title: 'translate("jobDetails")'),
        );
      }
    });
  }
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @urvashik-7span , thanks for opening up this issue. Can you also include the code snippet of where the `redirectAfterKill()` method is called?

According to [FirebaseMessaging documentation](https://pub.dev/documentation/firebase_messaging/latest/firebase_messaging/FirebaseMessaging/getInitialMessage.html) the RemoteMessage can be null either if it does not contain a [Notification](https://api.flutter.dev/flutter/dart-html/Notification-class.html) or the `RemoteMessage` was already consumed. Can you identify which condition exists in your case?

**Comment by urvashik-7span** [comment]
My  ``redirectAfterKill()`` is called on ``initState()`` of my home screen.
```
 @override
  void initState() {
    _observeForNewPushNotification();
    redirectAfterKill();
    super.initState();
  }
```

**Comment by Brazol** [comment]
Hi @urvashik-7span 

Are you also subscribing to both `onBackgroundMessage` and `onMessage` handlers in your implementation?
Given that your method is named `redirectAfterKill`, I assume you are testing scenarios where the app is killed. Is it in such cases that you receive a null response?
When you send the same push notification while the app is in the background or foreground, do you receive the proper message through `onBackgroundMessage` or `onMessage` handlers?
