### ISSUE TITLE
Right click with reactions does not work on web

### ISSUE THREAD

**Issue by dvmatyun** [GetStream/stream-chat-flutter#1765]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

stream_chat_flutter: ^6.11.0

### What happened?

On mobile platforms reactions working perfectly fine with long tap. However, on web version right click (or any other click) does not call any reactions pop-up.

### Steps to reproduce

```bash
1. Add <body oncontextmenu="return false;"> to html
My version looks like this:
<body oncontextmenu="return false">
  <div id="loader-id" class="container">
  </div>
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>

2. Use 'const StreamMessageListView()' widget to build messages list for selected channel
3. Right click on any message - see no reaction AT ALL. (But everything works with same code on mobile platforms)
```

### Supporting info to reproduce

Also, if you spam right click you will get following error (Irrelevant to issue):
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown:
Assertion failed:
file:///C:/Users/dima/fvm/versions/3.13.6/packages/flutter/lib/src/animation/animation_controller.dart:453:7
animation_controller.dart:453
_ticker != null
"AnimationController.forward() called after AnimationController.dispose()\nAnimationController
methods should not be used after calling dispose."
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49                throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3                  assertFailed
packages/flutter/src/animation/animation_controller.dart 453:15                             forward
packages/ezanimation/ezanimation.dart 228:19                                                start
packages/stream_chat_flutter/src/context_menu_items/context_menu_reaction_picker.dart 36:8  triggerAnimations
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                          <fn>
dart-sdk/lib/async/zone.dart 1407:47                                                        _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                                        runUnary
dart-sdk/lib/async/future_impl.dart 156:18                                                  handleValue
dart-sdk/lib/async/future_impl.dart 840:44                                                  handleValueCallback
dart-sdk/lib/async/future_impl.dart 869:13                                                  _propagateToListeners
dart-sdk/lib/async/future_impl.dart 632:7                                                   [_complete]
dart-sdk/lib/async/future.dart 424:15                                                       <fn>
dart-sdk/lib/async/zone.dart 1391:47                                                        _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                                        run
dart-sdk/lib/async/zone.dart 1209:7                                                         runGuarded
dart-sdk/lib/async/zone.dart 1249:23                                                        <fn>
dart-sdk/lib/async/zone.dart 1399:13                                                        _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                                        run
dart-sdk/lib/async/zone.dart 1233:23                                                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19                     internalCallback
════════════════════════════════════════════════════════════════════════════════════════════════════

### Flutter analyze output

```shell
flutter analyze
Analyzing qyre-flutter...                                               
No issues found! (ran in 18.1s)
```

### Flutter doctor output

```shell
fvm flutter doctor -v        
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2428], locale ru-RU)
    • Flutter version 3.13.9 on channel stable at C:\Users\dima\fvm\versions\3.13.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (9 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\sdk\Android\android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\sdk\Android\android-sdk
    • Java binary at: C:\Users\dima\Downloads\android-studio-2023.1.1.10-windows\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10353782)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\android-studio-canary
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Users\dima\Downloads\android-studio-2023.1.1.10-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10353782)

[√] VS Code, 64-bit edition (version 1.82.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 118.0.5993.120
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 118.0.2088.76

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @dvmatyun ,

Thank you for opening this issue with us. We are supporting Android and iOS officially, but also provide experimental support for web and macOS. So this is more a feature request than a bug. Unfortunately, this will have a low priority for us. If you really want this behaviour in web, I would encourage you to open a PR for it.
