### ISSUE TITLE
Upgrade connectivity_plus to 5.0.1

### ISSUE THREAD

**Issue by elroir** [GetStream/stream-chat-flutter#1769]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: 6.11.0 which depends on stream_chat_flutter_core 6.10.0

### What happened?

App crashes when building with Xcode 15. Crash logs said it was a problem with connectivity_plus. I saw you are using version 4.0.2.
According to connectivity_plus changelog, they fixed the problem in version 5.0.0

### Steps to reproduce

```bash
With TestFlight
1. Upload app to App Store Connect
2. Upload to TestFlight
3. Try to open the app
4. Send Crashlogs to developer
...
With real device
1. in the terrminal run command: flutter run --release
2. App wont't open
```

### Supporting info to reproduce

Because no versions of stream_chat_flutter match >6.11.0 <7.0.0 and stream_chat_flutter 6.11.0 depends on stream_chat_flutter_core ^6.10.0, stream_chat_flutter ^6.11.0 requires stream_chat_flutter_core ^6.10.0.
Because stream_chat_flutter_core 6.10.0 depends on connectivity_plus ^4.0.2 and no versions of stream_chat_flutter_core match >6.10.0 <7.0.0, stream_chat_flutter_core ^6.10.0 requires connectivity_plus ^4.0.2.
Thus, stream_chat_flutter ^6.11.0 requires connectivity_plus ^4.0.2.
So, because nannys_parents depends on both connectivity_plus ^5.0.1 and stream_chat_flutter ^6.11.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on connectivity_plus: flutter pub add connectivity_plus:^4.0.2

This is how I found it was stream_chat_flutter who was using an outdated version

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale es-419)
    • Flutter version 3.13.9 on channel stable at /Users/enriqueeidgalarza/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/enriqueeidgalarza/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 14.1 23B74 darwin-arm64

[✓] Network resources
    • All expected network resources are available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elroir** [comment]
I forgot to mention, manually changing connectivity plus to version 12.0 fixes the issue, but after running pod install, it downgrades again, thanks!

**Comment by shkvoretz** [comment]
Also, having the very same issue.

**Comment by elroir** [comment]
You can change minimum deployment to iOS 12, in connectivity_plus pod, it solves the issue, but after running pod update or pod install it goes back to 11
