### ISSUE TITLE
Hide quoted message header which called QuotingMessageTopArea

### ISSUE THREAD

**Issue by Muhammad-Gamal2** [GetStream/stream-chat-flutter#1776]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS

### Is your feature request related to a problem?

I want to customize the quoted message section but the QuotingMessageTopArea is always there. I can't remove or redesign it.
![Screenshot 2023-11-09 at 4 26 32 PM](https://github.com/GetStream/stream-chat-flutter/assets/71530119/b41ac116-8f9a-4593-a87a-1eb667003b25)

### Describe the solution that you'd like

You could add a boolean to show or hide it or add a custom builder for it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ihijazi** [comment]
Looking for similar feature.

Also for edit message to have control over the design.
