### ISSUE TITLE
Can't run stream_chat_flutter after upgrading flutter to 3.16.0

### ISSUE THREAD

**Issue by quangtuyen1993** [GetStream/stream-chat-flutter#1780]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

stream_chat_flutter 6.11.0
│   ├── contextmenu 3.0.0
│   │   ├── after_layout 1.2.0
│   │   │   └── flutter...
│   │   ├── animations 2.0.8
│   │   │   └── flutter...
│   │   └── flutter...
│   ├── dart_vlc 0.4.0
│   │   ├── audio_video_progress_bar 0.11.0
│   │   │   └── flutter...
│   │   ├── dart_vlc_ffi 0.2.0+1
│   │   │   ├── ffi...
│   │   │   └── path...
│   │   ├── flutter...
│   │   └── path...
│   ├── desktop_drop 0.4.4
│   │   ├── cross_file...
│   │   ├── flutter...
│   │   └── flutter_web_plugins...
│   ├── diacritic 0.1.4
│   ├── ezanimation 0.6.0
│   │   └── flutter...
│   ├── file_picker 5.5.0
│   │   ├── flutter_plugin_android_lifecycle 2.0.17
│   │   │   └── flutter...
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── path...
│   │   ├── plugin_platform_interface...
│   │   └── win32...
│   ├── file_selector 1.0.1
│   │   ├── file_selector_android 0.5.0+4
│   │   │   ├── file_selector_platform_interface...
│   │   │   ├── flutter...
│   │   │   └── plugin_platform_interface...
│   │   ├── file_selector_ios 0.5.1+7
│   │   │   ├── file_selector_platform_interface...
│   │   │   └── flutter...
│   │   ├── file_selector_linux 0.9.2+1
│   │   │   ├── cross_file...
│   │   │   ├── file_selector_platform_interface...
│   │   │   └── flutter...
│   │   ├── file_selector_macos 0.9.3+3
│   │   │   ├── cross_file...
│   │   │   ├── file_selector_platform_interface...
│   │   │   └── flutter...
│   │   ├── file_selector_platform_interface 2.6.1
│   │   │   ├── cross_file...
│   │   │   ├── flutter...
│   │   │   ├── http...
│   │   │   └── plugin_platform_interface...
│   │   ├── file_selector_web 0.9.3
│   │   │   ├── file_selector_platform_interface...
│   │   │   ├── flutter...
│   │   │   ├── flutter_web_plugins...
│   │   │   └── web...
│   │   ├── file_selector_windows 0.9.3+1
│   │   │   ├── cross_file...
│   │   │   ├── file_selector_platform_interface...
│   │   │   └── flutter...
│   │   └── flutter...
│   ├── flutter_markdown 0.6.18+2
│   │   ├── markdown 7.1.1
│   │   │   ├── args...
│   │   │   └── meta...
│   │   ├── flutter...
│   │   ├── meta...
│   │   └── path...
│   ├── flutter_portal 1.1.4
│   │   ├── collection...
│   │   ├── flutter...
│   │   └── vector_math...
│   ├── lottie 2.7.0
│   │   ├── archive...
│   │   ├── flutter...
│   │   ├── path...
│   │   └── vector_math...
│   ├── path_provider 2.1.1
│   │   ├── path_provider_android 2.2.1
│   │   │   ├── flutter...
│   │   │   └── path_provider_platform_interface...
│   │   ├── path_provider_foundation 2.3.1
│   │   │   ├── flutter...
│   │   │   └── path_provider_platform_interface...
│   │   ├── flutter...
│   │   ├── path_provider_linux...
│   │   ├── path_provider_platform_interface...
│   │   └── path_provider_windows...
│   ├── photo_manager 2.8.1
│   │   └── flutter...

### What happened?

../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Relevant log output

```shell
../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-VN)
    • Flutter version 3.16.0 on channel stable at /Users/tuyen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tuyen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/tuyen/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.3)
    • Android Studio at
      /Users/tuyen/Library/Caches/JetBrains/Toolbox/backup/AndroidStudio-223.8836.35.2231
      .10811636-18133638418168889510/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64
      • Android 11 (API 30) (emulator)
    • iPhone 15 Pro Max (mobile) • 9E75A2EC-C73B-4854-B76F-DE240BDB2B8A • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64
      • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript
      • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by flodaniel** [comment]
This is due to the [flutter_photo_manager dependency](https://github.com/fluttercandies/flutter_photo_manager). Version 3 is already in beta and stream-chat-flutter could already provide a pre-release too based on the beta channel with the changes described in migration guide [here](https://github.com/fluttercandies/flutter_photo_manager/blob/main/MIGRATION_GUIDE.md#2x-to-30).

**Comment by quangtuyen1993** [comment]
> This is due to the [flutter_photo_manager dependency](https://github.com/fluttercandies/flutter_photo_manager). Version 3 is already in beta and stream-chat-flutter could already provide a pre-release too based on the beta channel with the changes described in migration guide [here](https://github.com/fluttercandies/flutter_photo_manager/blob/main/MIGRATION_GUIDE.md#2x-to-30).

Thank. Glad to hear this from you

**Comment by flodaniel** [comment]
I would not close this as completed, as this is not yet done by anyone.

**Comment by flodaniel** [comment]
I would not close this as completed, as this is not yet done by anyone.

**Comment by ChiragGajjar** [comment]
After upgrading latest version for flutter and dart and stream chat, I got this error


/Users/chiragsondagar/.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/Users/chiragsondagar/.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/Users/chiragsondagar/.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
/Users/chiragsondagar/.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use

**Comment by hiloliddinj** [comment]
same problem need solution

**Comment by hiloliddinj** [comment]
Solved by this[https://github.com/fluttercandies/flutter_photo_manager/issues/1021#issuecomment-1819994207](url) for now

**Comment by esarbanis** [comment]
We do not support Flutter 3.16 in our stable release yet because our `photo_manager` library dependency, does not have a stable release supporting it. You can switch to our beta release or wait until `photo_manager` releases 3.0.0 and we update it in our stable release.
