### ISSUE TITLE
Integrate communication notifications

### ISSUE THREAD

**Issue by bjurkovic-margins** [GetStream/stream-chat-flutter#1787]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS

### Is your feature request related to a problem?

Communication notifications are the new type of notifications released in the previous iOS version, and all chat apps have already integrated them.

https://developer.apple.com/documentation/usernotifications/implementing_communication_notifications

It's a little frustrating since notifications from our app look out of place with this new notification type.

### Describe the solution that you'd like

In my opinion, all chat notifications should be migrated to this new API.

### Describe alternatives that you have considered

Provide documentation on how to integrate this manually and connect it to GetStream?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bjurkovic-margins** [comment]
Anything new regarding this?

**Comment by IvanTrejoDev** [comment]
any word?
