### ISSUE TITLE
invite.exists returns more results than invite.pending + invite.accepted + invite.rejected

### ISSUE THREAD

**Issue by Jan-Stepien** [GetStream/stream-chat-flutter#1792]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat: ^6.6.0

### What happened?

when calling `await _chatClient.queryChannelsOnline(`

with
```dart
filter: stream.Filter.exists('invite'),
```
and 
```dart
filter:  stream.Filter.or(
    [
        stream.Filter.equal('invite', 'pending'),
        stream.Filter.equal('invite', 'accepted'),
        stream.Filter.equal('invite', 'rejected'),
    ],
)
```

returns different results - meaning there is more values to query for in terms of `invite` parameter ( not shown by the documentation)

### Steps to reproduce
1.
Call `await _chatClient.queryChannelsOnline(filter: stream.Filter.exists('invite'),)`

and 
```
await _chatClient.queryChannelsOnline(
    filter:  stream.Filter.or(
        [
             stream.Filter.equal('invite', 'pending'),
             stream.Filter.equal('invite', 'accepted'),
             stream.Filter.equal('invite', 'rejected'),
        ],
    ),
);
```

2. compare result sets

`filter: stream.Filter.exists('invite')`
returns more results than 
```
filter:  stream.Filter.or(
    [
        stream.Filter.equal('invite', 'pending'),
        stream.Filter.equal('invite', 'accepted'),
        stream.Filter.equal('invite', 'rejected'),
    ],
)
```
Which leads me into thinking that there are more statuses that are not exposed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jan-Stepien** [comment]
Whats the status on this one? Its `pending invite` implementation blocker issue

**Comment by esarbanis** [comment]
Hey @Jan-Stepien , looking into this, I am sorry for the delay.

**Comment by Jan-Stepien** [comment]
No worry @esarbanis is there any way i can help you or is it clear?

**Comment by deven98** [comment]
Hey @Jan-Stepien 👋 

After checking with the backend team, the `invite.exists` filter is not the appropriate filter to use for checking for all invite states. The second filter you used is the correct one in this scenario. Invites were not meant to be checked with the exists filter and the newer backend query parser throws an error when this is used. 

Hope this helps - closing this for now. Thanks!
