### ISSUE TITLE
Support sendMessageKeyPredicate on Mobile

### ISSUE THREAD

**Issue by crxm** [GetStream/stream-chat-flutter#1796]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

I have mobile users with external keyboards who would like to be able to submit messages using a key combination. (Specifically, CMD+Enter on iOS)

It looks like send message key handling was explicitly omitted from mobile in this commit: https://github.com/GetStream/stream-chat-flutter/pull/1222/commits/d3fff37fcdd7adcc1defb63eeeb1d48e422fedbb

### Describe the solution that you'd like

I would like to be able to set a sendMessageKeyPredicate and have it be enabled on all platforms. I believe that if omitting that behavior from mobile was desired it should be done when building the predicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
@crxm can you try out the branch from #1947 and let me know if it works? I don't have a way to test this at the moment.

**Comment by deven98** [comment]
We're testing and merging the probable fix - please feel free to open another issue if you find yourself facing this again. 

Thanks!
