### ISSUE TITLE
Add more control over actions is StreamMessageInput 

### ISSUE THREAD

**Issue by Mounix99** [GetStream/stream-chat-flutter#1797]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web

### Is your feature request related to a problem?

I have 2 more custom actions and I would like place all actions as a list above input but there is no such option now. Also I would like to customise style/icon for default actions to have them in same style as my custom 

### Describe the solution that you'd like

I would like to have some kind of builder for actions with will contain as parameter default actions to customise them and also have in  `ActionsLocation` additional value `top`

### Describe alternatives that you have considered

Alternatively will be nice to have at least external widget for default actions to manage them by my own, for example `AttachmentButton` could be exported from package

### Additional context

<img width="399" alt="Screenshot 2023-12-01 at 19 24 06" src="https://github.com/GetStream/stream-chat-flutter/assets/64007188/e281b55e-6a1c-4475-88f9-f97562987b80">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mounix99** [comment]
https://github.com/GetStream/stream-chat-flutter/pull/1822

**Comment by esarbanis** [comment]
landed with #1822
