### ISSUE TITLE
Keyboard opens on top of camera view

### ISSUE THREAD

**Issue by isaiahtaylor** [GetStream/stream-chat-flutter#18]
To recreate:

* tap in the text area of the message send box so that the keyboard comes up
* with the keyboard still up, tap the + button for an attachment
* select "photo from camera" or "video from camera"

The keyboard will come up over the camera view. There's no way to escape this without force quitting the app.

Maybe the + button needs to unfocus the text field?

**Comment by imtoori** [comment]
Pretty sure It's related to this issue https://github.com/flutter/flutter/issues/42417
Trying to find a workaround
