### ISSUE TITLE
StreamChatTheme is overriding app's ThemeData.colorScheme.secondary value

### ISSUE THREAD

**Issue by stevenholt** [GetStream/stream-chat-flutter#1801]
I recently included the StreamChatFlutter package into my project (I REALLY appreciate what you all have built for us!) and when I did, I immediately noticed that everywhere in my existing code where I was using `Theme.of(context).colorScheme.secondary` to style things had changed to a blue color (the beautiful "StreamChat blue")!

I filed that little note away in my head and pressed forward to update the `StreamChatThemeData.colorScheme` details to style all the Stream components to my liking and they all look great now!

But then I went around to the other parts of my app and realized all of my `...colorScheme.secondary` items were now using the color value I'd assigned to `StreamChatThemeData.colorScheme.accentPrimary` instead of what I'd defined my app's ThemeData.

So I poked around thru the StreamChat package to see what was going on and found where the Theme that wraps the returned StreamChat widget assigns a new value to the app Theme's `...colorScheme.secondary` attribute on Line 123 of ~lib/src/stream_chat.dart. (link to that line of the code)

https://github.com/GetStream/stream-chat-flutter/blob/f19f6a71904407ad4c2c1d2de2f9edf3fdd9ede5/packages/stream_chat_flutter/lib/src/stream_chat.dart#L123

I commented that line out locally and that fixed the color/styling of my "non-StreamChat" widgets that use the app's `Theme.of(context).colorScheme.secondary` and now I am able to use the color I've defined in `StreamChatThemeData.colorScheme.accentPrimary` to style the StreamChat widgets as expected.

Please consider either removing that line or conforming to the MaterialTheme standard a little more closely (using a Primary and Secondary color scheme for styling/accenting... also `accentPrimary` is deprecated in the MaterialTheme spec).

I want to reiterate how much I appreciate what the team has built for us!  Keep up the great work!

**Comment by MasterNeuromancer** [comment]
Is there a way to avoid having to use StreamChatThemeData. I find that it overrides my theme data as well, and it turned my floating action button from square to circle. Not sure if this was intended, I had set up themedata for my app quite nicely, see below, but now streamchatthemedata is overriding it.

**Comment by MasterNeuromancer** [comment]
``

**Comment by MasterNeuromancer** [comment]
`class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final GoRouter router = ref.watch(goRouterProvider);
    const MaterialTheme materialTheme = MaterialTheme();
    final client = StreamChatClient(
      Config.streamApi,
      logLevel: Level.INFO,
    );

    return MaterialApp.router(
      title: 'Example',
      debugShowCheckedModeBanner: false,
      theme: materialTheme.light(),
      darkTheme: materialTheme.dark(),
      routerConfig: router,
      builder: (context, child) {
        return StreamChat(
          streamChatThemeData: StreamChatThemeData.fromTheme(Theme.of(context)),
          client: client,
          child: child,
        );
      },
    );
  }
}`

**Comment by IvanTrejoDev** [comment]
I solved the problem above by using the following:

`return MaterialApp.router(
      title: 'Example',
      debugShowCheckedModeBanner: false,
      theme: materialTheme.lightHighContrast(),
      darkTheme: materialTheme.dark(),
      routerConfig: router,
      builder: (BuildContext context, Widget? child) {
        return StreamChat(
          client: client,
          useMaterial3: true,
          child: child,
        );
      },
    );`

**Comment by IvanTrejoDev** [comment]
the relevant line is useMaterial3: true,

**Comment by IvanTrejoDev** [comment]
Hope this helps others experiencing similar issues.

**Comment by deven98** [comment]
Hey @stevenholt 👋 ,

As @IvanTrejoDev mentioned, we have a `useMaterial3` flag in the `StreamChat` widget that you can set to true. However, we are currently working on fixing or removing the flag entirely because it was meant to be a temporary flag to transition a few things in the SDK.  

```dart
StreamChat( 
  client: client, 
  useMaterial3: true, 
  child: child, 
)
```

I am adding removing this flag to our backlog and you will likely see in it a new release. Closing this for now, please feel free to reopen if this still doesn't fix it for you.

**Comment by mlab817** [comment]
I think this should be mentioned in the docs.

**Comment by itsmeemaaario** [comment]
Can we please reopen this issue? The suggested solution is no longer available since useMaterial3 flag had been removed. The issue is still persistent, I find no way to put StreamChat at the very top of the widget tree and still not overriding my theme's colorScheme. And I cannot get StreamChat down through the subtree because it causes StreamChatTheme errors using overlays and modals.

Please help, I need to use this package and it's overriding my app's theme.
