### ISSUE TITLE
StreamAttachmentWidgetBuilder is not accessible in 7.0.0

### ISSUE THREAD

**Issue by crxm** [GetStream/stream-chat-flutter#1804]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

7.0.0

### What happened?

It looks like the customAttachmentBuilders parameter on StreamMessageWidget was replaced by attachmentBuilders in 7.0.0.

attachmentBuilders accepts a list of StreamAttachmentWidgetBuilder, but the StreamAttachmentWidgetBuilder is not exported with the package so I am unable to get the default list or update my previous builders to extend the new format.

I did not see this change mentioned in the change log, so I believe this may have been left out by mistake.

### Steps to reproduce

```bash
Update the package to 7.0.0.
Attempt to create a class extending StreamAttachmentWidgetBuilder.
IDE reports StreamAttachmentWidgetBuilder does not exist as it cannot find it in the package.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Oh wow, thank you @crxm for spotting this so quickly! PR is already open.
