### ISSUE TITLE
UnreadMessagesSeparator have no count of unread messages

### ISSUE THREAD

**Issue by Mounix99** [GetStream/stream-chat-flutter#1809]
### Which packages are you using?

stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

7.0.0

### What happened?

in widget `UnreadMessagesSeparator` count of unread is passed but not inserted in the `unreadMessagesSeparatorText` why? My users like to know that. 

### Steps to reproduce

```bash
1. Extend GlobalStreamChatLocalizations and look into UnreadMessagesSeparator
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @Mounix99 , thanks for opening this issue.

You can actually use `StreamMessageListView` class' `unreadMessagesSeparatorBuilder` option to show the `unreadCount` if it fits your use-case better. We removed it back in v4.1 as part of our redesign.
