### ISSUE TITLE
Status change doesn't update properly and sets user offline.

### ISSUE THREAD

**Issue by talksik** [GetStream/stream-chat-flutter#1810]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

Linux

### What version are you using?

6.9

### What happened?

An action button in the appbar tries to change a parameter of the local user within extraData and it does that successfully. However, for some reason, the updated user received on the stream listener has the updated property online set to false.

Sorry for the noise, I had to add Linux as a platform because that's my development machine. It should be enough to only focus on example/lib/main.dart as that's the only place I had changes.

[Associated PR](https://github.com/GetStream/stream-chat-flutter/pull/1772)

### Steps to reproduce

```bash
1. Go to associated PR linked above.
2. Run the app
3. Click the test button in the navbar.
4. _You will see the status of the user change to offline._
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by talksik** [comment]
Any update on this? Surprised that basic presence working is not a priority for the team.

**Comment by deven98** [comment]
Apologies for the delay, the fix was ridiculously difficult to spot. 

This should be rolled out in the upcoming release.

**Comment by talksik** [comment]
Hey @deven98 thanks for fixing, I have since stopped using stream but I will revisit this!
