### ISSUE TITLE
Can't upgrade to UUID v4

### ISSUE THREAD

**Issue by ghost** [GetStream/stream-chat-flutter#1811]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web, Windows, MacOS, Linux

### What version are you using?

8.0.0-beta.1

### What happened?

Can't upgrade to UUID v4, which is required by some of the newer packages with the fixes/featuers I need. Got an error when trying to upgrade from UUID v3 to v4 from Stream chat:

Because no versions of stream_chat_flutter match >8.0.0-beta.1 <9.0.0 and stream_chat_flutter 8.0.0-beta.1 depends on stream_chat_flutter_core ^8.0.0-beta.1, stream_chat_flutter ^8.0.0-beta.1 requires stream_chat_flutter_core ^8.0.0-beta.1.
And because no versions of stream_chat_flutter_core match >8.0.0-beta.1 <9.0.0 and stream_chat_flutter_core 8.0.0-beta.1 depends on stream_chat ^8.0.0-beta.1, stream_chat_flutter ^8.0.0-beta.1 requires stream_chat ^8.0.0-beta.1.
Because stream_chat 8.0.0-beta.1 depends on uuid ^3.0.7 and no versions of stream_chat match >8.0.0-beta.1 <9.0.0, stream_chat ^8.0.0-beta.1 requires uuid ^3.0.7.
Thus, stream_chat_flutter ^8.0.0-beta.1 requires uuid ^3.0.7.
So, because shift_flow depends on both stream_chat_flutter ^8.0.0-beta.1 and uuid ^4.2.1, version solving failed.

### Steps to reproduce

```bash
Change UUID v3 to v4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @pixnbit thank you for opening this.

Can you please post the outcome of `flutter pub deps` in your project?
