### ISSUE TITLE
queryChannelsOffline method watching the channels

### ISSUE THREAD

**Issue by senkia24** [GetStream/stream-chat-flutter#1814]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_localizations: ^5.11.0
  stream_chat_flutter_core: ^6.10.0
  stream_chat_persistence: ^6.9.0
  stream_chat_flutter: ^6.11.0

### What happened?

When using queryChannelsOffline method, it is watching the channels

### Steps to reproduce

```bash
1. client.queryChannelsOffline();
2. connect the ws, openConnection()
3. connectionStatusStream running
4.  client.dart line 468: _connectionStatusHandler method's queryChannelsOnline default state and watch is true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
When `queryChannelsOffline` is called it fetches cached data from the local database. If the channel state was persisted to the database with `watch: true` then that is what you will get back.

Now, as we state in our [docs](https://getstream.io/chat/docs/flutter-dart/watch_channel/?language=dart) when `watch: true` then the server will send [channel events](https://getstream.io/chat/docs/flutter-dart/event_object/?language=dart) to the open websocket.

So, if you are still getting those events (which I think is what they mean that the channels are watched), this means that at some point, they either have called queryChannels  or queryChannelsOnline leaving the parameter watch to its default value `true`.

Depending on what you want to achieve you should either call the `queryChannels`  or `queryChannelsOnline`  function with `watch: false` before calling `queryChannelsOffline`. Or call `channel.stopWatching()` (you must be connected to do that), as mentioned in our [documentation](https://getstream.io/chat/docs/flutter-dart/watch_channel/?language=dart#stop-watching-a-channel).
