### ISSUE TITLE
Reaction counter is not updating on web when reaction sent from mobile

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1815]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

Web

### What version are you using?

Latest 7.0.1

### What happened?

Reaction counter is not updating in web when reacted to message from mobile

### Steps to reproduce

```bash
User 1:
Go to web chat
Open a chat channel
React to a message

User 2:
Open mobile chat
Open the same chat channel and react to the same message

User 2:
Go back to web and hover over the message reactions
Note that the counter will display 1 reaction and when we hover over there will be 2 reactions displayed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @geweald, please let me know if this is still an issue.

Testing on my end updates the reactions on web on the latest version. Let me know if there are any other code changes I need to be aware of.

Thanks!

**Comment by deven98** [comment]
Closing this for now because I can't replicate the issue. Feel free to reopen this if at all required.
