### ISSUE TITLE
Notification in Background : Not Clickable

### ISSUE THREAD

**Issue by samuel2629** [GetStream/stream-chat-flutter#1833]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

6.8.1

### What happened?

When following the steps you're mentioned in order to integrate notifications, if we choose to use data-only mode (for android) when receiving the notification in the background, clicking on it just open the app but never triggers onMessageOpenedApp function. And that is caused by the fact that the data payload doesn't have a click_action tag in his payload.

So the only solution i came up with so far is to use template, but template trigger another issue for my use case, since i'm using the translate functionality, if i use a template, message will always appear to the receiver as they have been sent and not translated as they should.

So i have to choose between delivering the message formatted properly and not being clickable (not triggering onMessageOpenedApp) OR delivering the message not formatted properly but being able to click and trigger the onMessageOpenedApp ?

Thank you

### Steps to reproduce

```bash
1. Follow steps : https://getstream.io/chat/docs/sdk/flutter/guides/push-notifications/adding_push_notifications_v2/
2. Use without template and try to click on the notification (in background)
3. Use with template and try to format (translate) the message
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aminraeisi** [comment]
@samuel2629 did you find a solution to this? Similar issue is in iOS while you are online, you receive push notification even while chatting in the same channel.

**Comment by samuel2629** [comment]
Hi @aminraeisi,

We are not talking about the same issue, about my issue for anyone asking, i had the team and they admitted that is a scenario not considered so you'll have to choose.

About your case @aminraeisi the doc state that you have to check the channel and filter notification if channel is the current channel, i'm guessing you're using flutter_local_notifications, if so, basically you should check if the notification entering has the same channel id that the current channel and if so not display it.

**Comment by aminraeisi** [comment]
@samuel2629 thanks for the answer. We tried that way but some ios users do not get our background (silent) notifications at all. So we switched to the reminder webhook provided by stream which based on that we send a normal push notification to a user if they have an unread message for within 5 mins of the last time they had one.

**Comment by samuel2629** [comment]
Sorry i don't understand, even with the webhook, notification on the foreground both on Android and IOS are not displayed except if you're implementing a library like flutter_local_notification, no ?

**Comment by aminraeisi** [comment]
@samuel2629 yeah but the main issue we had was if we try the stream chat notification that sends a notification for each new message, on ios even while chatting you get the notification and if you use background notification, some users will not receive as Apple does not guarantee the delivery.

**Comment by anhdo9797** [comment]
same +1

**Comment by deven98** [comment]
Closing this for now. If this is still an issue, please feel free to file another issue with the relevant details and we can take a look at it. 

Thanks!
