### ISSUE TITLE
Deleting image message does not call delete the image from backend

### ISSUE THREAD

**Issue by KestasVenslauskas** [GetStream/stream-chat-flutter#1837]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

7.0.1

### What happened?

We implemented our own `AttachmentFileUploader`. But we find it strange that after deleting image/file message from chat it does not call `deleteImage`/`deleteFile` methods on AttachmentFileUploader.

### Steps to reproduce

```bash
1. Upload image.
2. Delete image.
3. Observe deleteImage function not called.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @KestasVenslauskas ,

Thank you for opening this, I just need to verify that our backend does not do it, before I test cover and merge [the fix](https://github.com/GetStream/stream-chat-flutter/pull/1842).

**Comment by esarbanis** [comment]
Moving on with the fix

**Comment by KestasVenslauskas** [comment]
@esarbanis is it possible to "hard" delete a message for a chat member?
