### ISSUE TITLE
Compatibility with flutter 3.19.0-pre

### ISSUE THREAD

**Issue by GJJ2019** [GetStream/stream-chat-flutter#1839]
### Please select which package this feature is related to

stream_chat_flutter, stream_chat_persistance

### Which platforms would this feature impact?

iOS, Android, Web

### Is your feature request related to a problem?

Not able to run with `3.13.19.0-0.1.pre`

```
../../../.pub-cache/hosted/pub.dev/stream_chat_flutter-8.0.0-beta.2/lib/src/bottom_sheets/stream_channel_info_bottom_sheet.dart:324:1: Error: Expected 0 type arguments.
PersistentBottomSheetController<T> showChannelInfoBottomSheet<T>({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/stream_chat_flutter-8.0.0-beta.2/lib/src/bottom_sheets/stream_channel_info_bottom_sheet.dart:339:5: Error: Expected 0 type arguments.
    showBottomSheet<T>(
    ^
../../../fvm/versions/3.19.0-0.1.pre/packages/flutter/lib/src/material/bottom_sheet.dart:1327:33: Context: Found this candidate, but the arguments don't match.
PersistentBottomSheetController showBottomSheet({
                                ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @GJJ2019 , we do not support flutter SDK's pre-releases, as they are unstable may cause breaking changes to our users.

**Comment by talkbiz** [comment]
@esarbanis it is stable now, yet i see same issue

**Comment by behnamsattar** [comment]
Same here! I'm using the stable 3.19.0 and experiencing the same issue.

**Comment by mauriziopinotti** [comment]
Please reopen the defect, it's valid and causing a headaches!
