### ISSUE TITLE
Add ability to mark a channel as unread

### ISSUE THREAD

**Issue by matteinn** [GetStream/stream-chat-flutter#1864]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

Web

### Is your feature request related to a problem?

It's currently possible to [mark a channel as read](https://github.com/GetStream/stream-chat-flutter/blob/2cf6d7fe53d51f92ddb78f777e5a9817e4d4644b/packages/stream_chat/lib/src/client/channel.dart#L1346), but not the opposite. It would be great to have feature parity with the other platform's SDKs:
- iOS SwiftUI currently offers that ability
- Android currently offers that ability (but there's a [bug](https://github.com/GetStream/stream-chat-android/issues/5143))
- Flutter is not offering that ability

### Additional context

The same issue has been reported in the Android repository: https://github.com/GetStream/stream-chat-android/issues/5032

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hey @matteinn thank you for opening this issue with us, this feature is already part of our Q1 target goal. We will try to deliver it by the end of the month

**Comment by matteinn** [comment]
Isn't it part of the Q1 roadmap anymore?
