### ISSUE TITLE
StreamMediaAttachmentThumbnail is still inaccessible in 7.1.0

### ISSUE THREAD

**Issue by crxm** [GetStream/stream-chat-flutter#1877]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

7.1.0

### What happened?

In version 7, MessageInputMediaAttachmentThumbnail was removed in favor of StreamMediaAttachmentThumbnail, but StreamMediaAttachmentThumbnail was never made accessible from outside of the package. This is needed to continue to support the default attachment types after an additional custom attachment type has been implemented.

This issue was reported in early December, but was erroneously closed as a duplicate of an unrelated issue: https://github.com/GetStream/stream-chat-flutter/issues/1808

Please fix this so we can support custom attachment types at the same time as the default attachment types.

### Steps to reproduce

```bash
1. Follow your own tutorial to add support for location sharing: https://getstream.io/chat/docs/sdk/flutter/stream_chat_flutter/custom_widgets/adding_custom_attachments/
2. Attempt to add an regular image as an attachment.
3. The thumbnail will not render.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by szechyjs** [comment]
Please re-open
