### ISSUE TITLE
Release 7.2.0 has wrong dependency restrictions for connectivity_plus

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#1889]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS

### What version are you using?

7.2.0

### What happened?

Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-7.2.0/lib/src/stream_chat_core.dart:127:45: Error: A value of type 'Stream<List<ConnectivityResult>>' can't be assigned to a variable of type 'Stream<ConnectivityResult>?'.

### Steps to reproduce

```bash
installing stream chat together with connectivity_plus: 6.0.1 results in a failing build because stream_chat allows for connectivity_plus 6, while not implementing its breaking changes.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hey, this breaking change got through the cracks as we did our regression testing but didn't clear the cache 🤦 . 

Thank you for spotting it so fast, you can use `v7.2.0-hotfix.1` which is resolved

**Comment by StevePDing** [comment]
Hello. I Have an issue. It's change version to v7.2.0-hotfix.1 is best solution now?

**Comment by andrewkimjoseph** [comment]
Does this hotfix work for anyone?

It doesn't work for me.

**Comment by IvanTrejoDev** [comment]
dependencies:
  connectivity_plus: '5.0.2'
  stream_chat_flutter: '7.2.0-hotfix.1'

This seems to work for me. Hoping we get a new release soon.

**Comment by esarbanis** [comment]
Hi everyone, again sorry for the inconvenience, as the `connectivity_plus` update comes with breaking changes it will be included in the upcoming beta release.
