### ISSUE TITLE
Long-press reaction triggers web context menu on mobile

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1908]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

Latest

### What happened?

When long-pressing reaction on mobile, the web context menu appears. This should trigger the mobile menu or maybe better not trigger anything at all. 

Plus to context menu is sometimes scrollable even if there is enough space on the screen (unless it must have top corner in the place of tap). And the context uses root navigator, which is not ideal if we want to embeed the chat deeper in the app (then we still need to provide stream configuration at the very top of the whole app)

### Steps to reproduce

```bash
1. Open chat
2. Add reaction to a message
3. Long press the reaction
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @geweald,

The context menu is managed by the third party library [`contextmenu`](https://pub.dev/packages/contextmenu) you are right that this library does use the root navigator and does not provide any size control as well.

As this is part of a larger refactor on our reaction menus, currently on our backlog, I am going to close this, but will address it with the new menus.
