### ISSUE TITLE
Unread flag gets reset after refreshing the channels 

### ISSUE THREAD

**Issue by gadzhov** [GetStream/stream-chat-flutter#1919]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android, Web

### What version are you using?

stream_chat_flutter  - 7.2.0

### What happened?

1. When a distinct channel is created (without providing an id), unread flag is getting reset after doing channels refresh.

https://github.com/GetStream/stream-chat-flutter/assets/18680832/bd2f2cea-6298-4e38-a58e-c127c7fdf722

2. When listening for an **unreadChannelsStream**, the event emits 0 for distinct channels even there are unread messages.
`StreamChat.of(context).client.state.unreadChannelsStream.listen((event) {
      print(event); // 0
});`

Both issues don't happen with not distinct channels.
**Update:** I have found that the issues only happens on recreated distinct channels.

### Steps to reproduce

```bash
1. Create a distinct channel
2. Send a message
4. Use the other user
5. Channel should have an unread flag
6. Pull down to refresh
7. Unread flag is gone
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @gadzhov,

For some reason, I can't replicate this. Can you elaborate on what you mean by "recreated distinct channels"?

Thanks!

**Comment by gadzhov** [comment]
Hey @deven98,
You need to delete a channel, and to create it again, then the issue occur.
