### ISSUE TITLE
[HELP] How to handle decryption of messages before displaying them on the chat view or notification ?

### ISSUE THREAD

**Issue by sabin26** [GetStream/stream-chat-flutter#192]
I have encryption and decryption feature on my application. So, I need to decrypt the message before showing it on notification or chat view. I did not find any example on how to handle them.
Is there a way I can call a function (where I decrypt the messages) before saving it on the device?

gz#8430

**Comment by SeniYG** [comment]
Hi,

Stream does not provide any built-in solution for message encryption/decryption.
Virgil is probably one of the better options for integrating E2E encryption with Stream. Your other good option would be tanker.io. 

Here's a blog post on using Virgil with Stream React SDK
https://getstream.io/blog/building-an-end-to-end-encrypted-chatbot-with-stream-react-chat-virgil-security-and-google-dialogflow/
Unfortunately, we do not have the same article for Flutter SDK yet, however, the logic will be the same. As you will read in this article, you will have to create your own MessageInput and Message custom widgets to integrate your encryption/decryption solution.

Best regards,

**Comment by sabin26** [comment]
I have my own implementation of encryption and decryption. I just want to know if I can call a function to process the message before displaying it to user via notification or in chat.

**Comment by sabin26** [comment]
Adding custom widget is a good way but I believe the app will decrypt the message each time to display on chat. If stream chat saves the message on local db of user's device, can't I just decrypt and then save it ? In doing so, will the decrypted message be exposed to stream backend ?

**Comment by imtoori** [comment]
The sdk saves the messages as they come from the backend. You can decrypt them before showing them using a custom widget.
I understand your request, but I think this is the easiest way to do it
