### ISSUE TITLE
Null check operator used on a null value - wrong use of markdown

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1926]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web, Windows, MacOS, Linux

### What version are you using?

Latest

### What happened?

When you are on web and click on a message text or start selecting text you get spam of `Null check operator used on a null value` errors in the browser console
Sometimes the text selection misbehave because of that too

### Steps to reproduce

```bash
1. Open chat on web
2. Open dev tools console
3. Try to select text in the message bubble
```

### Supporting info to reproduce

This is an issue with use `MarkdownBody` inside `stream_chat_flutter/lib/src/message_widget/message_text.dart`

The `flutter_markdown` docs has this sections:
![image](https://github.com/GetStream/stream-chat-flutter/assets/16155640/939d5894-3e86-4dd7-b8e7-a23b32a5009d)

Yet `StreamMessageText` sets `selectable` to `true` for web and desktop, but the `onTapText` and `onSelectionChanged` are never set, which causes the error to be thrown.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @geweald 

We are using [flutter_markdown 0.6.17+1,](https://github.com/flutter/packages/tree/flutter_markdown-v0.6.17%2B1/packages/flutter_markdown) in this version's documentation there is no `Selection` section. Furthermore, I cannot reproduce this error in our `example` project. Have you overridden this dependency in your project?

Also the `selectable` field is used to create a [`SelectableText.rich`](https://github.com/flutter/packages/blob/flutter_markdown-v0.6.17%2B1/packages/flutter_markdown/lib/src/builder.dart#L844) which has [`onTap`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/selectable_text.dart#L481) and [`onSelectionChanged`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/selectable_text.dart#L496) optional, so I am not really sure how this could produce a `Null check operator used on a null value` error.

**Comment by deven98** [comment]
Hi @geweald 👋 

Thanks for bringing this to our attention. I've launched a PR that should fix this. 

Feel free to reopen this if the error reoccurs. Thanks!
