### ISSUE TITLE
8.0.0-beta.3 Bug: Messages not marked as unread when viewed.

### ISSUE THREAD

**Issue by mingjunsiek** [GetStream/stream-chat-flutter#1928]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter 8.0.0-beta.3

### What happened?

In the latest beta version, there seems to be an issue with marking messages as read behaviour inside the message list view.
I noticed that the UI has changed to this "badge" at the top of the list view which tells us how many unread messages they have with the cross button. But even when we scrolled down and viewed those messages, that "badge" stills shows. Navigating back to the channel list also shows us that the messages, although viewed, was not marked as read at all.

https://github.com/GetStream/stream-chat-flutter/assets/13094556/2c117f45-8379-4917-92f6-7753b0c90ed6

### Steps to reproduce

```bash
1. Have unread messages in the channel.
2. Scroll to the latest message.
3. Notice that the unread badge is still there.
4. Navigating back to the channel list also shows the unread indicator even though we already viewed the message.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mingjunsiek** [comment]
https://github.com/GetStream/stream-chat-flutter/assets/13094556/87e3dd05-04c0-466f-ba4b-6960579f98a8

Okay, I was able to get the mark as read working after looking into the code. But now there is this UI issue where if there are alot of unread messages, tapping the scroll to bottom button will jump to the bottom of the list view before doing an animated scroll to the first unread message? Can't we just do an animated scroll to the first unread instead?

**Comment by AndreHaueisen** [comment]
The issue persists in v8.0.0

**Comment by mohsin-notify** [comment]
Facing the same issue.

**Comment by Jonny1987** [comment]
Same issue in v9.70 too..please fix
