### ISSUE TITLE
Copy message with mention has id instead of name

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1929]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web, Windows, MacOS, Linux

### What version are you using?

Latest

### What happened?

When you long-press the message that contains mentioned user (eg. `@Adam`), select `Copy Message` and copy the message, when you paste instead of @Adam you will see the @ with id of the user.

### Steps to reproduce

```bash
1. Go to Chat
2. Mention user and send the message with the mention
3. Long press on the message with the mention
4. Select `Copy Message`
5. Paste the message
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Nice catch, thanks for the issue. This should be fixed with #1945 and will be out in the next release.
