### ISSUE TITLE
UI bug regarding new messages on StreamMessageListView

### ISSUE THREAD

**Issue by mmijalic-margins** [GetStream/stream-chat-flutter#1940]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat: ^7.2.1
  stream_chat_flutter: ^7.2.1
  stream_chat_flutter_core: ^7.2.1

### What happened?

There is a visual bug regarding Colors.transparent or null for backgroundColor on StreamMessageListViewThemeData. 
The issues is not visible on normal messaging but is only visible when new messages arrived, visual proof below.

### Steps to reproduce

```bash
1. Have two users in a channel
2. One user messages the other
3. The second user receives the message
4. New message is received and UI changes
```

### Supporting info to reproduce

 StreamMessageListViewTheme(
              data: const StreamMessageListViewThemeData(
                backgroundColor: null,
              ),
child....

<img width="320" alt="Screenshot 2024-06-11 at 09 10 11" src="https://github.com/GetStream/stream-chat-flutter/assets/139563774/4077b979-058d-4bab-a9bb-ebf4b473712f">
<img width="307" alt="Screenshot 2024-06-11 at 09 10 38" src="https://github.com/GetStream/stream-chat-flutter/assets/139563774/552674a5-b211-408c-a0c4-35ea968d8f90">

### Flutter doctor output

```shell
[!] Flutter (Channel stable, 3.19.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-HR)
    • Flutter version 3.19.2 on channel stable at /Users/marinmijalic/fvm/versions/3.19.2
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart-sdk/3.2.4/libexec/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/marinmijalic/fvm/versions/3.19.2. Consider adding /Users/marinmijalic/fvm/versions/3.19.2/bin to
      the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (3 months ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform
      update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/marinmijalic/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.69.1)
    • VS Code at /Users/marinmijalic/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • SM A536B (mobile)  • RZCT70D3B6K                          • android-arm64  • Android 14 (API 34)
    • Marin new (mobile) • F463815F-6875-446C-A6E4-DBCD9EB3ABF4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 125.0.6422.142
    ! Error: Browsing on the local area network for Valere’s iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @mmijalic-margins 👋 , can you please provide a small code sample to allow me to reproduce this? The `backgroundColor` you mention in the issue has a default property of null so I'm not fully sure how you're getting there. 

Thanks.

**Comment by justinfriberg** [comment]
We see this issue as well.  For us, setting the StreamMessageListViewThemeData backgroundColor to transparent allows the image behind the chat to be shown.  However, when a new message is received, we see an opaque color similar to the one shown in the screenshot reported above.

**Comment by deven98** [comment]
Hey folks, after trying this out a bit, I can't seem to replicate this with the latest Stream version.

I tried a Stack with a coloured widget beneath the `StreamMessageListView` and I seem to see it just fine along with the new message indicator. 

If this is still an issue, please attach a minimal code example that I can reproduce this with and I can take a look again.

<img width="244" alt="Screenshot 2024-09-03 at 1 29 56 PM" src="https://github.com/user-attachments/assets/9d4fb085-57bc-48d9-ad98-e33fd6f9c3dc">

**Comment by justinfriberg** [comment]
I tried to update the sample flutter sdk app (using step 6), but can't seem to get the background color to be transparent and I'm not sure why.  

In our app at least, we're using an SVG as the background throughout the app, which is why we're not using the backgroundImage in StreamMessageListViewThemeData.

Here's our background class that wraps the StreamChannel (which wraps the StreamMessageListView and StreamMessageInput):
```
class PageBackground extends StatelessWidget {
  const PageBackground({
    required this.child,
    super.key,
  });

  final Widget child;

  @override
  Widget build(BuildContext context) => Stack(
        fit: StackFit.expand,
        children: [
          SvgPicture.asset(
            'assets/background.svg',
            colorFilter: ColorFilter.mode(Theme.of(context).primaryColor.withAlpha(128), BlendMode.srcIn),
            fit: BoxFit.cover,
          ),
          child,
        ],
      );
}
```
