### ISSUE TITLE
Enabling push notification

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-flutter#195]
We recently enabled the push notification for the Stream Flutter SDK. There're different options, the easiest is relying on FCM for both iOS and Android, and let the FCM framework handling the iOS APNS:

- Setting up FCM would just be from the official Firebase FCM tutorial/walkthrough.
- In Flutter code, we would just provide the FCM token to the Stream client.
- In the Stream web portal, we would only need to provide FCM certificate and push template. 

There's no write up about how to enable push on the Stream website. Alternatively, you can differentiate the platform type and pass APNS tokens directly. It kinda defeats the purpose of Flutter. Hope this helpful to whoever is looking into this.

gz#8453

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8453'>Zendesk ticket #8453</a>:<br><br>Hi,

Thank you for providing this information. I will reach out to our team internally and get back to you.

Best,
Ryan

**Comment by imtoori** [comment]
At the moment you can use firebase only on android and apns on iOS.
You could also use a webhook to generate your own notifications so that you can use fcm for both platforms.
The best way at the moment I think it is to use this flutter package https://pub.dev/packages/flutter_apns

By the way we're working on a new version of our notification service that enables the possibility to use firebase on both android and iOS

**Comment by alpfactory-alex** [comment]
When would this new notification service be available? And we could use only firebase then for both systems on flutter apps?

**Comment by pixnbit** [comment]
> At the moment you can use firebase only on android and apns on iOS.
> You could also use a webhook to generate your own notifications so that you can use fcm for both platforms.
> The best way at the moment I think it is to use this flutter package https://pub.dev/packages/flutter_apns
> 
> By the way we're working on a new version of our notification service that enables the possibility to use firebase on both android and iOS

This is actually contrary to what I saw, FCM works on iOS too (with the FCM/APNs setup for Flutter), unless I miss something..

**Comment by imtoori** [comment]
@pixnbit are you using the package flutter_apns?

**Comment by pixnbit** [comment]
No I did not use flutter_apns, I used Flutter firebase messaging plugin: https://firebase.flutter.dev/docs/messaging/apple-integration

**Comment by shodgetts** [comment]
Hello, are you still having trouble here?

**Comment by imtoori** [comment]
I can confirm firebase_messaging is enough to set up push notifications
just have to keep in mind that you have to configure only android in Stream dashboard and always use `PushProvider.firebase` in the `client.addDevice` call

it's kind of a workaround, but it works well

I'm writing the docs, I'll update this issue once it's done

**Comment by imtoori** [comment]
here you can find the docs https://getstream.io/chat/docs/flutter-dart/flutter_push/?language=dart
feel free to reopen the issue for any problem
