### ISSUE TITLE
Copy Message is not working

### ISSUE THREAD

**Issue by Muthukumar0001** [GetStream/stream-chat-flutter#1972]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

7.2.2

### What happened?

I am not able to Copy the text messages. I checked the code. I think the code logic is wrong. It is only working when we have user mentions in message.
![image](https://github.com/GetStream/stream-chat-flutter/assets/104615488/d72d6031-fa87-4e0a-934e-1a9ae3d59b17)

### Steps to reproduce

```bash
1. Go to Channel Page
2. Send text message
3. try to copy the message
4. Issue - Message not added to clipboard
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @Muthukumar0001, thanks for the catch! The fix PR is up and should be merged and released soon.
