### ISSUE TITLE
User Avatar Not Showing

### ISSUE THREAD

**Issue by tjbaba** [GetStream/stream-chat-flutter#1985]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

7.3.0
latest

### What happened?

I am using the code provided in the examples on how to create a channel list view. 
everything is good but I am not able to see the user's avatar, it is always the initials of his name. 

here is the code I am using for the list. 

`child: StreamChannelListView(
                  controller: _listController,
                  // itemBuilder: _channelTileBuilder,
                  onChannelTap: (channel) {
                    Navigator.push(context,
                        MaterialPageRoute(builder: (context) {
                      return StreamChannel(
                        channel: channel,
                        child: const ChatScreen(),
                      );
                    }));
                  },
                ),`
                
in users db in get stream I can clearly see users avatar 

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @tjbaba 👋,

We fall back to the user's initials when the user image is not set. 
Can you verify you correctly set the user or channel image?

Thanks.

**Comment by tjbaba** [comment]
Thanks For the reply, i was able to resolve the issue myself, Thanks
