### ISSUE TITLE
Slide to reply

### ISSUE THREAD

**Issue by guplem** [GetStream/stream-chat-flutter#1986]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Our users have expressed frustration when they try to reply (quote) a message by sliding to the right. They do not expect needing to hold the message to select it and then tap "reply".

### Describe the solution that you'd like

You should be able to slide right any message to automatically select it as "quoted message" and be able to reply it.

### Describe alternatives that you have considered

Using the `flutter_slidable` package.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @guplem 👋 

This functionality is possible using the `Swipeable` class in the SDK. 

For a full implementation, you can check out [our example code](https://github.com/GetStream/stream-chat-flutter/blob/6363c4f9f7e704279ef289ccd6049629b432944b/packages/stream_chat_flutter/example/lib/main.dart#L304) which has it implemented.

Thanks!
