### ISSUE TITLE
Messages that are sent from different users at almost the same time appears in incorrect order

### ISSUE THREAD

**Issue by utopicnarwhal** [GetStream/stream-chat-flutter#1987]
### Which packages are you using?

stream_chat_flutter, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Web

### What version are you using?

  stream_chat_flutter:
    dependency: "direct main"
    description:
      name: stream_chat_flutter
      sha256: "0286ef445645d7f6af74bdc2a5dd7664269336dd1d0f4b1d2b84c58aab8cbf77"
      url: "https://pub.dev"
    source: hosted
    version: "6.12.0"
  stream_chat_localizations:
    dependency: "direct main"
    description:
      name: stream_chat_localizations
      sha256: "518bc171b3621b17d60a816f42132cb3b1f4fe72975137dd2506470f7f183d23"
      url: "https://pub.dev"
    source: hosted
    version: "5.12.0"

### What happened?

https://github.com/user-attachments/assets/0740465a-9199-4fe1-aee2-cce87c1386d7

The messages are in different order for both of users. I expected to have the same message order for both of them.

### Steps to reproduce

```bash
1. Run [the official sample app](https://github.com/GetStream/flutter-samples/tree/016d7ae4eff22e61cbad97c957d62b7164db2048/packages/stream_chat_v1) on two devices.  
2. Select different users on different devices.  
3. Open chat with each other.  
4. Type the different messages to the fields.
5. Try to send the messages at the same time.
```

### Supporting info to reproduce

I reproduced it also with the latest Flutter and package versions as well. For the example video I've used Flutter v3.10.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utopicnarwhal** [comment]
.

**Comment by utopicnarwhal** [comment]
bump

**Comment by utopicnarwhal** [comment]
bump

**Comment by dvmatyun** [comment]
I experienced and reported this issue with incorrect messages order in stream chat for like over a year now, how hard can that be for a multi-million company to fix it's core functionality lol?

**Comment by FrogMustang** [comment]
Also not stale.... still happening

**Comment by utopicnarwhal** [comment]
bump

**Comment by xsahil03x** [comment]
This isn't really an error but the expected behaviour. We always sort the messages by the local `createdAt` time and for both of the devices their own message createdAt is earlier then the one received from the server. This was done to maintain the order while sending multiple messages in a short duration.

More info can be found in the issue and PR below.

Issue: https://github.com/GetStream/stream-chat-flutter/issues/1293 PR: https://github.com/GetStream/stream-chat-flutter/pull/1616
