### ISSUE TITLE
Application crashes when the user pastes text

### ISSUE THREAD

**Issue by Leloo** [GetStream/stream-chat-flutter#1993]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

7.2.0

### What happened?

There are two different behaviors.
It's not possible to paste a message with more than 5000 characters (expected behavior), however, if the user starts typing a message and does copy/paste with an existing one and creates more than 5000 characters, the chat will freeze and crash.

https://github.com/user-attachments/assets/69368c24-ea7c-49d0-a2d7-9fe874264b4b

### Steps to reproduce

```bash
1. Start typing characters
2. Copy/paste
3. Repeat typing -> copy/paste
4. Observe
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @Leloo, thanks for reporting this. While we often check for large text sizes in the `TextField`, we have not yet checked for a >5000 character message size. We might need some time to resolve this issue due to other ongoing tasks but I will let you know when we have more updates.

Thanks!
