### ISSUE TITLE
Bump share_plus to 10.0.0

### ISSUE THREAD

**Issue by guplem** [GetStream/stream-chat-flutter#1996]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

8.0.0

### What happened?

I'm experiencing a dependency conflict in my Flutter project. The conflict arises due to the following dependencies:

- stream_chat_flutter >=8.0.0 depends on share_plus ^8.0.3.
- My project requires geolocator ^13.0.1, which depends on geolocator_web ^4.1.1 (requires web ^1.0.0).

Since share_plus ^8.0.3 depends on web ^0.5.0, this creates an incompatibility with geolocator ^13.0.1. I need to use geolocator 13 for my project.

Please update `stream_chat_flutter` to be compatible with newer versions of `share_plus` or remove the dependency on `share_plus`.

### Steps to reproduce

```bash
1. Add `stream_chat_flutter` ^8.0.0 to `pubspec.yaml`.
2. Add `geolocator` ^13.0.1 to `pubspec.yaml`.
3. Run `flutter pub get`.
```

**Comment by deven98** [comment]
Hi @guplem, we have to take into account all use cases and make the decision to upgrade dependencies based on various factors as well as how many people we think the change would affect. We will do a check on how soon we can upgrade this but for now I suggest you try to use a dependency override or downgrade the geolocator plugin. 

Thanks.
