### ISSUE TITLE
useMaterial3 is no longer supported

### ISSUE THREAD

**Issue by guplem** [GetStream/stream-chat-flutter#1997]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

8.0.0

### What happened?

[The documentation](https://getstream.io/chat/docs/sdk/flutter/stream_chat_flutter/stream_chat_and_theming/#a-note-on-material-3) allows the use of material3.
However, in version 8.0.0 is not existent and the 

### Steps to reproduce

1. Create a new app integrating StreamChat like this:
```dart
StreamChat(
  client: client,
  useMaterial3: true,
  child: child,
)
```
2. App won't compile since useMaterial3 does not exist

**Comment by deven98** [comment]
Hi @guplem, from v8 going forward, Material3 will be the default theme and we are no longer overriding the theme on our end. You can still use the `Theme`  from Flutter to make any changes yourself. 

We are in the process of updating the docs in this regard. Find more [here](https://github.com/GetStream/stream-chat-flutter/blob/master/docusaurus/docs/Flutter/05-guides/08-migrations/migration_guide_8_0.mdx).
