### ISSUE TITLE
Update GPA 8 for android module

### ISSUE THREAD

**Issue by cogivn** [GetStream/stream-chat-flutter#1999]
### Please select which package this feature is related to

stream_chat_flutter, stream_chat_flutter_core

### Which platforms would this feature impact?

Android

### Is your feature request related to a problem?

The packages cannot build with GPA8 on android module.

### Describe the solution that you'd like

Upgrade the packages will support the GPA8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dzab5** [comment]
This issue is because of the[ image_galelry_saver package](https://github.com/hui-z/image_gallery_saver/pull/295). It seems that package is dead, and the [stream_chat_flutter] (https://pub.dev/packages/stream_chat_flutter) uses it as a dependency.

This should be critically urgent, as the android applications cannot be built or distributed.

**Comment by Rioland** [comment]
they should make use of latest dependency

**Comment by AndreHaueisen** [comment]
> This issue is because of the [ image_gallery_saver package](https://github.com/hui-z/image_gallery_saver/pull/295). It seems that package is dead, and the [stream_chat_flutter](https://pub.dev/packages/stream_chat_flutter) uses it as a dependency.
> 
> This should be critically urgent, as the android applications cannot be built or distributed.

There is an [image_gallery_saver_plus](https://pub.dev/packages/image_gallery_saver_plus) replacement they can use

**Comment by deven98** [comment]
The new version for the packages upgrades to image_gallery_saver_plus instead and should solve this issue. Feel free to let us know if something is still missing to solve this issue.

Thanks!

**Comment by cogivn** [comment]
Hi @deven98,

Can you consider to migrate the `video_thumbnail` in stream_chat_flutter_core`?
The GPA8 still cannot to use with latest version.

Thank you,
