### ISSUE TITLE
Upgrade mime package to 2.x

### ISSUE THREAD

**Issue by mauriziopinotti** [GetStream/stream-chat-flutter#2069]
### Which packages are you using?

stream_chat_flutter, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

  stream_chat_flutter: ^8.3.0
  stream_chat_localizations: ^8.3.0

### What happened?

Because stream_chat_flutter >=8.3.0 depends on stream_chat_flutter_core ^8.3.0 which depends on stream_chat ^8.3.0, stream_chat_flutter >=8.3.0 requires stream_chat ^8.3.0.
And because stream_chat >=8.0.0 depends on mime ^1.0.5, stream_chat_flutter >=8.3.0 requires mime ^1.0.5.
So, because easyhour_app depends on both mime ^2.0.0 and stream_chat_flutter ^8.3.0, version solving failed.

### Steps to reproduce

```bash
1. Create a new project and add `stream_chat_flutter: ^8.3.0` and `mime: ^2.0.0` as dependencies
2. Tr to build the project
```

### Supporting info to reproduce

Upgrading to mime 2.x should pretty straightforward, see https://pub.dev/packages/mime/changelog
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Should be fixed in #2068
