### ISSUE TITLE
Videos show wide stretched

### ISSUE THREAD

**Issue by isaiahtaylor** [GetStream/stream-chat-flutter#21]
Videos, whether uploaded or taken, show as stretched horizontally.  See attached photos:

1. Screenshot from the original video taken on the iPhone 11 Max
![IMG_3840](https://user-images.githubusercontent.com/57509275/78944725-6571b580-7a73-11ea-9884-1fb74de3e20b.PNG)

2. How it looks in chat when played fullscreen
![IMG_3839](https://user-images.githubusercontent.com/57509275/78944769-820ded80-7a73-11ea-8422-21165e491874.PNG)

3. How it looks in chat inline
![IMG_3841](https://user-images.githubusercontent.com/57509275/78944738-6acf0000-7a73-11ea-88aa-0037a5bc7966.jpg)

**Comment by imtoori** [comment]
The property `showVideoFullScreen` was added mainly because of this issue https://github.com/brianegan/chewie/issues/261
