### ISSUE TITLE
Only one user can give a particular reaction

### ISSUE THREAD

**Issue by jamesbgl** [GetStream/stream-chat-flutter#216]
Once a reaction has been made by a user, no other user can add the same reaction. I believe this is not the intended behaviour.

https://github.com/GetStream/stream-chat-flutter/blob/05fd5858f46531fa53e10899b8816b6015250b90/lib/src/reaction_picker.dart#L34

gz#8677

**Comment by imtoori** [comment]
hey @jamesbgl it was a matter of visualization
I think now it's good
btw, we are working on a new version of the UI sdk that will be released soon and I think will solve these kind of small issues.

And thanks for reporting the issue :)
