### ISSUE TITLE
Need a way to disable the attachments button

### ISSUE THREAD

**Issue by isaiahtaylor** [GetStream/stream-chat-flutter#23]
Given the instability of the attachments feature, there should be a way to not show that attachments button.

**Comment by imtoori** [comment]
@isaiahtaylor 

I just created the repo Gitter for general discussions about the sdk
In case you'd like to join here's the link 

https://gitter.im/GetStream/stream-chat-flutter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge#
