### ISSUE TITLE
Example not executable due to missing file

### ISSUE THREAD

**Issue by cliffofdeath** [GetStream/stream-chat-flutter#234]
The sample app can't be executed due to missing the google-services.json file.

Output:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/beni/projects/stream-chat-flutter/example/android/app/src/nullnull/google-services.json
  /Users/beni/projects/stream-chat-flutter/example/android/app/src/debug/google-services.json
  /Users/beni/projects/stream-chat-flutter/example/android/app/src/nullnullDebug/google-services.json
  /Users/beni/projects/stream-chat-flutter/example/android/app/src/nullnull/debug/google-services.json
  /Users/beni/projects/stream-chat-flutter/example/android/app/src/debug/nullnull/google-services.json
  /Users/beni/projects/stream-chat-flutter/example/android/app/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1

gz#8867

**Comment by imtoori** [comment]
Hi @cliffofdeath 
you should put a custom google-services.json or just run one of the other example using 
`flutter run -t lib/multiple_conversation.dart` for example

**Comment by cliffofdeath** [comment]
Hi @imtoori 
Thanks for your quick reply.
But the other examples neither work, sample problem. I don't see why I need the google-services.json. Should I connect the app to a firebase project?

**Comment by imtoori** [comment]
Yeah, that's weird.
We added Firebase because we have push notifications in the sample app.
I can suggest going through the tutorial if you want to test the package. https://getstream.io/chat/flutter/tutorial/

Thanks for reporting the issue though, we'll see if there is a way to make it optional or probably we need to create a completely different sample project.

**Comment by imtoori** [comment]
closing this because we updated the example with a more minimal one that can run without the service.json
