### ISSUE TITLE
How to config push notification?

### ISSUE THREAD

**Issue by natchoz** [GetStream/stream-chat-flutter#247]
Hi,

Currently, I'm doing push notification on Android and I follow the example but I cannot make it work. I cannot get any messages from other user via push message (app in the background and set token in GetStream dashboard already). 

It works and I can get push message when sending with firebase command line `DATA='{"notification": {"body": "this is a body","title": "this is a title"}, "priority": "high", "data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done"}, "to": "<FCM TOKEN>"}'
curl https://fcm.googleapis.com/fcm/send -H "Content-Type:application/json" -X POST -d "$DATA" -H "Authorization: key=<FCM SERVER KEY>"` but I cannot get any chat messages.

It seems `showLocalNotification` in `client` will show notification from event messages but not from push messages.

Please advice.
Thank you.

gz#9004

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/9004'>Zendesk ticket #9004</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and get back to you soon.

Cheers
Stream Team

**Comment by natchoz** [comment]
I can make push notification woking on Android but not tested on iOS yet so I will close this issue first.

FYI,
I'm using 
- `flutter_apns`
- Save registered token in preference and call `addDevice` after `setUser`
- Add `<action android:name="FLUTTER_NOTIFICATION_CLICK" />` in `AndroidManifest.xml`and also add `FLUTTER_NOTIFICATION_CLICK` in GetStrem's dashboard so when getting push notification and click on it then we will get callback `onResume` when app is in background
