### ISSUE TITLE
StreamChatClient _connectCompleter should set back to null after disconnect

### ISSUE THREAD

**Issue by Goxiaoy** [GetStream/stream-chat-flutter#258]
**Describe the bug**
My app support user login and logout. 
When use the same global `StreamChatClient `, `setUser` or `setAnonymousUser` can not be called after disconnect

**To Reproduce**
```
await chatClient.setAnonymousUser();
...
await chatClient.disconnect(clearUser: true);
...
await chatClient.setUser( ... );
```

**Expected behavior**
new user be set

**Additional context**
```
 Exception: Already connecting
```

gz#9161

**Comment by xsahil03x** [comment]
Can you please mention the pubspec version of `stream_chat`.

**Comment by Goxiaoy** [comment]
I am using the latest beta version
```
  stream_chat_flutter: ^1.0.0-beta
  stream_chat_persistence: ^1.0.0-beta
```

**Comment by xsahil03x** [comment]
Thanks @Goxiaoy, we will try to replicate this and inform you of any update.

**Comment by xsahil03x** [comment]
Hey @Goxiaoy, I tried to reproduce it but it worked fine on my end. Can you share a reproducible code for further investigation? Also, try to upgrade to the latest version and check If it is still failing.

**Comment by Goxiaoy** [comment]
Oh I see
The following code will reproduce in lateset version or master.
```
chatClient.setAnonymousUser(); //do not wait
await chatClient.disconnect(clearUser: true);
await chatClient.setUser( ... );
```
Because the disconnect does not check `_connectCompleter`

**Comment by xsahil03x** [comment]
Thanks @Goxiaoy, that's a valid check while `disconnecting` the client. But ideally, you should always await the `setUser()` functions.
