### ISSUE TITLE
Support for Stream<List<User>>

### ISSUE THREAD

**Issue by KingIdee** [GetStream/stream-chat-flutter#26]
Just like we have a stream for list of channels: `Stream<List<Channel>>` Will it be possible to have a stream of users like this: `Stream<List<User>>`.  So, we can always have an updated list of users.

**Comment by imtoori** [comment]
Do you need to do something in particular?
I'm just asking to understand if there is already a way to do it

**Comment by KingIdee** [comment]
Nothing in particular. Just a list that'll be updated when the WebSocket(Stream's API) notifies that a new user is available.

**Comment by imtoori** [comment]
hey @KingIdee in the last alpha version you can find a list of users in `client.state.users` or a stream of the list in `client.state.usersStream`

**Comment by KingIdee** [comment]
Neat!

**Comment by imtoori** [comment]
the new stable version has this feature now :)
