### ISSUE TITLE
MessageListView pagination problem

### ISSUE THREAD

**Issue by luantrasel** [GetStream/stream-chat-flutter#260]
**Describe the bug**
I was trying to test the app performance, so to do that I configured the example app from this repo. Then I send 1 message to another user I also created and after that I created a button to send 150 messages one after the other (with 1 second of delay between them). Everything seemed to be ok, until I closed the app, opened it again on this same channel and scrolled up. When I did that I noticed that the pagination skipped from Message # 49 to Message # 126

It happened on the device that send these messages and also on the device that received these messages

**To Reproduce**
1. Create a new channel
2. Send 150 messages one after the other (with 1 second delay) indetifying each message with its number (1, 2, 3, etc)
3. Close the app and open it again on this same channel
4. Scroll up until it start loading more messages
5. Then you will se that it skipped a lot of messages

To create the 150 I created a button on the Channel Page of the example app of this same repo with the following code
```
final channel = StreamChannel.of(context).channel;
final list = List.generate(150, (index) => index);
Future.forEach(list, (element) async {
  await channel.sendMessage(Message(text: 'Message #${element + 1}'));
  await Future.delayed(Duration(seconds: 1));
});
```

**Expected behavior**
Not skipping any messages when scrolling the channel messages

**Screenshots**
https://ibb.co/B2r61By
https://ibb.co/wMFW6rZ

**Flutter doctor**
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 10.0.19041.746], locale pt-BR)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (9 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\luan-\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\luan-\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\luan-\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

**Additional context**
**If I start the client with persistenceEnabled: false I dont have this problem**

gz#9248

**Comment by imtoori** [comment]
Hi @luantrasel 
what sample app are you using?
the one inside packages/stream_chat_flutter/example?

**Comment by luantrasel** [comment]
@imtoori I was using the example app of the version 0.2.21

Now I saw that you have this new version 1.0.2-beta... On this version I did the same test with packages/stream_chat_flutter/example and it worked...

**Comment by luantrasel** [comment]
@imtoori  I can see that you keep doing a lot of changes on the beta version... So I'd like to ask if there's a chance of you guys to fix it on the 0.2.21 version?

**Comment by imtoori** [comment]
This beta version will soon become the stable one, but I'll see if we can fix this in the 0.x version
This is related to offline storage, right?

**Comment by luantrasel** [comment]
@imtoori yes, I think so. Because when I disable offline persistence I don't have this problem

**Comment by imtoori** [comment]
hey @luantrasel 
I'm sorry, but this won't be fixed on version 0.x as it's not easy to reproduce and we released version 1.x stable that brings a lot of new stuff and improvements 
I hope you understand and you'll try out our 1.x releases :)
