### ISSUE TITLE
JWTAuth error

### ISSUE THREAD

**Issue by jackrichardson** [GetStream/stream-chat-flutter#262]
**Describe the bug**
When connecting with the API key, the following error message appears:

> flutter: (2021-02-08 13:07:38.954157)  {code: 5, message: Connect failed with error: "JWTAuth error: token contains an invalid number of segments", StatusCode: 401, duration: 0.00ms, more_info: }

**Additional context**
I believe this is being caused by a change that you made to the connection process. However, perhaps connections being made with stream-chat-flutter are not using the new process?

There appears to have been a similar issue reported in [stream-chat-android](https://github.com/GetStream/stream-chat-android), which has been fixed with an updated version, see here for context: https://github.com/GetStream/stream-chat-android/issues/1213

gz#9260

**Comment by tbarbugli** [comment]
@jackrichardson do you get this error when you connect to chat or when there is a reconnection? If possible it would be great to get the logs from the request (URI, query params, ...)

**Comment by jackrichardson** [comment]
False alarm, sorry. My code was faulty.

**Comment by rohanvasishth** [comment]
@jackrichardson could you say how you fixed it? I am facing the same issue as well.
