### ISSUE TITLE
StreamChannel can not handle initialMessageId parameter changes

### ISSUE THREAD

**Issue by Goxiaoy** [GetStream/stream-chat-flutter#265]
**Describe the bug**
 `StreamChannel._futures`  should not be initialized in 'initState', Once widget `initialMessageId ` parameter  changes from null to not-null, 
https://github.com/GetStream/stream-chat-flutter/blob/896e8568576b58c4d1914f4b271a7cb654e29cc6/packages/stream_chat_flutter_core/lib/src/stream_channel.dart#L356-L357 will cauese index out of range  error

**Additional context**
This would fix
https://github.com/GetStream/stream-chat-flutter/compare/master...Goxiaoy:fix_stream_channel_initialMessageId_chaned

gz#9439

**Comment by imtoori** [comment]
hey thanks for reporting this issue!
your solution is ok, but probably doing this in the `didUpdateWidget` method would be better
I'll do it and see if it works
