### ISSUE TITLE
Customize ChannelHeader & MessageInput

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#27]
is there a way to customize ChannelHeader & MessageInput ?
for example change the logic to upload attachment to my own CDN, or use my own AppBar as ChannelHeader

**Comment by imtoori** [comment]
The `ChannelHeader` widget is completely optional, you can use your own `AppBar` with no problem.

At the moment is not possible to customize the logic to upload the attachment, but I think it makes sense to have such a feature
