### ISSUE TITLE
MessageListView Widget is not realtime

### ISSUE THREAD

**Issue by KingIdee** [GetStream/stream-chat-flutter#28]
I built a sample using your `MessageListView` widget and I was not getting messages in realtime. Here is a GIF:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/26332464/79347550-b8dc7b80-7f2b-11ea-836b-3dbac931659e.gif)

**Comment by imtoori** [comment]
@KingIdee  Did you use `client.queryChannels` or call `channel.watch`?

**Comment by KingIdee** [comment]
I don't think I did. Isn't the `StreamChannel` widget supposed to do that? I mean, I'm passing the channel to it:

```
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) {
            return StreamChannel(
              child: ChannelPage(),
              channel: channel,
            );
          },
        ),
      );
```

**Comment by imtoori** [comment]
You need to get the channel using `client.queryChannels` or call `channel.watch` after you created it otherwise you won't receive the events related to that channel
Can you try?

**Comment by KingIdee** [comment]
Oh yeah. I used `channel.watch`. It worked fine. Since it's chatting, the feature should work out of the box I think.

**Comment by imtoori** [comment]
That's the way it works on other SDKs
I'll take the request into consideration, thanks
