### ISSUE TITLE
Empty message created every time I'm trying to send a file.

### ISSUE THREAD

**Issue by troy379** [GetStream/stream-chat-flutter#286]
**Describe the bug**
Empty message created every time I'm trying to send a file.

The files I tried to upload:
*PDF*: http://www.orimi.com/pdf-test.pdf
*CSV*: https://sample-videos.com/csv/Sample-Spreadsheet-10-rows.csv

**To Reproduce**
1. Go to any channel;
2. Click on `+` on the `MessageInput`;
3. Select `Upload a file` and choose any file;
3. Wait until the file uploaded (the loading indicator disappear);
4. See that empty message created.

**Expected behavior**
The file is uploaded and visible in the channel (added to the `attachments` list).

**Screenshots**
![image](https://user-images.githubusercontent.com/12077345/109165794-a2769180-7784-11eb-98ab-9298f16129a2.png)

**Logs**
The message JSON:
```
{
  "id": "d7d2f5fb-207a-4021-b630-12966015e0b6",
  "text": "",
  "attachments": [],
  "mentioned_users": [],
  "parent_id": null,
  "quoted_message": null,
  "quoted_message_id": null,
  "show_in_channel": null,
  "silent": false,
  "html": "",
  "cid": "messaging:6cd5194a-657f-4a3c-8747-9f60b721c3e5",
  "pinned": false,
  "pinned_at": null,
  "pinned_by": null,
  "pin_expires": null
}
```
<details>
  <summary>flutter analyze</summary>                                       

```No issues found! (ran in 12.2s)```
</details>

<details>
  <summary>flutter doctor -v</summary>                                       
  
```[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale ru-UA)
    • Flutter version 1.22.6 at /Users/krol/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/krol/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/krol/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (1 available)            
    • iPhone 12 mini (mobile) • 0CF5689A-6F95-4F7D-8537-6948DC3B8EA3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)```

</details>


gz#9713

**Comment by xsahil03x** [comment]
Can you also please mention the package version please.

**Comment by troy379** [comment]
@xsahil03x `stream_chat_flutter: ^0.2.21`

**Comment by deven98** [comment]
Hey @troy379 👋

Just wanted to confirm a few things:

1) Does this happen on all channels to you on version 0.2.21?
2) Does this happen with these specific types of files or all files?
3) Does the example on stream_chat_flutter work as expected or does it give the same error?

**Comment by troy379** [comment]
hey @deven98 
1. Yes, it does;
2. I've tested `pdf` and `csv`, because I'm interested in them specifically;
3. It works almost as expected. The infinite loading is shown in the messages thread until I reload the screen

**Comment by deven98** [comment]
@troy379 we're having a hard time replicating the bug on our end with the files (I'm assuming you've tried uninstalling and reinstalling the app already) so is it possible for you to send us any logs or a recording of the bug? You can set the log level on instantiating the client.

**Comment by troy379** [comment]
I've tested the issue properly and found out that the problem is inside my `preMessageSending` builder 🤦 🤦 🤦 
Sorry for wasting your time and thanks for responding
