### ISSUE TITLE
Ability to render Custom Attachment Type

### ISSUE THREAD

**Issue by nosmirck** [GetStream/stream-chat-flutter#29]
The api provides a way to send a custom payload through [attachments](https://getstream.io/chat/docs/chat_bots/?language=js&q=command#step_3_-_attachment,_fields_and_actions) and we can have a MessageBuilder that easily handles this scenario:

```
MessageListView(
  showVideoFullScreen: true,
  messageBuilder:_buildCustomMessage,
  showOtherMessageUsername: true,
  threadBuilder: (_, parentMessage) {
  return ThreadPage(
  parent: parentMessage,
  );
  },
),
```
and in `_buildCustom Message` logic for it can be done, however, it would basically requiere to re-write the `MessageWidget` with all its features + a small set of builders for the attachments.

Proposed Solution:

Add a list of `AttachmentBuilders` to the `MessageListView` that can be passed down to the `MessageWidget` and it can be used during `_buildBubble`

**Comment by imtoori** [comment]
In the alpha version the `MessageListView` has a property `Map<String, AttachmentBuilder> attachmentBuilders`.
The key is the type of the attachment and the value is the builder.
It defaults to the regular attachment builders
