### ISSUE TITLE
Ability to create #HashTags

### ISSUE THREAD

**Issue by nosmirck** [GetStream/stream-chat-flutter#30]
Just like @mentions it would be great to have #hashtags and have a `onHashTagTap` as we have for mentions.

**Comment by imtoori** [comment]
I think it's better to add some property to `MessageInput` to make it easy for you to implement this feature as a customization of the SDK
It will fulfil your requirements and it will make the widget more versatile

**Comment by imtoori** [comment]
As pointed out by @nosmirck, we could pass a list of objects like this
```dart
class MessageParser{
  final RegExp exp;
  final Color color;
  final VoidCallback onTap;

  MessageParser({@required this.exp, @required this.color, this.onTap});
}
```
It's also a way to generalize the parsing of mentions.

The only problem I can see so far is that the message text is a `MarkdownBody` widget from the package `flutter_markdown`. 
At the moment mentions are made clickable substituting the text with a markdown link (@imtoori = [@imtoori]()) and handled using the property `onTapLink` of `MarkdownBody`.

I think this is a nice solution, but we need to review the markdown widget first

**Comment by imtoori** [comment]
This is doable using the `textBuilder` property of the `MessageWidget`, but I don't think we're gonna implement it in the SDK
Anyway, we're gonna add a guide on how to do this in our documentation
I'm closing this and I'll update you when the documentation is available
