### ISSUE TITLE
Feature: Customize MessageInput

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#302]
Hi @imtoori 

Use case: Customize MessageInput

- Disable some attachment type : isFileAttachmentEnable, isCameraAttachmentEnable etc...
- Add new custom type 

```dart
MessageInput(
   customAttachment: [
   IconWidget(Icons.XXX),  IconWidget(Icons.YYY)
   ],
   customAttachmentOnPressed: (type){
       // do your stuff
       return AttachmentFile(
          name: file.name,
          size: mediaInfo.filesize,
          bytes: await mediaInfo.file.readAsBytes(),
          path: mediaInfo.path,
        );
  }
)

In MessageInput.dart

line 837
Row(
   mainAxisAlignment: MainAxisAlignment.start,
   children: [
      GestureDetector(
          customAttachment...
      onTap: (){
            final attachmentFile = customAttachmentOnPresse();
            setState(() {
                  _attachments.update(attachment.id, (it) {
                    return it.copyWith(
                      file: file,
                      extraData: {...it.extraData}..update('file_size', (_) => file.size),
                    );
                  });
                });
      }
      ),
      IconButton(

```

Its pseudo code to show the idea.

Is a PR for this use case welcome ?

Thank you,

gz#9795

**Comment by Abacaxi-Nelson** [comment]
Hey,

The panel im trying to customize : 
![image](https://user-images.githubusercontent.com/556990/109653489-60bd6080-7b61-11eb-8b7e-7ea6acd32658.png)

- disable specific attachment types, so remove the tabs in the "bottom sheet" that opens when you tap on the attachment icon **=> Yes**
- add new attachment types, so add new tabs in that "bottom sheet" **=> Yes, like record an audio for example**

**Comment by imtoori** [comment]
This is a great idea and we'll do it eventually, but a pr is more than welcome!

**Comment by Abacaxi-Nelson** [comment]
i don't find an easy way to add new custom attachment to MessageInput.
I finally copy/paste ```MessageInput```to my package to customize it :(

**Comment by imtoori** [comment]
I'll let you know once we do it @Abacaxi-Nelson
