### ISSUE TITLE
Outdated Android NDK Dependency

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#305]
**Describe the bug**
Setting up the Stream SDK fails due to an older Android NDK dependency.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 22.0.6917172

What is the plan to upgrade the NDK version? An old version will cause builds to fail in our CI.

Also, why does Stream need the NDK? 

gz#9818

**Comment by shodgetts** [comment]
Are you able to please provide a stack trace with this error

**Comment by searchy2** [comment]
The error is thrown by Android Studio:

> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 22.0.6917172

**Comment by xsahil03x** [comment]
@searchy2 none of our packages is a [plugin](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin) package. i.e., we do not handle any platform-specific code. This issue is probably related to your local environment. Can you please try following these [solutions](https://stackoverflow.com/questions/60404457/no-version-of-ndk-matched-the-requested-version)?

**Comment by searchy2** [comment]
I was able to resolve the issue by installing the required NDK version.

There might be an incorrect configuration somewhere requiring a specific NDK version.

**Comment by deven98** [comment]
Hey @searchy2, we will take a look at any NDK constraints as soon as possible. Since your error was resolved, closing this issue for now. Please feel free to reopen if required. Thanks for bringing this to our attention!

**Comment by searchy2** [comment]
There's a missing NDK error again with the latest master. 

> > No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669, 22.0.6917172-rc1

I recommend updating to use the latest NDK.

![MaxthonSnap20210326121123](https://user-images.githubusercontent.com/19896174/112669225-7276e880-8e2d-11eb-964b-abebaf498bca.png)
