### ISSUE TITLE
Ability to send Custom Attachments

### ISSUE THREAD

**Issue by nosmirck** [GetStream/stream-chat-flutter#31]
We would like the ability to send custom attachment with custom payload

Example:

For the `MessageInput` Widget we would need to add `customAttachmentActions` which is a List of `AttachmentActions` that would appear alongside the normal attachment button (or maybe provide extra options to customize where it goes, either within the same attachments options or separate with a custom icon, right side, below/above the input box, etc)

```
{
  type: 'myinfo',
  payload: 
  {
    email: 'myemail@email.com',
    phoneNumber: '555-1234567'
    address: '123 My Avenue East, My City, AA, My Country, P0ST4L'
  }
}
```

or something like the following attachment:

```
{
  type: 'mytodo',
  payload:
  {
    title: 'groceries'
    items:
    [
      {
        name: 'pasta',
        completed: 'false'
      },
      {
        name: 'tomatoes',
        completed: 'true'
      }
    ]
}
```

Note: the actual custom object for attachment can be configured as you guys think is best, this is just an example, I used payload to describe the custom object I'm sending/receiving in my chat.

The idea here is that we can build custom messaging apps, for instance, a chat for groceries apps where you can keep your "to do" list of groceries and send it to your friend and renders a preview in the messages window.

**Comment by imtoori** [comment]
https://github.com/GetStream/stream-chat-flutter/pull/43
Could you tell me what do you think of this solution?
