### ISSUE TITLE
Field skip_push on sendMessage

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#313]
Hi,
[Documentation](https://getstream.io/chat/docs/react/send_message/?language=dart) have a field **skip_push**.

Can you confirm it does not exist right now ?

Thank you,

gz#9883

**Comment by imtoori** [comment]
yes I can confirm
I'll add it now 

but you can set it in the `message.extraData` map and it should work

**Comment by xsahil03x** [comment]
Added in #314

**Comment by Abacaxi-Nelson** [comment]
Hi @xsahil03x @imtoori 
Im still having webhook/notification trigger event passing 

in my code:
```dart
final message = stream.Message(
  showInChannel: true,
  text: comment.content,
  quotedMessageId: postId.replaceAll('dm_', ''),
  skipPush: true,
);
```

```dart
stream_chat > client.dart line 1303
/// Sends the message to the given channel
Future<SendMessageResponse> sendMessage(
    Message message, String channelId, String channelType) async {
  final response = await post(
    '/channels/$channelType/$channelId/message',
    data: {'message': message.toJson()},
  );
  print('sendMessage:  ${message.toJson()}');
  return decode(response.data, SendMessageResponse.fromJson);
}

sendMessage:  {id: e02ea4d1-6a89-455a-b1b6-74c56bd899cf, text: y, mentioned_users: null, parent_id: null, quoted_message: null, quoted_message_id: 946bde3e-fd44-45c5-ac2b-71597b5fc765, show_in_channel: true, silent: null, skip_push: true, pinned: false, pinned_at: null, pin_expires: null, pinned_by: null}
```

Do you see something wrong ?

**Comment by imtoori** [comment]
do you still receive the notification?
Because I think it's normal that the webhook is called anyway.
You can check the field message.skip_push and skip the message yourself if you don't want to handle it in the webhook

**Comment by Abacaxi-Nelson** [comment]
yes im receiving it.
i follow your advice, and it work: 

**_You can check the field message.skip_push and skip the message yourself if you don't want to handle it in the webhook_**
