### ISSUE TITLE
Update pubspec.yaml to work with Flutter v2 

### ISSUE THREAD

**Issue by jonasesr** [GetStream/stream-chat-flutter#321]
Most dependencies like jiffy, rxdart or path_provider need an update to get stream-chat-flutter working with Flutter v2.
Furthermore, the code needs adjustments in order to function under the new circumstances.

gz#9997

**Comment by imtoori** [comment]
Hey! We're working on it and will release a new version probably tomorrow

**Comment by imtoori** [comment]
published 1.4.0-beta

**Comment by jonasesr** [comment]
Am I seeing this wrong, or have you not adjusted the dependencies, but only changed their order?

In any case, this release cannot run with Flutter v2.
