### ISSUE TITLE
Destroy uploaded files

### ISSUE THREAD

**Issue by DineshTaral123** [GetStream/stream-chat-flutter#322]
I try to send pdf, it sending successfully not not opening when i try to open, it not opened also i check the pdf url on chrome, it showing me "Failed to load PDF document".
pdf url : https://stream-chat-us-east-c7.imgix.net/88733/attachments/f856780f-e208-4352-8ea8-0969fc242971.OBE%20Notification%20274-19-2-2021.pdf?dl=OBE%20Notification%20274-19-2-2021.pdf&s=c19b576bb6a7ff2f9e31c6e5fde9ea21

gz#10014

**Comment by imtoori** [comment]
Hi @DineshTaral123 can you send me the original file? I'll try to reproduce this behaviour

**Comment by DineshTaral123** [comment]
Thanks for instant reply.
please check the link for pdf https://drive.google.com/file/d/1-95kPt5MiKxBpe9wH2fdQEO5IIly9Chm/view?usp=sharing

**Comment by imtoori** [comment]
it's working fine for me 
btw we'll release a new beta version later today/tomorrow

**Comment by imtoori** [comment]
hey @DineshTaral123 is this still happening for you?
