### ISSUE TITLE
Version solving failed after upgrading firebase dependencies 

### ISSUE THREAD

**Issue by luvishq** [GetStream/stream-chat-flutter#330]
**Describe the bug**
Hi, I was updating the firebase dependencies in my project and after updating I am getting version solving issues with stream. Can you please help me with this?

**What package are you using? What version?**
pubspec.yaml

  uuid: ^2.2.2
  provider: ^4.3.2+2
  image_picker: ^0.7.2+1
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.19.3
  pin_code_fields: any
  flutter_dash: ^0.0.1
  email_validator: ^1.0.6
  progressive_image: ^1.0.1
  video_player: ^2.0.2
  shared_preferences: ^2.0.4
  stream_chat: ^1.3.2+1-beta

  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0
  firebase_crashlytics: ^1.0.0
  firebase_storage: ^8.0.0
  intl: ^0.17.0

**To Reproduce**
1. Upgrade the firebase dependencies in your project or use the above pubspec config
2. After pub get , getting version solving issue with stream_chat dependency

**Expected behavior**
There should not be any version solving issue 

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

```
Because no versions of firebase_storage match >8.0.0 <9.0.0 and firebase_storage 8.0.0 depends on firebase_storage_web ^1.0.0, firebase_storage ^8.0.0 requires firebase_storage_web ^1.0.0.
And because firebase_storage_web >=1.0.0 depends on http ^0.13.0 and no versions of http match >0.13.0 <0.14.0, firebase_storage ^8.0.0 requires http 0.13.0.
And because http 0.13.0 depends on http_parser ^4.0.0 and stream_chat >=1.1.0-beta depends on http_parser ^3.1.4, firebase_storage ^8.0.0 is incompatible with stream_chat >=1.1.0-beta.
So, because flutter_app depends on both stream_chat ^1.3.2+1-beta and firebase_storage ^8.0.0, version solving failed.
pub get failed (1; So, because flutter_app depends on both stream_chat ^1.3.2+1-beta and firebase_storage ^8.0.0, version solving failed.)
```

Paste the output of running `flutter doctor -v` here.

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 2.0.1 at /Users/laavaans/Downloads/flutter
    • Framework revision c5a4b4029c (9 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/laavaans/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

**Additional context**

gz#10176

**Comment by imtoori** [comment]
hey @luvishq 
unfortunately, we cannot update the http_parser dependency

can you try using dependency_overrides?

just add this to your pubspec:

dependency_overrides:
    http_parser: ^4.0.0

**Comment by luvishq** [comment]
@imtoori : I am getting errors after doing this :

`Error: Type 'Client' not found.`
`Error: Type 'Channel' not found.`
`Error: Type 'User' not found.`

How to fix these ?

**Comment by imtoori** [comment]
I'm sorry, I was hoping that would have worked
I think you should stick to the previous version of firebase dependency until we migrate to null-safety

**Comment by luvishq** [comment]
@imtoori : Sorry it seems firebase fixed some auth related issue in their latest version which are really important and blocker for us to proceed, can you please address this or if you can share a timeline  for this ?
