### ISSUE TITLE
Unreadcount not updating

### ISSUE THREAD

**Issue by luantrasel** [GetStream/stream-chat-flutter#338]
**Describe the bug**
client.state.**totalUnreadCountStream** and channel.state.**unreadCount** are not counting correctly while the chat is opened

**Version of the package**
tested with 1.4.0-beta and 1.3.0-beta

**To Reproduce**
1. Enter in a channel page and while you are with the chat open, ask the other user to send you a few messages
2. Back to the channels list you will notice that all messages received while you were on the channel are still being considered as unread on client.state.**totalUnreadCountStream** and channel.state.**unreadCount**
3. You can test it with example 6: https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter/example/lib/tutorial-part-6.dart

**Expected behavior**
If you are with the chat opened in the moment that you received the message, it means that you have read them, so they shouldn't be added to the unreadCount

gz#10259

**Comment by imtoori** [comment]
fixed in 1.5.1
reopen this if the issue persists
