### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#339]
What is the plan to migrate this library to null safety?
It depends on a lot of underlying libraries which seems to present an issue.

gz#10266

**Comment by imtoori** [comment]
we're gonna start the migration next week, starting from the `stream_chat` package up to `stream_chat_flutter`

**Comment by searchy2** [comment]
Thank you for the update. 
Also, the latest Stream announcement letting developers use Stream for free up to 2000 users is fantastic!

**Comment by aytunch** [comment]
@imtoori is stream depending on flutter_webrtc and xmpp_stone? Are there any blockers?

**Comment by imtoori** [comment]
@aytunch it's not
we're starting the migration and help migrate the packages that don't support null-safety, if any

**Comment by Chojecki** [comment]
Hi, I just have a spike task in next sprint to check a decent in app chat providers. Any estimations about migration end date?

**Comment by imtoori** [comment]
Hey @Chojecki 
it will take a while unfortunately, I can't give you an ETA yet, but it's one of our top priorities 

However, the package is still usable anyway
Hope to have more information soon

**Comment by Chojecki** [comment]
@imtoori thanks. Asking because we are migrating now. Will be tracking this issue

**Comment by FCView** [comment]
Looking forward to this. I just signed up and am unable to get started without rolling back several conflicting dependencies.

**Comment by imtoori** [comment]
@FCView  We're working on this and it should be ready in the following weeks
Make sure to follow this pr https://github.com/GetStream/stream-chat-flutter/pull/381

**Comment by Chojecki** [comment]
@imtoori Is there any way to use getStream with Flutter 2.0 with null-safety? Some beta release or something?

**Comment by imtoori** [comment]
@Chojecki not yet
that pr is the status of the migration, but it's a matter of days

**Comment by hoanle** [comment]
Any update?

**Comment by rubenvereecken** [comment]
Our entire migration is just pending Stream at the moment because of the large overlap in dependencies. We very much look forward to this one.

**Comment by imtoori** [comment]
We're working on the migration. You can check the progress in the PRs
I'm sorry, but it's a complicated process, as you might know, but we're working hard to make it as soon and as good as possible

**Comment by imtoori** [comment]
The pr has been merged
You can find the new version as `2.0.0-nullsafety.0`
It's not a stable release, but we'll test it and bring it to stable as soon as soon as possible and thanks in advance for your feedback!

**Comment by rubenvereecken** [comment]
So glad to hear this, thanks @imtoori! We're not relying on your null safety but good to see your dependencies are probably more stable. We were already using your dev branch last week so should be a tiny upgrade.

**Comment by rubenvereecken** [comment]
@imtoori I think you forgot to update your dependencies, see `stream_chat_flutter_core` 

https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/pubspec.yaml

**Comment by imtoori** [comment]
yep, sorry about that
just fixed it in the 2.0.0-nullsafety.1 release
thanks!
