### ISSUE TITLE
Cannot Create New Channel

### ISSUE THREAD

**Issue by JayPerfetto** [GetStream/stream-chat-flutter#348]
Disregard

**Comment by JayPerfetto** [comment]
Self-resolved - users tagged as members must exist before the channel can be watched / created

**Comment by shodgetts** [comment]
Agent comment from Sahil Kumar in <a href='https://getstream.zendesk.com/agent/tickets/10393'>Zendesk ticket #10393</a>:<br><br>Hey Jay,

Closing this ticket in response to your comment here. Feel free to open if you faced any problems.
