### ISSUE TITLE
MessageInput Attachment-Button-Row overflows when animating

### ISSUE THREAD

**Issue by JayPerfetto** [GetStream/stream-chat-flutter#349]
When hitting the attachment button in MessageInput(), the button row beneath the input area overflows as it animates open by 60 pixels (on iPhone XS) as it opens, and 8 px as it closes. I assume this issue exists just to varying degrees on different device sizes. 
```

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 8.0 pixels on the bottom.
The relevant error-causing widget was
MessageInput
lib/…/stream_chat_page/stream_channel_page.dart:47
════════════════════════════════════════════════════════════════════════════════

```

gz#10396
![IMG_695F1CF89EF6-1](https://user-images.githubusercontent.com/34031697/111926637-e3ec1b00-8a6a-11eb-93f4-6f2ec625041c.jpeg)

**Comment by JayPerfetto** [comment]
It's worth adding that I am not seeing this behavior in release builds, only debug profile builds, though it could be that the release profile simply silently swallows the overflow errors

**Comment by xsahil03x** [comment]
@JayPerfetto yes it won't be visible in release builds, We will soon release a fix for this but can't say anything about the timeline as it's not on our priority list. We are currently focusing on migrating the package to NNBD as soon as possible. Hope you understand 😄

**Comment by imtoori** [comment]
this is fixed in the latest develop
