### ISSUE TITLE
MessageWidget cannot handle Accessibility Text-Size scaling

### ISSUE THREAD

**Issue by JayPerfetto** [GetStream/stream-chat-flutter#356]
**Describe the bug**
When changing the text scale (iOS tested only) via the accessibility settings of the phone, the message sender text in a message widget overflows the bottom-baseline of the container. See the attached screenshots at min, default, and max scales.

**What package are you using? What version?**
Latest Stream-chat-flutter UX package

**To Reproduce**
1. Instantiate a channel + message list widget, with theme dictating the text size for messages and author names to be size 17.0.
2. get a message from another person in the channel so that their name is displayed - at default text scale, there is already bottom overflow for lowercase letters that hang below the text baseline like 'g' and 'y'.
3. change the text scale of your device to min - the problem is better but there is still some cutoff
4. change the text scale of your device to max - the screen is unusable

**Expected behavior**
The message widgets should scale appropriately with the system text scale, as do messages in iMessage and most other mainstream messaging platforms.

**Screenshots**

![IMG_3942](https://user-images.githubusercontent.com/34031697/112512381-8e588c80-8d50-11eb-8c56-40d902b960cb.PNG)
![IMG_3944](https://user-images.githubusercontent.com/34031697/112512394-90225000-8d50-11eb-8002-098f351a66f6.PNG)
![IMG_3943](https://user-images.githubusercontent.com/34031697/112512403-91537d00-8d50-11eb-909a-433e8de1b719.PNG)

**Additional context**
```
return StreamChat(
      client: locator<StreamChatService>().streamClient,
      streamChatThemeData: theme,
      child: StreamChannel(
        channel: model.currentChannel,
        child: Scaffold(
          extendBodyBehindAppBar: false,
          backgroundColor: MyTheme.chatScreenBackgroundColor(context),
          appBar: AppBar(
            elevation: 1.0,
            backgroundColor: Theme.of(context).colorScheme.background,
            leading: ChannelBackButton(),
            automaticallyImplyLeading: false,
            centerTitle: true,
            title: ChannelAppbarTitle(),
            actions: [],
          ),
          body: Column(
            children: <Widget>[
              Expanded(
                child: FadeIn(
                  child: MessageListView(
                    showConnectionStateTile: false,
                    showScrollToBottom: true,
                    dateDividerBuilder: (date) => Container(),
                  ),
                ),
              ),
              MessageInput(
                autofocus: true,
                disableAttachments: false,
                preMessageSending: (message) async {
                  model.setIsSending(true);
                  return message;
                },
                onMessageSent: (message) {
                  model.setIsSending(false);
                  return message;
                },
              ),
            ],
          ),
        ),
      ),
      
```

gz#10596

**Comment by xsahil03x** [comment]
Fixed in #365 and will be released soon.
