### ISSUE TITLE
Freezing channel not returning error on sending message

### ISSUE THREAD

**Issue by SarveshRamachandran** [GetStream/stream-chat-flutter#360]
Flutter documentation says that upon freezing a channel, that will disallow messages from being sent and any attempts to send a message will return a message of type error. However, when I was testing the functionality, after freezing the channel I can still send and receive messages from both test ids associated with the channel. I can verify that the channel is frozen and can filter out frozen channels, but being able to prevent messages from being sent would be very helpful as well

**Comment by deven98** [comment]
Hey @SarveshRamachandran, thanks for bringing this to our attention. 

Can you confirm no user here has the UseFrozenChannel permission?

**Comment by SarveshRamachandran** [comment]
That permission has not been granted, so it should be off by default right?

**Comment by imtoori** [comment]
can you check you have not disable permission checks? it's a switch in the dashboard

**Comment by SarveshRamachandran** [comment]
I checked the dashboard and 'disable permission checks' was on. I went ahead and switched it off to test it, but the same issue is still happening:
