### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by VitaliiKrochak** [GetStream/stream-chat-flutter#362]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...
√ `android\settings_aar.gradle` created successfully.
Building plugin file_picker...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin file_picker could not be built due to the issue above.

**Comment by imtoori** [comment]
hey @VitaliiKrochak 
did you take a look at this section of the readme? https://github.com/GetStream/stream-chat-flutter/tree/master/packages/stream_chat_flutter#troubleshooting

this is likely due to this https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1

I'll close it, feel free to reopen it
