### ISSUE TITLE
Pagination Spinner Continues To Appears on First Load

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#363]
**Describe the bug**
In the chat channels list, swiping up from the bottom repeatedly triggers the loading spinner to show. 
This only happens on the first load. After swiping back up, the loading indicator properly hides.

**What package are you using? What version?**
1.5.1

**What platform is it about?**
- [ X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/19896174/113020188-f855a500-9147-11eb-8f95-0d94f3552276.gif)

**Comment by xsahil03x** [comment]
@searchy2 can you confirm if this happens in the message list and not in the channels list?

**Comment by searchy2** [comment]
It's the channels list, my bad!
