### ISSUE TITLE
Message Screen First Load Freezes and is Very Slow

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#364]
**Describe the bug**
Message screen first load has performance issues. 

**What package are you using? What version?**
1.5.1

**What platform is it about?**
- [X] Android
- [ ] iOS
- [X] Web
- [X] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Open the message list. 

**Expected behavior**
Message page loads quickly and without freezing.

**Screenshots**
![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/19896174/113043580-44154800-9162-11eb-8291-ee44ea8d24ed.gif)

**Logs **
```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 2.0.3 at F:\Development\flutter-sdk
    • Framework revision 4d7946a68d (12 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
```

**Comment by imtoori** [comment]
Are you using offline storage? If so, how do you initialize it?

**Comment by searchy2** [comment]
No, offline persistence isn't being used.

**Comment by imtoori** [comment]
Sorry for the questions, but this has never happened to me. I know we have a couple of performance issues that we are addressing carefully, but I don't think this is related to that

How are you initializing the channel? 
Do you see any meaningful log?(you may want to change the loglevel for this)

**Comment by JayPerfetto** [comment]
Using offline persistence is key to avoiding this behavior, based on my own recent implementation

**Comment by searchy2** [comment]
@imtoori  The reason you're likely not seeing the issue is because the issue is masked by launching the new page. 
The freezing is very evident if you load the page progressively like in the demo video above.

The freeze can be easily reproduced by running `tutorial-part-2.dart` from the sample app.

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/19896174/113213532-ece4a580-923d-11eb-8453-1a003b22be5f.gif)

Notice I click once to open the chat and then it takes 3-4 seconds before the chat opens.

**Comment by ajosecueto** [comment]
I found the same issue, take a lot time to initialize a chat...

**Comment by poqueque** [comment]
Same issue here. Please address it.

**Comment by JayPerfetto** [comment]
It is not constructive to continue posting "same issue" - just thumbs up the original post

**Comment by poqueque** [comment]
Jay, I tried but for some reason it was disabled at the time of posting.

**Comment by imtoori** [comment]
performance is one of our top priorities 
we'll take care of this after the nnbd migration is done (it's really close)

**Comment by imtoori** [comment]
we've been doing some work on the performance issues
there is still a small junk (especially in [debug mode](https://flutter.dev/docs/testing/build-modes#debug), but that should be fine) while opening the ChannelPage, but overall it should be better
Let us know if you have any suggestion or if you want to report other performance issues, we're always working on that :)

**Comment by luvishq** [comment]
Why is this issue closed?
