### ISSUE TITLE
Null Pointer exception in Channel.dart - CORE BUG

### ISSUE THREAD

**Issue by JayPerfetto** [GetStream/stream-chat-flutter#368]
**Describe the bug**
On line 1599 of Channel.dart, in the method ```_countMessageAsUnread```, if user.mutes is null an exception is thrown as you cannot call .firstWhere on null.

This should be guarded in a simple ternary, or something like this:

```
 final userIsMuted = _channel.client.state.user.mutes != null
        ? _channel.client.state.user.mutes.firstWhere(
              (m) => m.user?.id == message.user.id,
              orElse: () => null,
            ) !=
            null
        : null;
```
<img width="644" alt="Screen Shot 2021-03-31 at 10 01 32 AM" src="https://user-images.githubusercontent.com/34031697/113183412-d7a15400-9208-11eb-948f-ff5ff4439144.png">

**Comment by imtoori** [comment]
this has been fixed, it will be in the next release
