### ISSUE TITLE
Client does not return without internet connection

### ISSUE THREAD

**Issue by SarveshRamachandran** [GetStream/stream-chat-flutter#369]
Client.connectUser does not work properly if there is no internet connection. It should return an error saying that there were connection issues, but it doesn't return anything at the moment

**Comment by imtoori** [comment]
I see, it returns null at the moment when there is no connection, or throws an exception if there is a server error
We'll work on more specific error types, thanks for the report

**Comment by SarveshRamachandran** [comment]
I don't think it returns null. While testing it yesterday, it wouldn't return at all, so any watchers that were linked to the client wouldn't begin correctly and instead get stuck in

**Comment by imtoori** [comment]
I tested it to understand your issue and it returns null if there is no connection
This is my snippet
```dart
final res = await client.connectUser(
    User(id: userId),
    userToken
  );

  print('res: $res');
```

I agree this is not the best behaviour, but at least it does not hang

**Comment by imtoori** [comment]
we added more specific errors, you can find the new implementation in the develop branch
it will be available in the next release
I'm closing this issue, feel free to reopen it if you have any doubt
