### ISSUE TITLE
Files Larger Than 20MB Can Still Be Sent and Become Permanently Stuck

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#371]
**Describe the bug**
Attempting to attach a file larger than 20MB shows the error but allows the file to be sent.
Upload then subsequently fails and the failed file becomes stuck permanently, with no ability to remove.

**What package are you using? What version?**
v1.5.1 

**What platform is it about?**
- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Attach video larger than 20MB.
2. Dismiss warning message.
3. File attachment still exists and can be sent.
4. Send
5. Sending fails and becomes stuck in chat with no ability to remove.

**Expected behavior**
Do not allow attachments that are larger than the file size limit.

**Screenshots**
![Screenshot_20210331-132550](https://user-images.githubusercontent.com/19896174/113214467-2964d100-923f-11eb-8271-0b1908d373e9.jpg)
![Screenshot_20210331-132606](https://user-images.githubusercontent.com/19896174/113214473-2b2e9480-923f-11eb-9b7d-9ea056437e91.jpg)

**Comment by xsahil03x** [comment]
Fixed in #377
