### ISSUE TITLE
_countMessageAsUnread function trying to call 'firstWhere' on null 

### ISSUE THREAD

**Issue by sofyan-ahmad** [GetStream/stream-chat-flutter#391]
**Describe the bug**
There is an error on :
```
final userIsMuted = _channel.client.state.user.mutes.firstWhere(
          (m) => m.user?.id == message.user.id,
          orElse: () => null,
        ) !=
        null;
```
caused by sometime `mutes` on user is `null`

**What package are you using? What version?**
flutter SDK: ">=2.7.0 <3.0.0"
  stream_chat_flutter: ^1.3.2-beta

**What platform is it about?**
- [Y] Android
- [Y] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Send a chat
2. Exception thrown and the error should appear on your log

**Expected behavior**
No error should Exception thrown even if mutes is null

**Logs **
```
NoSuchMethodError (NoSuchMethodError: The method 'firstWhere' was called on null.
                       Receiver: null
                       Tried calling: firstWhere(Closure: (Mute) => bool, orElse: Closure: () => Null))

Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ChannelClientState._countMessageAsUnread
package:stream_chat/…/api/channel.dart:1593
#2      ChannelClientState._listenMessageNew.<anonymous closure>
package:stream_chat/…/api/channel.dart:145
```

Paste the output of running `flutter doctor -v` here.
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-ID)
    • Flutter version 1.22.6 at /Users/sofyan.ahmad/flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
```

**Comment by imtoori** [comment]
This issue has been solved in the latest version of the sdk 
I'm closing this, feel free to reopen it if needed
