### ISSUE TITLE
How to clear badge count on iOS when all channels are read?

### ISSUE THREAD

**Issue by JayPerfetto** [GetStream/stream-chat-flutter#396]
The push notification documentation tells us how to set the badge to be equal to the unread count in the various push template formats - i.e here is my firebase template: 
```
{
    "title": "{{implodeMembers otherMembers nameField='name'}}",
    "subtitle":"{{ sender.name }}",
    "body": "{{ message.text }}",
    "click_action": "FLUTTER_NOTIFICATION_CLICK",
    "sound": "default",
    "badge": "{{ unread_count }}"
}
```
This works great, and my app badge increments as expected when new messages arrive, but then when the channel is marked as read the badge stays at that number rather than being cleared as you would expect.

How do we clear the app badge count one all channels have been marked read?

**Comment by imtoori** [comment]
you can use the plugin [flutter_app_badger](https://pub.dev/packages/flutter_app_badger)
that's what we use in the sample app
