### ISSUE TITLE
stream_chat_flutter depends on url_launcher: ^5.7.10 While my app is on latest ver of url_launcher

### ISSUE THREAD

**Issue by itsbhanupratap** [GetStream/stream-chat-flutter#398]
**Describe the bug**
When i tried to use[ in app review](https://pub.dev/packages/in_app_review) which depends on latest version of url launcher and when i do pub get it says:

`Because stream_chat_flutter >=1.0.0-beta depends on url_launcher ^5.7.10 and apnahood_seller depends on url_launcher ^6.0.0, stream_chat_flutter >=1.0.0-beta is forbidden.
So, because apnahood_seller depends on stream_chat_flutter ^1.5.2, version solving failed.`

**What package are you using? What version?**
  stream_chat_flutter: ^1.5.2

**What platform is it about?**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**

**Expected behavior**
Stream chat should also migrate to the latest ver of url launcher, so that no further version conflicts occur.

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.
`Because stream_chat_flutter 1.5.2 depends on url_launcher ^5.7.10 and no versions of stream_chat_flutter match >1.5.2 <2.0.0, stream_chat_flutter ^1.5.2 requires url_launcher ^5.7.10.
So, because apnahood_seller depends on both url_launcher ^6.0.0 and stream_chat_flutter ^1.5.2, version solving failed.
Running "flutter pub get" in apnabusiness-client...                     
pub get failed (1; So, because apnahood_seller depends on both url_launcher ^6.0.0 and stream_chat_flutter ^1.5.2, version solving
failed.)`

Paste the output of running `flutter doctor -v` here.
```
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.3 at /home/bhanu/snap/flutter/common/flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/bhanu/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/bhanu/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Mi A3 (mobile) • c5ff4ae63565 • android-arm64  • Android 11 (API 30)
    • Chrome (web)   • chrome       • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.```

**Additional context**
Add any other context about the problem here.

**Comment by xsahil03x** [comment]
@itsbhanupratap 

can you try overriding the dependency
```dart
dependency_overrides:
  url_launcher ^6.0.0
```
