### ISSUE TITLE
StreamChat dispose() tears down the Client connection

### ISSUE THREAD

**Issue by isaiahtaylor** [GetStream/stream-chat-flutter#4]
Hello, my team is evaluating Stream and I am very happy with the Flutter and React UI Kits so far. The flutter kit particularly was the big differentiator for us. Kudos!

One problem I was having was that tabbing away from the chat window using `BottomNavigationBar` tabs caused the Client object to get torn down and the connection to get disconnected, so that when I navigate back to it again I get errors that it has been disconnected.

This is despite the fact that my Client is initialized before `runApp` .

**Root Cause**

I found that `StreamChat.dispose()` calls `widget.client.dispose()`. This effectively ties the lifecycle of the Client object to the lifecycle of a widget that uses it. From a memory perspective this is not saving anything; in the Stream documentation it is recommended that the `Client` be created at the top and persist through the lifecycle of the entire app, so it doesn't make sense to dispose of that top level Client object when disposing of a widget that makes use of it.

**Workaround**

If anyone is experiencing a similar issue, I worked around it by extending the `Client` class and overriding the `dispose` method to do nothing:

```dart
import 'package:stream_chat_flutter/stream_chat_flutter.dart';
import 'package:dio/dio.dart';

class CustomClient extends Client {
  // Get this from the actual Client source code
  static const _defaultBaseURL = "chat-us-east-1.stream-io-api.com";

  CustomClient(
    apiKey, {
    tokenProvider,
    baseURL = _defaultBaseURL,
    logLevel = Level.WARNING,
    logHandlerFunction,
    Duration connectTimeout = const Duration(seconds: 6),
    Duration receiveTimeout = const Duration(seconds: 6),
    Dio httpClient,
  }) : super(apiKey,
            tokenProvider: tokenProvider,
            baseURL: baseURL,
            logLevel: logLevel,
            logHandlerFunction: logHandlerFunction,
            connectTimeout: connectTimeout,
            receiveTimeout: receiveTimeout,
            httpClient: httpClient);

  @override
  void dispose() {
    // Don't do anything so the connection doesn't get torn down
  }
}

```

Then, simply use this class rather than `Client` at the top of your app:

```dart
final client = CustomClient(
    'XXX',
    logLevel: Level.INFO,
  );
```

After this, the StreamChat widget will get torn down and restored as you tab back and forth, but the `Client` will survive it.

**Comment by imtoori** [comment]
Hi @isaiahtaylor 
You are right, that is not the right behaviour.
I'll update the StreamChat component not to dispose the Client automatically
