### ISSUE TITLE
When disableAttachments: true,

### ISSUE THREAD

**Issue by VitaliiKrochak** [GetStream/stream-chat-flutter#400]
Exception caught by rendering library 
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:320:12)
#3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2532:30)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
...
The following RenderObject was being processed when the exception was fired: RenderFittedBox#8c439 relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(unconstrained)
...  size: MISSING
...  fit: contain
...  alignment: Alignment.center
...  textDirection: ltr
  child: RenderFlex#27276 relayoutBoundary=up18 NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(unconstrained)
    size: Size(0.0, 0.0)
    direction: horizontal
    mainAxisAlignment: spaceEvenly
    mainAxisSize: max
    crossAxisAlignment: center
    textDirection: ltr
    verticalDirection: down
RenderObject: RenderFittedBox#8c439 relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(unconstrained)
  size: MISSING
  fit: contain
  alignment: Alignment.center
  textDirection: ltr
  child: RenderFlex#27276 relayoutBoundary=up18 NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(unconstrained)
    size: Size(0.0, 0.0)
    direction: horizontal
    mainAxisAlignment: spaceEvenly
    mainAxisSize: max
    crossAxisAlignment: center
    textDirection: ltr
    verticalDirection: down

Exception caught by rendering library 
RenderBox was not laid out: RenderFittedBox#8c439 relayoutBoundary=up17 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: RenderAnimatedOpacity#e4bc5 relayoutBoundary=up16 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: RenderExcludeSemantics#7b35c relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: RenderStack#d2444 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: RenderAnimatedSize#d3177 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: RenderClipRect#54f05 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: RenderPadding#b9a87 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: RenderFlex#6bd9c relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: RenderPadding#d22b3 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: RenderFlex#41673 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: RenderPointerListener#929e5 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: RenderSemanticsGestureHandler#c8167 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: RenderPadding#54fcc relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: _RenderColoredBox#ded5d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
RenderBox was not laid out: _RenderInkFeatures#64a16 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: RenderPhysicalModel#2d99d relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by rendering library 
RenderBox was not laid out: RenderFlex#f1675 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

 Exception caught by scheduler library 
There are multiple heroes that share the same tag within a subtree.

 Exception caught by rendering library 
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderPhysicalModel#2d99d relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1940:12)
#3      RenderBox.debugResetSize (package:flutter/src/rendering/box.dart:2080:12)
#4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:9)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1735:8)
#6      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
...
The following RenderObject was being processed when the exception was fired: RenderFlex#f1675 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=715.4)
...  size: MISSING
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
RenderObject: RenderFlex#f1675 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=715.4)
  size: MISSING
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
...  child 1: RenderStack#f6d2c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.tight
...    constraints: MISSING
...    size: MISSING
...    alignment: Alignment.center
...    textDirection: ltr
...    fit: loose
...    child 1: RenderStack#ebaa3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: not positioned; offset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      alignment: AlignmentDirectional.topStart
...      textDirection: ltr
...      fit: loose
...      child 1: RenderLeaderLayer#9fbb3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: not positioned; offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        size: MISSING
...        link: LayerLink#93b74(<dangling>)
...        child: _RenderLayoutBuilder#7f25a NEEDS-LAYOUT NEEDS-PAINT
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...    child 2: RenderOffstage#cae3d NEEDS-LAYOUT NEEDS-PAINT
...      parentData: not positioned; offset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      offstage: true
...    child 3: RenderConstrainedBox#5b33c NEEDS-LAYOUT NEEDS-PAINT
...      parentData: top=20.0; offset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      additionalConstraints: BoxConstraints(unconstrained)
...  child 2: RenderPhysicalModel#2d99d relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    size: MISSING
...    elevation: 8.0
...    color: Color(0xfffafafa)
...    shadowColor: Color(0xfffafafa)
...    shape: BoxShape.rectangle
...    borderRadius: BorderRadius.zero
...    child: _RenderInkFeatures#64a16 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...      size: MISSING
...      child: _RenderColoredBox#ded5d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...        size: MISSING
...        behavior: opaque
...        child: RenderPadding#54fcc relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...          size: MISSING
...          padding: EdgeInsets.zero
...          textDirection: ltr

 Exception caught by rendering library 
RenderBox was not laid out: RenderFlex#f1675 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

Exception caught by rendering library 
'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 1873 pos 12: 'hasSize': is not true.

**Comment by deven98** [comment]
Hey @VitaliiKrochak 

I can't seem to replicate this using the normal 

```
MessageInput(
  disableAttachments: true,
), 
```
Can you let me know if some other things are different in your MessageInput or send over a gist with an example of where this breaks?

Thanks.
