### ISSUE TITLE
Disable message Input instant commands

### ISSUE THREAD

**Issue by Siqlain-Hanif** [GetStream/stream-chat-flutter#408]
**Is your feature request related to a problem? Please describe.**
Currently in am using version 1.3.2-beta, seems like there's no way to disable the instant commands. Or is there any option that i am missing 

**Describe the solution you'd like**
I would like to have a flag that enables or disables the instant commands.

**Describe alternatives you've considered**
I copied over the widget code and removed the instant commands manually.

**Comment by imtoori** [comment]
we added that option in the latest release
there is a property in the `MessageInput` called `showCommandsButton`

**Comment by CedricSoubrie** [comment]
> we added that option in the latest release
> there is a property in the `MessageInput` called `showCommandsButton`

@imtoori Is there the same kind of variable for SwiftUI components ?
I'd like to do the same thing for iOS.

**Comment by streem-ua** [comment]
> MessageInput

Hello! Have you found a solution how to hide Instant commands button?
