### ISSUE TITLE
Disable onLongPress message panel

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#41]
![image](https://user-images.githubusercontent.com/41714881/80196575-cab6d080-8647-11ea-89b5-72ccaaafcbfc.png)

is there a way to disable that panel?

**Comment by imtoori** [comment]
Hi @brizaldi 

You can pass a function to `MessageListView` specifying what to instead of showing the panel

```dart
                MessageListView(
                  onMessageActions: (context, message) {},
                )
```

If you use a function like that one, nothing will happen

**Comment by brizaldi** [comment]
![image](https://user-images.githubusercontent.com/41714881/80197638-19189f00-8649-11ea-91fe-788b535173c0.png)
what about this panel? is it also customizable?

**Comment by imtoori** [comment]
At the moment you can only disable the attachment button

I was thinking that it could be interesting to add a parameter to pass as many actions as you want, like the `actions` argument of the `AppBar`.
In this way, you could disable the attachment button and add your custom button. 

Do you think it's a good idea?

**Comment by brizaldi** [comment]
yeah that's a good idea, i think every component should customizable and let the user choose what style/action for each component

**Comment by imtoori** [comment]
that's the ultimate goal, it's a matter of time

I'll close this issue and implement the customizable actions for `MessageInput`

**Comment by imtoori** [comment]
#43 
@brizaldi  Could you tell me what do you think of this solution?
