### ISSUE TITLE
Stream Chat Persistence : SortOption requires a comparator in order to sort

### ISSUE THREAD

**Issue by zevain** [GetStream/stream-chat-flutter#417]
**Describe the bug**
Error in debug mode whenever i use Stream Chat Persistence saying "SortOption requires a comparator in order to sort"

**What package are you using? What version?**
Stream Chat Flutter 1.5.4 and Stream Chat Persistence 1.5.2

**What platform is it about?**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Depends on stream chat persistence
2. Go to the channel list using the stream chat persistence plugin with debug mode
3. Debug mode shows error saying "SortOption requires a comparator in order to sort" and the apps will throw error widget saying "Error loading channels" with Retry button

**standard filter and sort option**
```
            filter: {
              'members': {
                '\$in': [StreamChat.of(context).user.id],
              }
            },
            sort: [
              SortOption('last_message_at', direction: SortOption.DESC)
            ],
            options: {
              'state': true,
              'watch': true,
              'presence': true,
            },
```

**Comment by imtoori** [comment]
that's because a comparator is required in order to apply the correct sort options to the offline channels
try replacing your SortOption with this 
```dart
              SortOption(
                  'last_message_at', 
                   direction: SortOption.DESC,
                   (ChannelModel a, ChannelModel b) {
                       final dateA = a.lastMessageAt ?? a.createdAt;
                       final dateB = b.lastMessageAt ?? b.createdAt;
                       return dateB.compareTo(dateA);
                   },
               )
```

or you can even remove it because that's the default SortOptions

**Comment by zevain** [comment]
@imtoori Thank you so much for the help, i really appreciate it.
