### ISSUE TITLE
Could Not Receive Notification Data When In Background

### ISSUE THREAD

**Issue by davidwijayanto2** [GetStream/stream-chat-flutter#418]
Hi, I'm currently develop application using stream_chat 0.2.23+3, i have an issue when implementing push notification following this guide https://getstream.io/chat/docs/flutter-dart/flutter_push/ I'm using FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler) to receive notification in background. When i'm terminate the app, its received the message but have null notifications data like body and title. I tested it using android Pocophone F1. Could you kindly help me fix this issue? Thank you.

**Screenshots**
![image0](https://user-images.githubusercontent.com/58428572/117258984-ca1a6200-ae77-11eb-9aef-d24dba2c444f.jpeg)

Paste the output of running `flutter doctor -v` here.
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-ID)
    • Flutter version 2.0.5 at /Applications/development/mobile/flutterSDK/flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/berkatbejana/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • POCOPHONE F1 (mobile) • 18baef7d • android-arm64 • Android 10 (API 29)

**Comment by imtoori** [comment]
Hi @davidwijayanto2 
have you tried customizing the notification template in your stream dashboard?

**Comment by davidwijayanto2** [comment]
currently I'm following this template

**Comment by imtoori** [comment]
Can I ask you to contact support for this?
They'll ask for your API key to better address the issue
https://getstream.io/contact/support/
