### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#419]
Hi Team,
Thanks a lot for your hard work, null safety version is available, that's great.

1- WIll "https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1" be migrated too ? (Some component are gone)
2- Do you have a migration for Filter ?

```dart
//old
final filter = {'cid': 'messaging:${dm.replaceAll('dm_', '')}'};
//new
Filter.in_('cid', ['messaging:${dm.replaceAll('dm_', '')}']);
```
This one is easy, but autocomplete is not clear for me :)

Nelson,
Thank you,

**Comment by xsahil03x** [comment]
@Abacaxi-Nelson 

```dart
// old 
filter: {'name': {'\$autocomplete': query}}

// new
Filter.autoComplete('name', query)
```

**Comment by imtoori** [comment]
About the sample apps, we're migrating them! :)

**Comment by Abacaxi-Nelson** [comment]
Thanks @xsahil03x @imtoori
