### ISSUE TITLE
Step by step for push notification

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#42]
is there a tutorial/example/step by step of how to implements push notification on iOS & android?

**Comment by imtoori** [comment]
The Flutter SDK does not offer any default implementation for push notification, so you should implement it yourself.

However, the alpha release of the library disconnects the client when the app is in the background. In this way, the backend will send notifications. 
At [this link ](https://getstream.io/chat/docs/push/?language=js), you can find a draft of the documentation that will be released once the alpha version becomes stable.
If you are willing to try out the alpha version, do not hesitate to ask for help. You can also reach me out on this repo [gitter channel](https://gitter.im/GetStream/stream-chat-flutter?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) 

By the way, note that it's possible to configure notifications also in the current stable version. Make sure to configure firebase/apn correctly and call `client.disconnect` when the app is in background
