### ISSUE TITLE
Allow a custom message list header or footer

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#422]
**Is your feature request related to a problem? Please describe.**
I'm trying to show a custom, entirely local, header widget above my message list (i.e. effectively the first 'message' in the list above the server-side messages). I don't need any other customizations, but right now I have to create a local copy of message_list.dart to do this.

**Describe the solution you'd like**
Add a 'header' and 'footer' Widget property to MessageListView, defaulted to empty SizedBox() (or some other zero-sized placeholder)

**Describe alternatives you've considered**
I've considered creating a system message when the channel is created.

**Comment by jgadsby** [comment]
Alternatively, is there a way to trigger a system message to a channel when it is first created / doesn't exist?

**Comment by imtoori** [comment]
This is a good idea, I'm adding it to our backlog
I think the best solution for the moment is to send a system message.
Are you creating channels client side?

**Comment by jgadsby** [comment]
@imtoori That works for me. Yes, I'm creating channels client-side, and I also noticed that sending a message with type set to 'system' doesn't seem to make a difference. How does the client send system messages?

**Comment by jgadsby** [comment]
Sweet! Thank you! Do I need to pass anything for the map of channelData? I tried null but that prevents the message from being sent. I guess it could just be an empty map?

**Comment by imtoori** [comment]
yes, or even better the existing extradata map you already have in the channel, because otherwise they'll be wiped out

**Comment by imtoori** [comment]
this is in develop, will be available in the next release as always :)
