### ISSUE TITLE
How to access the default chat UI?

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#423]
@Nash0x7E2 Hi, I'm struggling a little on how to just return the default chat message UI in some cases - because 'buildMessage' is a complex function that lives inside MessageListViewState, and MessageListView just checks to see if the entire builder is null before using the defaults:

```MessageListView(
              messageBuilder: (context, messageInfo, messages) {
                if (messageInfo.message.extraData.isNotEmpty) {
                  return MyCustomMessageWidget();
                } else {
                  return ????????? <I want to just return the default chat message widget here>
                }
              },`

**Comment by imtoori** [comment]
The problem is that the look of the message depends on the previous and following message in the default implementation.

But I guess we could expose a function like `buildDefaultMessage` that takes the messageinfo and returns the very default implementation.
I'll let you know when we do it

**Comment by jgadsby** [comment]
Thank you! That would be great. I suppose it's not a priority if I'm able to send and format system messages based on their extraData (see other issue I started)

**Comment by imtoori** [comment]
The solution for this is on `develop` 
The next release will support `MessageWidget.copyWith` to customize the default implementation
I think this is gonna solve many problems 😄
