### ISSUE TITLE
[Bug?] _CastError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#424]
**Describe the bug**
Hi team,
I have not migrate yet, but use your last migrated version.

im getting:
![image](https://user-images.githubusercontent.com/556990/117585808-ba6b7980-b114-11eb-8eca-9ace213f2479.png)

**What package are you using? What version?**

```dart
stream_chat_persistence: ^2.0.0-nullsafety.1
stream_chat_flutter: ^2.0.0-nullsafety.3
```

**What platform is it about?**
- [ ] Android
- [X ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

Thanks, Nelson

**Comment by Nash0x7E2** [comment]
Hi, thank you for filing this issue! 

Can you please share the output of `flutter doctor --verbose`?

**Comment by Abacaxi-Nelson** [comment]
Sure @Nash0x7E2 

```dart
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H1210 darwin-x64, locale fr-FR)
    • Flutter version 2.0.6 at /Applications/flutter
    • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nelson/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/nelson/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • iPhone (mobile) • bd6ca3ac71ea7bfceacaf9c03f2282312d475103 • ios            • iOS 11.4
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

Just for information, i remove persistence, and error goes away..

**Comment by Nash0x7E2** [comment]
I tagged @imtoori and @xsahil03x from our Flutter team, they'll investigate further and provide feedback.

**Comment by imtoori** [comment]
@Abacaxi-Nelson when does this happen?

**Comment by Abacaxi-Nelson** [comment]
hi @imtoori 
Listing channels (ChannelListView component)

**Comment by imtoori** [comment]
@Abacaxi-Nelson can you try uninstalling and reinstalling the app?
We didn't bump the db version and if you had some db data before upgrading sometimes you can get this kind of errors
Can you check please? I'm trying to reproduce it, but I'm not succeeding

**Comment by rohan20** [comment]
Hi, we have the same error. Happens on `ChannelListView` but not really sure under what conditions. We've tried reinstalling the app as well.

![image](https://user-images.githubusercontent.com/8232573/122397039-de727400-cf78-11eb-9225-c47e4541a4bf.png)

`$ flutter doctor`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.53.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by imtoori** [comment]
@rohan20 the 0.x version doesn't support nullsafety, and it's really old (we had version 1.x, and we're going for 2.x with nullsafety support and a lot of improvements)

I think your error is not the same as the one @Abacaxi-Nelson posted
I can try reproducing this btw
