### ISSUE TITLE
Customise TextOverflow property in ChannelName

### ISSUE THREAD

**Issue by hashirshoaeb** [GetStream/stream-chat-flutter#427]
**Is your feature request related to a problem? Please describe.**
Hi I'm using [`ChannelName`](https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter/lib/src/channel_name.dart#L10) class. And want to change text overflow style from `TextOverflow.ellipsis` to `TextOverflow.fade`. To made the desired change, I had to copy the whole class.

https://github.com/GetStream/stream-chat-flutter/blob/d297cf608cfb5c1207370f2f2573bbd4d0d1cb9d/packages/stream_chat_flutter/lib/src/channel_name.dart#L74

**Describe the solution you'd like**
Updating API like below, will let other developers to overriding the overflow style.
```diff
  const ChannelName({
    Key? key,
    this.textStyle,
+   this.overflow = TextOverflow.ellipsis
}) : super(key: key);
```

**Describe alternatives you've considered**
Or maybe giving a method to override. 
```dart
  @override
  Text customTextStyle(String title);
```

**Comment by deven98** [comment]
The PR for the fix has been merged into develop and should make it into next release soon. 
Please feel free to reopen this if any other issues arise. 
Thanks for bringing this to our attention!
