### ISSUE TITLE
customise styling 

### ISSUE THREAD

**Issue by hashirshoaeb** [GetStream/stream-chat-flutter#434]
I have a question:

how can I customise the icon color (close icon to go back). that is on the top left of the image previewer screen.  Is there any options available in `StreamChatThemeData` class for this?

<img src="https://user-images.githubusercontent.com/35165481/118503190-d342e300-b743-11eb-8176-71b53cc9facb.png" width=400 />

**Comment by imtoori** [comment]
Hi and thanks for the question
The icon takes the color from `themeData.colorTheme.black`
At the moment it's not easy to change its color without changing the color of other stuff, we'll take it into consideration and try and find a way to do this in the cleanest way

**Comment by hashirshoaeb** [comment]
i tried changing the `themeData.colorTheme.black` property but didn't workout.

**Comment by imtoori** [comment]
Can you paste a snippet showing me how you're doing it?

**Comment by hashirshoaeb** [comment]
Sorry my bad. Changes showed up later on hot restart. A big thanks for your help. ⭐

**Comment by hashirshoaeb** [comment]
> Hi and thanks for the question
> The icon takes the color from `themeData.colorTheme.black`
> At the moment it's not easy to change its color without changing the color of other stuff, we'll take it into consideration and try and find a way to do this in the cleanest way

@rubenvereecken and I are looking forward to it. ❤️

**Comment by imtoori** [comment]
@hashirshoaeb can I ask you how you got this ui? what did you change? 
![image](https://user-images.githubusercontent.com/20601437/119670331-16364200-be39-11eb-8b83-c8890d94e0e4.png)

**Comment by hashirshoaeb** [comment]
Is it not reproducible?  I tried to fix it by changing `themeData.colorTheme.black` but it also changes the color of bottom icons. So reverted it.

**Comment by GroovinChip** [comment]
@hashirshoaeb This issue is fixed now as of #546. Heads up that `ImageFooter` and `ImageHeader` have been renamed to `GalleryFooter` and `GalleryHeader`, and they now have their own theme data classes and inherited themes. You can check out that PR for more information.

I hope this helps! Have a great day!
