### ISSUE TITLE
Cannot Customize Reactions

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#437]
When trying to use:
```
StreamChatThemeData(
              reactionIcons: []
            ),
```
The ReactionIons class is not accessible.

**Comment by imtoori** [comment]
You can import it like this 
```dart
import 'package:stream_chat_flutter/src/reaction_icon.dart';
```

I'll make it accessible in the next release
Sorry about this and thank you for pointing it out

**Comment by rlee1990** [comment]
@imtoori is there any documentation on how we change the reaction icons? 
I added an image to my assets that shows up in other locations but when I try to use it as a reaction icon it gives errors then does not show. Should they all be SVGs?

**Comment by imtoori** [comment]
@rlee1990 yes, it should be an Svg
We'll work on abstracting it to allow any widget to be used as a reaction icon, I think it makes sense. Just added that to our backlog. For the moment please use an svg

**Comment by rlee1990** [comment]
Thanks @imtoori for the clarification.
