### ISSUE TITLE
Want to upload files larger than 20 MB

### ISSUE THREAD

**Issue by saurabh02ezest** [GetStream/stream-chat-flutter#439]
**Describe the bug**
Files less than 20 MB will gets uploaded to default CDN, but want to upload files larger than 20 MB (upto fixed limit, eg. 100MB, 200MB....) to own CDN (Firebase Storage).

Have been through the documentation - https://getstream.io/chat/docs/flutter-dart/file_uploads/?language=dart 
and done following changes whatever understood from the documentation.

Made own implementation of the *AttachmentFileUploader* interface, called *MyFileUploader* by referring -
https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat/lib/src/attachment_file_uploader.dart#L58

```
class ChatRepository {

//code

static StreamChatClient client;

client = StreamChatClient( 
  'api-key', 
  logLevel: Level.SEVERE,
  attachmentFileUploader: MyFileUploader(), 
); 

//code

}
```

```
class MyFileUploader implements AttachmentFileUploader {
  @override
  Future<SendImageResponse> sendImage(
    AttachmentFile file,
    String channelId,
    String channelType, {
    ProgressCallback onSendProgress,
    CancelToken cancelToken,
  }) async {
    final filename = file.path?.split('/')?.last ?? file.name;
    final mimeType = filename.mimeType;
    MultipartFile multiPartFile;

    if (file.path != null) {
      multiPartFile = await MultipartFile.fromFile(
        file.path,
        filename: filename,
        contentType: mimeType,
      );
    } else if (file.bytes != null) {
      multiPartFile = MultipartFile.fromBytes(
        file.bytes,
        filename: filename,
        contentType: mimeType,
      );
    }

    final response = await ChatRepository.client.post(
      'FirebaseStorage URL with https included and user has path access',
      data: FormData.fromMap({
        'file': multiPartFile,
      }),
      onSendProgress: onSendProgress,
      cancelToken: cancelToken,
    );
    return _client.decode(response.data, SendImageResponse.fromJson);
  }

  @override
  Future<SendFileResponse> sendFile(..) async{ //code }

  @override
  Future<EmptyResponse> deleteImage(...) async { //code}

  @override
  Future<EmptyResponse> deleteFile(...) async { //code }
}
```

with above implementation tried to send image which has size less than 1 MB still it didn't work (getting socket exception).

**What package are you using? What version?**
   stream_chat_flutter: ^1.5.4
   
   flutter sdk version : 2.0.5

**What platform is it about?**
- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by imtoori** [comment]
Hi @saurabh02ezest 
I'm trying the code you posted, but I'm pretty sure it doesn't work

```dart
    return _client.decode(response.data, SendImageResponse.fromJson);
```

the response from firebase is not the same as the one from our backend. 
You need to parse it properly and map it to the `SendImageResponse` class

Feel free to reopen the issue if you're still confused

**Comment by saurabh02ezest** [comment]
> Hi @saurabh02ezest
> I'm trying the code you posted, but I'm pretty sure it doesn't work
> 
> ```dart
>     return _client.decode(response.data, SendImageResponse.fromJson);
> ```
> 
> the response from firebase is not the same as the one from our backend.
> You need to parse it properly and map it to the `SendImageResponse` class
> 
> Feel free to reopen the issue if you're still confused

@imtoori What is the use of '**[duration](https://pub.dev/documentation/stream_chat/latest/stream_chat/SendImageResponse/duration.html)**' in [SendImageResponse](https://pub.dev/documentation/stream_chat/latest/stream_chat/SendImageResponse-class.html) and [SendFileResponse](https://pub.dev/documentation/stream_chat/latest/stream_chat/SendFileResponse-class.html)?

Its okay if we don't pass  '**[duration](https://pub.dev/documentation/stream_chat/latest/stream_chat/SendImageResponse/duration.html)**' while parsing?

**Comment by imtoori** [comment]
the duration is a field populated by our backend that tells us how much time it took to resolve the request
it's just debugging property, so yes, you can ignore it or assign a dumb value
