### ISSUE TITLE
Dependency Fails to Build on Web

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#444]
**Describe the bug**
Heads up, substring_highlight makes builds fail on web with the following error:
```
Target dart2js failed: Exception: /opt/hostedtoolcache/flutter/2.2.0-beta/x64/.pub-cache/hosted/pub.dartlang.org/substring_highlight-1.0.26/lib/substring_highlight.dart:5:27:
Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
const int int64MaxValue = 9223372036854775807; //HACK
                          ^^^^^^^^^^^^^^^^^^^
```

**What package are you using? What version?**
2.0.0-nullsafety.3

**What platform is it about?**
- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by imtoori** [comment]
I just opened a pr for fixing that https://github.com/remoteportal/substring_highlight/pull/14

**Comment by searchy2** [comment]
Nice, your PR is merged. When can we expect an updated Stream SDK?

**Comment by imtoori** [comment]
We'll release an update as soon as possible, even if I think you should be able to get the updated version of substring_highlight with a `flutter clean` `flutter pub upgrade`
