### ISSUE TITLE
How to listen for new messages to display badge outside of chat

### ISSUE THREAD

**Issue by Chojecki** [GetStream/stream-chat-flutter#445]
Hi we are implementing get stream chat and designer wants to display "new message badge" in bottomNavigationBar.

Can some one explain me how to listen for this event? I have all chat (client, connection etc.) configured and the chat is functional via our backend, so I guess everything is ready and I just need some kind of listener.

**Comment by imtoori** [comment]
hey @Chojecki do you need an unread count? Or just to get when a new message arrives?

**Comment by Chojecki** [comment]
Just info about "there is new unread message (at least one)", so no count needed

**Comment by imtoori** [comment]
you can use something like `client.state.totalUnreadCountStream`
and a `StreamBuilder` to build that kind of ui
