### ISSUE TITLE
Emoji as reactions

### ISSUE THREAD

**Issue by Chojecki** [GetStream/stream-chat-flutter#451]
I would like to add emoji icons as reactions

We are keeping reactions as remote config for A/B tests and we are just fetching them as `String` from our backend, so all we want to do is give ability to display reactions as Strings. Right now it's only SVG's as I understand.

**Comment by imtoori** [comment]
Hi and thanks for the request!
This is in our backlog and we'll address it as soon as possible

**Comment by Chojecki** [comment]
cool thanks

**Comment by imtoori** [comment]
This feature is available in the `develop` branch
It will be included in the next nullsafety release
