### ISSUE TITLE
connectUser only once

### ISSUE THREAD

**Issue by zevain** [GetStream/stream-chat-flutter#455]
Do we need to call the connectUser everytime we reopen the apps?
In my case, its kinda taking 2-5 secs before i got connected, and everytime i close the apps and reopen it, i must wait 2-5 secs again to get connected.

Thanks in advance.

**Comment by xsahil03x** [comment]
Hey @zevain, yes we advise disconnecting and connecting the WebSocket again when the app goes into the background. Maybe if you can share what package version you are using and some code, we might help you better.

**Comment by zevain** [comment]
Hi @xsahil03x , thanks for the answer.
I used Stream Chat Flutter 1.5.4 right now.
Its really not a problem. Based on your answer, i just need to adjust the code for my user no need to wait the connectUser method.
Thank you.

**Comment by xsahil03x** [comment]
Hey @zevain, if you are using `stream_chat_flutter` you don't really have to do anything we handle it automatically using the `StreamChat` widget.

https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter_core/lib/src/stream_chat_core.dart#L110

**Comment by zevain** [comment]
Yes @xsahil03x , but before we can get the list of the channels, do we still need to call the connectUser method ? Because i got an error after i close the apps, then if i reopen it without calling the connectUser method, it throw an error.

**Comment by xsahil03x** [comment]
@zevain can you share what you are actually doing in `ListChannel`. I can't help much without looking at the code.

**Comment by zevain** [comment]
@xsahil03x  Sorry for my bad explanation.

Step on my apps:
1.a. Login using username and password provided, save the user and pass to the ``sharedpreference`` then do the ``connectUser``
1.b. If i already got the user and pass saved, then just do the ``connectUser``
2. I got the channel list like usual and the behavior is as expected
3. Close the apps
4. Reopen the apps and it repeat the step 1.b. above

The problem is, ``connectUser`` method sometimes takes time to get connected ( around 2-5 secs in my case ), and in my apps it seems like the apps is lagging around that time ( because the user have to wait ).

My question is, if i did the step 1.a above once, do i need to call the ``connectUser`` again on step 1.b to use the StreamChat ? 
Can i just call the ``connectUser`` only once ( when the user login on step 1.a ) until the user decided to log out or uninstall the apps, so when the user closed the apps or restarted the phone, once he/she reopen the apps, he/she dont have to wait the ``connectUser`` again ?

And for the code you asked, actually all of it is working as expected, it just i wonder about the question above.

Main.dart
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setupLocator();
  await Firebase.initializeApp();
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'xXx',
        theme: ThemeData(
          primaryColor: Color.fromRGBO(255, 255, 255, 1),
          primaryTextTheme:
              TextTheme(headline6: TextStyle(color: Colors.black54)),
          inputDecorationTheme: InputDecorationTheme(
            labelStyle: TextStyle(
              color: Colors.black54,
            ),
          ),
        ),
        builder: (context, child) {
          return StreamChat(
            client: locator<ChatService>().client,
            child: child,
          );
        },
        home: Scaffold(resizeToAvoidBottomInset: true, body: LoginScreen()));
  }
}
```

Login.dart ( partial reference to step 1.b above )
```
getCredential() async {
    setState(() {
      _isInAsyncCall = true;
    });
    SharedPreferences prefs = await SharedPreferences.getInstance();
    if (prefs.getString("userId") != null) {
      final client = locator<ChatService>().client;
      if (client.wsConnectionStatus != ConnectionStatus.connected) {
        await client.connectUser(
          User(
            id: prefs.getString("userId"),
            extraData: {
              'name': StringUtils.capitalize(prefs.getString("userName")),
            },
          ),
          prefs.getString("userToken"),
        );
      }
      setState(() {
        Navigator.pushReplacement(
          context,
          CupertinoPageRoute(builder: (context) => new HomeScreen()),
        );
      });
    } else {
      setState(() {
        _isInAsyncCall = false;
      });
    }
  }
```

Home.dart
```
Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        backgroundColor: Color.fromRGBO(5, 37, 17, 1),
        onPressed: () async {
          await Navigator.push(
              context,
              new CupertinoPageRoute(
                  builder: (BuildContext context) => new NewChannel()));
        },
      ),
      appBar: new AppBar(title: Text("Channel List")),
      body: ChannelsBloc(
        child: ChannelListView(
            filter: {
              'members': {
                '\$in': [StreamChat.of(context).user.id],
              },
            },
            options: {
              'state': true,
              'watch': true,
              'presence': true,
            },
            pagination: PaginationParams(limit: 50),
      ),
    );
  }
```

Thanks in advance.

**Comment by xsahil03x** [comment]
@zevain so by re-opening the app you mean clearing it from the stack and opening it again right? In that case, you always need to call `connectUser` before doing anything else. `connectUser` basically opens up a `web-socket` connection for the user and returns a `connectionId` which is required in order to call other API's

**Comment by xsahil03x** [comment]
@zevain I think we are good here, feel free to re-open if you have any more doubts 😄
