### ISSUE TITLE
How to change background color of streamchat widget. 

### ISSUE THREAD

**Issue by divyanshub024** [GetStream/stream-chat-flutter#46]
Hey!! I want to change the bg color of my StreamChat widget but even after changing the `streamChatThemeData` nothing works. 

This is what my code looks like
```
Chat.StreamChat(
                  client: controller.client,
                  streamChatThemeData: Chat.StreamChatThemeData.fromTheme(appTheme),
                  child: Chat.StreamChannel(
                    channel: controller.channel,
                    child: ChannelPage(),
                  ),
                ),
```

**Comment by imtoori** [comment]
Hey! Thanks for opening this issue 

In the last version, there is a property called `backgroundColor` in `StreamChatThemeData`
If you initialize the theme using `StreamChatThemeData.fromTheme` it will default to `theme.scaffoldBackgroundColor`, otherwise it will be `Colors.white`

Let me know if that works for you

**Comment by divyanshub024** [comment]
@imtoori I can see only these params in `StreamChatThemeData`.

```
StreamChatThemeData copyWith({
    Color primaryColor,
    Color secondaryColor,
    Color accentColor,
    ChannelPreviewTheme channelPreviewTheme,
    ChannelTheme channelTheme,
    MessageTheme ownMessageTheme,
    MessageTheme otherMessageTheme,
    Widget Function(BuildContext, Channel) defaultChannelImage,
    Widget Function(BuildContext, User) defaultUserImage,
    IconThemeData primaryIconTheme,
  })
```

**Comment by divyanshub024** [comment]
And I'm on version ` ^0.2.0-alpha+2`.

**Comment by imtoori** [comment]
Can you try version `0.2.0-alpha+15` or the stable `0.1.35`? I just released those versions

**Comment by divyanshub024** [comment]
@imtoori Cool, I'll try that. Is there a place where I can see changelogs for alpha version?

**Comment by imtoori** [comment]
https://pub.dev/packages/stream_chat_flutter/versions/0.2.0-alpha+15#-changelog-tab-
There is no other place than the pub at the moment 

By the way thanks for trying the alpha version

**Comment by divyanshub024** [comment]
It's my pleasure to test cool things you guys are doing in alpha version.
