### ISSUE TITLE
Custom action on "menu (three dots)" button

### ISSUE THREAD

**Issue by Chojecki** [GetStream/stream-chat-flutter#461]
Hi, is that possible to add custom action for menu button in chat list cell after swipe? Right now it opens bottom sheet with chat overview and as I see in source code, it's hardcoded for `ChannelListView`. I think it's just few lines to add custom action there.

<img width="376" alt="Screenshot 2021-05-27 at 15 44 54" src="https://user-images.githubusercontent.com/20075941/119837054-86f56100-bf02-11eb-9487-7e30d513ea9c.png">

**Comment by deven98** [comment]
Hey @Chojecki, we're working on this as we speak and I'll let you know when the solution is merged.

**Comment by deven98** [comment]
Hey @Chojecki, 

The PR for the fix (https://github.com/GetStream/stream-chat-flutter/pull/465) was merged into develop.
You can now customize the default action callbacks as well as substitute them with your own.

I hope this solves your problem. 

Thanks for bringing this to our attention and please feel free to reopen or file a new issue if you require anything else. 

Thanks!
