### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by rvvarasdiya** [GetStream/stream-chat-flutter#466]
**Is your feature request related to a problem? Please describe.**
Integrate a stream is easy, But versioning dependencies which are depending on the stream version are hard to manage.

**Describe the solution you'd like**
Please update all the dependencies which you use in this package. So We also can use the latest version of the third-party dependencies.

**Describe alternatives you've considered**

**Additional context**

**Comment by deven98** [comment]
Hey @rvvarasdiya,

We're currently working on a stable release of null safety which will contain a significant number of changes.
To get the latest version immediately, try using the `develop` branch which will contain a number of package updates.

If there is something else that we can help you with, feel free to let us know. 

Thanks.

**Comment by rvvarasdiya** [comment]
Thank you, Deven.

**Comment by deven98** [comment]
I'm closing this issue for now.

If you see any irregularities or anything which isn't updated on develop, please feel free to reopen this.

Thanks!

**Comment by imtoori** [comment]
you can also use the nullsafety version of the packages https://pub.dev/packages/stream_chat_flutter/versions/2.0.0-nullsafety.4
