### ISSUE TITLE
Don't override app theme in StreamChat widget

### ISSUE THREAD

**Issue by paynekw** [GetStream/stream-chat-flutter#467]
**Describe the bug**
This is more of a design quirk than a bug. Following the documentation [here](https://getstream.io/chat/flutter/tutorial/#add-stream-chat-to-your-flutter-application), a `builder` is used to wrap the app in a `StreamChat` widget. In `StreamChat`'s `build` method, the following code overrides any `scaffoldBackgroundColor` that has been set in the `MaterialApp`'s `theme`.

From `build` method of `StreamChat`
```
            return Theme(
              data: materialTheme.copyWith(
                primaryIconTheme: streamTheme.primaryIconTheme,
                accentColor: streamTheme.colorTheme.accentBlue,
                scaffoldBackgroundColor: streamTheme.colorTheme.white, <------------
              ),
```

**What package are you using? What version?**
`stream_chat_flutter: ^2.0.0-nullsafety.4`

**What platform is it about?**
- [✔] Android
- [✔] iOS
- [✔] Web
- [✔] Windows
- [✔] MacOS
- [✔] Linux

**To Reproduce**
1. Try to customize the `scaffoldBackgroundColor` on the `MaterialApp` via its `theme` property.
2. The `StreamChat` widget will override any value set in 1.) above and force the color to be white.

**Expected behavior**
The `scaffoldBackgroundColor` set in 1.) above should persist and not be overridden.

**Comment by deven98** [comment]
Hey @paynekw,

Nice spot, I will let you know once the fix is merged. 

Thanks!

**Comment by imtoori** [comment]
This has been fixed with this pr https://github.com/GetStream/stream-chat-flutter/pull/559
It's in develop and you'll find it in the next release
