### ISSUE TITLE
StreamChat is overriding onGenerateRoute when navigating using named route

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#47]
**Expected results:**

When using Navigator.pushNamed it goes to my own `onGenerateRoute` from my `main.dart`

**Actual results:**

instead it goes to `onGenerateRoute` inside `stream_chat.dart`:
```
child: Navigator(
  initialRoute: '/',
  key: _navigatorKey,
  onGenerateRoute: (settings) {
    return MaterialPageRoute(
      settings: settings,
      builder: (_) => widget.child,
    );
  },
),
```

**Comment by imtoori** [comment]
We added a navigator to make the StreamChat widget always be on top of the widget tree.
This approach is not the best and we should refactorize it finding a good compromise between usability and convenience.
The point is to make the user write as less code as possible to make a working app.

I'll think about it and hopefully come with a better solution.

For the moment you can try to use 
`Navigator.of(context, rootNavigator: true).pushNamed('/test'),`

**Comment by brizaldi** [comment]
now i get this error when i call `StreamChat.of(context).client` : 

`You must have a StreamChat widget at the top of your widget tree`

**Comment by imtoori** [comment]
Are you trying to use `StreamChat.of` in your new route?
The problem is that once you push a new route, the `StreamChat` widget is not in your current widget tree anymore.
You may want to take a look at this https://stackoverflow.com/questions/49968817/flutter-inherited-widget-and-routes

A possible solution is to put the widget `StreamChat` in the builder method of your `MaterialApp` (like this answer https://stackoverflow.com/questions/49328362/get-access-to-the-context-of-inheritedwidget/49329255#49329255) 
 I think that's a better solution and in the next version, we can get rid of the additional Navigator (it was a workaround for this situation) suggesting to put the `StreamChat` widget there.

**Comment by imtoori** [comment]
Could you try the last version using the `StreamChat` widget in the builder method of the `MaterialApp`?

**Comment by brizaldi** [comment]
after using the last version and put `StreamChat` inside the builder, i can confirm that its working perfectly now, thank you for the quick response and maybe you can close this issue

**Comment by imtoori** [comment]
Thank you for reporting the issue :)

**Comment by pixnbit** [comment]
I was confused with that builder usage under MaterialApp and got rid of it, then I saw the same message error. I also use named routes. 
It's not a clean solution, having the StreamChat initialized this early and at such high scope. Look forward to the better solution. And in the meantime, maybe you can comment in the sample code that `builder:` was a temporary hack.

**Comment by imtoori** [comment]
I think that's true, but you can always just initialize the client and call `client.setUser` deeper in the tree.
That was the simplest way to avoid to pass the `StreamChat` widget on every `Navigator.push`.

We're trying to find a better solution by the way.

**Comment by siddhartha2000v** [comment]
> I think that's true, but you can always just initialize the client and call `client.setUser` deeper in the tree.
> That was the simplest way to avoid to pass the `StreamChat` widget on every `Navigator.push`.
> 
> We're trying to find a better solution by the way.



> I think that's true, but you can always just initialize the client and call `client.setUser` deeper in the tree.
> That was the simplest way to avoid to pass the `StreamChat` widget on every `Navigator.push`.
> 
> We're trying to find a better solution by the way.

@imtoori just wanted to check if this issue was resolved in the latest version.I am working on an application and dont want to initialise the client above authentication. I am getting the same error quoted above 'You must have a StreamChat widget at the top of your widget tree'

**Comment by siddhartha2000v** [comment]
Thanks for the update @imtoori. I am able to resolve the issue using the builder parameter in material app. However was looking for the update on better solution. Thanks for helping with current status anyways.

**Comment by barancezayirli** [comment]
it is a really bad design choice I think. The chat itself would require authentication (need to get a token for a specific user min). And as far as I see, no plan to change it :/

I am building an app, not concentrated on chat but have chat with as an extra feature. Users should log in (this is where they will get the token with their id). When a first-time user opens the app, there is no user so no token.

Furthermore, users can log out and log in with different credentials. That time the client will be initialized with a different token.

Any suggestions on what can I do without putting StreamChat into the builder?

**Comment by luvishq** [comment]
@barancezayirli : were you able to solve the issue ? I am in a similar situation right now . @imtoori : any solution for this ?
