### ISSUE TITLE
When chatting continuously then message not receiving after some time, Getting exceptions.

### ISSUE THREAD

**Issue by Okdone** [GetStream/stream-chat-flutter#48]
I am using version: 0.2.1-alpha+1.
I am facing some issues.

When we are chatting with each other then after some time message not received and getting exception like this.
Getting error:
1) Message is received but not display the error is like database:
E/flutter ( 5438): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: "SqliteException(5): database is locked, database is locked (code 5)"
E/flutter ( 5438): #0      PreparedStatement.execute (package:moor_ffi/src/impl/prepared_statement.dart:96:7)
E/flutter ( 5438): #1      _VmDelegate._runWithArgs (package:moor_ffi/src/vm_database.dart:72:12)
E/flutter ( 5438): #2      _VmDelegate.runInsert (package:moor_ffi/src/vm_database.dart:84:11)
E/flutter ( 5438): #3      _ExecutorWithQueryDelegate.runInsert.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:69:19)
E/flutter ( 5438): #4      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter ( 5438): #5      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
E/flutter ( 5438): #6      _ExecutorWithQueryDelegate.runInsert (package:moor/src/runtime/executor/helpers/engines.dart:67:12)
E/flutter ( 5438): #7      LazyDatabase.runInsert (package:moor/src/utils/lazy_database.dart:60:17)
E/flutter ( 5438): #8      _MoorServer._runQuery (package:moor/src/runtime/isolate/server.dart:87:25)
E/flutter ( 5438): <asynchronous suspension>
E/flutter ( 5438): #9      _MoorServer._handleRequest (package:moor/src/runtime/isolate/server.dart:57:14)
E/flutter ( 5438): #10     IsolateCommunication.setRequestHandler.<anonymous closure> (package:moor/src/runtime/isolate/communication.dart:163:31)
E/flutter ( 5438): #11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
E/flutter ( 5438): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter ( 5438): #13     _DelayedData.perform (dart:async/stream_impl.dart:593:14)
E/flutter ( 5438): #14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
E/flutter ( 5438): #15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
E/flutter ( 5438): #16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 5438): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 5438): #18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
E/flutter ( 5438): #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

2) If we satay on screen then after some time getting error like this.
The getter 'values' was called on null.
Receiver: null
Tried calling: values

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _MessageWidgetState._updateReactionPadding.<anonymous closure> (package:stream_chat_flutter/src/message_widget.dart:336:41)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
#4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)

**Comment by imtoori** [comment]
does it happen every time?

**Comment by RajKateshiya** [comment]
Yes, it is happening every time

**Comment by Okdone** [comment]
Yes, it is happening every time

**Comment by imtoori** [comment]
ok, thank you
could you try with the latest version `0.2.1-alpha+2`
I'm investing the problem

**Comment by Okdone** [comment]
Ok, i will check with "0.2.1-alpha+2"

**Comment by Okdone** [comment]
Have you released "0.2.1-alpha+2"?

**Comment by imtoori** [comment]
yes, last week I released the new version

**Comment by Okdone** [comment]
![img_20200518](https://user-images.githubusercontent.com/65529321/82193102-8e0e8a00-9912-11ea-85ac-a016b7f8c57e.png)

Can you check it, i can't find that version.

**Comment by imtoori** [comment]
I'm sorry, I forgot to push the tag.
For this kind of things I suggest looking at pub.dev https://pub.dev/packages/stream_chat_flutter

By the way, I'm releasing a new version with a small fix.
