### ISSUE TITLE
Keyboard covers input text box when editing message

### ISSUE THREAD

**Issue by poqueque** [GetStream/stream-chat-flutter#483]
**Describe the bug**
When editing a message the widget that shows the text to edit is covered by device keyboard

**What package are you using? What version?**
stream_chat_flutter: ^2.0.0-nullsafety.7

**What platform is it about?**
- [x] Android
- [x] iOS

**To Reproduce**
1. Go to a chat
2. Click on edit message
3. See error

**Expected behavior**
Edit message window appears above the keyboard

**Screenshots**
Added Video

https://user-images.githubusercontent.com/902418/122552888-2b1c8480-d037-11eb-9260-8d9ccabd369a.mp4

**Code **
This is the code used to display the chat page.

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: ChannelHeader(),
        body: Column(
          children: <Widget>[
            Expanded(
              child: MessageListView(),
            ),
            MessageInput(),
          ],
        ),
    );
  }
```

Paste the output of running `flutter doctor -v` here.

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale es)
    • Flutter version 2.2.1 at /Users/edi/development/flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/edi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/edi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

**Comment by imtoori** [comment]
Apparently flutter 2.2 breaks the previous behaviour 

https://stackoverflow.com/questions/53869078/how-to-move-bottomsheet-along-with-keyboard-which-has-textfieldautofocused-is-t
https://github.com/flutter/flutter/pull/77286/files

we'll fix it asap

Thanks a lot for reporting the issue!

**Comment by imtoori** [comment]
Fixed on develop
You'll find the fix in the next release
