### ISSUE TITLE
checkCommands: Null check operator used on a null value

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#484]
**Describe the bug**
When using the giphy command, the message '/giphy <search term>' gets sent rather than showing the giphy preview as in previous versions. Exiting the chat screen and returning will show the giphy preview as expected.

**What package are you using? What version?**
 stream_chat_flutter: ^2.0.0-nullsafety.7

**What platform is it about?**
- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Use the giphy chat command
2. Type a search term
3. Tap the search icon
4. See that instead of the preview, you see the text  '/giphy <search term>' rather than the preview.

**Expected behavior**
The giphy preview should show as soon as the search icon is tapped.

**Logs **
```
flutter: Null check operator used on a null value

#0      MessageInputState._checkCommands
package:stream_chat_flutter/src/message_input.dart:799
#1      MessageInputState._onChanged.<anonymous closure>
package:stream_chat_flutter/src/message_input.dart:721
#2      _rootRun (dart:async/zone.dart:1346:47)
#3      _CustomZone.run (dart:async/zone.dart:1258:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#5      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#6      _rootRun (dart:async/zone.dart:1354:13)
#7      _CustomZone.run (dart:async/zone.dart:1258:19)
#8      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
```

**Comment by deven98** [comment]
Hey @jgadsby, 

Thanks for reporting.

I will check the behaviour on the version you mentioned and get back to you shortly. 

Thanks!

**Comment by imtoori** [comment]
fixed in the develop :) you'll find it in the next release

**Comment by jgadsby** [comment]
Sweet! When are you planning on releasing this?

**Comment by imtoori** [comment]
probably next week
we're releasing a new version of the `stream_chat` package with a lot of improvements and some breaking changes
we need a couple of days to write changelogs and some information on how to migrate
