### ISSUE TITLE
Thread Reply Issue

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#487]
When we customize the MessageWidget we lose the default setup for threads and replies which we should still get unless we provide our own function or choose not to allow them. I think it would be better to have a bool to show the options of threads and replies and if true keep the default function unless a custom one is provided.

**Comment by deven98** [comment]
Hey @rlee1990,

The default setup for the threads and replies lies in the inbuilt `MessageWidget` which you can enable.
You can copy the implementation from there if you intend to fully use your own message widget. 

As for fully moving that implementation to the `MessageListView` instead of the `MessageWidget` - that will require some discussion with the team and I will get back to you on that.

Thanks.

**Comment by rlee1990** [comment]
@deven98 thanks for that. I wasn't asking to move it but just from looking at `MessageWidget` the onThreadTap function doesn't show a default option if you use the `messageBuilder`. You have to provide it yourself or the option is not there.

**Comment by rlee1990** [comment]
Here is my code:
```
messageBuilder: (context, messageDetails, messages) {
                    if (messageDetails.isMyMessage!) {
                      return MessageWidget(
                          showPinButton: true,
                          showUsername: false,
                          showTimestamp: true,
                          showSendingIndicator: true,
                          showUserAvatar: DisplayWidget.hide,
                          reverse: true,
                          showReplyMessage: true,
                          onThreadTap: (message) => AutoRouter.of(context).push(
                              ThreadPageRoute(
                                  parent: message, channel: widget.channel)),
                          showThreadReplyMessage: true,
                          showThreadReplyIndicator:
                              messageDetails.message.threadParticipants != null
                                  ? messageDetails
                                          .message.threadParticipants!.length >
                                      0
                                  : false,
                          showEditMessage: messageDetails.isMyMessage!,
                          message: messageDetails.message,
                          showDeleteMessage: messageDetails.isMyMessage!,
                          borderRadiusGeometry: BorderRadius.circular(12.0),
                          messageTheme: StreamChatTheme.of(context)
                              .ownMessageTheme
                              .copyWith(
                                  messageText: StreamChatTheme.of(context)
                                      .ownMessageTheme
                                      .messageText!
                                      .copyWith(
                                          color: widget
                                                  .channel!.extraData['isDark']
                                              ? Colors.white
                                              : Colors.black),
                                  messageBackgroundColor: Colors.transparent));
                    } else {
                      return MessageWidget(
                        showPinButton: true,
                        showUsername: true,
                        showTimestamp: true,
                        showSendingIndicator: true,
                        showReplyMessage: true,
                        onThreadTap: (message) => AutoRouter.of(context).push(
                            ThreadPageRoute(
                                parent: message, channel: widget.channel)),
                        showThreadReplyMessage: true,
                        showThreadReplyIndicator:
                            messageDetails.message.threadParticipants != null
                                ? messageDetails
                                        .message.threadParticipants!.length >
                                    0
                                : false,
                        showEditMessage: messageDetails.isMyMessage!,
                        showDeleteMessage: messageDetails.isMyMessage!,
                        message: messageDetails.message,
                        borderRadiusGeometry: BorderRadius.circular(12.0),
                        messageTheme:
                            StreamChatTheme.of(context).otherMessageTheme,
                      );
                    }
                  },
```
If i do not provide a function for `onThreadTap:` then the thread reply option does not show for any message same with replies and quoted messages.

**Comment by deven98** [comment]
@rlee1990 Gotcha,

Just confirming - you want to have the default behaviour of the onThreadTap available to use / as the default behaviour when you customise the MessageWidget, yes? (Default behaviour being opening the normal thread tap screen)

**Comment by rlee1990** [comment]
Yes @deven98 and the same for replies and quoted messages if possible. Because as of now we have to create our own functions for them when we customise the MessageWidget.

**Comment by deven98** [comment]
@rlee1990 Understood. 

This probably has a few different solutions, let me discuss and get back to you.

Thanks.

**Comment by rlee1990** [comment]
@deven98 thanks that sounds good.

**Comment by deven98** [comment]
Hey @rlee1990,

We're currently in the process of overhauling our `MessageWidget` to make it easier to use overall.
We'll try to make this easier in the same process. 
I'll let you know when the changes are merged.

Thanks.

**Comment by rlee1990** [comment]
@deven98 thanks.

**Comment by imtoori** [comment]
The solution for this is on `develop` 
The next release will support `MessageWidget.copyWith` to customize the default implementation
I think this is gonna solve many problems 😄

**Comment by rlee1990** [comment]
@imtoori am I able to try out the develop mode as of now?

**Comment by imtoori** [comment]
mmm, you could link the packages locally 

- `dart pub global activate melos`
- `git clone git@github.com:GetStream/stream-chat-flutter.git`
- `cd stream-chat-flutter`
- `melos bootstrap`

then you can go in the pubspec.yaml of your app and change

```yaml
dependencies:
  stream_chat_flutter: ^2.0.0-nullsafety.7
```

to 

```yaml
dependencies:
  stream_chat_flutter: 
    path: <path to packages/stream_chat_flutter/>
```

**Comment by rlee1990** [comment]
@imtoori thanks looks like It worked doing this also
```
stream_chat_flutter: 
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: ./packages/stream_chat_flutter
```

**Comment by xsahil03x** [comment]
@rlee1990 it won't work using this alone. You also need to override `stream_chat` and `stream_chat_flutter_core` dependencies.

so just add these too in pubspec
```dart
dependency_overrides:
	stream_chat: 
      	git:
          url: https://github.com/GetStream/stream-chat-flutter.git
          ref: develop
          path: ./packages/stream_chat_flutter
      
    stream_chat_flutter_core: 
      	git:
          url: https://github.com/GetStream/stream-chat-flutter.git
          ref: develop
          path: ./packages/stream_chat_flutter  
```

**Comment by rlee1990** [comment]
Thank you @xsahil03x just got an error for those packages.

**Comment by xsahil03x** [comment]
while running pub get or code errors?

**Comment by rlee1990** [comment]
@xsahil03x sorry I meant before adding them.

**Comment by xsahil03x** [comment]
Ohh sorry I forgot to change the path.... can you try again using this

> @rlee1990 it won't work using this alone. You also need to override `stream_chat` and `stream_chat_flutter_core` dependencies.
> 
> so just add these too in pubspec
> 
> ```dart
> dependency_overrides:
> 	stream_chat: 
>       	git:
>           url: https://github.com/GetStream/stream-chat-flutter.git
>           ref: develop
>           path: ./packages/stream_chat
>       
>     stream_chat_flutter_core: 
>       	git:
>           url: https://github.com/GetStream/stream-chat-flutter.git
>           ref: develop
>           path: ./packages/stream_chat_flutter_core  
> ```

**Comment by imtoori** [comment]
Ohh sorry @rlee1990 
i forgot those 🤦🏼‍♂️

**Comment by rlee1990** [comment]
Thanks.

**Comment by rlee1990** [comment]
@imtoori no worries

**Comment by xsahil03x** [comment]
@rlee1990 the LLC(`stream_chat`) might contain some breaking changes and we are currently in the process of writing migration. So feel free to ask if you face any error that you won't understand.

**Comment by rlee1990** [comment]
@xsahil03x will do I already ran into some so far I am able to get around.
