### ISSUE TITLE
Catching errors from the sdk

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#489]
Is there a way to catch the errors from the sdk such as when I banned user tries to send a message in a chat? As of now, I get an exception error but it would be nice to catch this somehow and display a message to the user.

**Comment by deven98** [comment]
Hey @rlee1990,

Just to get more info about this:

Are you trying to catch errors related to sending messages through input specifically or more generally for the sdk (missing permissions for example)?

**Comment by rlee1990** [comment]
I am using the sdk with the built-in ui and want to catch the errors for when things like a user sends a message but is banned.
@deven98

**Comment by deven98** [comment]
We've added this on our backlog, will let you know when the feature is merged.

**Comment by rlee1990** [comment]
@deven98 cool thanks.

**Comment by imtoori** [comment]
we added a `onError` parameter to the `MessageInput` 
it's already in develop and you're gonna find it in the next release
