### ISSUE TITLE
Incoming messages are not coming after a re-connection due to network change or connection reset

### ISSUE THREAD

**Issue by Okdone** [GetStream/stream-chat-flutter#49]
I am testing your Flutter Chat SDK "0.2.1-alpha+3" with offline capability which is critical for our use case. Reported a problem via GitHub page 2 days back and thanks for fixing the database exception quickly.

After trying the latest Alpha build one problem I have observed is incoming messages are not coming after a re-connection due to network change or connection reset, though outgoing messages are going after re-connection. If user manually refreshes the chats landing page by pull refresh, messages are being pulled from server by calling an API but until that is done manually messages are noting getting delivered to the client. What can we do to ensure message sent receive happens automatically as soon as server connection is established.

Also please let us know if we should report this kind of issues via support or should we post it on GitHub page, we will follow as you advise.

Steps to reproduce issue:
1. Login in app
2. Send messages
3. Turn off internet connectivity
4. Sent some messages from other device
5. Again turn on internet connectivity
Then that message is not received until we manually refresh the lending page or re-open app.

**Comment by imtoori** [comment]
Thanks for the reporting, I think this is a good place to report issues so far

At the moment we are developing a backend endpoint dedicated to resync the application data after reconnection, but that can take some time before landing in production.
I think for the moment we can just refresh the channels manually using the `queryChannels` endpoint.
Let me check it, if that works as expected I'll release another version of the low level client

**Comment by imtoori** [comment]
@Okdone I've just released a new version 
It should work as expected. I think this is a good compromise as far as we are working on a more specific endpoint
