### ISSUE TITLE
pubspec.yaml dependencies invalid path

### ISSUE THREAD

**Issue by lukepighetti** [GetStream/stream-chat-flutter#5]
```
  stream_chat:
    path: ../stream_chat_dart
```

This path does not exist in the project

**Comment by lukepighetti** [comment]
looks like it's a development quirk, can link via

```
  stream_chat:
    git: https://github.com/GetStream/stream-chat-dart.git
```

**Comment by imtoori** [comment]
Hi @lukepighetti 
Yes it was a silly mistake, sorry. Now it's fixed. 
For development we use a path import because sometimes we modify both libraries in the same time.
