### ISSUE TITLE
Online presence and Last Seen issue

### ISSUE THREAD

**Issue by Okdone** [GetStream/stream-chat-flutter#50]
We are testing the Alpha+4 build and enabled Presence and Last Seen in the application. Before doing that we figured out how to check information from server by logging and quering it at API level. 

What we observed is a inconsistent behavior from client on updating the status to server. 

Even if we kill the application of user A it keeps showing online on user B, and this goes on even if we restart application of User B it keeps showing user A as online. Secondly if User A is showing "5 mins back" to User B and we stop application on user B and then start application on user A send a message and stop it, it should show "few seconds or 1 min" back on user B but it shows "6 mins" back which means user A did not update the information to server correctly, to reverify it we checked on server and it was not updated. Same behavior if we interchange User A and User B or user C and user D, etc, so it is reproducible.

But at the same it is not happening every time, sometimes it is updating the information on server and we are able to see correctly.
Also we have checked with API response, user last active not showing correctly sometimes.

**Comment by imtoori** [comment]
the problem is that the client does not update user information depending on events
I'm working on this, so it'll be ready soon

**Comment by imtoori** [comment]
@Okdone can you try the latest version `0.2.1-alpha+6`?

**Comment by Okdone** [comment]
![image](https://user-images.githubusercontent.com/65529321/83120373-99ba3780-a0ee-11ea-90ac-b4fe66e6a499.png)

Have you pushed 0.2.1-alpha+6 ?

**Comment by imtoori** [comment]
yes I have, the tag was still to be pushed, but you can find it on pub.dev

**Comment by Okdone** [comment]
This issue still not solved "last Active" time is still displaying old time not updated with latest time. Also even if other user app is killed showing online sometimes and keeps showing online.

**Comment by imtoori** [comment]
are you talking about the time shown in the `ChannelHeader` subtitle?

**Comment by Okdone** [comment]
No, in `ChannelHeader` time is last message time, but i am talking about `user.lastActive`.
(using by `user.presence.changed)`.

**Comment by imtoori** [comment]
hey @Okdone 
I found the problem. It's a backend bug, we are looking into. I'll keep you updated, thanks

**Comment by damithsynapsys** [comment]
@imtoori Hey, 
this was happening the react-native also.

**Comment by imtoori** [comment]
Hey @damithsynapsys this should be solved by now, do you still have this issue?

**Comment by damithsynapsys** [comment]
yes, @imtoori. here are my environment details. 
    "react": "16.13.1",
    "react-native": "0.63.4",
    "stream-chat": "^2.8.0",
    "stream-chat-react-native": "^2.1.1",

"if User A is showing "5 mins back" to User B and we stop the application on user B and then start application on user A send a message and stop it, it should show "few seconds or 1 min" back on user B but it shows "6 mins" back which means user A did not update the information to the server correctly, to reverify it we checked on server and it was not updated. " 

the above scenario is still on there.

**Comment by imtoori** [comment]
Can I ask you to contact support for this issue?
Here we're supposed to have only flutter-related issues
@damithsynapsys
