### ISSUE TITLE
Strange formatting

### ISSUE THREAD

**Issue by rubenvereecken** [GetStream/stream-chat-flutter#503]
**Describe the bug**
Message widget inserts strange "\" when user sends a message with newlines in it. This happens both for message sent through the Flutter client, and messages sent by the server. Pretty sure it's the message widget.

**What package are you using? What version?**
`nullsafety.4`

**What platform is it about?**
- [x] Android
- [x] iOS

**To Reproduce**
Send message with newlines in it.

**Screenshots**

![image](https://user-images.githubusercontent.com/5216553/123547116-6154b500-d757-11eb-8a4b-a319fa73a1fe.png)

**Comment by imtoori** [comment]
That's weird, can you send me an example of message? I just tried it in the latest version and it's working fine

**Comment by rubenvereecken** [comment]
I think this particular message was copied in, maybe try that too. So part of the message:

> What you need to bring:
> - Reusable cup if you have one
> - ...

Also, here's a server message that did it for us (we have a "team" account that sends messages sometimes):
```typescript
      "To participate in ...:\n\n" +
      '(1) create a meetup and have fun (bonus points if you invite people)\n' +
      '(2) post a Memory of your meetup on Lessgo\n\n' +
      'Let us know if you have any questions and good luck 😄',
```

**Comment by imtoori** [comment]
oh yeah, it looks like it happens a \ at the end of list items
I'll take a look at it, I think it may be a bug of the markdown package

**Comment by imtoori** [comment]
fixed on develop
new release will contain the fix
FYI we're trying to release either today or tomorrow

**Comment by rubenvereecken** [comment]
No rush, thanks @imtoori!
