### ISSUE TITLE
"Error loading channels" in channel list view

### ISSUE THREAD

**Issue by rubenvereecken** [GetStream/stream-chat-flutter#504]
**Describe the bug**
See screenshot

**What package are you using? What version?**
`nullsafety.4`

**What platform is it about?**
- [x] Android
- [x] iOS

**To Reproduce**
No idea, probably a connection thing

**Expected behavior**
That's the real issue. When errors happen and they affect the user like this, they need to be retryable. So either it retries automatically or the user gets a retry button, which we have for if the whole screen has failed to load. But this is unrecoverable.

**Screenshots**
![image](https://user-images.githubusercontent.com/5216553/123548074-39675080-d75b-11eb-862d-68c2888e5042.png)

**Comment by imtoori** [comment]
we have a new design for this component
we'll implement it in the following days

**Comment by imtoori** [comment]
the new design is in develop
also we found a bug that was preventing the pagination to automatically be retried when the connection is back
now it should work fine
you'll find it in the next release
