### ISSUE TITLE
Cast Error on UserListView

### ISSUE THREAD

**Issue by poqueque** [GetStream/stream-chat-flutter#510]
**Describe the bug**
When using UserListView Widget it sometimes fails due to timeout or other network issues. When this happens non controlled exception is thrown with a wrong type:

**What package are you using? What version?**
  stream_chat_flutter: ^2.0.0-nullsafety.7

**What platform is it about?**
- [X] Android
- [X] iOS

**Expected behavior**
I would expect the widget to display a graceful error message asking the user to try again or something similar.

**Screenshots**
![image](https://user-images.githubusercontent.com/902418/123625349-f9ae7080-d80f-11eb-82e0-602acb0b011e.png)

**Logs **
I/flutter (20486): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20486): The following _CastError was thrown building StreamBuilder<List<ListItem>>(dirty, state:
I/flutter (20486): _StreamBuilderBaseState<List<ListItem>, AsyncSnapshot<List<ListItem>>>#b02f6):
I/flutter (20486): type 'DioError' is not a subtype of type 'Error' in type cast
I/flutter (20486): 
I/flutter (20486): The relevant error-causing widget was:
I/flutter (20486):   UserListView
I/flutter (20486):   ****.dart:60:16
I/flutter (20486): 
I/flutter (20486): When the exception was thrown, this was the stack:
I/flutter (20486): #0      _UserListViewState.build.<anonymous closure> (package:stream_chat_flutter/src/user_list_view.dart:160:36)
I/flutter (20486): #1      UserListCoreState._buildListView.<anonymous closure> (package:stream_chat_flutter_core/src/user_list_core.dart:176:39)
I/flutter (20486): #2      StreamBuilder.build (package:flutter/src/widgets/async.dart:546:81)
I/flutter (20486): #3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
I/flutter (20486): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
I/flutter (20486): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
I/flutter (20486): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)

**Additional context**
Cannot reproduce directly as it happens from time to time, mostly related to network timeout, I guess.

**Comment by imtoori** [comment]
this should be fixed in the latest release [2.0.0-nullsafety.8](https://github.com/GetStream/stream-chat-flutter/releases/tag/2.0.0-nullsafety.8)
