### ISSUE TITLE
Default video compression doesn't support VideoQuality.HighestQuality

### ISSUE THREAD

**Issue by saurabh02ezest** [GetStream/stream-chat-flutter#512]
Want to set video compression quality to **VideoQuality.HighestQuality** but it compress the video with lowest quality by default(360p)

**OS used** - iOS 14.3
**Package used** - Using [2.0.0-nullsafety.7](https://pub.dev/packages/stream_chat_flutter/versions/2.0.0-nullsafety.7)
**File for reference** - [video_service.dart](https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter/lib/src/video_service.dart)

![image](https://user-images.githubusercontent.com/84334887/123677158-a4676480-d7f9-11eb-89fd-607bf590e3c3.png)

@imtoori

**Comment by imtoori** [comment]
we'll add a parameter in the `MessageInput` to make it configurable 
Adding this to our backlog

**Comment by saurabh02ezest** [comment]
I want to put one more thing here, as **large videos take time for compression (more than a minute in some cases)** It will be better if we get **compression progress logs** and show them the file attachment process for a better user experience.

**Comment by imtoori** [comment]
@saurabh02ezest this makes sense, but we'll need a bit more time because at the moment the compression logic is in the UI package while the uploading and the progress logic is in stream_chat 

I'm adding this to our backlog and we'll do it eventually. Thanks for pointing it out btw, makes a lot of sense

**Comment by imtoori** [comment]
the quality options are in develop and will appear in the next release
I'll close this for the moment, feel free to reopen it if needed
