### ISSUE TITLE
Video thumbnails are not getting generated 

### ISSUE THREAD

**Issue by saurabh02ezest** [GetStream/stream-chat-flutter#513]
Sometimes some video thumbnails are not getting generated from the message list and it's showing only **Shimmer effect**, eventually app gets crashed. We have **implemented firebase storage as CDN** to upload larger files (upto 100MB), files are getting uploaded successfully.

**What package are you using? What version?**
[2.0.0-nullsafety.7](https://pub.dev/packages/stream_chat_flutter/versions/2.0.0-nullsafety.7)

**What platform is it about?**
- [ ] Android
- [x] iOS

**To Reproduce**
1. Have message list with larger videos attachment (around 60-100 MB)
2. Just scrolling through messages gives following error

> couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12792), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x282d16c10 {Error Domain=NSOSStatusErrorDomain Code=-12792 "(null)"}}

3. App gets crashed
 

**Expected behavior**
Video thumbnails should get generated without app crash

**Screenshot**
![image](https://user-images.githubusercontent.com/84334887/123675231-57828e80-d7f7-11eb-93d9-999264700048.png)

**Comment by imtoori** [comment]
This is probably a memory error due to how big the videos are
https://github.com/justsoft/video_thumbnail/issues/76

A solution might be to generate the thumbnails server-side (maybe using a firebase function in your case?)

if that could be a solution in your case we can add some logic to check if there is a `thumb_url` field in the video attachment and use that instead of generating the thumbnail locally

what do you think?

**Comment by saurabh02ezest** [comment]
Thanks for the suggestion 👍, Actually this will be half part of the solution - sometimes when the user tries to attach files then also it doesn't generate thumbnails, and uploading a file + generating a thumbnail will take time until the User will see only Shimmer effect.

Is there any other solution for generating thumbnails on the mobile side and then upload that thumbnail for future use?

**Comment by saurabh02ezest** [comment]
Hey @imtoori,  we didn't get the exact reason why [generateVideoThumbnail](https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter/lib/src/video_service.dart#L42-#L59) was not able to generate thumbnail locally or with video URL, but when we tried [video_thumbnail](https://pub.dev/packages/video_thumbnail) at our end, now we are able to generate thumbnails for larger videos (especially for .MOV with H.264) locally.

Hope you will get the exact reason 👍

**Comment by xsahil03x** [comment]
@saurabh02ezest can you also send some examples videos that are throwing errors.

**Comment by imtoori** [comment]
that would help
it's odd that it's working if you implement it since we're not doing anything weird
let me know if you can send us a sample

**Comment by saurabh02ezest** [comment]
@imtoori @xsahil03x Thanks guys for your prompt response 👍

I am not able to reproduce the issue for other videos, so closing this issue.
