### ISSUE TITLE
Avatar Background Color

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#516]
Can we get access to change just the background color for all avatars or can the default at least be set to transparent?.

**Comment by imtoori** [comment]
you could change the `accentBlue` color, but I guess having a more specific properties would make sense
adding it to the backlog

**Comment by rlee1990** [comment]
Thanks

**Comment by jasnicaa** [comment]
In regards to avatar: there is no way I could set my own images for an avatar?

**Comment by rlee1990** [comment]
@jasnicaa you can add them for the channel when the channel is created or when you update the channel by setting the image to your image string url. You can set the user's avatar by just adding it when you set the user.

**Comment by rlee1990** [comment]
@jasnicaa this might be able to help you too. [https://getstream.io/chat/flutter/tutorial/](url)

**Comment by imtoori** [comment]
you can even call channel.update or user.update for updating the image

**Comment by jasnicaa** [comment]
hey yess that's it! Think I saw that when I was setting up chat in the first place but then of course I forgot 😅
