### ISSUE TITLE
Querying channels using channel name

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#52]
Basically i want to do something like search box on the top of my ChannelListView.
I know that we can filter using members but currently it only allows filter using user.id not user name or channel name

**Comment by imtoori** [comment]
Right now the backend does not support queryChannels by name.
The good news is that it will be added this week! I'll let you know once it's deployed

**Comment by imtoori** [comment]
hey @brizaldi 
could you try now? we just updated the backend

**Comment by brizaldi** [comment]
thanks, will try it today

**Comment by imtoori** [comment]
I think this is solved, I'll close it. Reopen it if there is any problem

**Comment by Mounix99** [comment]
Hi! can you provide an example ? Seems like it is still impossible
