### ISSUE TITLE
GetOrCreateChannel failed with error: "When using member based IDs specify at least 2 members"

### ISSUE THREAD

**Issue by jasnicaa** [GetStream/stream-chat-flutter#526]
I don't get this error. I am passing - when creating a User, as an id some random numbers that the backend has generate it for me. And I am getting this error. While creating an example app with Vue I didn't receive this issue so far so what is the reason for it? I should pass all the id's from that channel involved? 

- Using the latest null safe version.

Thanks.

**Comment by imtoori** [comment]
Hi @jasnicaa, this is an error related to channels; while you talk about creating a user in the description.
Can you give us more details?

btw, this error is generated by the backend when you query/create a channel without passing an id, so the backend takes the user member ids and generates the id using those
If you pass neither an id nor 2 or more members, you get this error.

**Comment by jasnicaa** [comment]
Hmmm, yes your response was helpful. I was thinking that it has something to the with the creation of users, instead, it was the channel issue I looked into it and found an error. 

Thanks a lot!
