### ISSUE TITLE
How does timestamp hiding work for multiple successive messages from the same user?

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#527]
This is really just a question and not necessarily a bug - see title. This user commented twice in quick succession but I was expecting the first message timestamp to be hidden. See the screenshot below:

![image](https://user-images.githubusercontent.com/4282877/124942656-d175fd00-dfd9-11eb-8d2b-7230f0459886.png)

**Comment by xsahil03x** [comment]
Hey @jgadsby the current logic is as follows:
```dart
	timeDiff = Jiffy(nextMessage.createdAt.toLocal()).diff(
        message.createdAt.toLocal(),
        Units.MINUTE,
      );

    final showTimeStamp = (!isThreadMessage || _isThreadConversation) &&
        !hasReplies &&
        (timeDiff >= 1 || !isNextUserSame);
```
Can you also share the `createdAt` of the two messages for more clarity?

**Comment by imtoori** [comment]
just found the bug and opened a pr 
it will be fixed in the next release, thanks again for testing the prerelease, that's super useful 😄

**Comment by xsahil03x** [comment]
Hey @jgadsby the fix is now merged and we will soon release it. Until then you can use it via git path.

Thanks again for raising the issue 😄 
```dart
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: hotfix/timestampHiding
      path: packages/stream_chat_flutter
```

**Comment by jgadsby** [comment]
@xsahil03x Was this fix merged into nullsafety.9? I still see the same issue!

**Comment by imtoori** [comment]
@jgadsby it wasn't! it will be in the next one!
