### ISSUE TITLE
Read & Delivered indicator

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#53]
I think we need to add read & delivered indicator for one-to-one conversations, currently it only shows SendingIndicator

**Comment by imtoori** [comment]
yes, that's one of the next features to be added

**Comment by imtoori** [comment]
hey! the new version has read indicators

however, at the moment our backend does not support delivered indicators

**Comment by brizaldi** [comment]
is there any example that explain this feature?

**Comment by imtoori** [comment]
By default, you should see all the read indicators when available.

You can also override the behaviour passing a `MessageBuilder` in the `MessageListView` widget` and setting the `readList` as you prefer.

However, I'll make sure to dedicate a page in the docs for this feature

**Comment by brizaldi** [comment]
i dont know why but `readList` is always null, even though the other user already read the chats

**Comment by imtoori** [comment]
Is the user in the `channel.state.read` list?
Note that the user must be a channel member to be included in the list

**Comment by brizaldi** [comment]
yup, my user is always member of the channel since our app is only using one-to-one conversation

**Comment by imtoori** [comment]
> Is the user in the channel.state.read list?

what about this?

**Comment by brizaldi** [comment]
Nevermind, its always null because we didn't put `channel.state.read` on the `readList` parameter. Maybe you should put it in the documentation, thanks for responding 👍

**Comment by imtoori** [comment]
yes that's what I was saying [here](https://github.com/GetStream/stream-chat-flutter/issues/53#issuecomment-654691616)

and yes, I'll write some specific doc thanks

**Comment by jamesbgl** [comment]
Hi - I am trying to understand if it's possible to hide the read list - I have some chat groups where this is unwieldy, but I cannot find a way to use a custom messageBuilder at the same time as a threadBuilder - seems like if you use threadBuilder then you cannot use a custom messageBuilder in the root level MessageListView.

**Comment by imtoori** [comment]
hey @jamesbgl it's possible to use a custom messageBuilder at the same time as a threadBuilder, I just tested it in a sample app

**Comment by xsahil03x** [comment]
Hey @jamesbgl, yes currently it's not possible to use `threadBuilder` if you use a `custom message widget`. But it's easy enough to open the thread screen by navigating to it. We internally do the same when `threadPressed` is called 

```
Navigator.push(
          context,
          MaterialPageRoute(builder: (_) {
            return StreamBuilder<Message>(
                stream: streamChannel.channel.state.messagesStream.map(
                    (messages) =>
                        messages.firstWhere((m) => m.id == message.id)),
                initialData: message,
                builder: (_, snapshot) {
				  final parentMessage = snapshot.data;
                  return StreamChannel(
                    channel: streamChannel.channel,
                    child: YourThreadPage(parentMessage),
                  );
                });
          }),
        );
```
Let us know if you face any problem 😃

**Comment by jamesbgl** [comment]
Thanks for the quick reply! my issue is not the thread page, it's the root level that is the problem. I've got 100's of people in my readList and I do not want to show a list of avatars for the users at all. As it stands, the UI overflows and users have to download hundreds of avatar URLs which is slow and inefficient. Makes sense for me to simply not show them at this scale.

My current workaround is fine but I feel it makes sense to be a config setting, I have the message_list_widget.dart imported locally and I set my readList to an empty list. My app is growing quickly so I went with a dirty hack for now.

Mad respect for this plugin!

**Comment by imtoori** [comment]
Hey @jamesbgl 
What do you think of using the messageBuilder to build the message using our MessageWidget?
Something like this 
```dart
messageBuilder: (context, messageDetails, messages) {
                    final isMyMessage = messageDetails.isMyMessage;
                    final index = messageDetails.index;
                    final isLastUser = messageDetails.isLastUser;

                    final messageTheme = isMyMessage
                        ? StreamChatTheme.of(context).ownMessageTheme
                        : StreamChatTheme.of(context).otherMessageTheme;
                    return MessageWidget(
                      message: messageDetails.message,
                      messageTheme: messageTheme,
                      reverse: isMyMessage,
                    );
                  },
                )
```

without passing the readList.

This is just an example, but you can customise it how you want

**Comment by jamesbgl** [comment]
I found if I try to have threads, then I cannot provide a custom messagebuilder.

For example, if I uncomment the second line below, then threading functionality is gone completely. 

`MessageListView(
            //messageBuilder: _messageBuilder,
            threadBuilder: (_, parentMessage) {
              return ThreadPage(
                parent: parentMessage,
              );
            },
          )`

**Comment by jamesbgl** [comment]
Got it, thank you!
