### ISSUE TITLE
attachmentFileUploader missing in StreamHttpClient 

### ISSUE THREAD

**Issue by saurabh02ezest** [GetStream/stream-chat-flutter#530]
We want to upload large files to own CDN, In earlier versions it was supported with **attachmentFileUploader** parameter ([docs](https://getstream.io/chat/docs/flutter-dart/file_uploads/?language=dart#using-your-own-cdn) -> [implementation](https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat/lib/src/attachment_file_uploader.dart#L58)) in [StreamChatClient](https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat/lib/src/client.dart#L90) but with recent versions, instead of **StreamChatClient** we have to use [StreamHttpClient](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/core/api/attachment_file_uploader.dart#L62) which don't have **attachmentFileUploader** parameter.

I did not get any documentation for this. Please let me know if I am missing anything there

**What package are you using? What version?**
[2.0.0-nullsafety.9](https://pub.dev/packages/stream_chat_flutter/versions/2.0.0-nullsafety.9)

**What platform is it about?**
 - [x] iOS

**Comment by xsahil03x** [comment]
Hey @saurabh02ezest, We still provide it in `StreamChatClient` constructor
https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/client/client.dart#L73

Also, you should use your own httpClient in case you are overriding the default `AttachmentFileUploader`

**Comment by saurabh02ezest** [comment]
![image](https://user-images.githubusercontent.com/84334887/125085079-0b4d0f00-e07f-11eb-90b9-b63629e12821.png)

In  [2.0.0-nullsafety.9](https://pub.dev/packages/stream_chat_flutter/versions/2.0.0-nullsafety.9)  `StreamChatClient` don't have `post` method or anything related to it

**Comment by xsahil03x** [comment]
Hey @saurabh02ezest, can you please share a sample project showing your previous implementation.
