### ISSUE TITLE
Bad state: No element for one of our users in one specific channel.

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#532]
**Describe the bug**
One of our users sees a grey block where the message list should be in one specific channel. All other channels work fine. It looks like an issue in message_list_view#957.

**What package are you using? What version?**
nullsafety.8

**What platform is it about?**
- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Logs **
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following StateError was thrown building:
flutter: Bad state: No element
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
flutter: #1      _MessageListViewState.buildMessage
flutter: #2      _MessageListViewState._buildBottomMessage
flutter: #3      _MessageListViewState._buildListView.<anonymous closure>.<anonymous closure>
flutter: #4      _PositionedListState._buildItem
flutter: #5      _PositionedListState._buildSeparatedListElement
flutter: #6      _PositionedListState.build.<anonymous closure>
flutter: #7      SliverChildBuilderDelegate.build
flutter: #8      SliverMultiBoxAdaptorElement._build
flutter: #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
flutter: #10     BuildOwner.buildScope
flutter: #11     SliverMultiBoxAdaptorElement.createChild
flutter: #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
flutter: #13     RenderObject.invokeLayoutCallback.<anonymous closure>
flutter: #14     PipelineOwner._enableMutationsToDirtySubtrees
flutter: #15     RenderObject.invokeLayoutCallback
flutter: #16     RenderSliverMultiBoxAdaptor._createOrObtainChild
flutter: #17     RenderSliverMultiBoxAdaptor.insertAndLayoutChild
flutter: #18     RenderSliverList.performLayout.advance
flutter: #19     RenderSliverList.performLayout
flutter: #20     RenderObject.layout
flutter: #21     RenderSliverEdgeInsetsPadding.performLayout
flutter: #22     RenderSliverPadding.performLayout
flutter: #23     RenderObject.layout
flutter: #24     RenderViewportBase.layoutChildSequence
flutter: #25     UnboundedRenderViewport._attemptLayout
flutter: #26     UnboundedRenderViewport.performLayout
flutter: #27     RenderObject.layout
flutter: #28     RenderProxyBoxMixin.performLayout
flutter: #29     RenderObject.layout
flutter: #30     RenderProxyBoxMixin.performLayout
flutter: #31     RenderObject.layout
flutter: #32     RenderProxyBoxMixin.performLayout
flutter: #33     RenderObject.layout
flutter: #34     RenderProxyBoxMixin.performLayout
flutter: #35     RenderObject.layout
flutter: #36     RenderProxyBoxMixin.performLayout
flutter: #37     RenderObject.layout
flutter: #38     RenderProxyBoxMixin.performLayout
flutter: #39     RenderObject.layout
flutter: #40     RenderProxyBoxMixin.performLayout
flutter: #41     RenderObject.layout
flutter: #42     ChildLayoutHelper.layoutChild
flutter: #43     RenderStack._computeSize
flutter: #44     RenderStack.performLayout
flutter: #45     RenderObject.layout
flutter: #46     RenderProxyBoxMixin.performLayout
flutter: #47     RenderObject.layout
flutter: #48     _RenderLayoutBuilder.performLayout
flutter: #49     RenderObject.layout
flutter: #50     RenderProxyBoxMixin.performLayout
flutter: #51     RenderLeaderLayer.performLayout
flutter: #52     RenderObject.layout
flutter: #53     ChildLayoutHelper.layoutChild
flutter: #54     RenderStack._computeSize
flutter: #55     RenderStack.performLayout
flutter: #56     RenderObject.layout
flutter: #57     ChildLayoutHelper.layoutChild
flutter: #58     RenderStack._computeSize
flutter: #59     RenderStack.performLayout
flutter: #60     RenderObject.layout
flutter: #61     ChildLayoutHelper.layoutChild
flutter: #62     RenderFlex._computeSizes
flutter: #63     RenderFlex.performLayout
flutter: #64     RenderObject.layout
flutter: #65     RenderProxyBoxMixin.performLayout
flutter: #66     RenderObject.layout
flutter: #67     MultiChildLayoutDelegate.layoutChild
flutter: #68     _ScaffoldLayout.performLayout
flutter: #69     MultiChildLayoutDelegate._callPerformLayout
flutter: #70     RenderCustomMultiChildLayoutBox.performLayout
flutter: #71     RenderObject.layout
flutter: #72     RenderProxyBoxMixin.performLayout
flutter: #73     RenderObject.layout
flutter: #74     RenderProxyBoxMixin.performLayout
flutter: #75     _RenderCustomClip.performLayout
flutter: #76     RenderObject.layout
flutter: #77     RenderProxyBoxMixin.performLayout
flutter: #78     RenderObject.layout
flutter: #79     RenderProxyBoxMixin.performLayout
flutter: #80     RenderObject._layoutWithoutResize
flutter: #81     PipelineOwner.flushLayout
flutter: #82     RendererBinding.drawFrame
flutter: #83     WidgetsBinding.drawFrame
flutter: #84     RendererBinding._handlePersistentFrameCallback
flutter: #85     SchedulerBinding._invokeFrameCallback
flutter: #86     SchedulerBinding.handleDrawFrame
flutter: #87     SchedulerBinding._handleDrawFrame
flutter: #91     _invoke (dart:ui/hooks.dart:163:10)
flutter: #92     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter: #93     _drawFrame (dart:ui/hooks.dart:126:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Bad state: No element
flutter:
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      _MessageListViewState.buildMessage
#2      _MessageListViewState._buildBottomMessage
#3      _MessageListViewState._buildListView.<anonymous closure>.<anonymous closure>
#4      _PositionedListState._buildItem
#5      _PositionedListState._buildSeparatedListElement
#6      _PositionedListState.build.<anonymous closure>
#7      SliverChildBuilderDelegate.build
#8      SliverMultiBoxAdaptorElement._build
#9      SliverMultiBoxAd<…>

**Comment by deven98** [comment]
Taking a look into this,

I'll get back to you when I have more information.

Thanks!

**Comment by jgadsby** [comment]
@deven98 it was a bug on our end, the user wasn't in the channel like they should have been.
