### ISSUE TITLE
Tapping the 'cancel' button on the giphy preview sometimes doesn't do anything (try it multiple times with different searches)

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#533]
**Describe the bug**
See title

**What package are you using? What version?**
nullsafety.8

**What platform is it about?**
- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Use the giphy command to search for a gif
2. Tap 'cancel'
3. See that nothing happens. If it does correctly close the preview, try searching a couple more times. It's not predictable!

**Comment by deven98** [comment]
Taking a look into both this and the permission issues now.

**Comment by imtoori** [comment]
fixed in develop
you'll find it in the next release
thanks!
