### ISSUE TITLE
Build fails for web - Pointycastle javascript error

### ISSUE THREAD

**Issue by akul1994** [GetStream/stream-chat-flutter#534]
**Describe the bug**
Unable to build project on web

**What package are you using? What version?**
  stream_chat_flutter: ^2.0.0-nullsafety.9

**What platform is it about?**
- [ ] Android
- [ ] iOS
- [ Yes] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Add code from flutter stream tutorial
2. Run project for web(chrome)

**Expected behavior**
Code should build for web

**Screenshots**
<img width="1667" alt="Screenshot 2021-07-10 at 4 55 33 PM" src="https://user-images.githubusercontent.com/9698473/125161385-a5a47400-e19f-11eb-9929-d29033363b10.png">

**Logs **

`../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/key_derivators/argon2.dart:42:27: Error: The integer literal 0xFFFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x10000000000000000 is the nearest value that can be represented exactly.
  static const int M32L = 0xFFFFFFFFFFFFFFFF;
                          ^^^^^^^^^^^^^^^^^^
../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/src/utils.dart:313:9: Error: The integer literal 0xFFFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x10000000000000000 is the nearest value that can be represented exactly.
      ((0xFFFFFFFFFFFFFFFF) ^ ((1 << (64 - count)) - 1));
        ^^^^^^^^^^^^^^^^^^
../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/src/platform_check/platform_check.dart:6:35: Error: Method not found: 'getPlatform'.
  static Platform get instance => getPlatform();
                                  ^^^^^^^^^^^
Failed to compile application.`

Paste the output of running `flutter doctor -v` here.

`[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/akul/development/flutter
    • Framework revision f4abaa0735 (9 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/akul/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • HD1901 (mobile) • f2a3f0ec • android-arm64  • Android 10 (API 29)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
`

**Comment by deven98** [comment]
Hey @akul1994, we're taking a look into this. 
I'll let you know when we have more information.

Thanks.

**Comment by mtkopone** [comment]
Temporary fix: Downgrade pointycastle to 3.1.1 in your pubspec.yaml.

**Comment by deven98** [comment]
Hey @akul1994,

Prima facie this does not seem to be an issue on our end, you can find the issue on the pointycastle repo [here](https://github.com/bcgit/pc-dart/issues/112).

You can use the temporary solution given above using a dependency override. 

Closing this issue for now, feel free to reopen this if needed.

Thanks.
