### ISSUE TITLE
PaginationParams in MessageListCore

### ISSUE THREAD

**Issue by hiashutoshsingh** [GetStream/stream-chat-flutter#539]
**Is your feature request related to a problem? Please describe.**
Just like in the ChannelListCore, can we get PaginationParams for MessageListCore as well, because ultimately it should be UI call as many as messages they want to show?

Edit: I noticed now that, MessageListCore is returning all messages available in the channel.

**Describe the solution you'd like**
Introduce PaginationParams in MessageListCore
`pagination: PaginationParams(limit: 10)`

I am using  `stream_chat_flutter_core: 2.0.0-nullsafety.9`

@imtoori @deven98 @xsahil03x

**Comment by deven98** [comment]
Taking a look into this @hiashutoshsingh,

I'll get back to you when I have more info.

Thanks.

**Comment by deven98** [comment]
Hey @hiashutoshsingh, 

We will add a way to get a certain number of messages when paginating.
Adding this to our backlog.

Thanks for bringing this to our attention.
