### ISSUE TITLE
[Notification] Error during resync

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#54]
i got this error message after implementing notification for my ios app, but the notification and chat functionality is working fine though

```flutter: (2020-06-18 13:54:58.181137) 🚨 📡 Error during resync ApiError{body: Not Found, jsonData: null, status: 404, code: null}```

**Comment by imtoori** [comment]
hey @brizaldi 
that's normal, it tries to call the `sync` endpoint and it fails because it's still not deployed to production
as soon as it's deployed it will work, but it does not affect other things

**Comment by brizaldi** [comment]
so, it just a warning, okay then, i'm gonna close this
