### ISSUE TITLE
iOS photos permissions needs a fallback option when gallery permissions were denied

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#543]
**Describe the bug**
If a user has previously denied photos permissions in the app and attempts to enable permissions from the inline photo gallery, the button doesn't do anything. Ideally, it would forward users to the Settings app or at least tell them to enable photo permissions in the Settings app.

**What package are you using? What version?**
Nullsafety.8

**What platform is it about?**
- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Deny gallery permissions somewhere else in the app
2. Attempt to upload a photo from stream chat
3. See that the 'enable permissions' button does nothing

**Expected behavior**
See description

**Screenshots**
![Screen Shot 2021-07-13 at 11 06 15 AM](https://user-images.githubusercontent.com/4282877/125477147-10c9b9b5-9d7f-4e4c-97e0-f1135bf558e9.png)

**Comment by deven98** [comment]
Taking a look into this issue now.
