### ISSUE TITLE
More Of A Question About Photos

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#544]
Is there a way to get a list of all the photos or files sent in a channel?

**Comment by deven98** [comment]
Hey @rlee1990,

Yes absolutely, we do this in our `ChannelMediaDisplayScreen` to show media in a channel:

https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter/lib/src/channel_media_display_screen.dart

```
    messageSearchBloc.search(
      filter: {
        'cid': {
          r'$in': [StreamChannel.of(context).channel.cid],
        }
      },
      messageFilter: {
        'attachments.type': {
          r'$in': ['image', 'video']
        },
      },
      sort: widget.sortOptions,
      pagination: widget.paginationParams,
    );
```

Note: With the new filters, the filters would change to

`Filter.in_('cid', [StreamChannel.of(context).channel.cid])`

and 

`Filter.in_('attachments.type', ['image', 'video'])`

**Comment by deven98** [comment]
Closing this issue for now, if this does not answer your question, please feel free to reopen.
