### ISSUE TITLE
Push Notifications : Click Handling

### ISSUE THREAD

**Issue by hiashutoshsingh** [GetStream/stream-chat-flutter#547]
**Describe the bug**

We are trying to implement notifications using our own FCM backend service. The notifications are coming in as expected but we are struggling with user navigation i.e. when the user clicks on the notification, they should be redirected to the chat window. Right now, we get a screen with CircularProgressIndicator with the background as black while doing so when the app is in the BG or in the killed state. If the app is loaded and the inbox list has been fetched, the navigation works for some unknown reason. Would really appreciate help understanding the possible solution. 
Thanks.

**What package are you using? What version?**
```
  stream_chat_flutter_core: 2.0.0-nullsafety.9
  stream_chat_persistence: 2.0.0-nullsafety.8
  firebase_core: 1.0.2
  firebase_analytics: 7.1.1
  firebase_messaging: 9.0.1
```

**What platform is it about?**
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**

Steps to reproduce the behaviour:
1. Tap the notification.
2. Navigate using:
```
 Navigator.of(appNavigator.getContext()).push(
            MaterialPageRoute(
              builder: (context) => StreamChannel(
                channel: _streamChatClient.channel(
                  'messaging',
                  id: channelId,
                ),
                child: ChatMessageScreen(),
              ),
            ),
          );

```

**Expected behaviour**

We should be able to redirect to messages screen on tap of notification.

**Screenshot**

![Screenshot 2021-07-15 at 1 49 41 PM](https://user-images.githubusercontent.com/21235425/125754341-e74e9ee4-6e7f-406d-bd3d-ed6faff6b328.png)

**Logs**

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-IN)
    • Flutter version 2.2.3 at /Users/i0868/Documents/flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/i0868/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • E228B37F-4D7D-46CF-AC60-1F325F972977 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 91.0.4472.114

• No issues found!
```
@deven98 @imtoori @xsahil03x

**Comment by imtoori** [comment]
hey @hiashutoshsingh the issue is that you're not calling `channel.watch()`
that's how you initialize a channel created with `client.channel(channelType, id: channelId)`
