### ISSUE TITLE
Are there plans to develop a similar package for Stream's Activity Feeds service?

### ISSUE THREAD

**Issue by MaskyS** [GetStream/stream-chat-flutter#55]
Title. Stream is an extremely interesting product and company. Having a flutter package for your other service would lead to much more widespread use, especially considering Flutter's meteoric rise. Are there any plans to do so, or any works-in-progress the community can contribute to?

**Comment by imtoori** [comment]
Hey!
At the moment there is no implementation of Stream Feeds in Flutter, but for sure it's in our plans 
Thanks for the interest!
