### ISSUE TITLE
Side by side support for channel list and message list

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-flutter#56]
What would be the best approach to have a side by side chat experience? I'm developing an app that supports tablet screen width. Looks like route navigation is already built-in so clicking on a channel would just push open the provided channelWidget?

**Comment by imtoori** [comment]
That's a very cool example to make
I'll make it as soon as possible and add it to the example folder

**Comment by pixnbit** [comment]
Do you have a timeline for this?

**Comment by imtoori** [comment]
Hi @pixnbit, you can find an example in the `/example` folder
Let me know if that works for you

**Comment by pixnbit** [comment]
Thank you! Just in time, I just came back working on this
