### ISSUE TITLE
Reaction on parent message in thread

### ISSUE THREAD

**Issue by gvv-ua** [GetStream/stream-chat-flutter#572]
**Describe the bug**

**stream-chat-flutter v2.0.0**

**To Reproduce**
1. Open channel
2. Open thread for message
3. Add reaction to parent message
4. New reaction didn’t appear on parent message

**Expected behavior**
Parent messages updated with new reaction.

**Comment by imtoori** [comment]
Hi that's working fine for me
Are you personalizing the parent message or using the default implementation?

**Comment by gvv-ua** [comment]
Hi @imtoori ! Yes, we using parentMessageBuilder to customization this message. But, I tried default implementation and it also doesn't work for me.  When I add reaction to parent message in thread, that action not trigger changing the message, those reaction are not displayed in thread. After closing the thread I see this reaction on the original message. After reopening the thread this reaction also exists on parent message.

**Comment by imtoori** [comment]
can you try running the `tutorial_part_4.dart` file that you find in the /example folder of the `stream_chat_flutter` package and trying that?
It's working fine for me :/

**Comment by gvv-ua** [comment]
Thanks, it's really working.
