### ISSUE TITLE
Block channel

### ISSUE THREAD

**Issue by firsttimeeagle** [GetStream/stream-chat-flutter#58]
is there a way to block a channel so that all of the channel members no longer be able chat on that channel, and the blocked channel did not appear on channel list?

**Comment by firsttimeeagle** [comment]
or maybe block a user so that user no longer be able to initiate chat with us

**Comment by imtoori** [comment]
hi! you may want to take a look to 
- Channel hide: https://getstream.io/chat/docs/channel_delete/?language=kotlin&q=hide
- User ban: https://getstream.io/chat/docs/moderation/?language=kotlin&q=ban

**Comment by firsttimeeagle** [comment]
in my case its one-on-one conversation, both of that method that you've provide doesn't satisfy my requirement for blocked channel because:

- channel hide: the other user can still see, access, & use the channel because hiding channel only apply to one user not both user
- user ban: only admin & moderator can ban user from the channel, what about one-on-one conversation?

**Comment by imtoori** [comment]
> is there a way to block a channel so that all of the channel members no longer be able chat on that channel, and the blocked channel did not appear on channel list?

for this I think you can just remove the members from the channel

you should use a server-side SDK

**Comment by imtoori** [comment]
> or maybe block a user so that user no longer be able to initiate chat with us

for this I think you can use user mutes https://getstream.io/chat/docs/moderation/?language=kotlin#mutes
also banning users is possible on server-side SDK

**Comment by firsttimeeagle** [comment]
what do you mean with server side SDK? is this it? https://getstream.io/chat/docs/server_side_api/?language=dart

**Comment by imtoori** [comment]
yes, those are the server-side SDKs
