### ISSUE TITLE
Building for Web 

### ISSUE THREAD

**Issue by KieranLafferty** [GetStream/stream-chat-flutter#59]
When building via `flutter run -d chrome --verbose` web I get the following:

```
[        ] ../../../../.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.5.0/lib/src/bindings/types.dart:6:8: Error: Not found: 'dart:ffi'
[        ] import 'dart:ffi';
[        ]        ^
[   +3 ms] ../../../../.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.5.0/lib/src/impl/database.dart:2:8: Error: Not found: 'dart:ffi'
[        ] import 'dart:ffi';
[        ]        ^
[        ] ../../../../.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.5.0/lib/src/ffi/blob.dart:2:8: Error: Not found: 'dart:ffi'
[        ] import 'dart:ffi';
[        ]        ^
[        ] ../../../../.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.5.0/lib/src/ffi/utils.dart:1:8: Error: Not found: 'dart:ffi'
[        ] import 'dart:ffi';
[        ]        ^
[        ] ../../../../.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.5.0/lib/src/bindings/bindings.dart:5:8: Error: Not found: 'dart:ffi'
[        ] import 'dart:ffi';
[        ]        ^
[   +1 ms] ../../../../.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.5.0/lib/src/bindings/signatures.dart:5:8: Error: Not found: 'dart:ffi'
[        ] import 'dart:ffi';
[        ]        ^
[  +64 ms] ../../../../.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.5.0/lib/open_helper.dart:5:8: Error: Not found: 'dart:ffi'
[        ] import 'dart:ffi';
...
```
I've tried various things from this repository to try and get it working with no success https://github.com/rodydavis/moor_shared

Could you please provide a sample web target for this project to get started with this on Web?

gz#4510

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4510'>Zendesk ticket #4510</a>:<br><br>Hi,

Thanks for getting in touch.
I'm passing this on to our Flutter development team for more insights.
We'll get back to you shortly.

Best regards,
Seni

**Comment by imtoori** [comment]
Hi @KieranLafferty,
I'm sorry but at the moment we have no example on Web.
The biggest problem right now is the moor library: we need to implement the web part, but I didn't look into that yet.
The good news is that web support it's in our backlog, we'll keep you updated

**Comment by KieranLafferty** [comment]
thanks @imtoori this repo has a working example of moor on web/ios/android/mac/windows/linux if you need a reference point https://github.com/rodydavis/moor_shared

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4510'>Zendesk ticket #4510</a>:<br><br>Closing ZD ticket, feature request

**Comment by KieranLafferty** [comment]
Just a follow up to this. I've found that simply including `stream_chat_flutter` as a dependency in my project breaks the entire project's ability to build/run on flutter. Even if adding web support isn't something that will happen soon could you fix the build issues that arise from including this as a dependency on web

here's the error I get

```
Launching lib/main.dart on Chrome in debug mode...
Unhandled exception:
InvalidType doesn't have nullability.
#0      InvalidType.nullability  (package:kernel/ast.dart:6750:34)
#1      ProgramCompiler._mustBeNonNullable  (package:dev_compiler/src/kernel/compiler.dart:3145:14)

#2      ProgramCompiler._emitArgumentInitializers.initParameter  (package:dev_compiler/src/kernel/compiler.dart:3185:18)
#3      ProgramCompiler._emitArgumentInitializers  (package:dev_compiler/src/kernel/compiler.dart:3207:20)
#4      ProgramCompiler._emitConstructorBody  (package:dev_compiler/src/kernel/compiler.dart:1369:16)
#5      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure>  (package:dev_compiler/src/kernel/compiler.dart:1349:19)
#6      ProgramCompiler._superDisallowed  (package:dev_compiler/src/kernel/compiler.dart:3138:24)

#7      ProgramCompiler._emitConstructor.<anonymous closure>  (package:dev_compiler/src/kernel/compiler.dart:1348:15)
```

**Comment by imtoori** [comment]
@KieranLafferty I'll try to do it, but it's not our first priority given that Flutter web is still in beta

**Comment by imtoori** [comment]
Closing this since now the SDK builds on for web

**Comment by rohan20** [comment]
@imtoori Can you please help figure out what I may be doing incorrectly? I have issues with `moor` on web and hence `setUser` fails.

![image](https://user-images.githubusercontent.com/8232573/108700545-0855e580-7507-11eb-8903-87626d4f132e.png)

I'm on `stream_chat_flutter: ^0.2.21`. I know `stream_chat_flutter` isn't compatible with Web but I assume that's only for the UI part? `setUser` should still work I suppose. Or should I use `stream_chat_flutter_core` even for `setUser`? 

Thanks.

**Comment by imtoori** [comment]
@rohan20 check out this section of the readme https://github.com/GetStream/stream-chat-flutter/tree/master/packages/stream_chat_persistence#flutter-web

I think this should work, even using the higher level package

**Comment by rohan20** [comment]
@imtoori Perfect! Thank you. 

I also ended up using this to fetch the 2 files instead of getting them from the release: https://github.com/rodydavis/moor_shared

**Comment by Goxiaoy** [comment]
The latest sdk version  
```
  stream_chat_flutter: ^1.5.2
  stream_chat_persistence: ^1.5.1

```
 break again in web
```
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.4.0/lib/src/ffi/database_tracker.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.8/lib/src/api/database.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.8/lib/src/api/sqlite3.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/sqlite3-0.1.8/lib/src/api/statement.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';

```
