### ISSUE TITLE
Keyboard covering input field on Huawei Mate 20pro

### ISSUE THREAD

**Issue by jasnicaa** [GetStream/stream-chat-flutter#595]
**Describe the bug**

https://user-images.githubusercontent.com/25682164/127627708-09c66741-584d-4e22-b767-628cc4876f0e.mp4

**What package are you using? What version?**
2.0.0-nullsafety.8

**What platform is it about?**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**

Test on Huawei Mate 20pro.

**Expected behavior**
Keyboard not to hide input field while typing.

**Additional context**
We are having this issue only on this particular device.

**Comment by xsahil03x** [comment]
Hey @jasnicaa, can you try our latest version i.e: `stream_chat_flutter: ^2.1.1` and let us know if it's still happening. Thanks

**Comment by jasnicaa** [comment]
It is still happening on the same device. 

As well we have some other issues all of the sudden yesterday. Channel header is not displaying usernames, as well chatPreview in the list, and in the chat window under the message, there is userID instead of name.

![Screenshot_20210730-114251](https://user-images.githubusercontent.com/25682164/127635197-704542e6-b113-45bf-8d4a-dee5f1a10294.jpg)
![Screenshot_20210730-114424](https://user-images.githubusercontent.com/25682164/127635208-d5ec3ba0-24d5-4504-ad6b-5e5554e653bf.jpg)

**Comment by xsahil03x** [comment]
Hey @jasnicaa, I don't think it is related to `StreamChat`. Can you try replicating the same with a regular `TextField` instead of `MessageInput`on the same device just to be sure?

**Comment by jasnicaa** [comment]
Yeah, I changed to TextField and it is still happening so I will just file a bug on Flutter's git hub.

About my second issue- any help on this?

**Comment by imtoori** [comment]
@jasnicaa it looks like you removed the name from the user objects :/
is that possible?

**Comment by imtoori** [comment]
mmm 🤔  do you ever use updateUser or updateChannel calls?

**Comment by xsahil03x** [comment]
@jasnicaa if you look at the `user.name` implementation, you can find that we use the `user.id` as the name if it's not defined.

https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/lib/src/core/models/user.dart#L94

**Comment by jasnicaa** [comment]
@imtoori - no never, should I? 

@xsahil03x  yeah I saw the implementation, the only thing that bugged my- I didn't find any key in the extraData named name. there is only a nickname- which is used as a name, and first and the last name. But I think the real issue is here why is User empty..

**Comment by imtoori** [comment]
> the only thing that bugged my- I didn't find any key in the extraData named name
that's why you're having this issue

I think you should set the user name
is `state.chatDataModel!.username!,` the name you want to show?

**Comment by jasnicaa** [comment]
nope, there is a field named nickname which returns the name of the user

**Comment by xsahil03x** [comment]
Hey @jasnicaa, you can override the default `UserNameWidget` in `MesssageWidget` by using the `usernameBuilder` property.

by default we build something like this for username
```dart
    Text(
      widget.message.user!.name,
      maxLines: 1,
      style: widget.messageTheme.messageAuthor,
      overflow: TextOverflow.ellipsis,
    );
```

instead of `user.name` you can then use `user.extraData['nickname]`.

**Comment by jasnicaa** [comment]
so, correct me if I am wrong: if I am setting extraData on the user I have to set a name as well otherwise it won't pick up from our setup on the dashboard?

**Comment by jasnicaa** [comment]
I have to reopen this issue because the keyboard problem is still appearing I am able to reproduce it with an Android emulator. It is happening there, on some Android devices but not on iOS X, iOS 12 mini or on Samsung A71. Also, it is happening with MessageInput and with plain TextField. 

I will paste my code below:

```
class ChatScreen extends StatelessWidget {
  const ChatScreen();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        automaticallyImplyLeading: false,
        brightness: Brightness.light,
        centerTitle: false,
        backgroundColor: Colors.white,
        elevation: 0,
        title: const Text("Chat", style: CustomTextStyles.appBarBlueTitle),
        actions: [
          IconButton(
            padding: const EdgeInsets.only(right: 15),
            onPressed: () {
              Navigator.pushNamed(context, dashboardScreenRoute);
            },
            icon: const Icon(
              IconData(0xe800, fontFamily: 'side-menu-icon'),
              color: CustomColors.hintGrey,
              size: 20,
            ),
          ),
        ],
      ),
      body: BlocBuilder<ChatCubit, ChatState>(
        builder: (context, state) {
          if (state.status == ChatStatus.failure) {
            // TODO handle errors

          }
          if (state.status == ChatStatus.loaded &&
              state.channel != null &&
              state.client != null) {
            return ChannelsBloc(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(8, 16, 8, 16),
                child: ChannelListView(
                  loadingBuilder: (BuildContext context) {
                    return const LoadingIndicator();
                  },
                  filter: Filter.in_(
                    'members',
                    [StreamChat.of(context).user!.id],
                  ),
                  sort: [SortOption('last_message_at')],
                  pagination: PaginationParams(
                    limit: 30,
                  ),
                  channelWidget: ChannelPage(),
                ),
              ),
            );
          } else {
            return const LoadingIndicator();
          }
        },
      ),
    );
  }
}
```

```
class ChannelPage extends StatelessWidget implements PreferredSizeWidget {
  @override
  final Size preferredSize;
  final VoidCallback? onTitleTap;

  ChannelPage({
    this.onTitleTap,
    Key? key,
  }) : preferredSize = const Size.fromHeight(kToolbarHeight);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<ChatCubit, ChatState>(
      builder: (context, state) {
        return Scaffold(
          backgroundColor: Colors.white,
          appBar: CustomChannelHeader(
            leading: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Row(
                children: [
                  CircleAvatar(
                    radius: 20,
                    child:
                        Image.asset("assets/chat-icon-0.png", fit: BoxFit.fill),
                  ),
                ],
              ),
            ),
            actions: [
              IconButton(
                padding: const EdgeInsets.only(right: 15),
                onPressed: () => Navigator.of(context).pop(),
                icon: const Icon(
                  IconData(0xe800, fontFamily: "custom-close"),
                  color: CustomColors.hintGrey,
                  size: 18.0,
                ),
              ),
            ],
            onTitleTap: () {
              print('pritisnuto');
            },
          ),
          body: BlocBuilder<ChatCubit, ChatState>(
            builder: (context, state) {
              return Column(
                children: [
                  Expanded(
                    child: MessageListView(
                      threadBuilder: (_, parentMessage) {
                        return ThreadPage(parent: parentMessage);
                      },
                    ),
                  ),
                  chat.MessageInput()
                
                ],
              );
            },
          ),
        );
      },
    );
  }
}
```

**Comment by jasnicaa** [comment]
Any news on this?

**Comment by xsahil03x** [comment]
@jasnicaa We are not able to reproduce this issue and ff it's also happening with regular `TextField` then most probably it's an issue in the Flutter framework rather than Stream's `MessageInput`.
