### ISSUE TITLE
Cascade deletion for `stream_chat_persistance` database is not working.

### ISSUE THREAD

**Issue by incendial** [GetStream/stream-chat-flutter#604]
Hi! First of all, I'm very new to `moor` package and your `stream_chat_persistance` is a great example on how to setup and work with a database, thank you!

**Describe the bug**
While setting up moor, I found out that cascade deletion that you declare here https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_persistence/lib/src/entity/messages.dart#L81 is not working because `PRAGMA foreign_keys = ON` is not set. I was able to reproduce it with the next code example:

```dart
final userId = '123';
final channelId = '435:world';
final _client = StreamChatPersistenceClient();
await _client.connect(userId);

final cannel = ChannelModel(id: channelId, cid: channelId);
await _client.updateChannels([cannel]);

final message = Message(id: '3465');
await _client.updateMessages(channelId, [message]);

await _client.deleteChannels([channelId]);

final existedMessages = await _client.getMessagesByCid(channelId)
final existedChannels = await _client.getChannelByCid(channelId);

print(existedMessages); // prints `Message instance`, but in the docs it says that all messages of a cid will be deleted
print(existedChannels); // prints null
```
reproduces with `stream_chat_persistence: ^2.1.1` and `stream_chat: ^2.1.1`.

Another part that proves the problem is that for upsert you use `mode: InsertMode.insertOrReplace` which according to the docs deletes the row if it already exists which should trigger delete cascade, but it doesn't get triggered right now. If the pragma settings is on, then it works, **but leads to the data loss** (tested on my database 😞 ).

I'm not sure, that the solution I found for my database suits you, but I hope it helps.
1. I ended up setting pragma as described here: https://github.com/simolus3/moor/issues/41#issuecomment-504543642
    ```dart
    @override
    MigrationStrategy get migration => MigrationStrategy(
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON;');
        },
     );
    ```
2. Instead of `mode: InsertMode.insertOrReplace` I switched to `into(...).insertOnConflictUpdate`, which works just fine and doesn't perform deletions.

Also, could you please clarify one thing to me: I'm looking at your db migrations code https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_persistence/lib/src/db/moor_chat_database.dart#L58 and if I understand it correctly, on a schema version update it will drop all tables with their data and then create new empty ones. Am I right about this behaviour?

**Comment by xsahil03x** [comment]
Hey @incendial, thanks for reporting these bugs. We haven't focused much on persistence so might have missed these. Can you try creating a PR and write some tests for the same? It will be great help for us 😄 

Also, about this 

> Also, could you please clarify one thing to me: I'm looking at your db migrations code https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_persistence/lib/src/db/moor_chat_database.dart#L58 and if I understand it correctly, on a schema version update it will drop all tables with their data and then create new empty ones. Am I right about this behavior?

Yes, you are right about the behavior. Our persistence basically acts as a cache so we reset it whenever the db schema changes.

**Comment by incendial** [comment]
> Can you try creating a PR and write some tests for the same? It will be great help for us 😄

If it's okay for you to wait a bit with the fix, then sure, I'd be happy to contribute. I think I'll be able to do that at the end of this week or so.

> Yes, you are right about the behavior. Our persistence basically acts as a cache so we reset it whenever the db schema changes.

Ooh, now I get it, thanks!
