### ISSUE TITLE
Quoted Message Documentation

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#605]
This is more of a question if this does not already exist but is there any documentation on adding quoted message UI? Also is there a way to show a pinned message are the top of the message list view even when scrolled?

**Comment by deven98** [comment]
Hey @rlee1990, you can find the quoted message UI docs [here](https://getstream.io/chat/docs/sdk/flutter/stream_chat_flutter/message_input/#quoting-a-message).

The functionality you are asking for does not exist in the `MessageListView`, however, it would be easily to add by querying the pinned messages yourself and displaying them over the listview however you need them. 

[Here's an implementation](https://github.com/GetStream/flutter-samples/blob/main/packages/stream_chat_v1/lib/pinned_messages_screen.dart) of our own which fetches pinned messages, you could simply use the same with a MessageSearchListView as well.

**Comment by deven98** [comment]
Closing this issue for now, if you have any more questions, please feel free to reopen.
Thanks :)
