### ISSUE TITLE
MessageInput weird with SafeArea and Elevation

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#606]
Hello

![image](https://user-images.githubusercontent.com/556990/128088766-e3f4efb5-92c4-4549-a575-c2a3aa3965c5.png)

https://github.com/GetStream/stream-chat-flutter/blob/2bb8a94865ca3352fd3f03dc5dfd2595b7247760/packages/stream_chat_flutter/lib/src/message_input.dart#L393

Maybe, add a setting to disable this elevation ?

Thank you,
Nelson

**Comment by HayesGordon** [comment]
Hi @Abacaxi-Nelson! Thanks for creating an issue. These are good suggestions for additional customisation and we'll explore them. Just to confirm, in the above screenshot did you remove the SafeArea for the message box?

**Comment by Abacaxi-Nelson** [comment]
Hey @HayesGordon 
Thanks for your return.

This one: https://github.com/GetStream/stream-chat-flutter/blob/2bb8a94865ca3352fd3f03dc5dfd2595b7247760/packages/stream_chat_flutter/lib/src/message_input.dart#L333
?

No i let this component as you ship it in stream_chat_flutter...

**Comment by HayesGordon** [comment]
Thanks. Do you mind sharing the code that allowed you to capture the above screenshot. I just want to make sure I'm not jumping to the wrong conclusion.

**Comment by Abacaxi-Nelson** [comment]
Ooooo @HayesGordon 
You were right. it's my fault. i had a SafeArea...
I'm using now
```dart
SafeArea(
          bottom: false,
          child: Scaffold(
```
and works... sorry

**Comment by HayesGordon** [comment]
No problem! Feel free to reopen if you have questions/suggestions.
