### ISSUE TITLE
change message text link color

### ISSUE THREAD

**Issue by firsttimeeagle** [GetStream/stream-chat-flutter#61]
so, my message contains link and its color is always blue, is there a way to customize that link color?

gz#4536

**Comment by saifudin** [comment]
This happened to me too. any advice besides changing the bubble color ?
Thanks..

<img width="309" alt="Screenshot at Jul 21 10-47-24" src="https://user-images.githubusercontent.com/3888015/88010739-ce230080-cb3f-11ea-98fb-fd0ec1f7a09e.png">

**Comment by imtoori** [comment]
I just released a new version adding `messageLinks` to the `MessageTheme` class

```dart
    return StreamChat(
          child: widget,
          client: client,
          streamChatThemeData: StreamChatThemeData(
            ownMessageTheme: MessageTheme(
              messageLinks: TextStyle(color: Colors.red),
            ),
          ),
        );
```

a little example on how to customize the link color

**Comment by firsttimeeagle** [comment]
wow, thank you, already tried it and works perfectly
