### ISSUE TITLE
Fix hindi translations

### ISSUE THREAD

**Issue by amitkma** [GetStream/stream-chat-flutter#611]
There are couple of translation issues for Hindi which can be improved.
1. Correct translation should be -> जवाब दें
https://github.com/GetStream/stream-chat-flutter/blob/b20952d8141ec7d9c6114ff60b523f0484e35335/packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart#L200
2. Photos should be translated to -> फ़ोटोज
https://github.com/GetStream/stream-chat-flutter/blob/b20952d8141ec7d9c6114ff60b523f0484e35335/packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart#L227
3. Yesterday label should be translated to -> कल
https://github.com/GetStream/stream-chat-flutter/blob/b20952d8141ec7d9c6114ff60b523f0484e35335/packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart#L253
4. Channel muted label should be translated to -> चैनल म्यूट है
https://github.com/GetStream/stream-chat-flutter/blob/b20952d8141ec7d9c6114ff60b523f0484e35335/packages/stream_chat_localizations/lib/src/stream_chat_localizations_hi.dart#L256

**Comment by xsahil03x** [comment]
@amitkma can you create a quick PR for all these changes?

**Comment by amitkma** [comment]
Sorry but I don't have capacity to do that nowadays.
