### ISSUE TITLE
QueryChannels stop fetching new channels

### ISSUE THREAD

**Issue by gvv-ua** [GetStream/stream-chat-flutter#612]
**Describe the bug**
When we fetch all channels and make pull to refresh after that, pagination stopped work.

**What package are you using? What version?**
2.1.1

**What platform is it about?**
- [x] Android
- [x] iOS

1. Open chat list screen
2. Scroll down to the latest channel
3. Scroll top
4. Pull to refresh
5. Scroll down (pagination doesn't work)

**Expected behavior**
Load new channels with pagination

*

**Comment by gvv-ua** [comment]
In queryChannels of ChannelsBloc:

`final clear = paginationParams.offset == 0;`

but _paginationEnded not cleared.

**Comment by imtoori** [comment]
hey @gvv-ua thanks for reporting the issue! I'm fixing it right now
