### ISSUE TITLE
Message Input Error Handling

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#622]
When using the package to handle message input error it always sends an exception which is not ideal. Also the error is always of type object and so it makes it harder to check for certain error codes. It would be nice if we could get an alert or something if say a user was banned from a channel and tried to send a message. As of now we get code 17 error which is fine if we can parse the object.

**What platform is it about?**
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by rlee1990** [comment]
@xsahil03x are there any options for this?

**Comment by xsahil03x** [comment]
Hey @rlee1990, I guess you can do something like this.
```dart
MessageInput(
  onError: (error, stacktrace) {
    // this also automatically casts object
    // to StreamChatNetworkError inside the scope.
    if (error is StreamChatNetworkError) {
      if (error.code == 17) {
        // do something
      }
    }
  },
),
```

**Comment by rlee1990** [comment]
I will give that a try and see what happens @xsahil03x
