### ISSUE TITLE
How to listen onTap of the channel message list avatar. 

### ISSUE THREAD

**Issue by yswtrue** [GetStream/stream-chat-flutter#64]
How can I listen on the tap event of the message list avatar, such as click avatar to jump to user profile page? I couldn't find the param.

gz#4659

**Comment by imtoori** [comment]
you can pass a `MessageBuilder` to the `MessageListView`
It has a parameter called `onUserAvatarTap` 

Something like this: 
```dart
  Widget _messageBuilder(
    BuildContext context,
    MessageDetails details,
    List<Message> messages,
  ) {
    final message = details.message;
    final color = details.isMyMessage ? Colors.blueGrey : Colors.blue;
    if (message.isSystem) {
      return SystemMessage(
        message: message,
      );
    }
    return MessageWidget(
      message: message,
      messageTheme: details.isMyMessage
          ? StreamChatTheme.of(context).ownMessageTheme
          : StreamChatTheme.of(context).otherMessageTheme,
      borderSide: BorderSide(
        color: color,
        width: 2,
      ),
      padding: const EdgeInsets.all(2),
      attachmentBorderSide: BorderSide(
        color: color,
        width: 2,
      ),
      attachmentPadding: EdgeInsets.all(8),
      borderRadiusGeometry: BorderRadius.vertical(
        top: !details.isLastUser ? Radius.circular(16) : Radius.zero,
        bottom: !details.isNextUser ? Radius.circular(16) : Radius.zero,
      ),
      showSendingIndicator: DisplayWidget.gone,
      reverse: false,
      showUserAvatar:
          details.isNextUser ? DisplayWidget.hide : DisplayWidget.show,
      showTimestamp: !details.isNextUser,
      showUsername: !details.isNextUser,
      showReactions: false,
      showReplyIndicator: false,
      onUserAvatarTap: (user) {
        print('TAPPED USER ${user.name}');
      },
    );
  }
```

There is also an example in the `/example` folder, but we're planning to write more docs about this and other use cases

**Comment by yswtrue** [comment]
> ```dart
>     final message = details.message;
>     final color = details.isMyMessage ? Colors.blueGrey : Colors.blue;
>     if (message.isSystem) {
>       return SystemMessage(
>         message: message,
>       );
>     }
>     return MessageWidget(
>       message: message,
>       messageTheme: details.isMyMessage
>           ? StreamChatTheme.of(context).ownMessageTheme
>           : StreamChatTheme.of(context).otherMessageTheme,
>       borderSide: BorderSide(
>         color: color,
>         width: 2,
>       ),
>       padding: const EdgeInsets.all(2),
>       attachmentBorderSide: BorderSide(
>         color: color,
>         width: 2,
>       ),
>       attachmentPadding: EdgeInsets.all(8),
>       borderRadiusGeometry: BorderRadius.vertical(
>         top: !details.isLastUser ? Radius.circular(16) : Radius.zero,
>         bottom: !details.isNextUser ? Radius.circular(16) : Radius.zero,
>       ),
>       showSendingIndicator: DisplayWidget.gone,
>       reverse: false,
>       showUserAvatar:
>           details.isNextUser ? DisplayWidget.hide : DisplayWidget.show,
>       showTimestamp: !details.isNextUser,
>       showUsername: !details.isNextUser,
>       showReactions: false,
>       showReplyIndicator: false,
>       onUserAvatarTap: (user) {
>         print('TAPPED USER ${user.name}');
>       },
>     );
> ```

It worked, thank you
