### ISSUE TITLE
Hope support for sorting channel list by custom fields

### ISSUE THREAD

**Issue by yswtrue** [GetStream/stream-chat-flutter#65]
I need to put system_message channel and customer_message channel on the top of channelsPage, but I can't sort by a custom field like `priority`. Hope support for sorting by custom fields.

gz#4687

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4687'>Zendesk ticket #4687</a>:<br><br>You can sort by custom channel fields. Can you share how you're using `channellistview` and the `sort` parameter you're using, please?

**Comment by yswtrue** [comment]
> Agent comment from Stephen Hodgetts in [Zendesk ticket #4687](https://getstream.zendesk.com/agent/tickets/4687):
> 
> You can sort by custom channel fields. Can you share how you're using `channellistview` and the `sort` parameter you're using, please?

```dart

class ChannelListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        centerTitle: true,
        title: Text(
          'Messages',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
        ),
      ),
      body: ChannelsBloc(
        child: ChannelListView(
          filter: {
            'members': {
              '\$in': [StreamChat.of(context).user.id],
            }
          },
          sort: [
            SortOption('priority', direction: 1),
            SortOption('last_message_at')
          ],
          pagination: PaginationParams(
            limit: 20,
          ),
          channelWidget: ChannelPage(),
        ),
      ),
    );
  }
}
```
this is my ChannelListView code.

**Comment by imtoori** [comment]
hey @yswtrue I did some research and found out that you should keep in mind that the sorting fields are first transformed to `string` before being compared, so you should pad your priority field

eg: not `1` but `01`

check it here https://play.golang.org/p/GvJV0E5Sj2_4

however, this raises a bug related to channels being pushed to the top of the `ChannelListView` when they receive a new message. I'll make sure to fix this bug and find a solution as soon as possible

**Comment by imtoori** [comment]
@yswtrue did you solve your problem?

**Comment by yswtrue** [comment]
> @yswtrue did you solve your problem?

 I sort by message type now, so I haven't tried this solution.

**Comment by imtoori** [comment]
Closing this
Feel free to reopen it if this is still an issue
