### ISSUE TITLE
totalUnreadCount is always 0 on app launch

### ISSUE THREAD

**Issue by jasnicaa** [GetStream/stream-chat-flutter#659]
So I am trying to get the total unread count from the stream and data it is always 0 at first, although when I inspect the client I can see under totalUnreadCount that there is a number.  I want to show the number of unread messages in the tabBar when a user enters the app without the need to enter the channel itself. 

As you can see on the image both totalUnreadCount and unreadChannels are zero and totalUnreadCount is 3.

Am I missing something here?

![Screenshot 2021-09-06 at 15 47 39](https://user-images.githubusercontent.com/25682164/132226981-86eb81f3-4166-4f50-b273-09aa406064d6.png)

**Comment by xsahil03x** [comment]
Hey @jasnicaa, I am looking into this.

**Comment by jasnicaa** [comment]
HI guys, so I was just testing this fix, and still is not working for me as expected.

I enter the app and send a message from another account and when debugging I can see that in the currentUser totalUnreadCount has updated while totalUnreadCount from the Stream is zero. It only updates when I enter the channel.

![Screenshot 2021-09-10 at 16 03 18](https://user-images.githubusercontent.com/25682164/132866092-dd36fb92-7e15-47ff-b896-a694e2b5da53.png)

**Comment by imtoori** [comment]
this hasn't been released yet 
are you trying it using git dependency?

**Comment by jasnicaa** [comment]
no, I saw this 
<img width="765" alt="Screenshot 2021-09-10 at 16 10 39" src="https://user-images.githubusercontent.com/25682164/132866909-c9439c89-5df5-4f36-adea-341c6bb62490.png">

**Comment by imtoori** [comment]
yeah that was another issue
you can check the upcoming changelog here https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat/CHANGELOG.md

**Comment by rickgrade3** [comment]
> this hasn't been released yet

Do you have any workaround of this issue before the release?

**Comment by imtoori** [comment]
I can't think of nothing right now, but we'll probably publish the next release early next week

**Comment by jasnicaa** [comment]
@rickgrade3  If you are using bloc you can create your own totalUnreadCount from currentUser.totalUnreadCount - this number is updating correctly, I started this way but decided to wait for an update
