### ISSUE TITLE
When I hide a channel, and the channel can't auto display again.

### ISSUE THREAD

**Issue by yswtrue** [GetStream/stream-chat-flutter#66]
When I hide a channel, and channelsListView won't auto display when receiving a message, and I have to refresh channelsListView manually.

gz#5111

**Comment by imtoori** [comment]
Hey @yswtrue, the last release should solve this problem

**Comment by xie-samuel** [comment]
Hi, this issue appear again in stream v3.4.0. Do you have any idea what is the root caused?
