### ISSUE TITLE
Upgrade url_launcher for API level 30

### ISSUE THREAD

**Issue by Freyien** [GetStream/stream-chat-flutter#664]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

stream_chat_flutter: ^2.2.1

### What happened?

I send one PDF File, but android devices with API level 30 cannot launch the url.

Url launcher resolve it at version 6.0.8 

### Steps to reproduce

```bash
1. Open conversation
2. Send pdf file
3. In Android device with API level 30 try to open the file
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
At the moment the `url_launcher` dependency is constrained like this 
```yaml
  url_launcher: ^6.0.3
```
This means that if you run `flutter pub upgrade` you'll get the latest version that is < 6.1.0

So that would solve your issue apparently. I just ran `flutter pub upgrade` and got version 6.0.9 of `url_launcher`
