### ISSUE TITLE
Compatibility issue with graphql/ rxdart

### ISSUE THREAD

**Issue by mwawrusch** [GetStream/stream-chat-flutter#665]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

 graphql: ^5.0.0
stream_chat_flutter 2.2.1

### What happened?

I was forced to upgrade stream_chat_flutter from a 2.0.0 nullsafety version to the latest because the included file_picker in the older one does not compile with android. Now I get those version conflicts - and it prevents us from releasing our android version to testers.

```stacktrace
Because graphql >=4.0.3-alpha.1 depends on rxdart ^0.26.0 and stream_chat_flutter >=2.0.0-nullsafety.4 depends on rxdart ^0.27.0, graphql >=4.0.3-alpha.1 is incompatible with stream_chat_flutter >=2.0.0-nullsafety.4.
So, because roji_wallet depends on both stream_chat_flutter 2.2.1 and graphql ^5.0.0, version solving failed.
Running "flutter pub get" in roji_wallet...                             
pub get failed (1; So, because roji_wallet depends on both stream_chat_flutter 2.2.1 and graphql ^5.0.0, version solving failed.)
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@mwawrusch This should fix it.
```yaml
dependency_overrides:
  rxdart: ^0.26.0
```

**Comment by mwawrusch** [comment]
nice, live saver!!!
