### ISSUE TITLE
Event type when user taps on notification 

### ISSUE THREAD

**Issue by jasnicaa** [GetStream/stream-chat-flutter#667]
Hey guys, so I can see that there are multiple background events I can listen to, but there isn't one when the user taps on a specific notification, or is it NOTIFICATION.MARK_READ? I am not sure if this event is added after opening a channel or right after tapping on the notification.

Thanks.

**Comment by imtoori** [comment]
There is no event linked to the tapping of the notification
The `notification.mark_read` event is received when the total count of unread messages (across all channels the user is a member) changes
https://getstream.io/chat/docs/flutter-dart/event_object/?language=dart

So yeah, this is usually received after you open a channel with unread messages, not after the tapping on the notification

**Comment by jasnicaa** [comment]
yeah ok guess it should be handled through local notification package or/and firebase, just wanted to check. tnx
