### ISSUE TITLE
messageLinksStyle in MessageThemData is not applied

### ISSUE THREAD

**Issue by mingzew** [GetStream/stream-chat-flutter#670]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

2.2.1

### What happened?

There were couple of issues I've spotted
1. I expect the hyperlink to be light blue with an underline, but it's just in the style of set by messageTextStyle
2. In a message with hyperlink **and** if I was the owner of the hyperlink message - messageBackgroundColor of **ownMessageTheme** is the messageBackgroundColor of **otherMessageTheme**. For example, if my own msg background is black, and other's is white. I'd expect black background for my text with hyperlink, but in practice it's white.

```
  get lightBlue14RegularUnderline => TextStyle(
        color: hdLightBlue,
        fontFamily: 'Lato-Regular',
        fontSize: 14,
        decoration: TextDecoration.underline,
      );

final MessageThemeData hdOtherMsgTheme = MessageThemeData(
    messageBackgroundColor: hdGreyMediumBlueHue,
    messageBorderColor: transparent,
    messageLinksStyle: _appTheme.lightBlue14RegularUnderline,
    messageTextStyle: _appTheme.darkBlue14Regular,
);

final MessageThemeData hdOwnMsgTheme = MessageThemeData(
    messageBackgroundColor: hdPink,
    messageBorderColor: transparent,
    messageLinksStyle: _appTheme.lightBlue14RegularUnderline,
    messageTextStyle: _appTheme.white14Regular
);

StreamChat(
        streamChatThemeData: StreamChatThemeData(
          otherMessageTheme: hdOtherMsgTheme,
          ownMessageTheme: hdOwnMsgTheme,
      ...
))
```
if messageLinksStyle doesn't represent msgs with hyperlink, please let me know. Thanks!

### Steps to reproduce

```bash
1. set a custom messageLinkStyle and post a link in chat
2. the color/style won't be reflected (see above for details)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @mingzew, not able to reproduce the issue. Working fine for me.
Can you share a short sample project to test the issue?

**Comment by mingzew** [comment]
See ss and code below

1. I'd expect link that I've sent to be pink bg with white text for "hahaha" and blue + underline for hypedating.com
2. I'd expect link that the other person sent to be grey bg with blacktext for "jkjkjk" and blue + underline for Google.com
3. Not sure where the greyish-blue bubble is coming from for the link bubble as per ss

[my_app 2.zip](https://github.com/GetStream/stream-chat-flutter/files/7140179/my_app.2.zip)
![Screenshot_20210909-185846](https://user-images.githubusercontent.com/5702344/132774046-9560d128-7125-4b75-a0bd-d035412dab0f.png)

**Comment by xsahil03x** [comment]
Hey @mingzew,
I finally understood the issue. The actual issue is with `flutter_markdown` package which we use in order to parse the message text. It does not recognise url's without `www` or `http` as a valid url.

If you see in the ss below, making it a valid url works fine. 

<img width="361" alt="Screenshot 2021-09-10 at 3 02 14 PM" src="https://user-images.githubusercontent.com/25670178/132841368-6f917e19-e351-4ac2-b808-03483715882a.png">

I don't think we can do anything about this atm, but surely we will look for some better alternatives.

Thanks,
Sahil

**Comment by mingzew** [comment]
@xsahil03x is it possible to change the color of the background of the link bubble? Where was that coming from?

**Comment by xsahil03x** [comment]
Hey @mingzew, it's mentioned in my previous answer 🙂

**Comment by mingzew** [comment]
oh my apologies, the notification in my email did not include the edit. Thanks for the help and quick turn around!
