### ISSUE TITLE
StreamChannel() Doesn't Show Loading Screen

### ISSUE THREAD

**Issue by mingzew** [GetStream/stream-chat-flutter#678]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

2.2.1

### What happened?

Loading up widgets that contain StreamChannel() initially (after restart of app or Hot Restart) takes a long time (4-6 seconds) and it doesn't show a loading bar even with showLoading: true.

### Steps to reproduce

```bash
1. Set up a ChannelListView with channelPreviewBuilder that have a ontap function that calls StreamChannel()
2. Fire up the app for the first time and tap on the widget that builds StreamChannel()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jgadsby** [comment]
I noticed a related issue, that the message list view doesn't seem to use my loadingBuilder and instead shows a circular progress indicator with default colors, despite my theme colors already being defined.

**Comment by imtoori** [comment]
@mingzew can you add a snippet for reproducing the bug? thanks

**Comment by imtoori** [comment]
@jgadsby are you talking about the widget that shows when there are no messages?

**Comment by jgadsby** [comment]
> @jgadsby are you talking about the widget that shows when there are no messages?

No, just the widget that shows when the channel is loading.

**Comment by imtoori** [comment]
what do you mean? the loading indicator for pagination?

**Comment by jgadsby** [comment]
> what do you mean? the loading indicator for pagination?

What does loadingBuilder actually override in MessageListView?

**Comment by imtoori** [comment]
it overrides the list loading indicator that shows up when we're fetching the messages
are you trying to override the loading indicator for pagination? we should add that option I think

**Comment by jgadsby** [comment]
> it overrides the list loading indicator that shows up when we're fetching the messages
> are you trying to override the loading indicator for pagination? we should add that option I think

Yeah, that's what's not working for me. I'm not trying to override the pagination loader. See this snippet which doesn't work: 

`loadingBuilder: (context) { return Center( child: SizedBox( width: 128, height: 128, child: Lottie.asset( "assets/loading_indicator.json"))); },`

**Comment by imtoori** [comment]
yeah it's not that it doesn't work, it overrides only the main loading indicator that you can see when the first query is in progress, not the one used while paginating
I added a task in our backlog for letting users customize even that one. we'll work on that

**Comment by mingzew** [comment]
Hi i've attached a code example showing the issue. A few things
1. I've used a custom channel_type with character count to 1000 and all commands turned off
2. I created a bunch of channel with 2 users, with one of the user being "user1"
3. To run the code - change apiKey, channelType, and userId (assign it "user1" or w/e user name you've created) in stream_api.dart
4. once it ran, click any channel with some text msg in it and you can see console print out "chat initState is being called" and "chat finished build" really quickly, but it takes about 2-4 second to go to see the actual chat msg without loading screen

Let me know if you have any questions
[my_app 3.zip](https://github.com/GetStream/stream-chat-flutter/files/7200560/my_app.3.zip)

**Comment by imtoori** [comment]
hey @mingzew this is probably a performance issue, we're looking into that
I'll let you know as soon as we have more information

**Comment by mingzew** [comment]
Yeah the time it takes is not ideal, that seem like a performance related issue. The loading screen should show in the main time, no?

Perhaps there's a work around with futureBuilder?

**Comment by imtoori** [comment]
Hey @mingzew 
it's been a while since this issue received some comments
Now we are on version 3.5.1 of the SDK and I think we made some solid progress
Can you check and tell me what you think?

**Comment by Abacaxi-Nelson** [comment]
Hi @imtoori 
Do you want me to create a new issue ?
I'm experiencing long loading time (without the loader indicator).
I dont know if its same issue or not (last sdk version) (Circle chats on left have same behaviour, but i preload it)



https://user-images.githubusercontent.com/556990/159690158-dfd71d71-5fe3-4c81-bd84-f5b86c808752.mp4

**Comment by imtoori** [comment]
@Abacaxi-Nelson yes please create a new issue
This seems like a different issue
