### ISSUE TITLE
addMembers

### ISSUE THREAD

**Issue by originalgovernment** [GetStream/stream-chat-flutter#68]
Hi,

I'm currently trying to figure out how to add members to a channel.

This is the call I'm making but it seems to be resulting in a Dio related error (unable to encode an object)

I'm not really sure if I'm calling the function incorrectly or if this is a problem with Stream Chat. I'd really appreciate any guidance!

Please let me know if you need to see more of my code.

![image](https://user-images.githubusercontent.com/69223767/89356440-c9a42f00-d68b-11ea-9403-609841c951f9.png)

![image](https://user-images.githubusercontent.com/69223767/89356402-af6a5100-d68b-11ea-9e89-324026379934.png)

Also it seems the Dart docs are outdated, the way addMembers is called here seems incorrect.

![image](https://user-images.githubusercontent.com/69223767/89356509-ff491800-d68b-11ea-9fe4-8d45ffc46a10.png)

gz#5163

**Comment by imtoori** [comment]
hey @originalgovernment you were right
I just released a new version.
Now you can pass a list of userIds like the documentation says.
Thanks for the reporting

**Comment by originalgovernment** [comment]
Just tried it, it's working perfectly now.

Thank you for your quick response and for patching it!!
