### ISSUE TITLE
onAttachmentTap override in message.copyWith() doesn't do anything

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#680]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

2.2.1

### What happened?

`messageWidget.copyWith(
      onAttachmentTap: (message, attachment) {
      print("On attachment tap");
    }`

The above print statement never gets called in the log.

### Steps to reproduce

```bash
1. Override a messageWidget with copyWith and add a custom callback for onAttachmentTap.
2. See that the enclosed code block never gets called.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @jgadsby, 

I'm taking a look into this, I'll have an update soon.
Thanks.
