### ISSUE TITLE
Users lose their place in the conversation after replying in threads.

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#687]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

2.2.1

### What happened?

When replying in a thread from a parent MessageListView, sending a reply resets the scroll position of the parent MessageListView to the bottom, so users lose their place in the chat after replying. I'm guessing a fix for this would be to not automatically scroll to the bottom when a thread reply is added.

### Steps to reproduce

```bash
1. Override threadBuilder with your own ThreadPage implementation
2. Find a chat with a bunch of messages in it and scroll up to the top
3. Long press one of the first messages and tap on Thread Reply
4. Add a reply to the thread in ThreadPage
5. Exit ThreadPage and notice how the chat is now at the bottom and you've lost your place in the chat message list.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hey @jgadsby we're looking into this
sorry for the delay
