### ISSUE TITLE
Hope add support for voice chatting and video chatting

### ISSUE THREAD

**Issue by yswtrue** [GetStream/stream-chat-flutter#71]
We have embedded this chat SDK, and now we need to add voice chatting and video chatting, I had read the document, but Voxeet doesn't have a flutter SDK yet.  is there any plan of voice chatting and video chatting?  Thanks.

gz#5219

**Comment by yswtrue** [comment]
and voice chat is record audio then send to the channel, not real-time one.

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5219'>Zendesk ticket #5219</a>:<br><br>There are no plans to add this functionality, sorry.

**Comment by imtoori** [comment]
> and voice chat is record audio then send to the channel, not real-time one.

I think you can implement this using custom attachments
