### ISSUE TITLE
New Channel is not reflected when member is added again.

### ISSUE THREAD

**Issue by hiashutoshsingh** [GetStream/stream-chat-flutter#728]
### Which packages are you using?

stream_chat_flutter_core, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter_core: 3.1.1
  stream_chat_persistence: 3.0.0

### What happened?

When a user is added to a channel, channels in `ChannelListCore` is updated, then removing the same user or the user leaves the group from the same channel then also newly updated channels is reflected, but after adding the same user again to the same channel, newly updated channels are not reflected, it remains same.

Restarting the app channels is reflected as expected.

Although we get a event from `member.added` and `notification.added_to_channel`
But to render the list we need the context of the channel when the user has added again after removing it.

### Steps to reproduce

```bash
1. Add user to a channel.
2. Remove user from a channel or ask to leave from the channel.
3. Add the user to the same channel again.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TramPamPam** [comment]
@hiashutoshsingh @imtoori 

hi 

does this issue persist in stream_chat_flutter 3.3.2 ?

**Comment by xsahil03x** [comment]
> 1. Add user to a channel.
> 2. Remove user from a channel or ask to leave from the channel.
> 3. Add the user to the same channel again.

Hey @hiashutoshsingh, I am unable to reproduce the issue with the steps you mentioned above. Can you share a small video about the same?

Thanks,
Sahil
