### ISSUE TITLE
Pull to refresh channel list shown removed channel

### ISSUE THREAD

**Issue by hieubagiang** [GetStream/stream-chat-flutter#732]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

Android

### What version are you using?

  stream_chat_flutter: ^3.1.1
  stream_chat_flutter_core: ^3.1.1
  stream_chat_persistence: ^3.0.0
  stream_chat_localizations: ^2.0.0

### What happened?

Pull to refresh channel show leaved channel

### Steps to reproduce

```bash
1. Go to 'Channel List Page'
2. Pull to refresh
3. When data is loading from API, it shown leaved group
4. When done, it replaced by new data
```

### Flutter doctor output

```shell
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1237], locale vi-VN)
    • Flutter version 2.5.2 at D:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (11 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.1
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[√] Connected device (3 available)
    • Pixel 2 XL (mobile) • 192.168.0.125:5555 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome             • web-javascript • Google Chrome 94.0.4606.71
    • Edge (web)          • edge               • web-javascript • Microsoft Edge 94.0.992.38

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hieubagiang** [comment]
Update:
If i delete channel, screen will not delete channel in local data.
Show when i pull to refresh, it shows deleted channel from local data while data is be fetching.
if i logout and login (delete persistence data) - when pull to refresh channel list, every thing will be okay

**Comment by ManasviPatidar** [comment]
> Update:
> If i delete channel, screen will not delete channel in local data.
> Show when i pull to refresh, it shows deleted channel from local data while data is be fetching.
> if i logout and login (delete persistence data) - when pull to refresh channel list, every thing will be okay

I am also facing the same glitchy behaviour.
The source of the problems seems to be that the default [loadData](https://github.com/GetStream/stream-chat-flutter/blob/a3cce7ffff39511c3bb3cc165c5c1f9934443077/packages/stream_chat_flutter_core/lib/src/channel_list_core.dart#L152) of ChannelListView does not specify any `offset` in `paginationParams`. This value is passed down to [queryChannelsOnline](https://github.com/GetStream/stream-chat-flutter/blob/a3cce7ffff39511c3bb3cc165c5c1f9934443077/packages/stream_chat/lib/src/client/client.dart#L557) which updates the channel cache only when `paginationParams.offset == 0`.

In fact, this issue extends to all the situations where the channels cached by `StreamChatPersistenceClient` are outdated, not only the cases when they are deleted. These situations frequently occur in our use case where the user uses different devices to chat.

@imtoori I will suggest that [this](https://github.com/GetStream/stream-chat-flutter/blob/a3cce7ffff39511c3bb3cc165c5c1f9934443077/packages/stream_chat/lib/src/client/client.dart#L623) should also clear cache when `paginationParams.offset == null`.

**Comment by imtoori** [comment]
this has been fixed in develop, you'll see the patch in the next release
