### ISSUE TITLE
Username overwritten with user id when name is null

### ISSUE THREAD

**Issue by bschneidinger** [GetStream/stream-chat-flutter#736]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

2.2.1

### What happened?

connectUser is called for a user id that already exists (the user has a valid user name).
But when the user which is passed to connectUser has name = null, the username is overwritten in the DB with the id of the user. But the user name shouldn't change, when connectUser is called with a user object where only id is passed to the constructor.

### Steps to reproduce

```bash
1. Create a user with id "1" in the DB and set name to "mike"
2. Create a user object that references the user: final user = User(id: "1");
3. Connect the user: client.connectUser(user, token)
4. Observe that username in the DB changed from "mike" to "1"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Already fixed in [^3.0.0](https://pub.dev/packages/stream_chat/changelog#300)
