### ISSUE TITLE
Unread Counter not Stream Properly

### ISSUE THREAD

**Issue by mmustafaget** [GetStream/stream-chat-flutter#744]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

 stream_chat_flutter_core: ^3.1.1

### What happened?

Unread count shows only when the ui is build first time and also the one more time when new message is arrived ( **Only 1 time** unread counter streams when new message is received )

Also new `lastMessageStream` is perfectly working when new message is arrived but the problem is only with `unreadCountStream`. 

`unreadCountStream` should also work properly.

is there is something I am missing with code tell me I'll provide you all what you want, I have attached the snippet of code.

### Steps to reproduce

```bash
Open the app
1. navigate to channel list page.
   (you will see unread count per channel correctly)
2. you'll have to received the message for this user so will see the unread count issue.
3. when you received the first message
   lastMessageStream working properly also unreadCountStream
4. you'll need to received the message again on this user.
   now you'll see unread count not updating but last message update properly.
```

### Supporting info to reproduce

<img width="342" alt="Screenshot 2021-10-22 at 4 49 39 PM" src="https://user-images.githubusercontent.com/84316313/138448801-79f651fa-d4eb-4986-9f67-0ef86b4e8798.png">

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by akul1994** [comment]
This issue still persists in 3.3.2

**Comment by akul1994** [comment]
in my case both the `unreadCountStream` and `channel.state.unreadCount` are always returning 0, 
lastMessageStream seems to be working fine

**Comment by xsahil03x** [comment]
Hey @akul1994 , can you also share a small video about the issue? It will be much easier for us to replicate.

Thanks,
Sahil

**Comment by akul1994** [comment]
I will share the video on the support ticket I created for this.
I'll explain the logs here.

Here is the block of code I'm using for the unread and last message stream. I've added relevant logs too

```
void lastMessageStream() {
    primaryChannel?.state?.lastMessageStream.listen((event) async {
      if (lastMessage != null && lastMessage?.id != event?.id) {
        unreadCount = primaryChannel!.state!.unreadCount;
        if (mounted)
          setState(() {
            AppUtils.log(ClubChannelListItem.TAG,
                "Last message stream for message id ${event?.id} from user ${event?.user?.id} , My user id is ${StreamChat.of(context).currentUser?.id}");
            lastMessage = event;
          });
        widget.clubItemBloc
            ?.updateLatestClubMessage(lastMessage, primaryChannel);
        // widget.expertHomeBloc.refreshChannelController.add(true);
      }
    });
    primaryChannel?.state?.unreadCountStream.listen((event) {
      if (mounted)
        setState(() {
          AppUtils.log(
              ClubChannelListItem.TAG, "From unread count stream $event");
          unreadCount = event;
        });
      widget.clubItemBloc?.updateUnreadCount();
    });
  }
  ```
  
  As per the logs from the above code block, this is what I'm getting
  
  ```
  2021-12-24 14:18:13.338 16186-16321/com.tresscommas.threedots.stage I/flutter: │ 🐛 ClubChannelListItem ---- Last message stream for message id 5d1ceb7d-5a47-4d66-86a6-035a54b01d7a from user 9c36e41e-8002-4b17-88dc-0c0379a56177 , My user id is 3e9f7311-8e46-4ffb-8da3-1d4a9ec3030b
  
  2021-12-24 14:18:13.339 16186-16321/com.tresscommas.threedots.stage I/flutter: │ 🐛 ClubChannelListItem ---- From unread count stream 0
  ```
  
  Here you can see `lastMessageStream` fires with correct data, `unreadCountStream` always gives 0,
  Hope this helps

**Comment by akul1994** [comment]
I also just noticed that
`channel.state.unreadCount` is also returning 0

**Comment by akul1994** [comment]
Hey @xsahil03x, Any updates on this?
