### ISSUE TITLE
Better approach to fetch all channels

### ISSUE THREAD

**Issue by salihgueler** [GetStream/stream-chat-flutter#753]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, MacOS

### Is your feature request related to a problem?

Right now if a person would like to fetch all the channels they can not do it properly. They need to either;

- Listen to stream (not a Future) to fetch all channels
- Fetch the channels according to their state of being online and offline.

In addition to this, according to the doc [here](https://getstream.io/chat/docs/flutter-dart/query_channels/?language=dart#query-options) one person can fetch only 30 channels at once. I do not understand it properly. Does that mean I can only get 30 channels at once? If yes, what is the reason for that? 

### Describe the solution that you'd like

I want to have a way to fetch all channels at once. In addition, I would like to either increase the limit of fetching all channels or have a proper documentation about explainin how to get all channels or simply have a proper documentation on pagination. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by salihgueler** [comment]
Hello @imtoori, also, having the channel ids and trying to fetch the messages per channel as a separate call does not work either. If the channel state is too big of an object, I would recommend to make it available as smaller chunk of datas.

In addition to this, with the ChannelState reference, I would expect to have a way to update the properties (e.g. messages) as a call as well.

These are big stuff I know but they kinda block me at the moment.

**Comment by imtoori** [comment]
@salihgueler can I ask what's the use case here?

**Comment by salihgueler** [comment]
@imtoori In our case, the channel identifiers are related to another data set. So I know the channel ids that I have. But I would like to be able to get the messages for each channel id. I don't want to show only 20 of them, I want to be able to show it all. 

p.s. I also checked your tutorials etc. but they also cover only 20 latest messaging groups.

**Comment by imtoori** [comment]
Hey @salihgueler 
I checked with the backend team, and unfortunately, there's nothing to do about this since it's a backend limitation
All you can do is paginate data

**Comment by salihgueler** [comment]
Hey @imtoori I know pagination is the way but if a user scrolls quickly this means it will be a lot of requests to the backend and then BE says, it can not handle too many messages at once. How can we deal with that then?

**Comment by imtoori** [comment]
Hey @salihgueler,
backend team suggests throttling the requests client-side.
You could have a default duration for pagination (something like 300ms).
Unfortunately, there's nothing we could do on LLC level :/

**Comment by salihgueler** [comment]
@imtoori I see. Thank you anyways.
