### ISSUE TITLE
Channel sorting breaks when using StreamChatPersistenceClient.

### ISSUE THREAD

**Issue by jfacoustic** [GetStream/stream-chat-flutter#754]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS

### What version are you using?

  stream_chat_flutter: ^3.1.1
  stream_chat_persistence: ^3.0.0

### What happened?

Expected: Channels to when online

Actual:
ChannelListView shows "Error Loading Channels" despite being online.  This error goes away when I remove the sort from the ChannelListView.

```dart
      sort: const [SortOption('last_message_at')],
```

### Steps to reproduce

```bash
1. Link StreamChatClient instance with StreamChatPersistenceClient.
2. Navigate to an existing ChannelListView with a defined sort.
3. Channel list renders an error
4. Remove the sort, reload the app, and the list successfully renders.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hi @jfacoustic 
that's because you need to specify the comparator in the SortOption if you're using offline storage
That's because we need it to sort channels locally in case of reading from the cache

You can use something like this 
```dart

                        SortOption('last_message_at', comparator: (a, b) {
                          final dateA = a.lastMessageAt ?? a.createdAt;
                          final dateB = b.lastMessageAt ?? b.createdAt;
                          return dateB.compareTo(dateA);
                        }),
```

**Comment by ghunkins** [comment]
@imtoori can the above be added to the documentation on `StreamPersistenceClient`? I copied the sample app `SortOption` (does not have comparator) and was getting the error message, and could not figure out the issue for awhile.

Can confirm that the above solves this issue, thank you!
