### ISSUE TITLE
Notifications not opening on click

### ISSUE THREAD

**Issue by kalptech2021** [GetStream/stream-chat-flutter#757]
I have firebase messaging integrated into the flutter app, everything works fine when used with cloud functions. When I am using stream chat, the click action is not working. Do we have any documentation on how to handle click events? I can not find any. After clicking notifications it's not even opening the app. 
I am using the default firebase template and data template. Please help I can not find any documentation on flutter, how to navigate to a certain screen when the user clicks on the notification, any document will help.

**Comment by imtoori** [comment]
Hi @kalptech2021 
That's something you need to configure on your own
I'd suggest looking into firebase messaging documentation 
Anyway, I'll add to our backlog a task to write a guide on this for future reference

**Comment by kalptech2021** [comment]
Hello @imtoori , It's working now, I had to delete the click action from the default template.
