### ISSUE TITLE
FilePicker is called with withData=true, crashing on big files

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#760]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

3.1.1

### What happened?

When picking large files (videos with a >500 MB on my device, but this will vary), the app crashes because default `MessageInput` widget uses the following code to get a file from the FilePicker plugin:
```
  final res = await FilePicker.platform.pickFiles(
        type: type,
        withData: true,
      );
```
According to issues in the FilePicker github, the `withData` loads the full file in the phone memory, which is I believe not necessary and setting it to `false` seems to work fine too: https://github.com/miguelpruivo/flutter_file_picker/issues/392

### Steps to reproduce

```bash
1. Use stream chat flutter MessageInput Widget
2. Click Attachments and select large file 
3. Phone crashes with OutOfMemory exception
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @flodaniel,

Curious bug.
I'll try to see if we can work around this limit and let you know.
Thanks for reporting this.
