### ISSUE TITLE
deleteImage/deleteFile not called from custom AttachmentFileUploader

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#761]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

3.1.1

### What happened?

Delete methods  from custom `AttachmentFileUploader` are not being called. 
The actions modal, which is opened to allow the deletion of a message, calls in `channel.dart` (line 678):
`      final response = await _client.deleteMessage(message.id);
`
which never seems to hook into the `AttachmentFileUploader`

### Steps to reproduce

```bash
1. Implement custom version of AttachmentFileUploader
2. Send message with attachment and wait till it is sent
3. Long press the message and press delete
4. message is deleted but custom methods deleteImage or deleteFile are not called
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @flodaniel,

Calling `deleteImage` or `deleteFile` sounds good at first but the same attachment can be linked to multiple messages. So a better way is to call it as per your use-case.

```dart
  Future<void> customDeleteMessage(Message message) async {
    // Delete attachments
    for (final attachment in message.attachments) {
      if (attachment.type == 'image') {
        await channel.deleteImage(attachment.imageUrl);
      } else if (attachment.type == 'file') {
        await channel.client.deleteFile(attachment.assetUrl);
      }
    }

    // Delete Message
    await channel.deleteMessage(message);
  }
```

Thanks.

**Comment by flodaniel** [comment]
Hey @xsahil03x,

this information is clearly conflicting with how it is documented (https://getstream.io/chat/docs/flutter-dart/file_uploads/?language=dart, https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat/lib/src/core/api/attachment_file_uploader.dart#L7, https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat/lib/src/core/api/attachment_file_uploader.dart#L58). 

As your internal implementation of the `AttachmentFileUploader` also implements this interface I am not understanding why they are not being called for my custom implementation. Or did you also implement code+interface which is not used at all?

**Comment by xsahil03x** [comment]
Hey @flodaniel , the thing is we actually don't really call `deleteImage` or `deleteFile` in our SDK because of the reason I mentioned above.

> Calling `deleteImage` or `deleteFile` sounds good at first but the same attachment can be linked to multiple messages. So a better way is to call it as per your use-case.

If you look at the `deleteMessage` [implementation](https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat/lib/src/client/channel.dart#L651), we never called `deleteImage` or `deleteFile`. We handle it internally in our backend.

So, if you are using your own custom CDN and your use-case suggests deleting uploaded attachments while deleting message. You can use the code snippet I suggested above.

```dart
  Future<void> customDeleteMessage(Message message) async {
    // Delete attachments
    for (final attachment in message.attachments) {
      if (attachment.type == 'image') {
        await channel.deleteImage(attachment.imageUrl);
      } else if (attachment.type == 'file') {
        await channel.deleteFile(attachment.assetUrl);
      }
    }

    // Delete Message
    await channel.deleteMessage(message);
  }
```
