### ISSUE TITLE
Remove default divider in message_list_view.dart or make it configurable

### ISSUE THREAD

**Issue by futebolbryant** [GetStream/stream-chat-flutter#764]
### Please select which package this feature is related to

stream_chat_flutter

### Is your feature request related to a problem?

I'm unable to fully customize the look and feel of our channel pages because there is a `SizedBox(height: 2)` in `message_list_view.dart` returned by default in the `seperatorBuilder`.  This extra space seems like something that should be part of the message rather than the list view, or at least configurable.

### Describe the solution that you'd like

Removing the divider or making it configurable.

### Additional context

I'm trying to build a UI that looks like slack, which requires me to have control over all aspects of each individual message shown in `MessageListView`.  Note the space below the selected `CustomMessageWidget`.

![Screenshot_20211109-142704](https://user-images.githubusercontent.com/11775151/141015691-b366fedf-8cda-459c-9896-e6083b0561a1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @futebolbryant,

I have a fix ready for this which allows you to set default spacing as well as spacing in certain conditions and should be merged soon.

Thanks for reporting this and I'll let you know when it's merged.
