### ISSUE TITLE
AttachmentActionsModal should have configurable actions

### ISSUE THREAD

**Issue by futebolbryant** [GetStream/stream-chat-flutter#766]
### Please select which package this feature is related to

stream_chat_flutter

### Is your feature request related to a problem?

We don't want to show the 'Show in Chat' or 'Reply' actions that are hardcoded into the  `AttachmentActionsModal` when the user has tapped the image from a channel page.  I don't understand the purpose of the 'show in chat' action when you have just tapped the image from the current chat channel and can simply close the gallery view.  I understand its utility in a search context, but I find the 'Show in Chat' option confusing when I tapped it from the channel.  

Additionally, when tapped from the channel page, I'm not sure of a simple solution for `onShowMessage` in order to get the 'Show in Chat' option to just close the attachment detail view.  I ended up resorting to a less than ideal hack/workaround using route names, since in this case I know they came from the channel page.
```
  onShowMessage: (message, channel) {
    Navigator.of(context).popUntil((route) =>
        route.settings?.name ==
        RouteNameBuilder.chatChannelByCid(channel.cid));
  },
```

And the `Reply` option doesn't make sense for us at all because we don't support quoted replies or threads right now, so it would be nice to be able to remove it!

### Describe the solution that you'd like

Ability to configure the actions generated by the `AttachmentActionsModal` class.

### Additional context

Sorry if I'm missing something in the documentation about how to configure this, or just generally not understanding the point of these actions in the context described above.  Loving stream and stream flutter 👍 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Adding config options for this and pushing a PR soon. 

Will let you know when it's merged. 

Thanks.
