### ISSUE TITLE
Unable to run example at all on device. StatusCode":401,

### ISSUE THREAD

**Issue by veyhong** [GetStream/stream-chat-flutter#77]
```
 ℹ️ 🔌 already connecting
flutter: (2020-09-03 11:46:19.897330) ℹ️ 🔌 received new event: {"error":{"code":43,"message":"Connect failed with error: \"JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key \"tv8e7chkfsr7\"\"","StatusCode":401,"duration":"0.00ms"}}
flutter: (2020-09-03 11:46:19.897995) ℹ️ 🔌 connection estabilished
flutter: (2020-09-03 11:46:19.898600) ℹ️ 📡 handle new event: {type: connection.changed, cid: null, connection_id: null, created_at: null, me: null, user: null, message: null, channel: null, member: null, reaction: null, total_unread_count: null, unread_channels: null, online: true, is_local: true}
```

gz#5725

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5725'>Zendesk ticket #5725</a>:<br><br>Hi

Please let us know what are you specifically looking for. Thanks.

Cheers
Seetha

**Comment by veyhong** [comment]
Hi @shodgetts thank u for replying, I am trying to run the example folder provided in this git repo. 
Let me described what I did. 

I got API Key from Stream dashboard, I replace in file bellow : **main.dart**  

```
final client = Client(
    'my-api-key',
    logLevel: Level.INFO,
    showLocalNotification: Platform.isAndroid ? showLocalNotification : null,
    persistenceEnabled: true,
  );

  await client.setUser(
    User(id: 'super-band-9'),
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoic3VwZXItYmFuZC05In0.0L6lGoeLwkz0aZRUcpZKsvaXtNEDHBcezVTZ0oPq40A',
  );
```

when I run using this command: `flutter run -d all ` it did run, but I receive this **401** error stated that` received new event: {"error":{"code":43,"message":"Connect failed with error: \"JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key \"tv8e7chkfsr7\"\"","StatusCode":401,"duration":"0.00ms"}}`


My question is where should I generate a token (how to generate this token). I do not have any back end yet.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5725'>Zendesk ticket #5725</a>:<br><br>Hi

You can generate your token using this code. This is in JS though.


    const test = async () => {
        const client = new StreamChat(
          "api_key",
          "api_secret",
          { timeout: 3000 }
        );

        const token = await client.createToken("User_id");



Cheers
Seetha

**Comment by imtoori** [comment]
Hi @veyhong 
It's not possible to create the token using the SDK, you should create it server-side (https://getstream.io/chat/docs/tokens_and_authentication/?language=dart)
For development you can also use our token generator (https://getstream.io/chat/docs/token_generator/?language=dart)

**Comment by veyhong** [comment]
Thank  @imtoori and @shodgetts , it work now.
