### ISSUE TITLE
Channel header showing incorrect number of persons online

### ISSUE THREAD

**Issue by jasnicaa** [GetStream/stream-chat-flutter#776]
Just to test I switched my custom channel header to default one and it still shows that out of 5 persons 2 are online while I am the only one online.
![Screenshot 2021-11-18 at 10 01 11](https://user-images.githubusercontent.com/25682164/142384165-103db9c6-fa1f-4ff9-b32f-af23e5c2947a.png)

no one is online as you can see

and in the header
![Screenshot 2021-11-18 at 10 01 16](https://user-images.githubusercontent.com/25682164/142384219-d64cfbb3-feb2-46ca-934f-2b343c4387dd.png)

and when tap on group info:

![Screenshot 2021-11-18 at 10 06 15](https://user-images.githubusercontent.com/25682164/142384890-684a6018-0db5-42cc-a29f-c96b068a24ca.png)

It is just a ChannelPage with appBar: ChannelHeader().

I am currently using stream_chat_flutter 3.0.0

**Comment by deven98** [comment]
Hi @jasnicaa,

Taking a look into this. 
I'll get back to you when I have more info.

Thanks for reporting this.

**Comment by jasnicaa** [comment]
thanks, @deven98 . one question also while you are here.. is there any way besides customizing the whole activeSendButton in MessageInput to change the size of it? because it is really just one small change and I need to do a ton of copy/pasting your own methods. is there a way for you guys to expose those properties just like theming ones? thanks

**Comment by deven98** [comment]
Hey @jasnicaa,

At this moment, you do need to customise the entire button but we have a draft PR reworking the `MessageInput` in progress that should help with customisation for the button.

You can find the PR here: https://github.com/GetStream/stream-chat-flutter/pull/742

This should be added into the upcoming release.

**Comment by imtoori** [comment]
I found the problem and fixed it on develop
You'll find the fix in the next release :)

**Comment by jasnicaa** [comment]
Grazie mille :)
