### ISSUE TITLE
Updated Channel not reflected at top

### ISSUE THREAD

**Issue by hiashutoshsingh** [GetStream/stream-chat-flutter#777]
### Which packages are you using?

stream_chat_flutter_core, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter_core: 3.1.1
  stream_chat_persistence: 3.0.0

### What happened?

We are using ChannelsBloc and ChannelListCore with a limit of 10. 

Suppose a condition in which there are 50 channels on the server and we are opening and watching a channel (by using channeId) that is not fetched yet through pagination and if we send a message into that channel and go back to inbox screen then updated channel is not at the top or in the that 10 fetched channels, however, if we fetch all channels through pagination and then send a message, then that channel will be shown at the top of the list.

### Steps to reproduce

```bash
1. Fetch channels as per limit(10)
2. Watch a channel that is not in the 10 fetched channels list
3. Send a message into that channel
4. Observer that channel list again
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @hiashutoshsingh, 

In case the channel is not already present in the list you need also need to pass the `shouldAddChannel` function.

```dart
ChannelsBloc(
     shouldAddChannel: (event) => true,
     child: ChannelListCore(
     			...
          	),
       );
```

if this doesn't work, make sure you are creating your channel using `client.channel()`.

Thanks,
Sahil
