### ISSUE TITLE
Channel list not updated

### ISSUE THREAD

**Issue by hiashutoshsingh** [GetStream/stream-chat-flutter#778]
### Which packages are you using?

stream_chat_flutter_core, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter_core: 3.1.1
  stream_chat_persistence: 3.0.0

### What happened?

We are using ChannelsBloc and ChannelListCore with a limit of 10. 

Suppose a condition in which there are 50 channels on the server and we fetched all by paginating the list, now if we add a channel then the total `channels` is then reinitialized to 10 as in the beginning, then again we have to paginate to get all 41 channels from the server.

### Steps to reproduce

```bash
1. Fetch channels as per limit(10)
2. Paginate all channels more that limit
3. Now observe channels list length
4. Add a new channel
5. Now again observe channels list length
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @hiashutoshsingh,

We're aware of this limitation and the upcoming package version introduces a better way to handle channel lists and should solve this issue. 

Please track this PR for progress: https://github.com/GetStream/stream-chat-flutter/pull/775

Thanks.
