### ISSUE TITLE
 Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by papirovdavid** [GetStream/stream-chat-flutter#779]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

Android

### What version are you using?

2.2.1

### What happened?

Reopening the old issue:
https://github.com/GetStream/stream-chat-flutter/issues/45

### Steps to reproduce

```bash
https://github.com/GetStream/stream-chat-flutter/issues/45
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
this should be solved in the latest version 3.x
closing this for now
