### ISSUE TITLE
Blank screen when run main.dart in example

### ISSUE THREAD

**Issue by veyhong** [GetStream/stream-chat-flutter#78]
when I run: `flutter run -t lib/single_conversation.dart -d all` everything work fine. 
but when I try to run main.dart by : ` flutter run -t lib/main.dart -d all` it show blank screen! 

<img width="1440" alt="Screenshot 2020-09-03 at 5 01 57 PM" src="https://user-images.githubusercontent.com/13130694/92101650-a0e89400-ee07-11ea-90c6-2d78a95f1570.png">

It seem like in the main.dart do not create any channel. I cannot have it test. 

gz#5734

**Comment by imtoori** [comment]
it seems like you have no channels that match your filter

**Comment by veyhong** [comment]
seem like in the main.dart, there is not code that create any channel.

**Comment by imtoori** [comment]
that's true, but intentional

have you followed the tutorial? https://getstream.io/chat/flutter/tutorial

this is the documentation on how to create channels https://getstream.io/chat/docs/initialize_channel/?language=dart

**Comment by veyhong** [comment]
I have follow the tutorial, and the sourcecode in example is the end result. So if I wanted to build something like a groupchat, many users will watch on the same channel, is that correct ? to implement it, if a user created a channel, other user just need to watch on that channel, and pass messages to that channel, and there is no need to create channel any more on other user device ? 

It would be more easy to test out, if there is a example to create different type of chat like single chat or GroupChat.

**Comment by imtoori** [comment]
I can suggest to take a look at our [documentation](https://getstream.io/chat/docs/?language=dart)
For a groupChat you need to create a channel with the users as members and then everyone will see the channel in the channellist, but you need to use proper filters

**Comment by veyhong** [comment]
What I did for now is , I run app using `single_conversation.dart` with a user. then I run `main.dart `with another different user. but still `main.dart` not showing any channel list. but it receive message from` single_conversation.dart`

**Comment by veyhong** [comment]
I found out this code in tutorial to create a channel, is there any equivalent method in flutter SDK to setup a channel ? 

```
Future<CancelListening> listenToChannel(String channelId, Listener listener) async {
  await platform.invokeMethod<String>('setupChannel', {'channelId': channelId});
  var subscription = EventChannel('io.getstream/events/$channelId').receiveBroadcastStream(nextListenerId++).listen(
    (results) {
      listener(json.decode(results));
    },
    cancelOnError: true,
  );

  return () {
    subscription.cancel();
  };
}
```

**Comment by imtoori** [comment]
yes, as I said in the documentation you can find everything

https://getstream.io/chat/docs/initialize_channel/?language=dart

this is the section for creating channels

**Comment by tbarbugli** [comment]
@imtoori for the demo application what about we show some message when the channel list does not match anything?

ie.

```
We could not find any channel for this query.

Please make sure to use this example project along with the Flutter tutorial: https://getstream.io/chat/flutter/tutorial

If your application already has users and channels, you might need to adjust your query channel as explained in the docs [...]
```

Adding the + button to create a channel will also help (though you need to show a similar message when there are no users to chat with)

**Comment by imtoori** [comment]
@tbarbugli it's a good idea and it will solve this kind of problems

**Comment by imtoori** [comment]
@veyhong in the example app you can find a simple example of channel creation
