### ISSUE TITLE
HELP: StreamChatNetworkError(code: -1, message: Connecting timed out [6000ms])

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#787]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: ^3.1.1

### What happened?

Some users are getting :**StreamChatNetworkError(code: -1, message: Connecting timed out [6000ms])**
Problem is, they have a 5G mobile network, thats bad. 

### Steps to reproduce

```bash
Code to connect


if (chatClient.wsConnectionStatus == chat.ConnectionStatus.disconnected) {
      await chatClient.disconnectUser();
      await chatClient.connectUser(
        chat.User(
          id: uid,
          extraData: {
            'image': user.imageUrl ?? defaultImage,
            'name': user.userName,
          },
        ),
        response.body,
      );
      }


Code that crash

```dart
final chan = entry.client.channel(
    'livestream',
    id: entry.postId,
  );
  if (chan.state == null) {
    await chan.watch();
  }
  return chan;
```
```


### Supporting info to reproduce

_No response_

### Relevant log output

_No response_

### Flutter analyze output

_No response_

### Flutter doctor output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abacaxi-Nelson** [comment]
Happy to get some feedback about my code..

**Comment by Michaelbenchetrit91** [comment]
I do experience the same issue on my Android under very good network connections. 
Very often, the app displays "Searching for network"

**Comment by imtoori** [comment]
hey @Abacaxi-Nelson thanks for reporting the issue
That's a network error, usually, that's unrelated to our SDK
I'll run some tests, but I've never experienced that under good connectivity

**Comment by imtoori** [comment]
@Michaelbenchetrit91 do you have more info on that case? Do you do something specific like put the app in background or something like that?

**Comment by Michaelbenchetrit91** [comment]
@imtoori Thanks for the prompt reply. Yes, it usually occurs where I close the app and reopen it after a few minutes. For example I just opened the app right now, and see an "Offline... Try again" message on the header.

**Comment by imtoori** [comment]
that's very useful. it should reconnect automatically, let me test it

**Comment by imtoori** [comment]
hi @Michaelbenchetrit91 it's not happening for me on develop using our sample app
Can you give me more information about the issue if you have any?

**Comment by Abacaxi-Nelson** [comment]
Hey @imtoori 
Just information im having now..

I have a lot of:

flutter: 2021-12-08 08:48:28.514270 🚨 🕸️
flutter: 2021-12-08 08:48:28.514562 🚨 🕸️ ╔╣ DioError ║ DioErrorType.connectTimeout
flutter: 2021-12-08 08:48:28.514694 🚨 🕸️ ║  Connecting timed out [6000ms]
flutter: 2021-12-08 08:48:28.515089 🚨 🕸️ ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
flutter: 2021-12-08 08:48:28.515738 🚨 🕸️
flutter: 2021-12-08 08:48:28.515944 🚨 🕸️ ╔╣ Request ║ POST
flutter: 2021-12-08 08:48:28.516055 🚨 🕸️ ║  https://chat-us-east-1.stream-io-api.com/channels/livestream/d3a3d6a4-718b-4abe-b43c-98faecee8a6b/query?api_key=XXX&user_id=qby7mTX1DFgPOOiGbOUTjG9ubq83&connection_id=61a65b09-0a05-2fd7-0000-0000010674b9
flutter: 2021-12-08 08:48:28.516184 🚨 🕸️ ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

What is weird: im also using feed without any connection problem.
I have the feeling that the chat endpoint is less available...

The code triggering this is:
```dart
final channelFutureProvider =
    FutureProvider.autoDispose.family<Channel, EntryChannelFutureProvider>((ref, entry) async {
  final chan = entry.client.channel(
    'livestream',
    id: entry.postId,
  );
  if (chan.state == null) {
    await chan.watch(); // HERE
  }
  return chan;
});
```
Im in a strong WIFI connection, and again feed is working perfectly

**Comment by Abacaxi-Nelson** [comment]
ooo i see some outage:

https://status.getstream.io/

**Comment by Michaelbenchetrit91** [comment]
> hi @Michaelbenchetrit91 it's not happening for me on develop using our sample app Can you give me more information about the issue if you have any?

Sorry for the late reply. I keep seeing the "Searching for network" when closing and opening the app (on Android). We use the stream_chat_flutter package version 3.2.0

**Comment by Aanu1995** [comment]
I am experiencing the same issue. Even under a string internet connection or WIFI, I am still getting the same error!
