### ISSUE TITLE
Push notifications are working on android but not with Ios

### ISSUE THREAD

**Issue by kalptech2021** [GetStream/stream-chat-flutter#788]
Push notifications are working fine on android, but I am not receiving them on the Ios. My setup with firebase is correct, as I can receive the notifications from cloud functions on Ios, just not receiving them from stream_flutter. 
Things I have done,
Apn's settings are enabled -  On stream dashboard
Firebase settings are enabled - On stream dashboard (My android notifications are working)
I am using a real device.
Is there any additional configuration required from the stream dashboard? for Ios?

**Comment by Michaelbenchetrit91** [comment]
There is another problem with notifications. 
When a user clicks on a notification, it is redirecting to the home page (channel list) instead of redirecting to the specific conversation (chat) page pertaining to this notification. 

Any fixes scheduled for that?

**Comment by imtoori** [comment]
Hi @kalptech2021 
push notifications are not implemented in the package, but it's something you should set up
please take a look at the [documentation](https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications/) and at the [possible issues](https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications/#possible-issues)/[testing the setup](https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications/#testing-if-push-notifications-are-setup-correctly)

**Comment by imtoori** [comment]
Hi @Michaelbenchetrit91 
this is something you should implement
we're planning on writing a guide for this, but it's low-priority since it's something unrelated to our SDK and it strictly depends on your app architecture

**Comment by kalptech2021** [comment]
> There is another problem with notifications. When a user clicks on a notification, it is redirecting to the home page (channel list) instead of redirecting to the specific conversation (chat) page pertaining to this notification.
> 
> Any fixes scheduled for that?

This is not an issue, It is the default behaviour, you need to provide routes.

**Comment by kalptech2021** [comment]
> Hi @Michaelbenchetrit91 this is something you should implement we're planning on writing a guide for this, but it's low-priority since it's something unrelated to our SDK and it strictly depends on your app architecture

Hi, Notifications are sent by firebase, but stream sends the request to firebase or APN. That is why we need to set up firebase and APN from the stream dashboard. My firebase setup is correct and that is why I am receiving notifications for the new message on android. But in case of Ios it is not working, I am just wondering as payload goes from the stream to firebase or APN, do we need to do any additional steps apart from, uploading the p8 certificate on the stream dashboard for ios?

**Comment by kalptech2021** [comment]
It is working, and here is the reason,
To handle the background notifications, we do not need to use flutter_local_notifications plugin, In this case specifically. Firebase messaging is handling the background notifications for android, but for Ios, we need to use the plugin.
Overall, I love this package, it would be a nightmare to make a chat app like this from scratch. Thanks a lot stream team :-)

**Comment by ibhanu** [comment]
Hey Stream Team, Happy New Year,

I have a similar problem but the ios in the dashboard show status code 400 and the error message is BadDevice token and I don't know what is bad in that. I have logged the token and everything seems fine. The token matches as well

It would mean the world to me if I get some help

![image](https://user-images.githubusercontent.com/48940632/147906445-ef43221b-6821-4510-aaf9-590130f7be41.png)
