### ISSUE TITLE
onBackgroundEventReceived is not being called right after going into background

### ISSUE THREAD

**Issue by jasnicaa** [GetStream/stream-chat-flutter#789]
Hi, as the title says this is what is happening. Right after I pick another app and enter it I am leaving chat and sending myself messages from another account and I can see in the console log that I am receiving messages which should trigger notifications but it is not happening and the method is not being called. 

![Screenshot 2021-11-25 at 11 52 46](https://user-images.githubusercontent.com/25682164/143429352-0fd9f224-7005-451e-a7e2-486e10705f95.png)

Any idea? thanks

**Comment by imtoori** [comment]
hey @jasnicaa I just tested this using the sample app and it's working just fine, my onBackgroundEventReceived gets called regularly
How are you using it?
