### ISSUE TITLE
Force close on iOS

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#8]
I got an error like this after i add dependency `stream_chat_flutter: ^0.1.11`
when i try to run it on iOS, my app suddenly got force close

`*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c70ff8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff256e9b51 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   Flutter                             0x000000010249ae32 -[FlutterEngine registrarForPlugin:] + 282
	5   Runner                              0x000000010173bdd0 +[GeneratedPluginRegistrant registerWithRegistry:] + 1040
	6   Runner                              0x000000010173c2e0 $s6Runner11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 176
	7   Runner    <…>`

**Comment by imtoori** [comment]
Hi, I tried to build a project from scratch using iOS and (un)fortunately I don't have any problem.
Can you try to run `flutter clean` and try to rebuild the project?

**Comment by tbarbugli** [comment]
@brizaldi can you also include the entire stack trace error as well as information about the flutter version you are using?

**Comment by brizaldi** [comment]
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/41714881/77377088-b8294d00-6da4-11ea-8857-7940c775f8c6.png">

**Comment by imtoori** [comment]
@brizaldi did you do everything written here in the readme? https://github.com/GetStream/stream-chat-flutter#ios

**Comment by brizaldi** [comment]
@imtoori yeah, but still got crash whenever i try to open the app, btw i test it on iOS Simulator though

**Comment by imtoori** [comment]
So, I googled your stacktrace and I reach [this issue on the Flutter repository](https://github.com/flutter/flutter/issues/44668), but unfortunately it's still `waiting for customer response`

A question: have you modified the iOS project in any way?

**Comment by brizaldi** [comment]
i only change deployment target to 9.0 and add google gms api key in AppDelegate.swift

this is from simulator system.log
`Mar 27 10:02:52 rhezas-mbp-2 nanotimekitcompaniond[6524]: objc[6524]: Class NTKDActivityTracker is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion (0x7fff88ed28f0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/nanotimekitcompaniond (0x109975b18). One of the two will be used. Which one is undefined.
Mar 27 10:02:52 rhezas-mbp-2 nanotimekitcompaniond[6524]: objc[6524]: Class NTKDZIPArchivist is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion (0x7fff88ed3f70) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/nanotimekitcompaniond (0x109975e38). One of the two will be used. Which one is undefined.
Mar 27 10:02:52 rhezas-mbp-2 Runner[6527]: objc[6527]: Class FLTKeyboardVisibilityPlugin is implemented in both /Users/berkatbejana/Library/Developer/CoreSimulator/Devices/7DF0C3FB-7CFA-4AF0-A975-4C02084F3B33/data/Containers/Bundle/Application/C325B17B-08FF-4A02-8EFD-7F3BF5957DE8/Runner.app/Frameworks/keyboard_visibility.framework/keyboard_visibility (0x10f83bf48) and /Users/berkatbejana/Library/Developer/CoreSimulator/Devices/7DF0C3FB-7CFA-4AF0-A975-4C02084F3B33/data/Containers/Bundle/Application/C325B17B-08FF-4A02-8EFD-7F3BF5957DE8/Runner.app/Frameworks/flutter_keyboard_visibility.framework/flutter_keyboard_visibility (0x10f779f48). One of the two will be used. Which one is undefined.
Mar 27 10:02:52 rhezas-mbp-2 Runner[6527]: assertion failed: 19D76 17C45: libxpc.dylib + 83135 [F4467130-D9DA-3791-A4D0-F41C91F1CFEA]: 0x7d
Mar 27 10:02:52 rhezas-mbp-2 com.apple.CoreSimulator.SimDevice.7DF0C3FB-7CFA-4AF0-A975-4C02084F3B33[4768] (UIKitApplication:id.homy.homyMobile[702c][rb-legacy][6527]): Service exited due to SIGABRT`

i dont know if this gonna help but i got an error in GeneratedPluginRegistrant.m saying `Module 'file_picker' not found`
<img width="742" alt="Screen Shot 2020-03-27 at 10 11 04 AM" src="https://user-images.githubusercontent.com/41714881/77717889-17d95f80-7014-11ea-9992-152805284d49.png">

here's my GeneratedPluginRegistrant.m
[GeneratedPluginRegistrant.m.zip](https://github.com/GetStream/stream-chat-flutter/files/4391272/GeneratedPluginRegistrant.m.zip)

**Comment by imtoori** [comment]
I think something broke during `flutter packages get`. Sometimes it happens with Flutter

Can you try this?
- delete the file ios/Podfile 
- run `flutter clean`
- retry to run the app

**Comment by brizaldi** [comment]
still got the same error

**Comment by brizaldi** [comment]
@imtoori @tbarbugli  i think i've found the culprit, its because this plugin is incompatible with [flutter_form_builder](https://pub.dev/packages/flutter_form_builder), when i remove `flutter_form_builder` from dependency, the error suddenly gone, maybe you guys can find out whats the problem, because my app depends a lot from that plugin

**Comment by tbarbugli** [comment]
@brizaldi thank you for the additional information; if possible would you mind sharing a dart file that reproduce the problem with the form builder and chat?

**Comment by brizaldi** [comment]
just create a new flutter project, and then add `flutter_form_builder` and `stream_chat_flutter` dependency

**Comment by imtoori** [comment]
@brizaldi can you retry now using the new version 0.1.12?

We were using the plugin `keyboard_visibility` while `flutter_form_builder` was using `flutter_keyboard_visibility`. The former is a fork of the latter and it seems better maintained so we'll stick to that.

**Comment by brizaldi** [comment]
it seems working fine now, thanks @imtoori, i'm closing this now
