### ISSUE TITLE
Cannot view the list of people reacting to a message in FLutter. Had it in Native and React SDK

### ISSUE THREAD

**Issue by Aftab-Werq** [GetStream/stream-chat-flutter#80]
We've used Native and React SDK's in the past for Chat and it had the option to view the name of the people who've reacted to the message. Unable to see any option here in Flutter.

gz#5991

**Comment by imtoori** [comment]
Thanks for reporting this issue
I added it to our backlog

**Comment by cemozerr** [comment]
How soon do you expect to implement this feature? It's pretty critical for my needs.

**Comment by imtoori** [comment]
Hi @cemozerr we are working on it right now
