### ISSUE TITLE
Chewie dependency (Provider dependency) needs updated

### ISSUE THREAD

**Issue by FCView** [GetStream/stream-chat-flutter#805]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter 3.3.0

### What happened?

Compatibility issue with other packages and stream_chat_flutter with following message when running "flutter pub get":

> Because stream_chat_flutter >=2.0.0-nullsafety.5 depends on chewie ^1.2.0 which depends on provider ^5.0.0, stream_chat_flutter >=2.0.0-nullsafety.5 requires provider ^5.0.0.
> So, because fcView depends on both provider ^6.0.0 and stream_chat_flutter ^3.3.0, version solving failed.
> pub get failed (1; So, because fcView depends on both provider ^6.0.0 and stream_chat_flutter ^3.3.0, version solving failed.)

It appears that this dependency was updated in chewie about a month ago ([see pull request here](https://github.com/brianegan/chewie/pull/548)), but they haven't issued a new pub.dev release.

I am able to roll back provider in my own dependencies, but if I do, then I am unable to update stream_chat_flutter beyond 3.1.0 due to other conflicts that require this provider dependency to be resolved in stream_chat_flutter/chewie.

So, I am submitting this issue in case chewie is no longer issuing pub.dev releases.

### Steps to reproduce

```bash
while using stream_chat_flutter >=2.0.0-nullsafety.5, add following dependency to pubspec.yaml:

provider: ^6.0.0

run "flutter pub get"
```

### Flutter doctor output

```shell
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
    • Flutter version 2.5.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (9 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:/Users/ksuav/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:/Users/ksuav/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
Process finished with exit code 0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasnicaa** [comment]
yeah I also got this and as a _temporary_ solution I override in dependecy_overrides provider: 6.0.1

**Comment by deven98** [comment]
I'm taking a look into this. 
Will get back to you with more info.

Thanks.

**Comment by imtoori** [comment]
> yeah I also got this and as a _temporary_ solution I override in dependecy_overrides provider: 6.0.1

I think this a possible solution at the moment
There isn't much more we can do as of now

**Comment by imtoori** [comment]
if you're interested in this, you can follow this issue https://github.com/brianegan/chewie/issues/580

**Comment by AndreHaueisen** [comment]
On Github, chewie is using provider 6.0.1 already.
One suggestion is for you guys to change the dependency to
```
  chewie:
    git:
      url: https://github.com/brianegan/chewie
```

**Comment by imtoori** [comment]
It's not possible to use a git dependency when publishing a package, so we have to wait for them to publish a new release :/

**Comment by AndreHaueisen** [comment]
😢
