### ISSUE TITLE
Error Symbol not found: _OBJC_CLASS_$_Reachability when build ios - Request update connectivity_plus

### ISSUE THREAD

**Issue by davidwijayanto2** [GetStream/stream-chat-flutter#806]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter_core - 3.3.0

### What happened?

Hi, i try to update stream chat version in our app using latest stable version (3.3.0). When i try to run in iOS device (iPhone 6s), it stuck at splash screen and i got this error message Symbol not found: _OBJC_CLASS_$_Reachability. When i search deeper, i found that this issue is related with connectivity_plus 2.0.2 https://github.com/fluttercommunity/plus_plugins/issues/563. But its look like connectivity_plus already fix this issue with version 2.1.0 https://github.com/flutter/plugins/pull/2281. Can you update your dependencies to connectivity_plus to 2.1.0? 
Thanks for your help.
regards

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @davidwijayanto2,

I can see the issue in the connectivity_plus plugin and I'll test it out a bit and get back to you with more info.

Thanks.

**Comment by CalHoll** [comment]
Also hitting this issue, can't build on ios

**Comment by brbatwork** [comment]
Is there a timeline on when this will be in a release?  Is there a workaround I can write so I can get iOS publishing in the meantime?

**Comment by quanguyenka** [comment]
![image](https://github.com/GetStream/stream-chat-flutter/assets/22728405/5f6c7c61-fcf7-4d0a-b40d-845765f4c024)

I got this error when my colleague added this library, I solved it by removing it.

**Comment by rahul-mobilecoderz** [comment]
check if there is connectivity package you have used or not. Replaced with connectivity_plus plugin  and upgrade your flutter_blue_plus plugin to latest version .
