### ISSUE TITLE
Dependency version mismatch

### ISSUE THREAD

**Issue by duzenko** [GetStream/stream-chat-flutter#807]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

3.3.0

### What happened?

stream-chat-flutter 3.3.0 relies on stream_chat_flutter_core: ^3.2.0

I think it's the reason why I get this build errors after updating from 3.2.0

```
/C:/dev/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-3.3.0/lib/src/stream_chat.dart:117:47: Error: Getter not found: 'defaultUserAgent'.
                          '${StreamChatClient.defaultUserAgent}-ui',
                                              ^^^^^^^^^^^^^^^^
/C:/dev/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-3.3.0/lib/src/stream_chat.dart:115:38: Error: Setter not found: 'additionalHeaders'.
                    StreamChatClient.additionalHeaders = {
                                     ^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.
```

### Steps to reproduce

```bash
Update app dependencies - stream-chat-flutter from  ^3.2.0 to  ^3.3.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
a big facepalm 🤦🏼‍♂️ 
Thanks for reporting this

I just published v3.3.1
