### ISSUE TITLE
swipeActions won't work on android nor web (only on ios)

### ISSUE THREAD

**Issue by tahaJemmali** [GetStream/stream-chat-flutter#811]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android, Web

### What version are you using?

3.2.0

### What happened?

swipeActions works only on ios. 

### Steps to reproduce

```bash
1. Go to 'ChannelListView' on android device or web device
2. set swipeToAction: true,
2. Scroll horizontal one of the channels
=> nothing appears

PS: this features work only on ios
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @tahaJemmali, 

Just checking this out, I'll get back to you with more information. 

Thanks.

**Comment by deven98** [comment]
Hi @tahaJemmali, 

I tried the [example app](https://github.com/GetStream/stream-chat-flutter/blob/3.2.0/packages/stream_chat_flutter/example/lib/tutorial_part_6.dart) with the `swipeToAction` set to true and the swipe on channel (right to left) shows the actions:

<img width="549" alt="Screenshot 2021-12-06 at 5 40 41 PM" src="https://user-images.githubusercontent.com/26357843/144843794-3efaaecd-2bff-4ea4-a51e-7019aa5f8b53.png">

Do you think there might be something else in your app that might change this function or something I might need to know for testing?
