### ISSUE TITLE
The chat screen becomes gray during a few seconds when sending a voice message

### ISSUE THREAD

**Issue by Michaelbenchetrit91** [GetStream/stream-chat-flutter#814]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

3.2.0

### What happened?

When sending a voice message, the conversation (chat) screen becomes entirely gray during a few seconds until the message is being sent. We encountered this UX bug on 2 different Android models. 

![VOICE MESSAGE](https://user-images.githubusercontent.com/93865456/145215391-2ce12d28-8d36-4973-93af-075606c73f92.png)

### Steps to reproduce

```bash
1. Go to "Chat screen"
2. Click on 'microphone" icon
3. Speak a few seconds and click on the "Stop" (red) icon
4. Problem: the conversation screens becomes gray a few seconds until the message is sent.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @Michaelbenchetrit91, 

The grey screen (I'm assuming in release mode on your test devices) is an indication of some kind of error which isn't caught during development but Flutter chooses not to show them in release mode to not alarm the user. 

Does this not happen at all in development on an Android emulator? If possible, the debug error is better for us to understand what is going wrong here. 

Also, are you using your own audio implementation or using the official flutter guide [here](https://getstream.io/blog/instantly-send-audio-messages-with-stream-chat-and-flutter/)? 

Thanks.
