### ISSUE TITLE
New Stream Chat Edge Infrastructure

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#816]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

During outage in the morning, i get server i am connected to :  https://chat-us-east-1.stream-io-api.com/XXXXX
I read this [(article)](https://getstream.io/blog/chat-edge-infrastructure/) that announce new edge server.

We have users in europe, america and mexico.
Our server app is us-east, but it will be awesome to let users connect to close servers.

**How to do it**
doc say : You can easily switch to our new edge infrastructure today by changing the base URL of your API endpoint or SDK. The new url is https://chat.stream-io-api.com.

Location ENUM show only 5 regions, not edges..
@Deprecated('Use location to change baseUrl instead') String? baseURL,

### Describe the solution that you'd like

Is there flutter sdk ready for this ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @Abacaxi-Nelson , yes I tried after the new edge infrastructure we don't need to region-based base URLs  anymore.
Can you use the `baseUrl` property for now and we will soon remove the deprecation from it and deprecate `Location` instead.

Thanks,
Sahil

**Comment by Abacaxi-Nelson** [comment]
hey @xsahil03x 

```dart
final chatClient = stream_chat.StreamChatClient('XXXX',
    logLevel: stream_chat.Level.SEVERE,
    baseURL: 'https://chat.stream-io-api.com');
```

You confirm ?
Seems to work

**Comment by xsahil03x** [comment]
@Abacaxi-Nelson , yes this should work
