### ISSUE TITLE
The audio playback takes time to load (voice messages)

### ISSUE THREAD

**Issue by Michaelbenchetrit91** [GetStream/stream-chat-flutter#817]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

3.2.0

### What happened?

The audio player takes a few seconds to load voice messages 

![image](https://user-images.githubusercontent.com/93865456/145217641-3302bf2c-37b9-4c57-8b5f-369880ae0221.png)

### Steps to reproduce

```bash
1. Go to 'Chat screen" of "Aviel"
2. Send a few (short) audio messages 
3. Close the app
4. Enter the app and go back to the "Chat screen" of Aviel
5. The audio messages are not instantly available for playback. Instead, it takes a few seconds until it fully loads (from 2s to 10s).

This issue happens even on very short audio messages.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @Michaelbenchetrit91 , I don't think we provide an out-of-the-box `attachment` for the `audio` type. The delay can be due to various issues and the way how you implemented them.

Thanks,
Sahil

**Comment by Michaelbenchetrit91** [comment]
Hi @xsahil03x, we followed carefully step-by-step the official tutorial wrote by get-stream: https://getstream.io/blog/instantly-send-audio-messages-with-stream-chat-and-flutter/

Nonetheless, every time we enter inside a chat conversation, the audio type messages are not immediately available for playback, instead, there is a small delay (few seconds) where the audio messages are being loaded. It seems like the audio messages are constantly being pulled out from the server instead of being cached on the user's mobile device

**Comment by HayesGordon** [comment]
Hi @Michaelbenchetrit91,

Which version of just_audio are you using. Seems like they resolved a problem with their caching in version `0.9.17`:
https://github.com/ryanheise/just_audio/issues/47#issuecomment-964129347

Otherwise there may be something else going on and may require improvements to the tutorial.

**Comment by Michaelbenchetrit91** [comment]
Thanks for your feedback @HayesGordon. We'll test it and update you accordingly

**Comment by papirovdavid** [comment]
We are using the latest just_audio: ^0.9.18 version

**Comment by Michaelbenchetrit91** [comment]
Hi @HayesGordon,

As @papirovdavid said, we're using the latest just_audio: ^0.9.18 version. 
We'd really appreciate if you can have a look into the issue since the loading time can be very significant under certain scenarios.

**Comment by HayesGordon** [comment]
Hey @Michaelbenchetrit91, this may be a problem with signed urls. The URLs may be changing between different sessions, meaning that the just_audio package cannot cache the file as the URL is different. It may require a custom approach to caching these voice messages yourself, and providing a local file path to just_audio.

This is just a theory though. I will investigate this a bit more. Are you using Stream's CDN, or which CDN are you using?
