### ISSUE TITLE
Pin chats on top of the channel screen

### ISSUE THREAD

**Issue by Michaelbenchetrit91** [GetStream/stream-chat-flutter#818]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

No

### Describe the solution that you'd like

Provide users with the ability to pin a chat on top of all other chats regardless of the messages received on other non-pinned chats.

Users will have to right swipe on the chat they want to pin and then select "Pin"

![image](https://user-images.githubusercontent.com/93865456/145220831-875db853-97f0-4111-bb3f-1b0665dfa56b.png)

### Additional context

This is a very important features as many users handle dozens of chat and want to pin (mark) their favorite important chats on top of the screen to save time. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @Michaelbenchetrit91,

This is possible by implementing a few things: 

1) In the `channelData` for a `StreamChannel`, you could add a boolean value named 'pinned'.  
2) You can add a pin action using the `swipeActions` parameter in the `ChannelListView` to add a pin button (ignore if you're not using the `stream_chat_flutter` package). 
3) When the appbar pin button is pressed, you can now fetch channels with a filter such as: 
`Filter.equals('pinned', true)`.

Let me know if this makes sense.

**Comment by ROCKSTARfromday1** [comment]
it doesnt

**Comment by imtoori** [comment]
@ROCKSTARfromday1 can you tell us what's the issue? 
Also, please make sure to follow our code of conduct when commenting on issues https://github.com/GetStream/stream-chat-flutter/blob/develop/CODE_OF_CONDUCT.md

**Comment by imtoori** [comment]
Closing this issue, let me know if you need more help with this

**Comment by Michaelbenchetrit91** [comment]
Thanks @deven98 for your reply. Could we use the same logic to archive/unarchive a chat or a group?

**Comment by Michaelbenchetrit91** [comment]
Hi @imtoori , would appreciate your help on this

> Thanks @deven98 for your reply. Could we use the same logic to archive/unarchive a chat or a group?

**Comment by Srj-Love** [comment]
Hey there,
Can we have a flittered list with pinned channel  + last_message_at wise in channeList in a single. 
my approch is currently like below

```
late final _peopleStreamControllers = StreamChannelListController(
    client: Get.find<ChatService>().client,
    filter: Filter.and([
      Filter.in_('members', [StreamChat.of(context).currentUser!.id]),
      Filter.in_('type',['messaging']),
      Filter.lessOrEqual('member_count', 2),
    ]),
    presence: true,
    limit: 50,
    channelStateSort: [
      
      // check with pinned wise
      const SortOption('pinned',direction: SortOption.ASC)     ,
      const SortOption('last_message_at')
    ]
    ,
  );
```

My expectation is if I pinned a channel it should be stricked and other coming messages can be below that.

**Comment by Srj-Love** [comment]
Hey @imtoori , any update on this?

**Comment by deven98** [comment]
@Srj-Love can you open a new issue for this? It is difficult for us to track comments on closed issues.
