### ISSUE TITLE
The app becomes extremely slow when sending a video file

### ISSUE THREAD

**Issue by Michaelbenchetrit91** [GetStream/stream-chat-flutter#819]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

3.2.0

### What happened?

When sending a video file (30/40sec) to someone, the app becomes incredibly slow (the phone's screen is even frozen from time to time), preventing users from doing parallel actions such as sending text messages or scrolling up the chat screen.

### Steps to reproduce

```bash
1. Go to 'Chat screen"
2. Send a video file of 30-40sec
3. While the video is being sent, try to do additional actions such as scrolling up or sending text messages.
4. Problem: the app becomes extremely slow during the "sending process", making the usage of the app very poor.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @Michaelbenchetrit91,

I'll test this out and come back to you with more information. 

Thanks.

**Comment by Michaelbenchetrit91** [comment]
Hi @deven98 

Did you get a chance to review this?

I did additional tests with different video sizes and confirm that the "lag/slow mode" is felt in a very significant manner during the video upload (I use a modern Android phone / Galaxy A20).

Sending videos is a core feature of our chat app use case, unfortunately the current experience makes the app usage very challenging.

**Comment by xsahil03x** [comment]
Hey @Michaelbenchetrit91,

@deven98 is currently a bit sick, so I'm gonna take a look at this issue and will be back soon with updates.

Thanks.

**Comment by Michaelbenchetrit91** [comment]
Many thanks @xsahil03x!
Swift recovery @deven98

**Comment by Michaelbenchetrit91** [comment]
Hi @xsahil03x 
Updating you that the issue occurs not only with video files, but also when sending images (under certain unknown scenarios)
Today I tried to send 3 images via the app. For some unknown reasons, none of them have been uploaded. 

After failures to send pictures, the whole app became incredibly slow. Every page navigation takes time. Scrolling up/down on the screen is very laggy. As if something were "stuck" in the background, taking a lot of memory/CPU. 

![image](https://user-images.githubusercontent.com/93865456/147414569-c5b1d05e-708b-421a-ad83-6e280cc3c22a.png)

**Comment by deven98** [comment]
Hi @Michaelbenchetrit91,

Apologies for the delay, I'm back and better now. 
Is there any associated error with the aforementioned picture uploads you could give us?

Also, the video slowdown unfortunately I can't seem to reproduce on an emulator (let me know if it also happens on an emulator for you) so I am going to try to run it on a physical device and test it out today.

Thanks.

**Comment by Michaelbenchetrit91** [comment]
@deven98 Happy that you feel better!

I don't use an emulator to test the app (I work as a Product Manager). The issue is felt very significantly on my (physical) Android device.

Again: as soon as I send a video OR send pictures that failed to be delivered, the app becomes incredibly slow, making its use almost impossible. This is quite critical for us..

**Comment by deven98** [comment]
Hi @Michaelbenchetrit91,

We're working on this and moving some computation when sending videos to separate isolates to make sending videos a smoother experience overall in the upcoming sprint. I will give you an update when we have a PR ready to use. 

Thanks.

**Comment by imtoori** [comment]
This has been solved in the latest release
Let me know if you're still experiencing it
