### ISSUE TITLE
Strange behavior in rich text

### ISSUE THREAD

**Issue by EtcGonza** [GetStream/stream-chat-flutter#825]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Windows

### What version are you using?

stream_chat_flutter: ^3.1.1
stream_chat_localizations: ^2.0.0

### What happened?

Hello! I have strange behavior when I send a message between these characters. '' For example, "Hi, how are you?"

This message will have a white background color. if I send a message with one line, it works great, but with multiple lines it doesn't.

For example, if I send this message:

![image](https://user-images.githubusercontent.com/44512291/145866781-b0ebf628-6b53-49ac-866d-42c7a402db49.png)

I see it in this way...

![image](https://user-images.githubusercontent.com/44512291/145865174-dde23e6a-763a-4f60-a370-ec59e138b348.png)

The last two lines are ignored. Also, I saw that if you put four spaces before your message, you will get the rich text with the background color. In the same way if you put the `` character between your message.

What I need is if I send this message:

![image](https://user-images.githubusercontent.com/44512291/145867330-9c27860d-c05b-4ba2-969d-1bb733c97204.png)

Should be see it like this

![image](https://user-images.githubusercontent.com/44512291/145867195-96f492b6-d77a-4373-8dbc-cdfb95d0cc1f.png)

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi we're using the [flutter_markdown](https://pub.dev/packages/flutter_markdown) for rendering rich text
I think you should use three backticks (`) for showing that kind of message
I think that behaviour is expected
What do you think?

**Comment by EtcGonza** [comment]
> Hi we're using the [flutter_markdown](https://pub.dev/packages/flutter_markdown) for rendering rich text I think you should use three backticks (`) for showing that kind of message I think that behaviour is expected What do you think?

Yeah, you are right. That's the behavier that I want. Thanks for the answer!
