### ISSUE TITLE
[Feature] Combine ChannelListView

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#826]
### Please select which package this feature is related to

stream_chat, stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Im trying to show list of channel user belongs to.
On top, 3 livestream channel (show a button to load other)
And after in list, all other type of channels.

My first try: Combine two ChannelListView in a column
But these two ChannelListView seems to share same key or session, cause they display same channel event if i change filters..

Do you know a simple way to do it ?
i wanted to keep your components, cause they are awesome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
mmm have you tried using two different `ChannelsBloc` too?

**Comment by Abacaxi-Nelson** [comment]
It seems to work, but refreshing show remove my limit param..
i think i need to go custom if i want this behaviour :)
