### ISSUE TITLE
Video should start automatically after clicking on the thumbnail

### ISSUE THREAD

**Issue by Michaelbenchetrit91** [GetStream/stream-chat-flutter#828]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Currently users have to click twice on the video before starting the playback:
1- First from the chat screen (when they click on the video thumbnail)
2- Secondly when the video is opened

The  second click is irrelevant and may create user frustration. 

### Describe the solution that you'd like

When clicking on the video thumbnail, the video should start automatically.

![image](https://user-images.githubusercontent.com/93865456/145985338-a613a814-707f-4787-8769-d61990783e84.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @Michaelbenchetrit91, 

I'm looking into adding some sort of autoplay option for videos.
I'll let you know when I have more info.

Thanks.

**Comment by deven98** [comment]
Hey @Michaelbenchetrit91, 

I've opened a PR for autoplaying the video when thumbnail is clicked. 
Should be merged soon.

**Comment by deven98** [comment]
Hey @Michaelbenchetrit91, we're in the process of merging this PR.

To auto-play videos, you need to edit the default behaviour on attachment tap like this: 

```
            MessageListView(
              messageBuilder: (context, details, messages, defaultWidget) {
                return defaultWidget.copyWith(
                  onAttachmentTap: (message, attachment) {
                    Navigator.push(context, MaterialPageRoute(builder: (_) {
                      return StreamChannel(
                        channel: StreamChannel.of(context).channel,
                        child: FullScreenMedia(
                          mediaAttachments:  [attachment],
                          message: message,
                          autoplayVideos: true,
                          // Other FullScreenMedia params
                        ),
                      );
                    }));
                  },
                );
              },
              // Other MessageListView params 
            ),
```

**Comment by Michaelbenchetrit91** [comment]
Thank you very much for the fix!
