### ISSUE TITLE
ChannelListView does not respect sort after entering/exiting channel

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#834]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

3.3.1

### What happened?

I want to keep 4 public channels in the same order when using ChannelListView

First I tried to create my own parameter on the channel, it seems to work when loading the channels, but not if I go into a channel, send a message, and then exit.

 stream.SortOption( 'listPriority', direction: stream.SortOption.ASC, ),
 
 I have also tried "created_at", but this also doesn't keep it in the same order. It seems like after the order is originally created, once you send a message in a channel it just defaults back to "last_message_at", and places the channel you interacted with at the top of the list.

### Steps to reproduce

```bash
1. Create a ChannelListView with a sort of "created_at", with 4-5 different channels
2. Click on a channel lower down the list, send a message, then exit the channel
3. At this point the channel list should be in a different order, with the most recently active channel at the top - NOT in the "created_at" sort order.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi!
You could use the property `ChannelsBloc.channelsComparator` to sort the channels when a new message arrives
There will be a better way of doing it in the upcoming v4 release, but this should solve your issue

**Comment by CalHoll** [comment]
Aha! This is what I was looking for, thanks Salvatore!

**Comment by 3ph** [comment]
Hi, I'm using v5 and this issue still exists but `ChannelsBloc` seem to have been removed. Any fix for this yet?
