### ISSUE TITLE
In MessageListView  userAvatar is cropped

### ISSUE THREAD

**Issue by jasnicaa** [GetStream/stream-chat-flutter#836]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

3.3.1

### What happened?

If I put a conditional in showUserAvatar it crops images in chat.

when showUserAvatar is included:
![Screenshot_20211222-114636](https://user-images.githubusercontent.com/25682164/147080937-2aecdecb-a884-437d-9313-c6556ce12e45.jpg)

when I comment out showUserAvatar:
![Screenshot_20211222-114653](https://user-images.githubusercontent.com/25682164/147080969-d2586eb4-0cd3-47c6-b2f1-781ff7ccfe71.jpg)

### Steps to reproduce

In MessageListView I have a field called 

`isPrivateChat = channel.type == 'private-messaging',`

and if it is true than 

`return showUserAvatar: isPrivateChat ? DisplayWidget.hide : DisplayWidget.show`

When this present the images are cropped and when commented out it is fine.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @jasnicaa,

We generally recommend showing the user avatar only on the last message of the user if they are sent continuously, something like this: 

```
final showUserAvatar = isMyMessage
        ? DisplayWidget.gone
        : (timeDiff >= 1 || !isNextUserSame)
            ? DisplayWidget.show
            : DisplayWidget.hide;
```

Regardless, the error you are getting should not be showing up. Trying this in the example app, I can't seem to replicate this error: 

<img width="263" alt="Screenshot 2021-12-27 at 1 12 14 PM" src="https://user-images.githubusercontent.com/26357843/147447855-9208c137-0608-4168-9cf6-e9bdfaa9a544.png">

Could you give me some insight into your implementation or a snippet which causes the same error so I can understand the root of the problem better? 

Thanks.
