### ISSUE TITLE
FlutterError: Failed to find definition for url(#paint0_linear)

### ISSUE THREAD

**Issue by SriramPatibanda** [GetStream/stream-chat-flutter#838]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

^3.3.2

### What happened?

When a file is attached, this error is thrown: 

```
The following assertion was thrown while parsing AssetBundlePictureKey(bundle: PlatformAssetBundle#0fc45(), name: "packages/stream_chat_flutter/lib/svgs/filetype_Generic.svg", colorFilter: null) in _getDefinitionPaint:
Failed to find definition for url(#paint0_linear)

This library only supports <defs> and xlink:href references that are defined ahead of their references.

This error can be caused when the desired definition is defined after the element referring to it (e.g. at the end of the file), or defined in another file.

This error is treated as non-fatal, but your SVG file will likely not render as intended
```
Editing the SVG code by bringing the ```<def>``` tags to the top of the SVG file can resolve this issue.

This can be helpful: https://stackoverflow.com/questions/61202925/svgpicture-image-rendering-error-in-flutter

### Steps to reproduce

```bash
1. Go to 'message text field'
2. Click on 'attach icon'
3. Click on 'Files icon'
4. Choose any '.jpg file'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @SriramPatibanda,

I can confirm this error occurs with the current SVGs in the SDK due to the existing Flutter issue.
I will let you know when I have a PR ready with the fix.

Thanks for reporting this.
