### ISSUE TITLE
Allow floating dateDivider to be above the messages

### ISSUE THREAD

**Issue by duzenko** [GetStream/stream-chat-flutter#842]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

latest

### What happened?

the custom floating date overlaps and blends with the messages

### Steps to reproduce

```bash
Use custom divider text
```

### Supporting info to reproduce

![image](https://user-images.githubusercontent.com/1481807/147597854-3cdf89ab-1b66-4853-a1ff-b41c97bb9f06.png)

### Code of Conduct

- [X] #889

**Comment by deven98** [comment]
Hi @duzenko,

Assuming I have understood your bug correctly, here is some more information about date dividers:

The `MessageListView` keeps two types of date dividers - ones that are embedded in the listview and the second is a floating date divider which changes once it passes an embedded date divider beneath it. The one which you have mentioned that overlaps with the messages is the floating date divider. 

You can either choose to turn off the floating date dividers like this:

```
    MessageListView(
        showFloatingDateDivider: false,    
    ),
```

OR you can add some kind of background to the date dividers like this to not make it look overlapping with the messages:

```
    MessageListView(
        dateDividerBuilder: (dt) {
            return Center(
                child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 1),
                    decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.7),
                        borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                        'Your text here',
                    ),
                ),
            );
        },
    ),
```

Let me know if this makes sense or if you think I may have misunderstood the issue at hand.

**Comment by duzenko** [comment]
Thanks, the two workarounds are kinda obvious
I was wondering if you can make the floating date to show above the messages, not on top of them

**Comment by imtoori** [comment]
Hi @duzenko
can you elaborate more on this? I'm not getting it, thanks

**Comment by duzenko** [comment]
> Hi @duzenko can you elaborate more on this? I'm not getting it, thanks

Use a Column instead of Stack

**Comment by imtoori** [comment]
we have a date divider in a column. In your screenshot `December 28` is not in a Stack, and it's above the message, isn't it?

**Comment by duzenko** [comment]
"August 3" on top is in a stack

**Comment by imtoori** [comment]
yes, that's the floating date divider that shows you the current timestamp you're on.
You can remove that as @deven98 mentioned [here](https://github.com/GetStream/stream-chat-flutter/issues/842#issuecomment-1002532980)

Am I missing something?

**Comment by deven98** [comment]
Just for some clarification: Both date dividers exist at the same time by default - as shown in your screenshot. If you don't allow the floating date divider, it will still show as column instead of a stack. If this is still confusing, you can send us a basic wireframe for us to understand better.

**Comment by duzenko** [comment]
If the floating date is disabled then the first messages show up with out date at all

**Comment by deven98** [comment]
Hi @duzenko,

Would having the first messages with the date solve your issue?

**Comment by duzenko** [comment]
> Hi @duzenko,
> 
> Would having the first messages with the date solve your issue?

I think so, however it's not very clear what you mean

**Comment by imtoori** [comment]
hey @duzenko 
you could use the `MessageListView.headerBuilder` parameter like this 

```dart

                  showFloatingDateDivider: false,                  
                  headerBuilder: (context) {
                    final date = StreamChannel.of(context)
                        .channel
                        .state
                        ?.messages
                        .first
                        .createdAt;
                    if (date == null) {
                      return const Offstage();
                    }
                    return DateDivider(
                      dateTime: date,
                    );
                  },
```

Let me know if that works for you

**Comment by duzenko** [comment]
I think that's a half-solution
Ideally I would like an option for the floating date to not overlap with the messages

**Comment by imtoori** [comment]
I don't think this makes a lot of sense, but I think I know how to help you with this
For now please use our workaround, I'll find a way of adding the date divider to the top when you disable the floating one

**Comment by rohan20** [comment]
@imtoori Would it be possible to provide `showFloatingDateDivider` on top of `stream_chat_flutter: ^2.0.0-nullsafety.2`? 

`stream_chat_flutter: ^2.0.0-nullsafety.2` is the only version we are compatible with. We just upgraded from `stream_chat_flutter: ^1.5.6` but it seems that this flag was only made available on `stream_chat-v2.0.1`. This is a critical issue for us and earlier you helped us get this flag as a hotfix on `^1.5.6`. Would be immensely helpful if you could do something similar on top of `stream_chat_flutter: ^2.0.0-nullsafety.2`. 

Happy to open a PR if you like:

```dart
if (widget.showScrollToBottom) _buildScrollToBottom(),
if (widget.showFloatingDateDivider) ...{
  Positioned(
     ...
   );
},
```

**Comment by imtoori** [comment]
@rohan20 do you want to hide the date divider? that's why you need it, right?

**Comment by rohan20** [comment]
@imtoori Yes. We want to set `showFloatingDateDivider` to `false`.

**Comment by rohan20** [comment]
@imtoori Just checking if you have a decision on this? :)

**Comment by xsahil03x** [comment]
Hey @rohan20, we are happy to receive a PR for this.
Can you make one and assign me as a reviewer?

Thanks,
Sahil

**Comment by rohan20** [comment]
Thanks @xsahil03x. I can do that. Can you please create a branch from the `2.0.0-nullsafety.2` git tag that I can base my PR on?

**Comment by xsahil03x** [comment]
@rohan20 sure, here you go https://github.com/GetStream/stream-chat-flutter/tree/2.0.0-nullsafety.2

**Comment by xsahil03x** [comment]
@rohan20 sure, here you go https://github.com/GetStream/stream-chat-flutter/tree/release/2.0.0-nullsafety.2

**Comment by xsahil03x** [comment]
@rohan20 here's the new release: https://pub.dev/packages/stream_chat_flutter/versions/2.0.0-nullsafety.3-beta
tag: https://github.com/GetStream/stream-chat-flutter/tree/stream_chat_flutter-v2.0.0-nullsafety.3-beta
