### ISSUE TITLE
Update flutter_slidable dependency

### ISSUE THREAD

**Issue by kightsonsanom** [GetStream/stream-chat-flutter#845]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Flutter_slidable package has gone through a major rework after version 0.6.0 (version currently used by stream_chat_flutter)
`Complete package rewriting in order to be more flexible and simple to use.`

Because of this it is not possible to use the latest version of the flutter_slidable and stream_chat_flutter. 

### Describe the solution that you'd like

stream_chat_flutter uses at least 1.0.0 version of flutter_slidable 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
sounds good, I'll work on a pr for this

**Comment by imtoori** [comment]
So, we're planning on removing the dependency since it's not really needed.
In v4 we'll remove it and write a guide on how to do it on your own. 
We think this is the best approach as it's something that you don't really always need and removing a dependency it's always a good thing.

**Comment by aaa59891** [comment]
Hi @imtoori, could I know when does the team plan to release v4 :)? since we would like to integrate with stream but got this dependency issue, would like to know the timeline so that we can make the decision whether we should build some UI widgets on our own first :)

**Comment by imtoori** [comment]
@aaa59891 we're pushing a RC by the end of week/start of next one
