### ISSUE TITLE
Message.ownReactions is truncated

### ISSUE THREAD

**Issue by damianmolinskifdt** [GetStream/stream-chat-flutter#846]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter_core - 3.3.1

### What happened?

Messages with more then 10 reactions have incorrect list of reactions added by current user.

I expected `Message.ownReactions` not to be truncated.

### Steps to reproduce

```bash
Add more then 10 reaction to message.
```

### Supporting info to reproduce

When messages are fetched and parsed without modifications by SDK `Message.latestReactions` contains first page (**max 10**) of reactions while `Message.ownReactions` contains list of all reactions from current user.

With that beaning said when message has more then **10** reactions **ownReactions** is truncated by what's in **latestReactions** because SDK have code similar to this 

```
    final ownReactions = [...latestReactions]
      ..removeWhere((it) => it.userId != user!.id);

    final newMessage = message.copyWith(
      latestReactions: latestReactions,
      ownReactions: ownReactions,
    );
```

I found some kind of variation of this logic `channel.dart`:  `sendReaction, deleteReaction`, `_listenReactionDeleted`, `_listenReactions`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi @damianmolinskifdt 
we're taking a look at this and see what we can do
I'll be back with more info soon

**Comment by imtoori** [comment]
So
Reactions are paginated and the default page length is 10
However, you can paginate through reactions using the `channel.getReactions` method as you can find [here](https://getstream.io/chat/docs/other-rest/send_reaction/?language=#paginating-reactions)
Let me know if that works for you

**Comment by damianmolinskifdt** [comment]
Hi @imtoori!
I've modified this [example](https://github.com/GetStream/stream-chat-flutter/tree/develop/packages/stream_chat_flutter_core/example) a little with following logic to show problem better.

Now when you long press any message it triggers adding new reaction and also displaying counts in message itself.

```
final item = messages[index];
final client = StreamChatCore.of(context).client;
final alignment = item.user!.id == client.uid
    ? Alignment.centerRight
    : Alignment.centerLeft;

final latestReactions = item.latestReactions ?? [];
final ownReactions = item.ownReactions ?? [];

final text =
    '${item.text}\nlatestReactions.count: ${latestReactions.length}\nownReactions.count: ${ownReactions.length}';

return GestureDetector(
  onLongPress: () {
    StreamChannel.of(context).channel.sendReaction(
          item,
          (reactionIndex++).toString(),
        );
  },
  child: Align(
    alignment: alignment,
    child: MessageWidget(text: text),
  ),
);
```

Also here is [Gist](https://gist.github.com/damianmolinskifdt/62de8be1f68f1d76782b3021abb21220) with example that you can reproduce this.

Also screen recording here. After 10 reactions `ownReactions` trounced and after restarting app `ownReactions` has correct data.

https://user-images.githubusercontent.com/47773413/150121851-694b205e-ec6c-4191-97e2-a0653d0518f0.mov

**Comment by imtoori** [comment]
ok I think I got the issue, but it's very hard to solve
I think this is the cause
```dart
    final ownReactions = [...latestReactions]
      ..removeWhere((it) => it.userId != user!.id);

    final newMessage = message.copyWith(
      latestReactions: latestReactions,
      ownReactions: ownReactions,
    );
```
The problem is there's a reason we did that, and it was a workaround for a backend little bug
Let me check if I can fix that

**Comment by TomBeckett** [comment]
@imtoori Hey Imtoori 👋 

Any idea when this fix may be released?

Thanks,

**Comment by imtoori** [comment]
hey @TomBeckett I hope to push a new 3.x release by the end of the week

**Comment by TomBeckett** [comment]
Hey @imtoori , sorry to bug. Any update on a potential 3.x release? Whats the best way to track a release?

**Comment by imtoori** [comment]
hey @TomBeckett we're releasing that today
sorry for the delay, but we're including as many fixes as possible
