### ISSUE TITLE
"Bad state: Cannot add new events after calling close" occurring at: stream_chat_flutter_core/src/channels_bloc.dart:153

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#848]
### Which packages are you using?

stream_chat_flutter, stream_chat_flutter_core

### On what platforms did you experience the issue?

Android

### What version are you using?

3.3.2

### What happened?

While loading up my channels I get a Crashlytics error, if I step past it it'll load the channels, but it's probably worth resolving so the issue isn't thrown.

### Steps to reproduce

```bash
Didn't dig into it, app's doing a lot, but this is getting picked up by Crashlytics and should be a simple fix, see included suggestion
```

### Supporting info to reproduce

I think the issue is that ChannelsBloc is not a top level widget, so it gets rebuilt when first loading the page. Looks like it causes the loading status callback to try to write after it's being closed. You might not be cleaning up your callbacks in the dispose or you could just check to see if it's closed before trying to ".add(" to the "_queryChannelsLoadingController".

For a quick example, you might just need to wrap it in a check to see if the controller is closed like so:

```
     if (!_queryChannelsLoadingController.isClosed) {
          _queryChannelsLoadingController.sink.add(false);
     }
```

Or maybe short-circuit the function before the next lines with something like...
```
     if (!_queryChannelsLoadingController.isClosed) {
          return;
     }
```

### Relevant log output

```shell
Bad state: Cannot add new events after calling close
#0   _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1   Subject._add                     package:rxdart/…/subjects/subject.dart:142
#2   Subject.add                      package:rxdart/…/subjects/subject.dart:136
#3   _StreamSinkWrapper.add.          package:rxdart/…/subjects/subject.dart:168
#4   ChannelsBlocState.queryChannels  package:stream_chat_flutter_core/src/channels_bloc.dart:153
<asynchronous suspension>
```

### Flutter analyze output

```shell
all clear minus a little dead code in unrelated files
```

### Flutter doctor output

```shell
No issues found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ezet** [comment]
I am experiencing the same issue, with a similar scenario.

**Comment by imtoori** [comment]
Weird bug, I think we'll add the check you're suggesting, just to be sure that doesn't happen
