### ISSUE TITLE
Close File Picker Section 

### ISSUE THREAD

**Issue by NiyazFazlyev** [GetStream/stream-chat-flutter#853]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android

### Is your feature request related to a problem?

Now the file picker section section of MessageInput widget closes when you click on the attachment button or the text field

### Describe the solution that you'd like

I want to close the file picker section by clicking  anywhere from the outside, for example, by clicking on MessageList

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @NiyazFazlyev,

We are working on a new version at the moment which includes a `MessageInputController` which allows you to manually modify many aspects of the state of the `MessageInput` - including opening and closing the attachment picker. 

You can follow #855 for more updates and this should be out soon.

**Comment by imtoori** [comment]
https://getstream.io/chat/docs/sdk/flutter/customization/custom-widgets/customize_attachment_picker_modal/#initial-attachments
I think this is possible. Please take a look at the docs.
