### ISSUE TITLE
Ban and Unban Users

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#857]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

Hey,
Im tying to ban and unban users from a channel.
My problem is that result seems inconsistent.

### What happened?

Ban a user
```dart
await channel.banUser(otherUser.userId!, {
  'banned_by_id': currentUser!.id,
  'timeout': 5256000 // 10 years
}); 
```

Unban
```dart
await channel.unbanUser(otherUser.userId!);
```

_Problem 1:_

**otherUser.banned**  can be true, but **queryUsers(filter: Filter.and([Filter.equal('id', otherUser.userId!), Filter.equal('banned', true)]))** return nothing right after.
Same if i go on dashboard UI and query Channel ID

![Capture d’écran 2022-01-12 à 13 36 34](https://user-images.githubusercontent.com/556990/149141578-ba526018-2900-4d9f-9348-c951241af28a.png)

_Problem 2:_

I would like to refresh my UI, switching text from "Block User" to "Unblock User".
How can get an uptaded status of banned user for this channel, and update UI accordingly ? 
queryUsers seems to not work, channel.state continu to hold old data...

Thank you,

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abacaxi-Nelson** [comment]
**in docs**

1- Using the dedicated query bans endpoint
2- User Search: you can add the banned:true condition to your search. Please note that this will only return users that were banned at the app-level and not the ones that were banned only on channels.

In Flutter we only have queryUsers, so seems that we can get banned user at channel level in Flutter..

**Comment by xsahil03x** [comment]
Hey @Abacaxi-Nelson , I'll test this out and soon come up with my findings.
