### ISSUE TITLE
Update flutter_svg to 1.0.1 stable release

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#861]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, MacOS

### Is your feature request related to a problem?

I can't update the flutter_svg version in my project until you update the dependency in stream_chat_flutter to fix dependency conflict.

### Describe the solution that you'd like

Update flutter_svg to ^1.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @CalHoll,

The new version seems compatible with the version currently being used.
Can you try adding a dependency override in your app for the moment?

```
dependency_overrides:
  flutter_svg: 1.0.1
```

We will upgrade the version in the next release coming up. 

Let me know if this works for you.

**Comment by CalHoll** [comment]
Override will probably work, just a bit clunky having to remember to remove in the future. Might just wait for next release. Thanks for resolving issue!

**Comment by imtoori** [comment]
closing this as the new version will be used in the next release
