### ISSUE TITLE
A non-null value must be returned since the return type 'OwnUser' doesn't allow null.

### ISSUE THREAD

**Issue by wasim919** [GetStream/stream-chat-flutter#869]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

Android (flutter run on windows 10)

### What version are you using?

stream-chat-flutter-core^3.3.1

### What happened?
When doing flutter run in Windows 10 with android phone connected via USB:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat-3.3.1/lib/src/client/client.dart:338:19: Error: A non-null value must be returned since the return type 'OwnUser' doesn't allow null.     
 - 'OwnUser' is from 'package:stream_chat/src/core/models/own_user.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stream_chat-3.3.1/lib/src/core/models/own_user.dart').
  Future<OwnUser> openConnection() async {
                  ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

### Steps to reproduce

```bash
1. In windows 10
2. flutter run
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @wasim919 
I don't see this issue while running the sample app using the 3.x version of the package
Can you try cleaning your project cache and everything and retry?
Thanks

**Comment by wasim919** [comment]
I am using stream_chat_flutter_core 3.3.1. I have used this from pub.dev. I cleared my project cache, I even removed the project and cloned it again. But it doesn't seem to work. It's working in IOS but not in windows. It started happening after 1 PM IST.  I tried it running again now, but it doesn't seem to work

**Comment by imtoori** [comment]
@wasim919 ok so it's a windows issue
Thanks, I'll make sure to look into it

**Comment by wasim919** [comment]
I am still facing this issue. My development has been stuck since last 2 days. Can you resolve this issue asap

**Comment by Peeyush14198** [comment]
It happens the same, when my team develops on mac os it works if we build for android and ios but the other team which develops for windows when they compile android app it fails giving the same error

**Comment by imtoori** [comment]
@wasim919 did you solve it?
