### ISSUE TITLE
Thread message is not deleted when using hard: true parameter

### ISSUE THREAD

**Issue by damianmolinskifdt** [GetStream/stream-chat-flutter#871]
### Which packages are you using?

stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter_core: ^3.3.1

### What happened?

When one of users deletes thread message it does not disappear for other users. It only happens when parameter `hard:` is set to true.

### Steps to reproduce

```bash
1. Open same thread on least 2 devices
2. One of users creates message
3. Same user needs to delete message
4. It will not disappear for other user
```

### Supporting info to reproduce

[Here](https://gist.github.com/damianmolinskifdt/25e608d8e5bf1f2809a64ca44ac2f5f0) is code that you can reproduce this bug with.

This is modified example from core repo with following logic when building message. 

- Shows message **text** and **type**,
- When taping message it opens thread for it.
- When long pressing message you can hard delete message.

```dart
                      final item = messages[index];
                      final client = StreamChatCore.of(context).client;
                      final isCurrentUserMessage = item.user!.id == client.uid;
                      final alignment = isCurrentUserMessage
                          ? Alignment.centerRight
                          : Alignment.centerLeft;

                      final canOpenThread = widget.parentMessage == null;

                      final text = '${item.text!} -> type ${item.type}';

                      return GestureDetector(
                        onTap: canOpenThread
                            ? () {
                                Navigator.of(context).push(
                                  MaterialPageRoute(
                                    builder: (context) {
                                      return StreamChannel(
                                        channel: channel,
                                        child: MessageScreen(
                                          parentMessage: item,
                                        ),
                                      );
                                    },
                                  ),
                                );
                              }
                            : null,
                        onLongPress: isCurrentUserMessage
                            ? () async {
                                final dynamic result = await showDialog<bool>(
                                  context: context,
                                  builder: (_) =>
                                      const DeleteConfirmationDialog(),
                                );

                                if (result == true) {
                                  await channel.deleteMessage(item, hard: true);
                                }
                              }
                            : null,
                        child: Align(
                          alignment: alignment,
                          child: MessageWidget(text: text),
                        ),
                      );
```
Here is short video showing bug.

https://user-images.githubusercontent.com/47773413/150530915-e20ac9e3-3eef-42dc-8761-241778fca765.mov

I was able to narrow down to implementation of `ChannelClientState.removeMessage`. Basically type of message is different and that's why its not removed.

`threads[parentId]!..remove(message)`
![remove_message_1](https://user-images.githubusercontent.com/47773413/150531390-b27c0ce4-4622-47c1-97d9-e7e731357b37.png)
![remove_message_2](https://user-images.githubusercontent.com/47773413/150531406-ad97d06b-503f-4066-b98b-6de47a9d9bda.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @damianmolinskifdt,

Thanks for such a detailed issue report. 
I'm taking a look at this now, I will let you know when I have more details.
