### ISSUE TITLE
stream_chat_persistence 3.0.0 causes build error

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-flutter#881]
### Which packages are you using?

stream_chat_persistance

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_persistence 3.0.0
drift 1.3.0

### What happened?

Build failure.

stream_chat_persistence uses GeneratedColumn(typeName: ...) here:
https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_persistence/lib/src/db/drift_chat_database.g.dart#L403

But "typeName" has been renamed to "type" in the underlying Drift library, as of Nov 2021 (the latest version is 1.3.0):
https://github.com/simolus3/moor/commit/fad654a5aac897cbb2feef2eec83138c553ea8fa

stream_chat_persistence's pubspec.yaml specifies this dependency:
```
drift: ^1.0.0
```

As a result, when I use "stream_chat_persistence: 3.0.0" in my app, I picked up Drift 1.3.0, which causes the build error. One of the error messages is:

```
Error: No named parameter with the name 'typeName'.
../…/db/moor_chat_database.g.dart:421
          typeName: 'TEXT', requiredDuringInsert: true);
          ^^^^^^^^
```

### Steps to reproduce

```bash
1. Add "stream_chat_persistence: 3.0.0" as dependency to a clean sample app.
2. Build and see error
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by linhewinner** [comment]
The work around is to use this in your pubspec.yaml dependencies:
```
drift: 1.0.1
```

It would be nice if stream_chat_persistence can update its implementation ... so we don't have to be stuck with an old version of Drift

**Comment by imtoori** [comment]
closing since it's a duplicated of #837 
we're releasing a new version with a fix asap

**Comment by linhewinner** [comment]
Why are this and #837 both closed?

If there is a new release fixing the problem, we should fix the issues after the new release is .... released.
I wasn't able to find #837 because it was closed. If it weren't, i would not have created this issue.

I would suggest reopening #837 until it's actually fixed.

**Comment by imtoori** [comment]
we closed that because the override was a valid temporary solution
btw in the new release #884 we're using the latest version of drift, so I think we can keep this closed, do you agree?

**Comment by linhewinner** [comment]
I'd keep issues open until there is a permanent solution, but each project is different. I'll let you decide how you want to manage issues for this one.

**Comment by imtoori** [comment]
we just released a new version of the packages using the latest version of drift, how is that not a permanent solution?

**Comment by linhewinner** [comment]
Oh cool! I didn't see that 3.4.0 release, sorry.

Yeah sounds good to close. Glad this one is gone

**Comment by imtoori** [comment]
good, thanks for reporting this! :D
