### ISSUE TITLE
Message.user.extraData wrapped with additional extraData map

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#886]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: ^3.4.0
  stream_chat_localizations: ^2.1.0
  stream_chat_persistence: ^3.1.0

### What happened?

When using the `extraData` of the user to add some additional info the object is correctly displayed in the streamchat dashboard. 
However when getting the extraData in the usernameBuilder via `message.user.extraData`, the object looks like this: 
![image](https://user-images.githubusercontent.com/6661557/152373364-680e7f52-d43f-4ec1-a2e9-e953c9c18054.png)

### Steps to reproduce

```bash
1. Add extraData via nodejs backend
2. Use a custom usernameBuilder and use the message oject provided to get the user and user.extraData
3. see that the extraData is wrapped in an extraData
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/floriandaniel/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/floriandaniel/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/floriandaniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • MI 9 (mobile)      • 7a53e08a                             • android-arm64  • Android 11 (API 30)
    • iPhone 12 (mobile) • 949CC6AD-F683-47F1-B119-8CA8E00436D4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 97.0.4692.99

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @flodaniel I just tested this and it's working fine
how do you set the extraData map?

**Comment by flodaniel** [comment]
in our NestJs backend we do this: 

```
 await this.serverClient.upsertUsers(
            streamChatUsersWithData.map((user) => {
                return {
                    id: user.username,
                    role: UserRole.user,
                    extraData: user.extraData,
                };
            })
        );
```

where each `user` in `streamChatUsersWithData` is a `ChatUserData` :

```
export interface ChatUserData {
    username: string;
    extraData?: Record<string, string>;
}

```
and this is how it shows up in the Chat Explorer

![image](https://user-images.githubusercontent.com/6661557/152385107-0ef00719-1e1a-49ee-af74-3fcd8772d325.png)

**Comment by imtoori** [comment]
oh yeah that's the issue

Basically, `user.extraData` (like `channel.extraData` and others) is just our way of dealing with custom properties in a typed language like Dart
The backend and other SDKs (for example the js one) have those properties available as normal object properties. Since that's not possible in Dart (and the same applies to other SDKs like Android, iOS and others) we have to deserialize those properties in a `Map<String, Object?>`.

Ok, maybe that was longer than needed 😅 

_How can you solve your issue?_
I think it'd be enough for you to change your model to something like this 
```js
export interface ChatUserData {
    username: string;
    role: string;
}
```

Let me know if that's clear and if I can help you in some other way

**Comment by imtoori** [comment]
oh and also you don't need to pass `extraData` while upserting the users
so maybe something like this 
```js
 await this.serverClient.upsertUsers(
            streamChatUsersWithData.map((user) => {
                return {
                    id: user.username,
                    role: UserRole.user,
                };
            })
        );
```

**Comment by flodaniel** [comment]
Hey @imtoori,
that seems kinda logically. I first looked at the dart api as it kinda well documented due to the strict types, so this is why I did not recognise, that the `extraData` on the javascript side is not necessary!
Thanks again :)
