### ISSUE TITLE
Unban not working

### ISSUE THREAD

**Issue by developerpaaji** [GetStream/stream-chat-flutter#888]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

3.3.2

### What happened?

Ban command working  but not unban command. With ban command when i send user name then its okay but with unban it seems it require user id

### Steps to reproduce

```bash
1. Go to message screen 
2. Click on command icon
3. Click on unban
4. Mention user
5. You will get error - Invalid unban cmd, please specify a valid user

Here is the video -
```
[Video Link](https://firebasestorage.googleapis.com/v0/b/xwealth-88890.appspot.com/o/2022-02-04%2016.08.48.mp4?alt=media)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Thanks for the video, we will soon work on fixing this 👍🏼

**Comment by developerpaaji** [comment]
When i unban user in chat then everything it gives success response when that user try to send message i get error saying 

`🕸️ ╔ DioErrorType.response 
2022-05-03 11:39:19.821 🚨 🕸️ ║    { 
2022-05-03 11:39:19.821 🚨 🕸️ ║         code: 17, 
2022-05-03 11:39:19.821 🚨 🕸️ ║         "SendMessage failed with error: "Sorry, you do not have access to this feature. Your account is currently
suspen
2022-05-03 11:39:19.821 🚨 🕸️ ║         ded from chat."" 
2022-05-03 11:39:19.821 🚨 🕸️ ║         StatusCode: 403, 
2022-05-03 11:39:19.821 🚨 🕸️ ║         duration: "0.00ms", 
2022-05-03 11:39:19.821 🚨 🕸️ ║         more_info: "https://getstream.io/chat/docs/api_errors_response" 
2022-05-03 11:39:19.821 🚨 🕸️ ║    } `

**Comment by imtoori** [comment]
@developerpaaji 
I think the error says it all 
`SendMessage failed with error: "Sorry, you do not have access to this feature. Your account is currently suspended from chat.`
You should contact support about this

**Comment by developerpaaji** [comment]
@imtoori  but this happens only after I ban user

**Comment by developerpaaji** [comment]
these are permission i have configured for group. 

[
	{
		"action": "Deny",
		"name": "No guests or anonymous access",
		"resources": [
			"*"
		],
		"roles": [
			"anonymous",
			"guest"
		],
		"owner": false,
		"priority": 90
	},
	{
		"action": "Allow",
		"name": "Owner permissions",
		"resources": [
			"DeleteAttachment",
			"DeleteChannel",
			"DeleteMessage",
			"DeleteReaction",
			"RunMessageAction",
			"UpdateMessage",
			"RecreateChannel"
		],
		"roles": [
			"channel_member",
			"channel_moderator"
		],
		"owner": true,
		"priority": 80
	},
	{
		"action": "Allow",
		"name": "Moderator only features",
		"resources": [
			"ReadMessageFlags",
			"SkipChannelCooldown",
			"UpdateChannelCooldown",
			"UpdateChannelFrozen",
			"PinMessage",
			"BanChannelMember"
		],
		"roles": [
			"channel_moderator"
		],
		"owner": false,
		"priority": 70
	},
	{
		"action": "Allow",
		"name": "Channel member and moderator permissions",
		"resources": [
			"AddLinks",
			"CreateMessage",
			"CreateReaction",
			"ReadChannel",
			"SendCustomEvent",
			"UploadAttachment"
		],
		"roles": [
			"channel_member",
			"channel_moderator"
		],
		"owner": false,
		"priority": 50
	},
	{
		"action": "Deny",
		"name": "deny all policy",
		"resources": [
			"*"
		],
		"roles": [
			"*"
		],
		"owner": false,
		"priority": 1
	}
]

**Comment by imtoori** [comment]
@developerpaaji can you contact support? we can help you more easily since we can ask for your app id
thanks a lot
