### ISSUE TITLE
Using StreamChatPersistence errors out when application is launched when offline

### ISSUE THREAD

**Issue by brbatwork** [GetStream/stream-chat-flutter#898]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS

### What version are you using?

`stream_chat_persistence: ^3.1.0`
`stream_chat_flutter: ^3.4.0`

### What happened?

After adding stream chat persistence to the application, when launching the applications in airplane mode, wifi off stream still tries to connect to the server and gets a DNS error.

How the client is being instantiated:

```
  final messagePersistence = StreamChatPersistenceClient(
    connectionMode: ConnectionMode.background,
  );
  final messageClient = StreamChatClient(
    config.streamKey,
    logLevel: Level.WARNING,
  )..chatPersistenceClient = messagePersistence;
```

### Steps to reproduce

```bash
1. Display a ChannelListView that contains a list of channels for a given user
2. Turn device radios off so the device can't connect to a network
3. Stop application and launch again
4. Observe channels are not loaded in, and have connection errors to stream chat servers
```

### Supporting info to reproduce

State of the device radios before launching the application:
![IMG_4D5BCBDEA4FD-1](https://user-images.githubusercontent.com/867681/153653909-14e00386-62c6-4c9e-8490-c67d479c40db.jpeg)

### Relevant log output

```shell
[   +7 ms] flutter: 2022-02-11 14:02:24.650164 🚨 📡 error connecting ws
[   +1 ms] flutter: WebSocketError(message: WebSocketChannelException: SocketException: Failed host lookup: 'chat.stream-io-api.com' (OS Error: nodename nor servname provided, or not known, errno = 8))
[        ] flutter:
[ +244 ms] flutter: 2022-02-11 14:02:24.895046 🚨 🕸️
[   +1 ms] flutter: 2022-02-11 14:02:24.895329 🚨 🕸️ ╔╣ DioError ║ DioErrorType.other
[        ] flutter: 2022-02-11 14:02:24.896116 🚨 🕸️ ║  SocketException: Failed host lookup: 'chat.stream-io-api.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
[   +2 ms] flutter: 2022-02-11 14:02:24.896419 🚨 🕸️ ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
[        ] flutter: 2022-02-11 14:02:24.897825 🚨 🕸️
[        ] flutter: 2022-02-11 14:02:24.898017 🚨 🕸️ ╔╣ Request ║ POST
[        ] flutter: 2022-02-11 14:02:24.898693 🚨 🕸️ ║  https://chat.stream-io-api.com/devices?api_key=yhp6sf3smfkq&user_id=1
[        ] flutter: 2022-02-11 14:02:24.899312 🚨 🕸️ ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
[   +5 ms] flutter: StreamChatNetworkError(code: -1, message: SocketException: Failed host lookup: 'chat.stream-io-api.com' (OS Error: nodename nor servname provided, or not known, errno = 8))
```
```


### Flutter analyze output

_No response_

### Flutter doctor output

```shell
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/bbarbour/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bbarbour/Library/Android/sdk
    • Platform android-31, build-tools 29.0.3
    • ANDROID_HOME = /Users/bbarbour/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Test iPad 02 (mobile) • 9a68e1382359c778dd3cf667251d5df6d8bdecb3 • ios            • iOS 15.3 19D50
    • Chrome (web)          • chrome                                   • web-javascript • Google Chrome 98.0.4758.80

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sampontec** [comment]
This happens even if the user was previously logged in and all messages were retrieved. I would expect if the user already has messages, goes offline, closes app, and opens app that the messages would be populated. Should this happen or is it not the way this was designed?

**Comment by xsahil03x** [comment]
Hey @brbatwork @sampontec these are just network error `logs` which you don't have to handle, you can easily disable it using the `logLevel: Level.OFF`.

`StreamChat` does show the previously saved channels in case of network errors. Let me know if this isn't the case.

**Comment by brbatwork** [comment]
> Hey @brbatwork @sampontec these are just network error `logs` which you don't have to handle, you can easily disable it using the `logLevel: Level.OFF`.
> 
> `StreamChat` does show the previously saved channels in case of network errors. Let me know if this isn't the case.

@xsahil03x Thanks for the tip.  In my case though it does **not** load the previous channels from storage, instead it shows the loading indicator indefinitely.

**Comment by xsahil03x** [comment]
Hey @brbatwork, I was unable to reproduce the issue. Can you please share a sample project where I can test it?

**Comment by xsahil03x** [comment]
Also, can you test it on our [SampleApp](https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1) and let us know if you are able to reproduce it?

**Comment by brbatwork** [comment]
> Also, can you test it on our [SampleApp](https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1) and let us know if you are able to reproduce it?

Not able to reproduce with the sample app.  It turns out switching the connection mode to regular fixed the issue in our app.  Thank you
