### ISSUE TITLE
Add capabilities dependencies to the readme

### ISSUE THREAD

**Issue by isaiahtaylor** [GetStream/stream-chat-flutter#9]
This app introduces at least a few capabilities that need to be added to `info.plist` and other places on iOS. 

* Apple notification service
* Photo library
* Contacts?
* Location?
* Speech Recognition?
* Calendars?

I'm not sure what's generating all these requirements in my app. The top two at least are clearly from this package. Could all of the necessary capabilities be listed?

**Comment by imtoori** [comment]
@isaiahtaylor There were some instruction in the README, but some information was missing.
Go [here](https://github.com/GetStream/stream-chat-flutter/blob/master/README.md#ios) to read more about what we require.

This is all due to dependencies like file_picker, image_picker and video_player.
