### ISSUE TITLE
Ensure reactions bubble gets rendered as closely as possible to the thought bubble indicator thingy

### ISSUE THREAD

**Issue by GroovinChip** [GetStream/stream-chat-flutter#965]
The calculation for the x-axis alignment of this widget needs modification.

**Comment by GroovinChip** [comment]
@imtoori can you please take a look at my bad hack in [1896b6c](https://github.com/GetStream/stream-chat-flutter/commit/1896b6c8149c4467694f42fc91d1d982c61729b3) please and tell me if you see a better way to handle this?

**Comment by imtoori** [comment]
@GroovinChip I know it kinda sucks, but I don't think there's another way

**Comment by GroovinChip** [comment]
Oof. Ok. I'm closing this, then.
